### ISSUE TITLE
build error on macosx 10.9.5 

### ISSUE THREAD

**Issue by artynet** [snes9xgit/snes9x#103]
I keep getting this error missing functions error and other similar ones :

mac-appleevent.cpp:218:4: Use of undeclared identifier 'QuitApplicationEventLoop'
mac-appleevent.cpp:321:12: No matching function for call to 'NewAEEventHandlerUPP'

when building the source with XCode 6.2. I also had to edit some include paths and nest this source code :

https://github.com/MrRio/js-snes-player

into the **$ROOT/apu** folder of the sources. any hints on this series of errors ?

```
Regards, Arturo
```

**Comment by mcclure** [comment]
As far as I understand, these are functions that exist in the 32-bit OS X but not in the 64-bit OS X libraries. Try building SNES9X for 32-bit mac.

**Comment by bearoso** [comment]
I think this is resolved. If not, open a new issue like "64-bit MacOS version."
