### ISSUE TITLE
mario rpg freezes are solved_??

### ISSUE THREAD

**Issue by mckaygerhard** [snes9xgit/snes9x#107]
mario rpg, six start legen, under the 1.41 version works well, but since recent seems does not work when comes the axess boses.. the game freeze if the red axe comes to fight

what are changed? if there any related commit please show me that can i backported to my builds! due the 1.4X versions seems does not crash on many RPG excelents games as such chronno trigger

of course i do not use ruindows. ok! neither winbuntu!

**Comment by carlospea** [comment]
yes this are still happened, i must play in win32 with gui to made some tircks

**Comment by mckaygerhard** [comment]
was solved with some tips, i recompiled and made debian packages ONLY for venenux, debian squeeze and lenny.

**Comment by mckaygerhard** [comment]
repo here: 

http://venenuxrepo.fundacite-aragua.gob.ve/

or here:

http://larutadelaseda.com.ve/venenux/
