### ISSUE TITLE
Sound crackling DK 3 Level 41 (Poisonous Pipeline)

### ISSUE THREAD

**Issue by WizLizard** [snes9xgit/snes9x#108]
Sound crackling, not to bad though but still there.

**Comment by WizLizard** [comment]
Never mind this happens on higan v097 and real hardware.

**Comment by OV2** [comment]
Thanks for checking and confirming.

**Comment by vgturtle127** [comment]
@WizLizard Really? Huh, that's weird. I never noticed. :smile:

**Comment by WizLizard** [comment]
@vgturtle127 I'm going to test virtual console on my wii tonight as well.

**Comment by vgturtle127** [comment]
@WizLizard OH! I would like to hear the results. :wink:

**Comment by WizLizard** [comment]
@vgturtle127 Exact same behavior on virtual console.

**Comment by vgturtle127** [comment]
@WizLizard Huh, OK. It's kind of weird I never noticed it, but also that Nintendo didn't fix it in the VC release.
