### ISSUE TITLE
Why was ppa:bearoso/ppa removed from launchpad?

### ISSUE THREAD

**Issue by ewscott9** [snes9xgit/snes9x#110]
Until recently the ubuntu build for snes9x has been available from ppa:bearoso/ppa. Is there a reason why this ppa has been closed?

**Comment by sergiobenrocha2** [comment]
I have no idea.

You can install it using this PPA: https://launchpad.net/~random-stuff/+archive/ubuntu/ppa

**Comment by bearoso** [comment]
It was glitchy because I don't use ubuntu. Someone else doing it is better.
