### ISSUE TITLE
Gtk errrors on Ubuntu 16.04, segfaults

### ISSUE THREAD

**Issue by axfelix** [snes9xgit/snes9x#112]
Hi folks,

Looks like there are some Gtk errors in Snes9x on Ubuntu 16.04 now that I've upgraded from 14.04 where it used to work fine. I can duplicate this with both a) the old deb package that hasn't been updated in a long time, b) a gtk2 build I just made myself, and c) a gtk3 build I just made myself.

axfelix@shoebox:~/Desktop/snes9x/gtk$ snes9x-gtk 

(snes9x-gtk:8018): Gtk-CRITICAL **: gtk_widget_set_double_buffered: assertion 'GTK_IS_WIDGET (widget)' failed

(snes9x-gtk:8018): Gtk-CRITICAL **: gtk_widget_realize: assertion 'GTK_IS_WIDGET (widget)' failed

(snes9x-gtk:8018): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(snes9x-gtk:8018): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(snes9x-gtk:8018): Gtk-CRITICAL **: gtk_widget_get_window: assertion 'GTK_IS_WIDGET (widget)' failed
Segmentation fault

**Comment by bearoso** [comment]
Already fixed in git. See commit 9a27cf6b for the fix if you want to backport it.

**Comment by axfelix** [comment]
This is in master? Because I just built from master and still had the issue...

**Comment by bearoso** [comment]
Yeah. Should work. What are your gtk+ 2 and 3 version numbers?

**Comment by axfelix** [comment]
Looks like 2.24 and 3.18.

**Comment by axfelix** [comment]
Oh god, maybe I managed to run the version on my path after building rather than the one I just built. Yesterday was a long day... hang on.

**Comment by axfelix** [comment]
Yup, that worked. Not proud of that one... closing :)

Should probably repackage this for Ubuntu at some point.
