### ISSUE TITLE
SNES9X FuSoYa Custom Builds - 8MB

### ISSUE THREAD

**Issue by jcdenton2k** [snes9xgit/snes9x#121]
So this:
http://fusoya.eludevisibility.org/emulator/index.html

> This program is an unofficial build of Snes9x, which fixes Snes9x's implementation of the SA-1's bank switch registers to honor bit 7 (previously it would act as though the bit was always on). This means that by placing the values 4,5,6,7 in $2220-$2223, you can access all 8MB of a 64Mbit ROM at the same time without any further bank switching required.

> This build also restores the ExLoROM map to 64Mbits, as it appears to have been accidently reduced to 48Mbits in the current 1.5x series of Snes9x. The fixes have already been submitted and accepted for the official Snes9x project, so they'll hopefully be in the next official build (1.54?).

That FuSoYa release was way back in December 2012.
So has this already been introduced into the SNES9X official v1.53 build?

How about the v1.53 Oct 2015 'official mirror' build found here?
http://www.s9x-w32.de/dl/testbuilds/?C=M;O=A

Is there a good way I can test this out with a test rom or otherwise to make sure the build I'm using supports this feature?

**Comment by OV2** [comment]
That's been added in d8e5d090, there's an accompanying issue #26 
All testbuilds since them have this included. I don't think there are any normal roms that use this, you'll have to find a romhack that uses this feature.

**Comment by jcdenton2k** [comment]
Thank you for the information!

I'll be sure to propogate this info to the relevant romhacking/modding communities.  Too many people have been pointing at those older builds for romhacks when they should be using more updated builds like the Oct 2015 testbuild that already includes 3+ years of fixes and updates.

Going to go ahead and close this out.  Thanks again!
