### ISSUE TITLE
Were is the downlad link?

### ISSUE THREAD

**Issue by floowsnaake** [snes9xgit/snes9x#126]
:,(

**Comment by roflcopter777** [comment]
It was on the 1.54 thread in the issues section

https://sites.google.com/site/bearoso/

**Comment by qwertymodo** [comment]
I think it was mentioned in the release issue thread that nobody has access to modify the main page of the website, which is why it's being hosted elsewhere.

**Comment by jcdenton2k** [comment]
They may need to consider just up and moving to a new/alternate website then.
If they can't even edit the main website then access needs to be transferred or just moved over to the new website.

**Comment by roflcopter777** [comment]
I think his name was Zones or something, no one can get a hold of him
