### ISSUE TITLE
problem loading roms with shortcut

### ISSUE THREAD

**Issue by stubl** [snes9xgit/snes9x#128]
I put emulator shortcuts on my taskbar in quicklaunch, and this works fine with my other emulator shortcuts, but if I load snes9x this way it then fails to load games (emulator crashes when loading game)

if snes9x is a shortcut on the desktop this doesnt happen, but as a shortcut on the taskbar it does

Im using windows 8 and this happens with all snes9x versions I know including new version 1.54, and I thought Id mention it here

**Comment by stubl** [comment]
yeah a custom toolbar on the taskbar, snes9x .exe is in my "emulators" folder elsewhere

if a snes9x shortcut is in a custom toolbar, and its launched and you then find a game and load it then snes9x will crash and not load the game

maybe try twice, but its a weird quirk I experience

**Comment by OV2** [comment]
Tried it a few times, worked fine here. I created a new toolbar on an empty folder, created a shortcut to snes9x.exe in this folder, then started via this shortcut and opened a rom via file->load game. Both 32bit and 64bit worked fine (win8.1).

**Comment by stubl** [comment]
I guess its just my computer setup then

I have no idea what could be causing this tho, since all my other emulator shortcuts load roms and work well
