### ISSUE TITLE
Window Size incorrectly remembered when exiting Fullscreen

### ISSUE THREAD

**Issue by Nicholas-Steel** [snes9xgit/snes9x#130]
Exiting Fullscreen Mode will restore the program to the Window Size it started at rather than what it is configured to if the user changed the Window Size during that session

Steps to reproduce:
**1)** Delete configuration file and open Snes9x.
**2)** Configure Windows Size to 4x.
**3)** Configure the program to utilize Exclusive Fullscreen Display Mode (Not borderless) and enable Fullscreen Mode.
**4)** Press Escape.
**5)** Emulator is at 1x Window Size (Should be at 4x).

**6)** Set Window Size to 4x.
**7)** Close and re-open emulator program.
**8)** Repeat steps **3** and **4**.
**9)** Emulator is correctly still at 4x Window Size.

The program either:
- Isn't dumping the changes to the config file as their made and is referencing this out of date value in the config file when exiting Fullscreen mode.
- Isn't immediately updating the value in RAM and the program refers to that RAM value when exiting Fullscreen mode.
- Both of the above happens.

Windows 10 x64
Snes9x v1.54 Win32_x64
Software is not installed to Program Files or Program Files (x86).

**Comment by OV2** [comment]
Thanks, fixed.

**Comment by jcdenton2k** [comment]
Thank you for the fix.  I had to manually go into the config file and set the window options manually to get them to 'stick'.  And it wasn't 'locked' or read-only either.

Future potential improvements could involve putting some of these options into the GUI instead of leaving them only in the config file.
