### ISSUE TITLE
Closing Custom Dialog Box may cause emulator lag

### ISSUE THREAD

**Issue by Nicholas-Steel** [snes9xgit/snes9x#131]
Snes9x v1.54 Win32_x64
Windows 10 Pro x64

1) Enable Custom Load dialog box.
2) Open Custom Load dialog box.
3) Immediately close Custom Load dialog box.
4) Entire program hangs for 3-5 seconds.

It seems to occur when there is no Save, ROM or Cheat folder where Snes9x is installed to (ie: the emulator has to create those folders). If those folders already exist than the issue can't be reproduced.

**Comment by OV2** [comment]
Can't reproduce this. However the custom rom dialog immediately starts getting information about the roms to display in the dialog, maybe this caused the lag for you.

**Comment by Nicholas-Steel** [comment]
Maybe? I did try deleting the config file when trying to reproduce the issue. Is there another config file I can try deleting, maybe stored in a different location to the emulator?

**Comment by Nicholas-Steel** [comment]
It seems to occur when there is no Save, ROM or Cheat folder where Snes9x is installed to (ie: the emulator has to create those folders).

**Comment by jcdenton2k** [comment]
I haven't experienced this issue but I realized why I never use that option now.  The window is NOT able to be resized and that creates a pain in the ass for having to navigate around within it.

**Comment by bearoso** [comment]
If this issue is still relevant, reopen.

**Comment by Nicholas-Steel** [comment]
It seems to have been solved since v1.54.
