### ISSUE TITLE
compiling error using the newest source VS14

### ISSUE THREAD

**Issue by regneq** [snes9xgit/snes9x#132]
I had been compiling this using 2013 with no issue until code were recently change to use VS14 and winxp compatible toolset.   I now get this error:

LINK : fatal error LNK1181: cannot open input file 'ddraw.lib'

**Comment by OV2** [comment]
If it cannot find ddraw.lib then you're most likely using a DirectX SDK that is too new. The direct draw library was removed in the June 2010 release. Either install one that still has the file, or you could try to find the lib file and copy it to the library folders.

**Comment by regneq** [comment]
yeah   I'll probably revert that change on my branch since I didn't get
that error before.   Thanks for the hard work.

**Comment by regneq** [comment]
ah okay,   Thanks for the explanation about DirectX SDK.  I went ahead and install it.  thanks.  can probably just close the issue.

**Comment by regneq** [comment]
ran into another compile issue.  libpng isn't compatible since it was build against an older compiler.  I had used snes9xgit-vs2013-dependencies zip files from another site.  Is there one for 2015?

**Comment by jcdenton2k** [comment]
Request:
Remove dependencies on DirectDraw as no modern systems exist (even within the past decade) that require it.  Almost every system that runs this emulator at a playable speed should support DirectX.

LibPNG should likely be updated with the latest version imported from upstream and modified for SNES9X use.

**Comment by OV2** [comment]
I uploaded a prebuilt libpng and zlib here: http://www.s9x-w32.de/dl/win32-prebuilt-libpng-zlib.zip

**Comment by regneq** [comment]
cool   thanks OV2

**Comment by qwertymodo** [comment]
Just an FYI, something else I ran into compiling on Windows 10 x64 with VS2015: https://github.com/snes9xgit/snes9x/commit/4a7d40e94e1abdf569cb44ccbc840ae1529787e9

**Comment by OV2** [comment]
I already looked at it in your branch. Looks like you are not compiling with unicode, and the DXERR replacement I added is unicode only. The correct fix is to also remove the TEXT() macros, otherwise your fix breaks unicode builds - I'll change it when the msu1 branch is merged into main.

**Comment by qwertymodo** [comment]
Weird, I have the project properties set to use Unicode.  In any case, I'll admit I'm not very familiar with Unicode handling in C++, so whatever works.
