### ISSUE TITLE
shift key input

### ISSUE THREAD

**Issue by stubl** [snes9xgit/snes9x#138]
the shift keys currently define the same in input configuration

is there a way to set left shift key and right shift key different from each other? if not, could this be implemented as a feature

I like using shift keys, different shift keys are good for pinball games, and games like cameltry

**Comment by jcdenton2k** [comment]
Need to determine if we are using scankey codes or another method of determining input.  I'd also like to see the alt and control keys defined as left and right.

**Comment by OV2** [comment]
You can already do that by manually editing the snes9x.conf file and changing the mappings to "LShift" or "RShift" respectively. If I can find some time I might look into changing the GUI to allow you to enter them.

**Comment by jcdenton2k** [comment]
Thank you for the response!  The workaround should be suitable for now until the GUI is updated.

**Comment by stubl** [comment]
thanks for the information

Im kind of combining topics here, but is there a way for snes9x to load last rom folder when loading a game?  

the GUI only allows for a specific set directory for roms

**Comment by OV2** [comment]
Fixed with 1fb5d790e3a83d3a60b78476a8a808cd7431f96a
