### ISSUE TITLE
[Request] Option to overclock SuperFX chip

### ISSUE THREAD

**Issue by jcdenton2k** [snes9xgit/snes9x#140]
Continuing the brief conversation from here:
https://github.com/snes9xgit/snes9x/issues/124#issuecomment-253004923

Just would like to see the option (in the GUI or INI files or command line) to overclock the SuperFX chip (both v1 and v2) for StarFox 1, StarFox 2, and other SuperFX games if desired.

I understand it is not 'accurate' and may interfere with those who want accuracy foremost.  But let's be real.  Higan/bsnes (and forks) are the most accurate so accuracy isn't the top priority for SNES9X.

I enjoy that I can run SNES9X on older hardware and I feel that end-user customization and usability should distinguish SNES9X from the other emulators.

This would be an OPTION and NOT enabled by default.  Once enabled it would only affect SuperFX games and would NOT affect anything if the SuperFX chip is not present for the original game.

I'd like to see the community speak their mind on this issue.

**Comment by qwertymodo** [comment]
Star Fox 1, at least, has no frame limiting, and simply relies on the GSU access waits to set the game speed, so overclocking the GSU doesn't just increase the framerate, it actually speeds up the entire game, making it considerably more difficult. I can't speak for other games, but it's unlikely to really be of much use for that reason, and even in the best case, it wouldn't be much more than a curiosity. That being said, if it's not a lot of work, eh, why not?

**Comment by jcdenton2k** [comment]
There's already a branch of libretro with an SNES9X-Next core based on v1.53 so I'm hoping that existing code can be ported over for v1.54.1
If I knew coding I'd throw out some commits but as of now I'm just an issues guy.

**Comment by jcdenton2k** [comment]
I've found some additional information & precedent for permitting the overclocking of the SuperFX chips.
From what I've read, the 'divide clock speed' is reprogrammed to act as a clock speed multiplier instead.  

Doing this, you can get StarFox 1 and 2 running at over 50 Mhz!  (compared to around 10 Mhz on the original).  Someone calling themselves 'Drakon' has done SuperFX overclocks using client-provided donor hardware and the results are pretty amazing.

https://www.youtube.com/watch?v=ZLcw3O7aTgo
https://www.youtube.com/watch?v=qqi1aow6GZI
https://www.youtube.com/watch?v=U4pm8WCtGX0

Previously he was unable to get it overclocked without affecting game speed, but with the newer information I believe he has done so.

http://forums.nesdev.com/viewtopic.php?p=110879#p110879
http://www.sega-16.com/forum/showthread.php?23839-Guide-How-to-overclock-your-SNES-Super-FX-games

I would ask any devs to strongly consider adding this type of functionality into the emulator itself.  I realize it is a specific use-case but considering how many people would love to play StarFox 1 and 2 at 'normal' smoother speeds above ~10 FPS would be phenomenal :)

**Comment by stubl** [comment]
overclock options are in some of the snes emulators on the wii I use, and would be great in windows too

**Comment by jcdenton2k** [comment]
I wouldn't mind a slider/multiplier to adjust speeds for the SuperFX chip (and possibly other chips) as far as their internal speeds.  Sometimes they will break (as Drakon showed) but just leave things at default for an 'accurate' experience and overclock things a bit for better in-game FPS in SuperFX games like StarFox 1.

Even with the sped-up gameplay it is still very playable because the inputs are sped up as well and so on.

Aka 'Street Fighter 2 Turbo mode' but for the SuperFX chip ;)

**Comment by stubl** [comment]
perhaps someone can port code from the snes9x wii emulator that has a SuperFX overclock feature implemented:

[https://github.com/dborth/snes9xgx](https://github.com/dborth/snes9xgx)

**Comment by bearoso** [comment]
Done.
