### ISSUE TITLE
Secret of Evermore (PAL) Random Freezes on scene change still present in 1.54.1

### ISSUE THREAD

**Issue by Pat86** [snes9xgit/snes9x#142]
I know this bug is known. Just wanted to confirm, that its still present in the new 1.54.1 release. Just tested it with my german version. This is a major bug that keeps me away from using snes9x. :-(

**Comment by jcdenton2k** [comment]
You could just use the NTSC release since you already own the kart.  I don't feel they'd bug you about it.
I wasn't aware if the game's text was translated into German or other languages outside of English.  For once it is a game that wasn't released in Japan.

**Comment by Pat86** [comment]
Naah, i'd like to play the german version. especially both "Secret of ..." games had a very nice and unique translation that i grew up with. dont want to play without it. ;-)

**Comment by jcdenton2k** [comment]
I understand what you mean.  I hope that this issue is fixed.  It would be cool if you could edit your original post to link to the bug in question just so that it is easier to find information on it.

**Comment by Nicholas-Steel** [comment]
There's these comments on the issue: https://code.google.com/archive/p/snes9x-gtk/issues/51

**Comment by Pat86** [comment]
Hopefully it will get fixed some day... i mean Secret of Evermore is a quiet a huge and well known game for the plattform. Not an obscure japanese only title that only 10 people will play. ;)

**Comment by jcdenton2k** [comment]
Time to summon the dev crew.  This issue has persisted long enough.

@bearoso @OV2 @any other devs

Let's see what they have to say on this.

**Comment by Nicholas-Steel** [comment]
They are (afaik) watching all the reports here as they occur, I don't think there's any need to directly call them out.

**Comment by bearoso** [comment]
Should be fixed now. Can't get it to lock up anymore.

**Comment by CharlesCorrin** [comment]
The fix was reverted in 30a924f , so I suppose this issue topic should be opened again?

**Comment by Nicholas-Steel** [comment]
Analysis info from BearOso is available here if you're interested: https://board.byuu.org/viewtopic.php?f=8&t=2065

**Comment by bearoso** [comment]
[i]Now[/i] it's fixed for sure.

**Comment by NeoRageX0** [comment]
What does it mean? Is there a new version out für the snes mini classic edition?

**Comment by Nicholas-Steel** [comment]
If the developer of that version of Snes9x incorporates the changes in to their version than yes. Otherwise No.
