### ISSUE TITLE
Makefile unresolved autoconf variable

### ISSUE THREAD

**Issue by bparker06** [snes9xgit/snes9x#146]
Trying to compile for Linux from the unix directory after the MSU-1 merge:

./configure && make
...
configure: creating ./config.status
config.status: creating Makefile
Makefile:5: *** missing separator.  Stop.

Where line 5 of the Makefile is:
@S9X_SYSTEM_ZIP@

Any idea what's going on? This did not happen with the msu1 branch before it was merged.

**Comment by qwertymodo** [comment]
Looks like it's a problem with the new --with-system-zip config option, but I'm not sure if it's a problem with the initial commit or if it got borked by the merge.  Can you try checking out https://github.com/snes9xgit/snes9x/commit/def3936a5353924fb7b9ffa30b8c1c96c9175ca7 and see if you have the same issue?

**Comment by bparker06** [comment]
That commit fails as well, but the one right before it works.

**Comment by bearoso** [comment]
I'll look at this.

**Comment by bearoso** [comment]
Needed to update configure and add pkg-config macros to aclocal. Fixed.
