### ISSUE TITLE
Speedy Gonzales - Los Gatos Bandidos (USA) (Rev 1). Rewind issue.

### ISSUE THREAD

**Issue by Cibomatto2002** [snes9xgit/snes9x#151]
Sometimes if you rewind the game it will have bad colors.

![capture11-19-2016-2 54 50 pm](https://cloud.githubusercontent.com/assets/21169038/20458363/f3d49f20-ae68-11e6-8b29-6a57c6ca7774.jpg)

**Comment by bearoso** [comment]
This is a save-state consistency problem.  Confine this to #411.
