### ISSUE TITLE
Configure error for SYSTEM_ZIP is a bit odd

### ISSUE THREAD

**Issue by ProfessorKaos64** [snes9xgit/snes9x#154]
When configuring on Arch Linux for the AUR package I maintain, this line affects the new build

```
if test "x${with_system_zip}" != "xcheck"; then
		AC_MSG_ERROR([--with-system-zip requested but no proper zlib found.])
else
		AC_MSG_WARN([zlib not found. Build without SYSTEM_ZIP support.])
fi
```

I noticed the commit entry added "Polynomial-C Introduce --with-system-zip configure flag to use system zip (**minizip**)". Adding minizip to my makedepends worked, but the message seems to imply `zlib` is missing, when package `zlib` is not, or is not needed.

**Comment by bearoso** [comment]
Looks like a copy-paste job, but he forgot to change the library name. Fixed.
