### ISSUE TITLE
MultiTap is Broken for NHL 97

### ISSUE THREAD

**Issue by newoski** [snes9xgit/snes9x#162]
I've tested all other SNES MultiTap games without issue, but NHL 95, NHL 96, NHL 97 appears to be broken. Only P1 and P2 show up in the player assignment screen. Really hoping this can be fixed. 

(For context, MultiTap is working as expected in NHL 94 and NHL 98)

**Comment by newoski** [comment]
Also broken on NHL 95

**Comment by OV2** [comment]
http://gaming.stackexchange.com/questions/286819/how-to-activate-the-multiplayer-feature-with-the-multitap-in-eas-nhl-series-on

Sounds like those games do not support more than 2 players.

**Comment by newoski** [comment]
Hi OV2,

I can't say I disagree, I read the same post, but I've also seen then listed on every MultiTap list I've ever seen. Their Genesis counterparts do support MultiTap

**Comment by qwertymodo** [comment]
Can you test in higan, and see how it behaves there?

**Comment by newoski** [comment]
I've never used higan. I've tested in bsnes, which is the higan varient I believe, but no MultiTap games work with bsnes

**Comment by newoski** [comment]
I see the option to enable Super MultiTap, but not to actually map the
additional controllers on higan

**Comment by newoski** [comment]
Page 23 of the manual describes up to 5 players in Practice Mode:
http://www.gamesdatabase.org/Media/SYSTEM/Nintendo_SNES/manual/Formated/NHL_-97_-_1996_-_Electronic_Arts.pdf

**Comment by OV2** [comment]
That's the number of players in the team, not the number of human players.

**Comment by newoski** [comment]
Hmm. OK, then this can be marked closed. Thanks for clarifying and sorry for the false bug report
