### ISSUE TITLE
GTK: default sound driver in Linux

### ISSUE THREAD

**Issue by marcosfrm** [snes9xgit/snes9x#166]
Snes9x GTK 1.54.1 has OSS as default sound system, which is not optimal on Linux -- it does not even work on Arch[1] without manual configuration. ALSA would be much better because it works OK with PulseAudio too.

[1] I think Fedora also does not support OSS at all nowadays.

**Comment by loganmc10** [comment]
Same here, OSS doesn't work in Fedora

**Comment by musuruan** [comment]
I committed snes9x and snes9x-gtk v1.54.1 for Fedora in RPM Fusion:
https://pkgs.rpmfusion.org/cgit/nonfree/snes9x.git/tree/

It's already available in updates-testing.

snes9x-gtk already supports pulseaudio. 

You can use padsp to run applications that support the OSS API for audio playback (/dev/dsp) on top of PulseAudio. Thus you can also run and have sound on snes9x (cli version).

**Comment by loganmc10** [comment]
The point is that it doesn't work "out of the box", if you compile and run snes9x on Fedora, and run a game, you'll have no sound

**Comment by marcosfrm** [comment]
Yes, the point is the *default* sound output, when we launch Snes9x on an empty profile. ALSA by default will work on every distribution out there, whatever PulseAudio is used or not. OSS does not work out of box (I use the GTK GUI version on Arch Linux).

**Comment by musuruan** [comment]
Have you tried passing --without-oss to ./configure?

**Comment by marcosfrm** [comment]
No because I use Arch's repository and they compile it this way:

https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/snes9x

**Comment by marcosfrm** [comment]
`--without-oss` removes OSS from the combo box, but then SDL is the new default (`USE_JOYSTICK` is defined and `USE_PORTAUDIO` is not here).  The entries in

https://github.com/snes9xgit/snes9x/blob/master/gtk/src/gtk_preferences.cpp#L1076

could be rearranged, but this probably would break pre-existing `snes9x.xml` settings since the index would change (sorry if I am talking nonsense, I have no clue about GTK programming).

**Comment by musuruan** [comment]
If you can't see PulseAudio in the Sound driver list it is very likely you haven't installed pulseaudio-libs-devel at compile time.

**Comment by bearoso** [comment]
The default is portaudio, but since it's not compiled in, it switches to OSS. This is a conscious choice. OSS Emulation through ALSA is actually the best performing sound driver because of the way its API works. 

You're also not supposed to run with the defaults, even though you can. That's one reason why the controller bindings aren't set.
