### ISSUE TITLE
Is there a specific reason dxerr is Unicode only?

### ISSUE THREAD

**Issue by bonimy** [snes9xgit/snes9x#167]
In win32/dxerr.cpp, the functions are strictly for Unicode, when it seems they can easily support both it and ASCII with proper macro treatment. I was just wondering if there was a specific reason only Unicode was implemented? This also breaks calls to dxerr functions (look for DXTRACE_ERR_MSGBOX) which pass strings with the TEXT macro rather than strict Unicode L prefix.

If there's no reason to not support both, I can push an implementation that does.

Cheers.

**Comment by OV2** [comment]
The only reason is that the replacement that was provided by some guy from the dx team was unicode only. Since there isn't really a need for an ansi versions I left it as is.
