### ISSUE TITLE
Integer Scale

### ISSUE THREAD

**Issue by ghost** [snes9xgit/snes9x#168]
Is it possible to add Integer Scale option in a future release? It prevent problems with shaders, specially crt shaders.

**Comment by OV2** [comment]
There are integer scale filters included from 1x to 4x.

**Comment by PinkLouie** [comment]
How? Here, it is always 100% streched vertically in full screen. No way to black bars,

**Comment by OV2** [comment]
Turn off "Strech Image" in the video options, or a similar option if you are not using the windows port.

**Comment by PinkLouie** [comment]
It do not streatch vertically anymore, but only multiply

**Comment by PinkLouie** [comment]
It do not streatch vertically anymore, but also do not multiply. With image output set to none, it is always x1, it depends on filters, but not all filters have all sizes. Maybe the size of the filter should be a different setting (below Hi-Res)? Or the size of the image should be a different setting, independently of the filter setting? Integer scale seems something different from streatch image.

**Comment by PinkLouie** [comment]
Closed accidentally, sorry for that.

**Comment by OV2** [comment]
The filters all have fixed sizes that they produce. If you want to combine one of them with another fixed size output you can only set the window size to that or look for a shader that does this (border shaders for example). Not likely that I'll add another option.

**Comment by bearoso** [comment]
Done.
