### ISSUE TITLE
Sailormoon (France)

### ISSUE THREAD

**Issue by ghost** [snes9xgit/snes9x#169]
Shadows get flashing in this game. Is it normal? 

In this video shadows normal: https://www.youtube.com/watch?v=1o3gJWEGXgE

**Comment by Oggom** [comment]
That's intentional, it's done in order to create a fake transparency effect for the shadow. You don't see it in the Youtube video because it was uploaded at 30fps (instead of 60fps), effectively cutting out the "shadow off" frames.

**Comment by PinkLouie** [comment]
So should snes9x use 30fps instead of 60fps for better accuracy?

**Comment by Oggom** [comment]
No, that would be the opposite of accuracy.

**Comment by jcdenton2k** [comment]
Comix Zone on Genesis may be related to a similar type of shadow-effect designed for CRT TVs.
Perhaps if the game was played with a CRT-style filter (or on an actual CRT) then the desired shadowing effect would be produced.
