### ISSUE TITLE
Replace old shaders.

### ISSUE THREAD

**Issue by ghost** [snes9xgit/snes9x#170]
What about remove old and bad shaders and add better e more useful shaders from retroarch? Anti-dithering shaders are very useful. Super Xbr is very beautiful and do cause problem with the dithering effect, like Xbrz does. I miss simple x3, x5, x6, and so on too.

**Comment by OV2** [comment]
Shaders aren't included, so there are none to be replaced. You can use many of the shaders from retroarch.

**Comment by bearoso** [comment]
NVIDIA (and Retroarch) have discontinued Cg. Probably need to update to their latest XML format eventually. Good thing I never actually got around to implementing Cg in the GTK+ port. :-)

**Comment by OV2** [comment]
The common-shaders repository is still only cg, I'm not aware of any new format.

**Comment by bearoso** [comment]
NVIDIA deprecated Cg 5 years ago. I assume they're still in Cg format because it can be automatically converted to whatever. I installed Retroarch and could only get it to pull the glsl and slang versions.

**Comment by bearoso** [comment]
And I guess it's not XML at all, just an ini-style preset file and individual shader pass files, and with pragmas defining the uniforms that can be used for configuration.

**Comment by PinkLouie** [comment]
I mean... output imagem processing, filters.

**Comment by OV2** [comment]
Those are software filters, and you cannot simply take a shader and make it into a software filter. If you want super xbr you can load the retroarch shaders.

**Comment by PinkLouie** [comment]
The shaders are tried, do not worked :(, I got an error windows with some of them. Crt-Hyllian for example. Maybe the problem is my graphics card?

**Comment by OV2** [comment]
You might want to try OpenGL as output method, the compatibility there seems to be higher.

**Comment by bearoso** [comment]
Fixed?
