### ISSUE TITLE
Show game's name in titlebar

### ISSUE THREAD

**Issue by ghost** [snes9xgit/snes9x#175]

**Comment by bonimy** [comment]
Were you thinking of the game's filename, or the internal name in the ROM data?

What OS are you using btw? I could probably do this for the windows side.

**Comment by PinkLouie** [comment]
I think Internal game name is better, because filename can be wrong. I'm using the latest version of Windows 10. Thank you for help.

**Comment by PinkLouie** [comment]
Filename is also nice, because roms usually come with the right name. Better then no name at all. Would be nice to see in 1.55.

**Comment by bonimy** [comment]
Should this feature be implemented across all platforms? Should this be a configuration option?

**Comment by Lululalu** [comment]
@bonimy probably across all platforms.

**Comment by bearoso** [comment]
Done.
