### ISSUE TITLE
Dolby Surround sound decoding

### ISSUE THREAD

**Issue by Robz8** [snes9xgit/snes9x#177]
I have a surround sound system set-up on my PC (without a receiver), so I wanted to ask.
I've heard that some games, such as Jurassic Park 1 & 2, Super Turrican 1 & 2, and Seiken Densetsu 3 (Secret of Mana 2), use Dolby Surround to play surround sound on an SNES.
I know the Wii/GC emulator Dolphin has Dolby Prologic II decoding (works without a receiver), so I don't see why Dolby decoding can't be implemented to snes9x.

**Comment by bearoso** [comment]
I'm not sure if there's anything to do with this. The SNES has only two-channel stereo output, and separation is game-dependent. A SNES game can't output true surround, it's likely just a marketing gimmick.

**Comment by jcdenton2k** [comment]
There's a few games like Star Ocean that use simulated 'fake' Surround Sound as well.  You can hear it in the first few seconds of it starting up.

The SNES only outputs Stereo sound, as do the NES and Sega Genesis/MegaDrive.

**Comment by roflcopter777** [comment]
The NES only had mono output, not sure where you got that info from.

**Comment by jcdenton2k** [comment]
My bad, you are correct.  I was thinking of people who modded their NES's to output Stereo Sound.  So used to it now <3

**Comment by roflcopter777** [comment]
No worries.

**Comment by FateForWindows** [comment]
I'd like to point out that the SNES does in fact support quadrophonic surround sound, which is done over a stereo signal in the first place. With a Dolby Pro Logic-compatible receiver, you can decode the stereo audio sent by the games that support it into 4-channel surround sound. It's a neat novelty for the few games that support it.
