### ISSUE TITLE
Super 8 (USA) (Unl)

### ISSUE THREAD

**Issue by PinkLouie** [snes9xgit/snes9x#180]
This rom (no-intro) do not work. I get a black screen.

**Comment by orbea** [comment]
Has this game ever worked? The initial commit in this repo does not work nor do any of the libretro snes9x cores.

**Comment by orbea** [comment]
Its even worse than that...I can reproduce this issue with bsnes, included the accuracy, balanced and performance profiles... Higan does not remotely compile with gcc7 so I have not tested that. Maybe the nointro dump is bad?
```
$ md5sum Super\ 8\ \(USA\)\ \(Unl\).sfc 
539858c3f2b8cd6f4765ad4a96560005  Super 8 (USA) (Unl).sfc
```

**Comment by PinkLouie** [comment]
I think it is not a game, it is a Bios, or something for this accessory: https://en.wikipedia.org/wiki/Super_8_(video_game_accessory)

**Comment by orbea** [comment]
I like that hypothesis, I wonder how to test it?

**Comment by bearoso** [comment]
PinkLouie looks to be correct. This is not a game. That it behaves the same in bsnes indicates there's nothing outstanding to fix.
