### ISSUE TITLE
Adding a .gitignore file

### ISSUE THREAD

**Issue by bonimy** [snes9xgit/snes9x#181]
I've noticed that snes9x doesn't have a .gitignore file. I suggest using [gitignore.io](https://www.gitignore.io/) to generate one automatically. Tags I would suggest are 'VisualStudio', 'C', and/or 'C++'. The only problem with the 'C' tag is that it removes library (*.a) files, and snes9x uses one, [macosx/libz_u.a](https://github.com/snes9xgit/snes9x/blob/master/macosx/libz_u.a), which probably shouldn't be there at all since the windows side has to build its own zlib, but I'm not sure. I'll open an issue later about it.

Regardless, I think a .gitignore should be added. For Visual Studio, [this](https://www.gitignore.io/api/visualstudio) file works nicely.

Because the snes9x executable builds to the win32 directory, we should probably remove the executable, stdout, stderr, and folders it creates too.

If this sounds like a good idea, I'll create a pull request for it. I had one [earlier](https://github.com/snes9xgit/snes9x/pull/178), but closed it due to it not being fully comprehensive and I didn't want it to be prematurely merged.

**Comment by bearoso** [comment]
This is fine with me. Don't worry about being fully comprehensive. The point is to add things as you notice or are irritated with them. You can always add an exclusion for specific files.

**Comment by bonimy** [comment]
In #182, I updated the solution file and included a .gitignore file (with the proper files excluded). It would have been wise to separate these changes, but the solution references the .gitignore file and I wanted to avoid merge conflicts. If you want the pull requests separated, I can do that.

**Comment by bearoso** [comment]
Then I'll leave it to OV2, as he handles the Windows stuff.

**Comment by bonimy** [comment]
This can be closed now. The .gitignore was added in #182
