### ISSUE TITLE
Shaders wont work on linux

### ISSUE THREAD

**Issue by wingedonezero** [snes9xgit/snes9x#186]
I get the error 

Cannot read shader file.
/media/chaoz/Emulation/Shaders/Glsl/Old/shaders_glsl 2015-10-17/xbr/xbr-lv2.glslp:1: parser error : Start tag expected, '<' not found
shaders = 1
^
Cannot read shader file.

All the shaders ive tested work fine on windows though but for some reason wont on debian or ubuntu.

**Comment by LeCharlatan** [comment]
The same here
Shaders don't work on Kubuntu Xenial

**Comment by wingedonezero** [comment]
Ive tested probably 30 shaders that work on the windows build and none work for any linux build currently and it also for some reason does not work in  1.53 either. I have built the latest git and the1.53 and 1.54.1 multiple times and no compile errors or anything.

**Comment by OV2** [comment]
CG shaders are only supported on the windows port, so this is expected behavior. The glsl variants you are trying are not supported in any port at the moment.

**Comment by wingedonezero** [comment]
On the linux port it says glsl shader. It should be easy enough since nvidias cg runtime is on linux to.

**Comment by bearoso** [comment]
The glsl variants described in this bug are working as of 1.56.
