### ISSUE TITLE
Gtk : coredump when enabling rewind in controls

### ISSUE THREAD

**Issue by YamashitaRen** [snes9xgit/snes9x#188]
How to reproduce : 
Open snes9x-gtk master on latest Archlinux.
Go to Options>Preferences...>Shortcuts>Misc and assign a key for "Rewind".
Click on "Apply" and "OK".
Snes9x hangs.

Here's the log : https://gist.github.com/YamashitaRen/7ebfd002b47219db6d9b5fafa7e140d8/da173e7b11ec8ad04097c717e5f135a6023d805e

**Comment by bearoso** [comment]
I can't duplicate. I'm on Arch Linux myself. Can you get a backtrace with a build that has debugging enabled? (pass --with-debug to configure)

**Comment by YamashitaRen** [comment]
Here's what I get : https://gist.github.com/YamashitaRen/7ebfd002b47219db6d9b5fafa7e140d8/2a35d1e1105f87b3ae3024db6835642d38fc7298#file-trace-log

Hope that's what you need, I followed theses instructions : https://wiki.archlinux.org/index.php/Debug_-_Getting_Traces#Getting_the_trace

**Comment by bearoso** [comment]
It seems to be complaining about a double freeing of preferences, but that's impossible. I've made a change to master, see if that fixes it.

**Comment by YamashitaRen** [comment]
ARGH I'm the one who introduced the bug while hacking snes9x... I'm sorry :/
There is no bug on 898e204fcf58885403fc59dcc5ee295649835e59. I should have triple checked I was using it...

At least I have learned a few things. Thanks.
