### ISSUE TITLE
Add a Copyright text on the main folder

### ISSUE THREAD

**Issue by jristz** [snes9xgit/snes9x#193]
Additionally to all the licence headers we have it will be nice to have the licence in the main directory as
LICENSE or COPYRIGHT plain text file so anyone reaching the project will inmediatelly see the license without need to dig or see the files and they can ever say "I dont read sourcecode" since it will be awailable without read it.
Also will help github search tool.

I was going to add a copy but then do you want all the license? it have a name? it can be split in CONTRIBUTORS and LICENSE itself? do you want the file named as COPYRIGHT or LICENSE?

**Comment by orbea** [comment]
I suggest calling it `LICENSE` as that is standard for countless projects. I also suggest that `CONTRIBUTORS` to be a separate file.

**Comment by bonimy** [comment]
What License does snes9x use?

**Comment by orbea** [comment]
The license is in every file.
Example: https://github.com/snes9xgit/snes9x/blob/master/dsp.cpp

**Comment by bearoso** [comment]
License is now in root folder as LICENSE and details included projects.
