### ISSUE TITLE
support xdg standard directory structure

### ISSUE THREAD

**Issue by jristz** [snes9xgit/snes9x#194]
Actually the configuration files are placed on $HOME/.snes9x for store user specific
It will be better if snes9x start using the xdg- standard specification that now is used for most programs like gnome, kde, xfce, pacma package manager, wayland, etc.

the file in linux in question is the _cpp_ file gtk/src/gtk_config.cpp with contain in get_config_dir a hardcoded path to fix this a simple change in that file is need.

a _bash_ example is of how showld look is:
´´´
XDG_SNES9X_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/snes9x"
if [[ $SNES9X_XML = "$confdir/snes9x.xml" && -r "$XDG_SNES9X_DIR/snes9x.xml" ]]
	source_safe "$XDG_SNES9X_DIR/snes9x.xml"
elif [[ $SNES9X_XML = "$confdir/snes9x.xml" && -r "$HOME/.snes9x/snes9x.xml" ]]; then
	source_safe "$HOME/.snes9x/snes9x.xml"
 fi
´´´
than an example in _bash_ that check for snes9x.xml fire in the XDG_USER_DIR and fallback to the old location if not found and again fallback to the sysconfdir if not found too.

this will make snes9x go in line with standard specification used and will not affect old userd if the fallback is used

this is the entire paper abiut the xdg structure https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by bearoso** [comment]
Should be handled now. Looks for the directory, not the config file.
