### ISSUE TITLE
Light Fantasy (J) unable to save games

### ISSUE THREAD

**Issue by chriskern** [snes9xgit/snes9x#201]
In 1.54.1, the Japanese RPG Light Fantasy doesn't save games. The game says the save has succeeded, but the save is not there. Also for some reason the cursor starts on save file 3 instead of 1. It works in various versions of bsnes/higan.

Here's how to get to the save dialogue, since it's all in Japanese (I didn't see a post edit option)

1. When you start the game, just keep hitting A to get through the dialogue until you have control.
2. Walk to the bed, then hit A to get through more dialogue.
3. When you have control again, choose アイテム, then めがみのしょ, and that will bring up the save option. When you select a save slot, it should then show a saved game in that slot before exiting the menu. Instead, it just says it saved successfully but nothing appears in the slot.

I tried it on two different computers, and I've had no problem saving other games in Snes9x.

**Comment by qwertymodo** [comment]
Solution courtesy of hex_usr https://board.byuu.org/viewtopic.php?f=8&t=1629&start=0#p41504

>Snes9x's issue is that its LoROM mapping is not very forgiving and does not account for save RAM being accessed through  70-7d,f0-ff:8000-ffff. Specifically, Light Fantasy uses 70:8000-9fff to save

**Comment by bearoso** [comment]
I've made a small change that fixes Light Fantasy based on what hex_usr said. Let's see if it breaks anything else.
