### ISSUE TITLE
unsupported vertex format

### ISSUE THREAD

**Issue by Marc34** [snes9xgit/snes9x#202]
Hi 

When I try to use opengl, I have sound but no video. Error message : 

E ../../../../../src/gallium/drivers/r600/r600_asm.c:2484 r600_vertex_data_type - unsupported vertex format PIPE_FORMAT_B5G5R5A1_UNORM

I'm on Kubuntu 17.04.

Thank for your help.

**Comment by bearoso** [comment]
Try changing the "pixel-buffer objects" option. If it's off, toggle on. If it's on, select 24 or 32 bit color.

**Comment by Marc34** [comment]
It works when I select 32 bit color. Thank !
