### ISSUE TITLE
(Windows) Input Config screen doesn't differentiate LShift/RShift

### ISSUE THREAD

**Issue by qwertymodo** [snes9xgit/snes9x#204]
The Input Configuration screen doesn't differentiate between L/R shift, ctrl, alt, etc. so if you try to use both, they turn blue, indicating that the button is already in use.  However, the emulation core does properly differentiate them, so I often use them as my L/R buttons.  I'm not sure if the other ports have the same issue, but it definitely exists in Windows.

![snes9x_input](https://user-images.githubusercontent.com/5988870/27014628-9f54fe60-4eb1-11e7-9a0b-5f9946897267.png)

**Comment by OV2** [comment]
Which version did you try? I fixed that in 1fb5d790e3a83d3a60b78476a8a808cd7431f96a, it was mentioned in #138

**Comment by qwertymodo** [comment]
Well, that explains it, I think my build was off of the msu1 branch, which forked on the same day you committed that change, so I just missed it.  Also, apparently I suck at searching.

**Comment by OV2** [comment]
No problem - reminded me to close the other issue ;)
