### ISSUE TITLE
(Windows) identifier "D2D1_PIXEL_FORMAT" is undefined

### ISSUE THREAD

**Issue by qwertymodo** [snes9xgit/snes9x#205]
The Windows project doesn't build properly in Visual Studio 2015 when configured for the Visual Studio 2015 (v140) toolset, throwing errors in wincodec.h about D2D1_PIXEL_FORMAT being undefined and PixelFormat being an unknown override specifier.  The solution appears to be in dxerr.cpp to include <d2d1.h> immediately before <wincodec.h> but I don't have any other build configurations/toolsets available to test if that breaks any other setups.  Worst case, it might require a preprocessor version check.

**Comment by OV2** [comment]
I'll add the include, causes no problems for me in 2017. Using the non-xp toolsets has some other caveats, such as problems with the older directx sdks, but obvious problems like this we can fix.

**Comment by qwertymodo** [comment]
Ok, I added the include in 75d3ac2a1b2689237f45fd4864b86b1f3f8fff3d
