### ISSUE TITLE
Looney Tunes B-Ball (USA) multitap not recognized until reset

### ISSUE THREAD

**Issue by clobber** [snes9xgit/snes9x#212]
Snes9x v1.54.1 win32
Looney Tunes B-Ball (USA).sfc (MD5 = 9cc7336325379139afc58d12a776696a)

Steps to replicate:
* Launch app
* Input > check 'Use Super Multitap (5-player)'
* Load ROM

Notice that the 2v1 and 2v2 player options are greyed out:
<img width="624" alt="screen shot 2017-07-16 at 1 14 51 am" src="https://user-images.githubusercontent.com/1303132/28245074-31869a14-69c4-11e7-9d38-b90e3526ccff.png">

Only way to resolve this is to hit 'Reset Game' which will then enable the multitap player modes. I tried this game in BSNES/Higan and the additional modes were enabled without the need for a reset.

**Comment by OV2** [comment]
It looks like the game is checking the controllers before s9x is connecting them (they stay connected on a reset). Will have to take a closer look at the connection logic.

**Comment by kps501** [comment]
void S9xControlsSoftReset (void)
	{
	for (set<struct exemulti *>::iterator it = exemultis.begin(); it != exemultis.end(); it++)
	delete *it;
	exemultis.clear();
	
	for (int i = 0; i < 2; i++)
	for (int j = 0; j < 2; j++)
	read_idx[i][j]=0;
	
	FLAG_LATCH = FALSE;

    curcontrollers[0]=newcontrollers[0];
    curcontrollers[1]=newcontrollers[1];
	}

83/F348 reads 4017 and doesn't see mp5. Does S9xSetJoypadLatch later. Above idea seems to run on emu startup, rom load, soft reset. Hope this helps out!

**Comment by clobber** [comment]
@kps501 Thanks, can you open a pull request? You can do the file editing and everything right from GitHub.

**Comment by kps501** [comment]
I don't know if this addition causes problems or if snes9x devs have a better way of handling it -- I'll let them comment first.
(don't want to junk up the repository with unknown bad code)

**Comment by bearoso** [comment]
That looks fine. I don't quite understand why the original dev did it this way, but I won't mess with it if it works otherwise.
