### ISSUE TITLE
black borders 

### ISSUE THREAD

**Issue by jaapdaniels1984** [snes9xgit/snes9x#213]
i know this might not really be an issue, but is it possible to add custom borders for todays screens? adding the option to fill it up with a picture like https://retropie.org.uk/forum/assets/uploads/files/1491583272229-snesbezel1.png where the transparent color would be the actual game screen in full screen. personal this would solve the problem of scratching the game out of proportions (doesn't looks nice) or having to look at black borders on the side of the screen...

**Comment by OV2** [comment]
You can do this in the win port by using the border shaders from here: https://github.com/libretro/common-shaders/tree/master/borders
