### ISSUE TITLE
Fails to build on linux with ./configure --enable-debugger

### ISSUE THREAD

**Issue by TimothySchmitz** [snes9xgit/snes9x#215]
Selected output:

../apu/bapu/snes/../smp/debugger/debugger.hpp:1:53: error: expected class-name before ‘{’ token
 class SMPDebugger : public SMP, public ChipDebugger {
                                                     ^
../apu/bapu/snes/../smp/debugger/debugger.hpp:3:30: error: ‘string’ has not been declared
   bool property(unsigned id, string &name, string &value);
                              ^
../apu/bapu/snes/../smp/debugger/debugger.hpp:3:44: error: ‘string’ has not been declared
   bool property(unsigned id, string &name, string &value);
                                            ^
../apu/bapu/snes/../smp/debugger/debugger.hpp:5:3: error: ‘function’ does not name a type
   function<bool ()> step_event;

**Comment by TimothySchmitz** [comment]
This is in the /unix directory, btw

**Comment by OV2** [comment]
The smp debugger is not working at the moment. If you don't need it you can use this patch to make it compile: [debugger_temp_fixes.patch ](https://gist.github.com/OV2/d2218e3fe1bb8fbd2e8143ea543e5dac)

**Comment by TimothySchmitz** [comment]
That's exactly what I needed, thanks!
