### ISSUE TITLE
[MacOS 10.12] File->Open ROM Image doesn't open dialog in Sierra

### ISSUE THREAD

**Issue by jacobthehammer** [snes9xgit/snes9x#216]
(This is using the 1.5.3 build from 2012, I couldn't find a more recent package for Mac.)

Steps for recreating the bug are fairly simple.
1. Open Snes9x.app
2. Either click File->Open Rom Image or use cmd+o
There is no Finder dialog as expected. 

Using Console in MacOS we can see exactly what happened. I've included a [screenshot here for reference.
](http://imgur.com/a/NmDdg)

![screen shot 2017-08-06 at 8 48 50 pm](https://user-images.githubusercontent.com/9625866/29009498-5f1d35c4-7ae9-11e7-81f4-2d916444104f.png)

`[WARNING] could not find container for id: com.apple.Documents`
`[WARNING] could not find container for id: com.apple.Documents`
`[WARNING] could not find container for id: com.apple.Documents`
`-[NSView setNeedsDisplayOnHICocoaView]: unrecognized selector sent to instance 0x1c254d0`
`Connection to sharingd became invalid`
`Exception raised!: -[NSView setNeedsDisplayOnHICocoaView]: unrecognized selector sent to instance 0x1c254d0`

---

Based on the data from console, I'd chalk this up to some change in Cocoa that Apple has made since OSX Lion came out in 2012. 

Thanks for making such a great emulator!

**Comment by OV2** [comment]
Unfortunately there is no maintainer for the osx port at the moment, so this is unlikely to get fixed anytime soon.

**Comment by GB-CG** [comment]
@jacobthehammer There's the 1.54.1 port on OpenEmu, but that's another story.

**Comment by mcclure** [comment]
The error triggers somewhere inside of Apple's `NavDialogRun` function (called in `NavOpenROMImage`).

`NavDialogRun` is a VERY old system function (it does not even exist in 64-bit executables) and I think it just stopped working correctly with Sierra…

The entire open/save dialog system in snes9x seems to be written for compatibility with Mac OS 9 and so it uses a lot of functions that are deprecated…

**Comment by bearoso** [comment]
Apparently fixed.
