### ISSUE TITLE
Mac: Build Issues

### ISSUE THREAD

**Issue by speedofmac** [snes9xgit/snes9x#22]
I'm getting quite a few compilation warnings and errors when compiling snes9x on OS X 10.6.8. The majority of problems seem to stem from the /apu directory. Here's a link to the compilation output: http://pastebin.com/ZJCY29JE

One thing that fixed the majority of issues was to apu/apu.cpp:185 to:

```
#include "bapu/snes/snes.hpp"
```

I'm not sure about the others. Adding the /apu/bapu directory to the project didn't seem to fix the missing file issues, but someone more knowledgeable than I should be able to figure out what's going on.

**Comment by vgturtle127** [comment]
Any updates on this? Mac users haven't been having issues all this time have they?

**Comment by eisnerguy1** [comment]
I still can't compile the master code in Xcode 8.3.3.
