### ISSUE TITLE
Patch&Cheat directory should be split into separate directories

### ISSUE THREAD

**Issue by qwertymodo** [snes9xgit/snes9x#220]
Currently, there is a single entry in the configuration drop-down for a Patch&Cheat directory.  None of the other directories in the list are combined, these should really be split into separate directories.  Also, the enum value IPS_DIR in the code should probably be renamed PATCH_DIR, since we support IPS, UPS, and BPS.

**Comment by OV2** [comment]
I guess at the time most patches were for cheating (trainers and such). We can split and rename, sure.

**Comment by OV2** [comment]
Implemented in cb3ace471e9fa73e80006da8364b5e800206b55b
