### ISSUE TITLE
Updating .gitignore

### ISSUE THREAD

**Issue by bonimy** [snes9xgit/snes9x#224]
## Issue
Sometimes I will put a test ROM into the snes9x directory to work with. When uploading pull requests to github, I have to remember to discard these files.

## Resolution
Add the following extensions to the [.gitignore](https://github.com/snes9xgit/snes9x/blob/master/.gitignore) file.
- *.smc
- *.sfc
- *.fig
- *.srm
- *.001-009
- *.oops
- *.ips
- *.ups
- *.bps

I know I'm missing a few. What other game-based extensions should we ignore?

**Comment by qwertymodo** [comment]
If you're including .ips, you'll want .ups and .bps as well.
