### ISSUE TITLE
ScaleFX working only on Retroarch, but not in the standalone version of 1.54.1.

### ISSUE THREAD

**Issue by Khronikos** [snes9xgit/snes9x#226]
Hello, recently I have been having problems getting shaders to run at all in D3D, and most will run in OpenGL, yet ScaleFX is broken in both of them. Just a black screen or error.

I have not used shaders in the past. Usually just the in-app xBRZ. I am on Win 7 64, Nvidia 1070, newest drivers, 2500K, and have the relevant dlls in the app.

Would be nice to see what is wrong since the Retroarch version of SNES9x and ScaleFX work perfectly together.

I can see an image on some of the separate passes of the shader, but a few of the passes are blank or blacked out in the standalone version.

**Comment by OV2** [comment]
Does it work on Retroarch with D3D output and CG shaders? Might be a limitation in the CG runtime.

**Comment by Khronikos** [comment]
Whatever is default is working. I'm not sure how retroarch could get this working and SNES9x cannot though. Same emulator and version number. Whatever is the default backend is what I am using. I didn't even know you could switch it.

**Comment by Khronikos** [comment]
Okay, it was OpenGL that was working. Just tested out D3D and the same black screen appears.

**Comment by Khronikos** [comment]
But that still leaves the fact that OpenGL is not working in standalone. I hope maybe someday it will work possibly with another patch or something I can do on my end.

**Comment by bearoso** [comment]
Should work now with both glsl and slang shaders.
