### ISSUE TITLE
[Bug] Games issues

### ISSUE THREAD

**Issue by nemo93** [snes9xgit/snes9x#228]
I'm carefully and thoroughly testing games with the [libretro-core](https://github.com/libretro/snes9x) on Retropie latest version (4.2.18 as of writing on RPi3). Everything is being up to date on my system (including Raspbian packages). It went well so far except with the following games:

- **Chou Aniki Bakuretsu Rantouden** (Japan): game doesn't launch. Go straight into black screen and stays there. Not working on Snes9x1.53 & 1.54.1 Windows (10 x64) either but apparently does work on Bsnes or Zsnes. Regession confirmed => #187

- **Final Fantasy VI (1)**: I got sound crackling/stuttering at some locations only (Figaro South is a good example). Just go to these locations and you'll be able to hear the sound crackling from time to time.
- **Final Fantasy VI (2)**: after a battle it may happen that the screen keeps on doing the mosaic effect in the background. It's annoying but it could go away simply by entering another battle. 

- **JoJo no Kimyou na Bouken** (Japan): this one does launch. However screen goes full with garbage characters during intro. Same issue on Snes9x 1.54.1 Windows.

- **Marko's Magic Football** (Europe): crash during intro / unplayable. Same issue on Snes9x 1.54.1 Windows (even **crashes** the emulator!).
- **Sufami Turbo chip games** launch but can't pass the instruction screen. I believe this is due on how ST games are supposed to work. Some ST games: Gekisō Sentai Carranger: Zenkai! Racer Senshi, Crayon Shin Chan, Sailor Moon Stars Panic 2, Gegege No Kitarou, ...

**Comment by bearoso** [comment]
The Retropie version is ancient and deliberately speedhacked to hell. so if something works in Windows, but not there, it's not a bug.

**Comment by bonimy** [comment]
If these are all distinct bugs, I would suggest we separate them into separate issues.

**Comment by nemo93** [comment]
Let me know if I should raise separate tickets for each item and I'll gladly do so. All games listed (except Deae Tonosama Appare Ichiban) do have issues as well on the latest Snes9x 1.54.1 Windows as mentioned.

**Comment by qwertymodo** [comment]
Yeah, these are all separate issues.  If they exist in the PC builds, go ahead and report them separately and we can close this one.

**Comment by nemo93** [comment]
Done. Tickets #229 #230 #231 and #232 created. Thanks for your help.
