### ISSUE TITLE
[Bugs] Final Fantasy VI (FFIII) - sound issue + mosaic weirdness

### ISSUE THREAD

**Issue by nemo93** [snes9xgit/snes9x#229]
* Sound crackling/stuttering at some locations only (Figaro South is a good example). This occurs when you enter or visit the cities and villages. Just go to these locations (Figaro South, Narshe, etc) and you'll be able to hear the sound crackling from time to time.

* After a battle it may happen that the screen keeps on doing the mosaic effect in the background. It's annoying but it could go away simply by entering another battle. This tends to happen mostly early in the game.

It does happen on Snes9x 1.54.1 Windows x64 (and also Snes9x 1.54.1 libretro+RPi). I'm using a translated rom (based on a patched FFIII US rom+ips from Terminus traduction).

**Comment by jcdenton2k** [comment]
@nemo93 try this out on a 'verified clean dump' of the US version of FF6 without any rom patches applied and see if the issue persists.

**Comment by nemo93** [comment]
@jcdenton2k you're correct. With a stock FF3 rom the sound issue has gone away. Yet there's still moments where music is crackling but it's very faint (still occurs while visiting the cities/villages) but definitely not as big issue as I mentioned previously.

**Comment by jcdenton2k** [comment]
Many of the older/earlier translation patches like the one for Dragon Quest 3 on SNES ended up causing other issues/bugs due to unforseen complications and a lack of time to do full-playthrough testing in detail.
