### ISSUE TITLE
[Bug?] Sufami Turbo Chip games - unplayable

### ISSUE THREAD

**Issue by nemo93** [snes9xgit/snes9x#232]
These games launch but can't pass the instruction screen. I believe this is due on how ST games are supposed to work but I'm no expert on that matter. Some ST games: Gekisō Sentai Carranger: Zenkai! Racer Senshi, Crayon Shin Chan, Sailor Moon Stars Panic 2, Gegege No Kitarou, ...

Tested on Snes9x 1.53 + 1.54.1 Windows x64 (as well as Snes9x 1.54.1 libretro+RPi).

**Comment by OV2** [comment]
I can't reproduce, all of those games work fine with 1.54.1.
Do you have the sufami turbo bios in the bios dir and named stbios.bin? And then load the game in slot A via File->Load Multicart?

**Comment by nemo93** [comment]
Silly me. I just didn't know about that. All games work fine indeed as you mentioned. Let's close this off and let me apologize for the tme waste.
