### ISSUE TITLE
[Win] Adding separate configuration for DirectDraw?

### ISSUE THREAD

**Issue by bonimy** [snes9xgit/snes9x#233]
# Issue
[DirectDraw](https://en.wikipedia.org/wiki/DirectDraw) is a deprecated API. It was last included in the DirectX June 2008 SDK, which Microsoft no longer supports.
To my understanding, we keep it for Windows XP users. Can I get some confirmation on this? snes9x, in its current configuration, is very hard for new users to build if they don't have [DirectX June 2008 SDK](https://www.google.com/search?q=directx+june+2008+sdk) installed on their computer for no reason. They would have to strip out all of the DirectDraw code and exclude the ddraw.lib file from the Library Includes option.
# Resolution
The Visual Studio solution presently has two configurations:
- Debug
- Release

I propose we separate this into four:
- Debug
- Release
- DDraw Debug
- DDraw Release

Alternatively, we could name it _XP Debug/Release_, or whatever names fit them.

The differences of the configuration will be a preprocessor define `USE_DDRAW` that removes or adds the DirectDraw-related code from the project. Additionally, we should explicitly remove the ddraw.lib library include from the Debug/Release configuration.

**Comment by OV2** [comment]
I've already merged the changes of your old pull request #184 a while ago, and since then ddraw is not compiled in by default.

**Comment by bonimy** [comment]
Hmm. Maybe my old branch is very out of date. Let me do a quick update and see where it's all at.

**Comment by bonimy** [comment]
Oh okay. So it has. My mistake then. We can close this issue (unless having a configuration switch for DDRAW users is something you'd like implemented).
