### ISSUE TITLE
Snes9x crashes entirely when opening some roms.

### ISSUE THREAD

**Issue by ghost** [snes9xgit/snes9x#235]
Snes9x crashes when one tries to open the following two roms:

NFL Quarterback Club (USA) (Beta)
Little Magic (Japan) (Beta) (no rom of this game seems to work)

Also, some other beta roms do not work with Snes9x 1.54.1 (x64) right now, but they work with Higan:

Little Magic (Japan)
Little Magic (Europe) (Proto)

Super Loopz (Europe) (Proto)
Eurit (USA) (Proto)
Shinseiki Odysselya (Japan) (Sample)
Pop'n TwinBee (Japan) (Putative Sample) [b]
Zool (USA) (Sample)
SD F-1 Grand Prix (Japan) (Sample)
Wolfenstein 3D (USA) (Beta 1)
Dream TV (USA) (Beta 2)
Contra IV - The Alien Wars (USA) (Beta)
Mario Paint (Japan, USA) (Beta)
Uchuu no Kishi Tekkaman Blade (Japan) (Beta)
Road Runner (Europe) (Beta)
Marvel Super Heroes - War of the Gems (USA) (Beta)
King Arthur's World (USA) (Beta)
Killer Instinct (USA) (Beta)

Thank you all.

**Comment by qwertymodo** [comment]
Since most of these are betas, my immediate suspicion is that the issue is due to the mapping heuristics believing the ROM and SRAM size fields in the internal headers, which are quite often wrong in betas

For instance, Little Magic (J) (Beta) has a value of 0x9C for ROMSize and 0x22 for SRAMSize, which correspond to a ROM size of 2^166 bytes and SRAM size of 2^44 bytes.  Attempting to allocate buffers that large is... problematic.

**Comment by qwertymodo** [comment]
As a potential fix, we could just cap the ROM size to the actual file size (minus any headers), and RAM size to 1M or something like that in cases where the header is so wildly off. It might not actually run properly, especially if there are any RAM mirroring-based copy protections, but that's still probably better behavior than trying to allocate an exabyte array and crashing.

**Comment by bearoso** [comment]
Sounds OK.

**Comment by qwertymodo** [comment]
Does anybody know the largest legitimate header sizes for ROM and RAM in the official library?

**Comment by bearoso** [comment]
Little Magic is getting confused by a WRAM refresh that occurs late while loading the SMP. It's timing-related.

**Comment by SimpleTease** [comment]
There's that Canoe hack which "fixes" this game in snes9x (and modifies lots of other unneeded stuff). Asked around some more and supposedly it's some apu engine "bug" that was something:

[code]
0DAC 7E F4     CMP Y,$F4            A:10 X:00 Y:01 S:CB P:nVpbHizC 114 1366 1342
0DAE B0 ED     BCS $0D9D            A:10 X:00 Y:01 S:CB P:nVpbHizC 115 0042 0041
==> 10 E9  BPL $0D9D

0DB0 7E F4     CMP Y,$F4            A:00 X:00 Y:00 S:CB P:nVpbHizc 007 0286 0267
0DB2 B0 E9     BCS $0D9D            A:00 X:00 Y:00 S:CB P:nVpbHiZC 007 0354 0330
==> 10 E9  BPL $0D9D
[/code]

Heard that using Rendering Ranger R2 audio timing hack works in older snes9x 1.51. Supposedly lots of Human games have this exact same audio "bug" also.

**Comment by bearoso** [comment]
Fixed the ones of these that are legitimate.
