### ISSUE TITLE
LoROM mapping issue

### ISSUE THREAD

**Issue by qwertymodo** [snes9xgit/snes9x#242]
Passing along this report which was sent to me by Conn, one of the guys behind the BS Zelda and a bunch of MSU-1 hacks (I'm curious if this might be related to #241):

I found a bug in snes9x 1.55 lorom addressing, which doesn't appear in 1.51, zsnes or bsnes. If you expand a lorom to 4 MB you can address until pc 38/0000 normal (lorom 6f:fe00, fastrom ef:fe00), as soon it gets higher it would reach 70:0000, which is sram/ram, so both, lorom and fastrom switch to f0:8000 here.

and here's the problem with snes9x 1.55: if I expand a rom to 4 MB, and address a lorom to an address there, like here I tested in super ghouls n ghosts (geiger log):

$00/812F 22 00 F3 FB JSL $FBF300[$FB:F300]   A:00FF 

$FB/F300 A2 01       LDX #$01                A:00FF 
$FB/F302 A0 0B       LDY #$0B                A:00FF 
$FB/F304 6B          RTL                     A:00FF 

this address is taken by snes9x 1.51, zsnes, bsnes but not the new snes 1.55 (this emu will crash).

It is rather important that the new snes versions take these addresses, because Ancient Stone Tablets, Conker and so on use these for the ending images.
I tried AST week 1 and it breaks as soon such an address is about to be executed :(

Is there any easy way to fix this?

**Comment by bearoso** [comment]
Revert the Light Fantasy commit, and that'll likely fix it.

**Comment by qwertymodo** [comment]
Reverting that fixed #241 I'll send it to Conn and have him test the games he had issues with.

**Comment by qwertymodo** [comment]
Conn confirms that reverting 9f84ba9d0f846042bd6beff84d7f6c8fa04b48d4 fixes his issues as well.

**Comment by qwertymodo** [comment]
Ok, so I'm going to adjust the map_LoROMSRAM function to match higan: https://gitlab.com/higan/higan/blob/master/icarus/heuristics/super-famicom.cpp#L103

The 2 main changes are

if (ROMSize >=10) ==> if (ROMSize > 11 || SRAMSize > 5)

and

map_index(0x70, 0x7f... ==> map_index(0x70, 0x7d...

I feel like that second one could potentially cause issues, but I've double checked, and that matches both the icarus heuristics and every LoROM mapped game in byuu's database.  I'm going to upload test builds before I push, so please give them a try: https://dl.qwertymodo.com/snes9x_msu.zip

**Comment by qwertymodo** [comment]
I managed to test Light Fantasy with the new mapping, and saving works, so I'm going to go ahead and push e4d08bb71a3355bb4ba0a31885584754df2e1dab to close this.
