### ISSUE TITLE
[Windows] OpenGL crashes in default option

### ISSUE THREAD

**Issue by ofernandofilo** [snes9xgit/snes9x#245]
I'm not a programmer. In the config file the default option is:
`    OpenGL:DisablePBOs          = FALSE  # do not use PBOs in OpenGL mode, even if the video card supports them
`

But if we read the comment we will think that the default option need to be TRUE instead of FALSE:
> do not use PBOs in OpenGL mode, even if the video card supports them

And when I change the valeu in the config file to TRUE, the emulator run in OpenGL mode.

So I believe that line 897 in the "wconfig.cpp" should be change for:
`AddBoolC("OpenGL:DisablePBOs", GUI.OGLdisablePBOs, true, "do not use PBOs in OpenGL mode, even if the video card supports them");`

Instead of:
`AddBoolC("OpenGL:DisablePBOs", GUI.OGLdisablePBOs, false, "do not use PBOs in OpenGL mode, even if the video card supports them");`

obs.: There is a way to patch my snes9x.exe to change just this value? I would love to do it, xD

cheers!

**Comment by OV2** [comment]
By default pixel buffer objects are used because it is faster that way. The option to disable them is only for compatibility if it does not work as in your case.

**Comment by ofernandofilo** [comment]
If the problem is just my machine, then, the default comment must be change from:
> do not use PBOs in OpenGL mode, even if the video card supports them

to:
> do not use PBOs in OpenGL mode, when your video card don't supports them

the default option does not agree with the default comment.

cheers!

**Comment by OV2** [comment]
The comment is correct: s9x always asks your graphics driver if it supports PBOs, your driver tells it "yes I do", and then it crashes when it is used. In this case you can disable it with this option, even though your card says it supports them.

**Comment by ofernandofilo** [comment]
I'm sorry, I'm not an english speaker nor a programmer, but you are clearly lacking in truth.

>The comment is correct - by OV2.

The commend is clear: **"do not use PBOs in OpenGL mode"**

> s9x always asks your graphics driver if it supports PBOs - by OV2

The command is clear: AddBoolC("OpenGL:DisablePBOs", GUI.OGLdisablePBOs, **_FALSE_**, "do not use PBOs in OpenGL mode, even if the video card supports them"); in line 897 of the file wconfig.cpp at:
https://github.com/snes9xgit/snes9x/blob/master/win32/wconfig.cpp

There is no ask to the video-card, none!

I was able to change the default behavior through ImmunityDebbuguer:
Original:
00686E7E     C78424 A401000>MOV DWORD PTR SS:[ESP+1A4],0
Patched:
00686E7E     C78424 A401000>MOV DWORD PTR SS:[ESP+1A4],1

Lastly, you are free to do anything. Anything. You do not need to change the code! But you do not have to lie. Say you do not want to change it or will not change it, fine!, But do not make excuses for it.

The behavior of the program is not in agreement with the comment present in the configuration file. Do you need to change it? No! But in this case it is necessary to live with this contradiction.

cheers

**Comment by OV2** [comment]
The code checks in [LoadPBOFunctions](https://github.com/snes9xgit/snes9x/blob/d174b82134f1d3d0370a59065618cd2401ac91c7/win32/COpenGL.cpp#L629) (glGetString).
