### ISSUE TITLE
Graphics corruption in Doom

### ISSUE THREAD

**Issue by j0r9** [snes9xgit/snes9x#247]
The walls in Doom have are filled with graphical artifacts. The pattern changes with each movement, however when you move back and forth in the same position, same same artifacts re-appear, so it's most likely a bug SuperFX 2 rendering (wrong calculation or something).

This is one of the major bugs left in Snes9x, that affects every version since 1.51 or so. Some users including myself are even contemplating offering a monetary bounty for getting this fixed. Any help or feedback is greatly appreciated.

![doom1](https://user-images.githubusercontent.com/4481215/31450969-22dcc084-aeab-11e7-9770-5d46739ef196.png)

**Comment by bearoso** [comment]
It affects every version, period. The assembly SFX code was dropped in 1.51, and it didn’t affect that, which is why you didn’t see it on x86 until then.

**Comment by Fergdog** [comment]
Is doom the only SuperFX2 game with lots of issues? I haven't noticed any problems with Yoshi's Island or Star Fox 2 which are both SuperFX2 games.

**Comment by jjfmz42015** [comment]
I can confirm that this does in fact happen with DOOM.


My solution was to use BSNES and gasp ZSNES.

**Comment by j0r9** [comment]
Still not fixed in 1.55 :(

**Comment by jjfmz42015** [comment]
do what i did switch to bsnes-plus


loads the roms like snes9x not like official higan and everything i can throw at it works flawless.

**Comment by bearoso** [comment]
Yep, not fixed yet, will probably require some transliteration of the ASM version. Use higan/bsnes for now, or even better, use a port of the real DOOM.

**Comment by qwertymodo** [comment]
Some useful test cases (all of which are currently failing): https://board.byuu.org/viewtopic.php?f=16&t=1871

**Comment by bearoso** [comment]
That’s surprising. I didn’t think the opcodes would be so off. Very helpful, though.

**Comment by qwertymodo** [comment]
Here's the full test ROM suite compiled:

[GSUTest.zip](https://github.com/snes9xgit/snes9x/files/1489162/GSUTest.zip)

**Comment by bearoso** [comment]
Fixed.

**Comment by jjfmz42015** [comment]
Can someone compile a test build of this please?

**Comment by bearoso** [comment]
Don't know where your test build comment went, but you can always click the little green checkbox to get to the Appveyor builds and download the job artifact, like here: https://ci.appveyor.com/project/snes9x/snes9x/build/job/j1bnikqty19au344/artifacts

**Comment by bearoso** [comment]
What test roms? The krom tests here?: https://board.byuu.org/viewtopic.php?f=16&t=1871
We're passing all those, unfortunately. The cause was resetting register 14 after x many cycles in the synchronization code, which Doom was using to read texture locations from ROM.

**Comment by jjfmz42015** [comment]
I deleted my comment thinking I didnt want to be rude. Used your link, works great! Thank you.
