### ISSUE TITLE
PowerFest 94 - Super Mario Kart

### ISSUE THREAD

**Issue by ghost** [snes9xgit/snes9x#251]
Snes9x stops responding after try to start the game. It works in Higan/Bsnes

**Comment by kps501** [comment]
bsnes
80805d lda $106000   [106000] A:ffff
808061 bit #$0002             A:8080

106000-6fff = 8080
107000-7fff = 8484

snes9x
$80/805D AF 00 60 10 LDA $106000[$10:6000]   A:FFFF
$80/8061 89 02 00    BIT #$0002              A:FFFF
*crash*


Hope this helps snes9x authors? Have no idea what this means.

**Comment by kps501** [comment]
Found an answer. DSP1GetByte returns 0xff when out_count = 0. This should be 0x80 or 0x00 or something ~0x0002. 0xff blows up game. bsnes+ uses 0x80.

**Comment by bearoso** [comment]
Ok, went and changed it.
