### ISSUE TITLE
Tengai Makyou Zero - English Translation Support

### ISSUE THREAD

**Issue by wumd-ar** [snes9xgit/snes9x#253]
Hello,

The English translation recently released for this game includes a ROM expansion modification that's unsupported by most emulators, however DougRPG of the translation team managed to make a repro cartridge that boots up on real SNES hardware. Considering you already have support for the MSU-1 that is in a similar situation, I figured you would be at least open to considering the idea.

Higan and bsnes can already boot this game with the xml file included with the translation. That file has information about the internal ROM layout which may be useful. It can be downloaded from here:
http://www.romhacking.net/translations/3243/
byuu said he will implement support for the feature sometimes in the future.

A fork of Snes9X 1.5.4 with this support already added:
http://www.mediafire.com/file/q8hqh0cdfwy48sd/snes9x_tmz.rar
A fork of Snes9X GX with this support already added and its source:
http://www.dropbox.com/s/7r1kwcjathngppr/spc7110-patch.zip?dl=1
http://github.com/dborth/snes9xgx/releases/tag/4.3.7

I have another slightly related request. Older emulators used to have the option to set the real time clock for this game and the clock used with Satellaview games. Currently however, emulators use the system time and date. Is it possible to bring back an option to override those and set our own time and date?

Thanks a lot.

**Comment by qwertymodo** [comment]
I don't have time to push the commit today, but here's a test build: https://dl.qwertymodo.com/snes9x.zip

**Comment by ImSpecial** [comment]
Not sure if its me or your build, but I can't seem to get it to work with your test build linked. But then again this translation is a bit different then most which includes some other files for the emulator to read in order to work properly, so maybe I'm just missing something. One of the translators posted this [SNES9X build](https://depositfiles.com/files/zeg5av82f) that does work though, so all the files required are in that zip ready to go, so swapping your test build with his should have everything still working, but it's a no go.

**Comment by wumd-ar** [comment]
Unfortunately, the translation is still failing the built-in checks at startup.

The error messages and failed checks in the game are:
"The backup data isn't working"
Failed A Button Checks (1/10):
D-PORT ACC FF 00 NG

Failed B Button Checks (2/2):
RTC Backup NG
S-RAM Backup NG

It's just like the older versions where the translation was not supported.
Forcing the game to boot with save files from the JP version results in a black screen.

At any rate, thanks a lot for looking into this.

**Comment by qwertymodo** [comment]
Just to confirm, your patched ROM file should have a SHA-1 of fd92dd90b125252cbe4d75ffabd46a9a16f06fd5 (which results in an invalid internal checksum, but that's the result I get from the .ips file at the RHDN link in the OP).  You should NOT be using the ROM splitter .jar, just load the 7MB .sfc file directly.  Using the 32-bit build I linked above, which should have a digital signature timestamped ‎Sunday, ‎October ‎22, ‎2017 9:55:21 AM, it is working fine here, at least as far as I am able to pass all of the A and B button self-checks, reboot into the game, set the current date and my birthday, and then continue into the game intro.  Maybe try deleting your .srm and .rtc file.

**Comment by ImSpecial** [comment]
Not sure what the deal is then, this is what I am getting. https://i.imgur.com/2wgIBWI.png

Both snes9x/x64 are clean (as in, no pre-existing config file.)

**Comment by qwertymodo** [comment]
So... potentially stupid question, but you did press 'A' at the first test prompt, right?  Accidentally hitting 'B' instead will result in the error screen you posted.

**Comment by qwertymodo** [comment]
Slight update to the test build, try re-downloading.  I missed a variable initialization.

**Comment by ImSpecial** [comment]
So... I have no words...

I was not hitting "A" because the config file was fresh, and my keys are normally shifted one place over, so I was hitting "B" all this time. After actually hitting "A", reset, "B", reset, the game now seems to works.

One thing I noticed was turbo does not work, which is weird. I also see that you have posted an updated build (have not tried yet.)

**Comment by qwertymodo** [comment]
I wonder if turbo is disabled due to the RTC (could potentially cause issues).

**Comment by ImSpecial** [comment]
Your guess is as good as mine, I noticed another user saying the same thing only the Fast Forward works in bsnes, so maybe bsnes does it a little different?

http://www.romhacking.net/forum/index.php?topic=23162.msg345765#msg345765

**Comment by qwertymodo** [comment]
I'm sure there is some bit of code which is intentionally disabling FF.  The fact that it works in bsnes just means bsnes doesn't choose to disable it under the same circumstances.

At this point, I'm kind of waiting on opinions from @bearoso and @OV2 on the question of merging in a game-specific mapping hack before I commit my code.  Here are the relevant changes, slightly modified from DougRPG's original patch:

memmap.cpp:
```
void CMemory::Map_SPC7110HiROMMap (void)
{
	. . .
	map_index(0x30, 0x30, 0x6000, 0x7fff, MAP_HIROM_SRAM, MAP_TYPE_RAM);
	if(Memory.ROMSize >= 13)
		map_hirom_offset(0x40, 0x4f, 0x0000, 0xffff, CalculatedSize, 0x600000);
	map_index(0x50, 0x50, 0x0000, 0xffff, MAP_SPC7110_DRAM, MAP_TYPE_ROM);
	. . .
}
```
(I'm not sure if the ROMSize check is actually useful or not, the size field is the same for the 5MB unmodified TMZ as it is in the 7MB translation)

spc7110dec.cpp
```
uint8 SPC7110Decomp::dataread() {
  unsigned size = memory_cartrom_size() > 0x500000 ? memory_cartrom_size() - 0x200000 : memory_cartrom_size() - 0x100000;
  . . .
```

spc7110emu.cpp
```
unsigned SPC7110::datarom_addr(unsigned addr) {
  unsigned size = memory_cartrom_size() > 0x500000 ? memory_cartrom_size() - 0x200000 : memory_cartrom_size() - 0x100000;
  . . .
```

**Comment by qwertymodo** [comment]
I went ahead and pushed the code to a new branch just so it's online in full (both for license compliance and because I know a bunch of the forks are trying to add it, might as well have it here).  If everybody is ok with adding a game-specific mapping hack, we can merge it into master.

https://github.com/snes9xgit/snes9x/commit/81d287cbd8d8d42099fb0b939fe21d5bccf75663

**Comment by OV2** [comment]
I have no problem with it, there aren't that many SPC7110 games that it could cause problems with.
But why is it subtracting 0x200000 for the wrap check and then only adding 0x100000 for the actual address?

**Comment by qwertymodo** [comment]
I believe the expanded ROM data is at the end of the file, so the main ROM still starts at 0x100000.

**Comment by bearoso** [comment]
I’m ok with it. If you want to enable fast forward, that’s ok, too.

**Comment by qwertymodo** [comment]
Ok, merged 81d287cbd8d8d42099fb0b939fe21d5bccf75663 and nuked the branch.  I'll poke around and try to figure out the FF issue.

**Comment by qwertymodo** [comment]
Fast-forward re-enabled in 7a1b270bb9bad4765294556dab1bbb7fe7544409

**Comment by ediielol** [comment]
> So... potentially stupid question, but you did press 'A' at the first test prompt, right? Accidentally hitting 'B' instead will result in the error screen you posted.

this was my mistake thank you your a lifesaver
