### ISSUE TITLE
[1.55] Mac version still reads 1.53

### ISSUE THREAD

**Issue by GB-CG** [snes9xgit/snes9x#260]
<img width="275" alt="screen shot 2017-11-20 at 9 13 55 pm" src="https://user-images.githubusercontent.com/11931125/33049198-ccd0ebb8-ce56-11e7-898e-dc6e58a08b80.png">

**Comment by qwertymodo** [comment]
Ok, should be fixed in d03700483c38ee1dc89476b9bfaea64ea32ddd7a
