### ISSUE TITLE
1.55 direct draw build not on this site under releases.

### ISSUE THREAD

**Issue by jjfmz42015** [snes9xgit/snes9x#261]
1.55 direct draw build not on this site under releases.

is it buggy? what version should i use?

http://www.s9x-w32.de/dl/snes9x-1.55-win32-ddraw-support.zip

I use D3d mode anyway. Just curious on thoughts and differences

**Comment by qwertymodo** [comment]
I guess I just overlooked it, simple as that.

**Comment by jjfmz42015** [comment]
is there an difference in which release is used if using D3D mode?

**Comment by OV2** [comment]
I simply forgot to turn on directdraw for the release compile, so I made an extra compile for those that really need it (there was a request in the s9x forums). There is no other difference other than that you can select directdraw as video output.

**Comment by jjfmz42015** [comment]
s9x forums??? I hadnt been on those forums in over a decade and thought they were dead. going to head over there and open an account!

**Comment by qwertymodo** [comment]
Ah, so I didn't miss it, it just wasn't there yet.  In any case, it's up here now too.
