### ISSUE TITLE
SNES9x reads Start button on control pad as Esc key

### ISSUE THREAD

**Issue by ms8889** [snes9xgit/snes9x#262]
I have an adapter that allows me to connect an old SNES controller with a usb adapter, but when I try to map the Start button to Start in the Input options, it disables it and just reads it as the Esc key. All that does is toggle the menubar at the top of the screen, and I can't use the Start button as normally in the game. I've also had this happen with third party controllers I've used with 9x. How can I fix this?

**Comment by bearoso** [comment]
You don't have any software like joytokey installed that might be remapping the button?

**Comment by ms8889** [comment]
I don't.

**Comment by ms8889** [comment]
See in my SNES9x's options, it says Esc is used to both toggle the menubar, as well as disable mapped keys. For some reason it keeps reading the Start button on any gamepads I use as the Esc key, so it just disables Start when I try to map it in Input Configuration. So when I play games, Start no longer pauses the games, it just toggles the menubar at the top of the screen. This is very problematic.

**Comment by bonimy** [comment]
Hi @ms8889. If I could, there's a few questions I'd like to ask to narrow down the issue.

* If you map a different button to "Start" in the controller layout, does Esc functionality still happen?
* If you map a keyboard key to "Start" does Esc still happen?
* If you unmap the "Start" button altogether, does Esc still happen?
* Could you share a screenshot of your Input Configuration menu and your Customize Hotkeys menu?
* Could you share your config.cfg file?

**Comment by bearoso** [comment]
Here's something else to try and narrow it down:
Open another application and do something like open a menu that would normally respond to ESC, then press the start button on the controller. Does the menu close or the ESC action happen there, too?

**Comment by ms8889** [comment]
Hello. Thank you for your responses. I'll answer the questions as best I can, hopefully we can get to the bottom of this issue.

Yes, the Esc function still happens if I map "Start" to a different button
Yes, Esc still happens if I map "Start" to a keyboard key
Yes, if "Start" is unmapped entirely, Esc still happens
Here are some screens of my Input Configuration, and my Customize Hotkeys Menu
![menus](https://user-images.githubusercontent.com/33909090/33190662-1f7b095c-d07d-11e7-945e-a80fbe2523a0.png)

Also, here's a screenshot of the menu, where you can see it says Hide menubar - Esc

![menu2](https://user-images.githubusercontent.com/33909090/33190709-d9939b56-d07d-11e7-8c03-0faa9731f116.png)

And I'm not sure how to give you my .cfg file, but there is a file called snes9x.conf, might that be what you need to see?

**Comment by bearoso** [comment]
Yeah, the snes9x.conf file is the one. You could try moving it out into another folder and see if the default configuration fixes it.

Also, try what I mentioned earlier: With no programs open, click the Windows start menu to open it, and then hit the Start button on your controller. Does the start menu close?

**Comment by ms8889** [comment]
Okay, I'll try moving the file.

And yeah, I can still use the Start button on the gamepad like Esc for other things too, including closing the start menu.

**Comment by ms8889** [comment]
Okay I'm still getting the issue even after moving the config file.

**Comment by bearoso** [comment]
Hmm. Then that narrows it down to something in your Windows configuration. Something is registering your controller as a keyboard. May be a secondary HID profile built into the device or some other program running. 

Can you look at your process list and shut down all the extraneous stuff? I know Steam has been known to cause this, so it might be the problem.

**Comment by ms8889** [comment]
Son of a gun! It WAS Steam doing that! I just had to tweak its controller configurations to resolve the issue!
Okay, well time will tell if this is the end-all fix to my problem, but it seems to be working so far! Thank you all very much for your help!
