### ISSUE TITLE
[Request] Merge input lag fix

### ISSUE THREAD

**Issue by vanfanel** [snes9xgit/snes9x#269]
Hi there,

Back in 2016, there was an input lag fix developed for the snes9x and snes9x2010 cores on the RetroArch forum and git repository.
https://github.com/libretro/snes9x/commit/a62198f9c61fa9a6f6afa6d9365e18bb8be17bd8
With these fixes:
https://github.com/libretro/snes9x/commit/bff9d87f772f6d1688bccf3bb1c6bd34631ffeee
https://github.com/libretro/snes9x/commit/c380131746009431d717366d897365297a2bdb79

Can you guys please merge this optional fix? It was tested and brings 1 whole frame less of input lag to snes9x.

Thanks!

**Comment by bearoso** [comment]
This was done already: commit 10e0ef005d1d86301d8b87215ef23821bdd4d441
