### ISSUE TITLE
libpng and zlib source not found

### ISSUE THREAD

**Issue by llimpeo** [snes9xgit/snes9x#270]
libpng and zlib source not found, require for compile project snesx or source from download.

**Comment by qwertymodo** [comment]
I've been wanting to add those as submodules for awhile now.  Now that I have write access, I'll look into it.  I think the biggest hurdle will be moving them inside the main snes9x source tree and getting all of the various Makefiles/vcxproj files pointed to the new location.

**Comment by qwertymodo** [comment]
Ok, so I managed to track down what I believe to be the canonical git repositories

libpng: https://git.code.sf.net/p/libpng/code
zlib: https://github.com/madler/zlib.git

I'm going to try with the latest version of each (libpng 1.6.34 and zlib 1.2.11).  I'm currently placing them in [repo root]/libs/(libpng,zlib), but if anybody has any objections I can move them elsewhere within the repo source tree.

**Comment by qwertymodo** [comment]
Wait, are the manual downloads only necessary for the Windows builds?  The Linux Makefiles seem to refer to system installed libs.  If that's the case, it would make more sense to just put the submodules directly into the win32 tree i.e. /win32/(libpng|zlib)/src

**Comment by bearoso** [comment]
Yes, Unix uses system libs, and libz and libpng are dirt-standard ones.

**Comment by qwertymodo** [comment]
What about OSX?  I know we don't currently have builds working there, but if I'm going to make this change I'd like to at least try to be consistent across the board.

**Comment by bearoso** [comment]
OS X uses frameworks. I don’t think that’s well-facilitated by in-tree sources. You should keep the sub modules in the win32 directory.

**Comment by qwertymodo** [comment]
Ok closing via ea39685ccdcc9a177a924856224c2a962539185b

If you checked out the source using git, you should be able to pull in the submodules by running

`git submodule init && git submodule update`

**Comment by bearoso** [comment]
I remembered that The OS X port had some static libs, and sure enough, a libz.a is there in the tree. So maybe putting these in the root is OK. What you’ve done is fine for now, though, until someone can update the OS X port.
