### ISSUE TITLE
Build failure with CFLAGS="-ggdb"

### ISSUE THREAD

**Issue by khumba** [snes9xgit/snes9x#272]
Hello,

snes9x-1.55 on Gentoo amd64 fails to build when CFLAGS/CXXFLAGS contains `-ggdb`, because unix/configure.ac has the following code:

    # Remove -g and -O2 flags manually.

    if test "x$CFLAGS" != "x"; then
    	CFLAGS="`echo \"$CFLAGS\" | sed -e 's/-g//'`"
    	CFLAGS="`echo \"$CFLAGS\" | sed -e 's/-O2//'`"
    fi

    if test "x$CXXFLAGS" != "x"; then
    	CXXFLAGS="`echo \"$CXXFLAGS\" | sed -e 's/-g//'`"
    	CXXFLAGS="`echo \"$CXXFLAGS\" | sed -e 's/-O2//'`"
    fi

which causes `gdb` to be passed as a literal argument to GCC:

    make --jobs=8 --load-average=16
    x86_64-pc-linux-gnu-g++ -I. -I.. -I../apu/ -I../apu/bapu -I../jma/ -I../filter/ -c -pipe -march=native gdb  -DJOYSTICK_SUPPORT -DUNZIP_SUPPORT -DSYSTEM_ZIP -DJMA_SUPPORT -DPTR_NOT_INT -DMITSHM ../apu/apu.cpp -o ../apu/apu.o
    x86_64-pc-linux-gnu-g++ -I. -I.. -I../apu/ -I../apu/bapu -I../jma/ -I../filter/ -c -pipe -march=native gdb  -DJOYSTICK_SUPPORT -DUNZIP_SUPPORT -DSYSTEM_ZIP -DJMA_SUPPORT -DPTR_NOT_INT -DMITSHM ../apu/bapu/dsp/sdsp.cpp -o ../apu/bapu/dsp/sdsp.o
    x86_64-pc-linux-gnu-g++: error: gdb: No such file or directory
    make: *** [Makefile:77: ../apu/apu.o] Error 1
    make: *** Waiting for unfinished jobs....
    x86_64-pc-linux-gnu-g++: error: gdb: No such file or directory
    make: *** [Makefile:77: ../apu/bapu/dsp/sdsp.o] Error 1

It would be nice if this flag could be used with the build.  Also note there are other `-g...`, flags, as well as `-g...<level>`.

Thanks!

**Comment by SoapGentoo** [comment]
In general, the proper solution here is to use the `AX_CHECK_ENABLE_DEBUG` macro from the Autoconf archive before `AC_PROG_CC`, which only mucks with user flags if `--enable-debug` is given to `configure`.

**Comment by bearoso** [comment]
Yeah, we shouldn't be messing with flags like that. I removed that block, and moved the user's flags to the end, so they take precedence.
