### ISSUE TITLE
Snapshot every 10 frames, then exit, do not works

### ISSUE THREAD

**Issue by julien2512** [snes9xgit/snes9x#273]
Hi,

I am trying TensorFlow to learn playing on SFII on snes9x.
To make it play and play again, I am trying to get snapshots after about 10 frames then exit.
So that I can start it over after learning on 10 frames more, and again, and again.

I tryed adding S9xFreezeGame in many different files (gfx.cpp, controls.cpp, even cpuexec.cpp) but the snapshots are randomly scratched (black screen).
I can't figure why snapshots always works by keystroke, but randomly works by code.
On my best try, I got 5 snapshots every 10 frames, then the 6th do no works properly.

The oops file do not help as it happens while Resetting the game (manually or from beginning).

Finally, I tryed using Settings.Paused & Settings.StopEmulation to TRUE (as I see in server.cpp) but it does not change anything.

I spend only a few days on it, but now I am stuck. I am considering now sending a keystroke by code to simulate the keyboard ! 
My code is on my fork, branch tf (but I did not share the non working features).

I think you know better than me how the snes9x works, and may be exactly know where to put S9xFreezeGame and on which conditions ? Or maybe it is not a possible thing to do ?

Regards,

**Comment by qwertymodo** [comment]
When playing normally, if you freeze the game and then take a snapshot, it won't actually take the snapshot until you resume or frame advance. You might try that.

**Comment by julien2512** [comment]
Yes, I know. That's because the action is stored in a FIFO and take action only at resume. I mainly use gtk, maybe it is different with the unix version, I need to try it.

What I will also try to do is to add the action command on that gtk FIFO to simulate the key.
There must be another solution.

**Comment by OV2** [comment]
You should always create snapshots outside of S9xMainLoop. The rewind feature takes a snapshot every x frames, in the gtk port you can find it in [gtk_s9x.cpp](https://github.com/snes9xgit/snes9x/blob/886ea13/gtk/src/gtk_s9x.cpp#L365)

**Comment by julien2512** [comment]
Thank you both. I will look at rewind sources and try to snapshot after a few cycle after pause.

**Comment by julien2512** [comment]
It is true S9xStreamToFreeze is used both in snapshot & rewind features. I keep you in touch.

**Comment by julien2512** [comment]
I put my code in gtk_s9x.cpp and it works.
The solution wasn't to find the conditions to make a snapshot, it was to find the conditions not to make a snapshot ! It seems not to be possible anywhere inside the main loop.

Thanks for all.

**Comment by julien2512** [comment]
Oh, and Zangief wins this time ;)
