### ISSUE TITLE
Koryu no Mimi

### ISSUE THREAD

**Issue by hossbags2** [snes9xgit/snes9x#279]
After using the English patch, the game freezes up just before you start to fight at the beginning.

**Comment by LodanZark** [comment]
the romhack link: https://www.romhacking.net/translations/852/
I had the same issue but I suppose the issue it's related with patch and not the emulator itself.

**Comment by bearoso** [comment]
It's a pretty old patch, so it might be incorrectly coded. Try it with bsnes/higan, and if it works there then this is a legitimate bug.

**Comment by bearoso** [comment]
Seems to be a bug in the emulator.

**Comment by OV2** [comment]
I've changed the DMA timing for this translation, that causes it to trigger correctly. Besides this freeze the strange loop the translation is doing also causes lag every time you hit an enemy when the name pops up, but that also happens in higan.

**Comment by bearoso** [comment]
Honestly, now that I know that slowdown isn't normal, I don't think it's really necessary to have a game hack for this. The translation patch is so bad that it's unplayable on anything but zsnes, even if it doesn't lock up. :-)

**Comment by LodanZark** [comment]
A new update to the rom translation was released: https://www.romhacking.net/translations/852/
I assume that fix became irrelevant now

**Comment by bearoso** [comment]
It's working on latest git, but the patch is still needed or it locks up.
