### ISSUE TITLE
Speedy Gonzales Lockup on level 6-1

### ISSUE THREAD

**Issue by Cibomatto2002** [snes9xgit/snes9x#280]
Has this game been fixed? I haven't used snes9x for some time now.

On Level 6-1 the game freeze if I press this green button (and it is necessary to advance in this level)

Is there anymore games that lockup like this?

**Comment by bearoso** [comment]
I don't know if we have the timing granularity for this. It requires an HDMA read to change the data register right before an open bus read. I don't think Snes9x's DMA implementations actually set the MDR properly, either, especially since it's stored in two different places in the code.

**Comment by Cibomatto2002** [comment]
Is this something to get fixed on the to do list that is if you have a to do list?

**Comment by SimpleTease** [comment]
There's a hack that fixes the game and is a temporary solution
http://www.romhacking.net/hacks/3875/

**Comment by bearoso** [comment]
I tried to use a level select cheat to get to this level, but then there's this transporter thing that doesn't function.

If someone wants to run through the game and put up a save state before the level or at the switch, feel free. I definitely don't want to play through this entire piece of crap.

**Comment by Cibomatto2002** [comment]
[Speedy Gonzales - Los Gatos Bandidos (USA) (Rev 1).zip](https://github.com/snes9xgit/snes9x/files/2018688/Speedy.Gonzales.-.Los.Gatos.Bandidos.USA.Rev.1.zip)

**Comment by qwertymodo** [comment]
Sorry about the hasty edit @Cibomatto2002 , that was a save state, not a ROM.  My mistake.

**Comment by Cibomatto2002** [comment]
It's not a ROM it's a save state I had to zip it up because it says We don't support that file type.
[Speedy Gonzales - Los Gatos Bandidos (USA) (Rev 1).zip](https://github.com/snes9xgit/snes9x/files/2018701/Speedy.Gonzales.-.Los.Gatos.Bandidos.USA.Rev.1.zip)

**Comment by qwertymodo** [comment]
Yeah, I saw that and restored your original comment.  I had initially removed it because I mistakenly thought you had also included the ROM file.  Obviously not the case, mea culpa, carry on.

**Comment by bearoso** [comment]
Well, it certainly isn't comprehensive, since we should be writing to OpenBus (the MDR) many more places, but I added it to S9xSetPPU, which didn't have it before, and that's used in HDMA, and this fixes the game. If this game had used indirect addressing, it wouldn't have happened because we update OpenBus in S9xGetWord.

**Comment by Cibomatto2002** [comment]
Thanks for getting this fixed.
