### ISSUE TITLE
Cheats Improvements

### ISSUE THREAD

**Issue by Cibomatto2002** [snes9xgit/snes9x#281]
Could someone add more spaces to the Cheat Description so I could explain my codes better? it only has 22 spaces. Trying to add this text to this Code Skip intro and start on Planet Zebes on new game. DD38-C4A8. Super Metroid game.

**Comment by bearoso** [comment]
The cheats support in Snes9x is completely terrible. It needs an almost complete overhaul, to be honest. Variable number of cheats, longer descriptions, grouping for multiple codes, and a file format that is human-readable.

**Comment by qwertymodo** [comment]
If we ever replace the cheats format, I'd suggest the higan format, it ticks pretty much all the boxes, and cross compatibility never hurts.

**Comment by Cibomatto2002** [comment]
The higan format would be great I have a lot of codes for that emulator that i'm having to redo for Snes9x 1.55 wish there was some kid of converter to do the work for me.

**Comment by Cibomatto2002** [comment]
Where can I download the cheats.bml file for Snes9x Git (2018/05/04)?

**Comment by Cibomatto2002** [comment]
Never mind Found it.

**Comment by OV2** [comment]
Implemented with 448d7e66607533604033bb0235d7aef34ac53abf

I've included cheats.bml in the testbuild zip file.

**Comment by Cibomatto2002** [comment]
Thank you.
