### ISSUE TITLE
Controller disconnect crashes Snes9x

### ISSUE THREAD

**Issue by edale2** [snes9xgit/snes9x#282]
I'm on Windows 10 x64, using an Xbox 360 wireless controller with an official Microsoft dongle (this kind: https://www.amazon.com/Microsoft-Xbox-Wireless-Receiver-Windows/dp/B000HZFCT2 ), and SNES9x v1.55.

If I don't touch my controller for 5 min or so, it shuts itself off, and this causes SNES9x to crash.

**Comment by EnderofGames** [comment]
Possible repeat of issue #137

**Comment by vaendryl** [comment]
I can confirm the exact same thing happens to me. same OS, same controller and same dongle. when the controller goes into standby mode it crashes the emulator. the emulator gives no error, nor does there seem to be an error log generated. instead, the OS reports the software has stopped responding and must be terminated.

**Comment by OV2** [comment]
It seems to be a bug in the windows multimedia functions that snes9x is using. I'll probably just disable hotplugging support and add a menu entry to scan for controller changes.

**Comment by vaendryl** [comment]
I've just discovered that this crash *does not occur* when you disable the "Pause when inactive" option.

**Comment by OV2** [comment]
Since the crash is somewhat random this probably just changed the timing a bit. I need to let the controller turn of a few times to cause a crash.

**Comment by OV2** [comment]
Joypad recheck is now a manual menu entry.
