### ISSUE TITLE
Super Punch-Out!! crashes while fighting Mad Clown

### ISSUE THREAD

**Issue by furrykef** [snes9xgit/snes9x#285]
This was discussed in issue #122, but that one also discussed other issues that appear to be unrelated, so I'm creating this one to focus specifically on the Mad Clown bug.

Here's what I've been able to figure out. The IRQ routine uses a variable, $4b, to decide what to do. The NMI routine always zeroes out this variable. On the offending frame, BSNES Plus shows that an IRQ is triggered which sets $4b to a nonzero value, then the NMI is triggered during the IRQ routine to zero it back out. Thus, the next IRQ will find zero in $4b and the game will behave as expected.

In snes9x, if I'm understanding this correctly, sometimes a DMA causes the NMI to be missed, which means $4b doesn't get cleared and the next IRQ misbehaves. Anomie's SNES Timing Doc claims that a DMA can never cause an NMI to be missed, only delayed until the DMA is complete.

This is the tracelog that snes9x produces in the offending section (with some WRAM refreshes trimmed out):

```
$00:A254 8D 0B 42    STA $420B  [$00:420B]   A:2101 X:6000 Y:0088 D:2100 DB:00 S:06F2 P:envMxdizc HC:0384 VC:216 FC:05 011
*** WRAM Refresh  HC:0538
-snip-
*** WRAM Refresh  HC:0534
$00:A257 AD 90 0F    LDA $0F90  [$00:0F90]   A:2101 X:6000 Y:0088 D:2100 DB:00 S:06F2 P:envMxdizc HC:1340 VC:243 FC:05 011
$00:A257 AD 90 0F    LDA $0F90  [$00:0F90]   A:2101 X:6000 Y:0088 D:2100 DB:00 S:06F2 P:envMxdizc HC:1340 VC:243 FC:05 011
$00:A25A F0 08       BEQ $08    [$A264]      A:2104 X:6000 Y:0088 D:2100 DB:00 S:06F2 P:envMxdizc HC:0008 VC:244 FC:05 011
$00:A25C AE 91 0F    LDX $0F91  [$00:0F91]   A:2104 X:6000 Y:0088 D:2100 DB:00 S:06F2 P:envMxdizc HC:0024 VC:244 FC:05 011
$00:A25F 86 16       STX $16    [$00:2116]   A:2104 X:6900 Y:0088 D:2100 DB:00 S:06F2 P:envMxdizc HC:0064 VC:244 FC:05 011
$00:A261 8D 0B 42    STA $420B  [$00:420B]   A:2104 X:6900 Y:0088 D:2100 DB:00 S:06F2 P:envMxdizc HC:0092 VC:244 FC:05 011
*** WRAM Refresh  HC:0542
-snip-
*** WRAM Refresh  HC:0538
$00:A264 A2 00 00    LDX #$0000              A:2104 X:6900 Y:0088 D:2100 DB:00 S:06F2 P:envMxdizc HC:0292 VC:002 FC:06 011
```

Here we see rendering ended and we moved on to a new frame without triggering NMI.

I'll take a whack at fixing this, but I'm completely unfamiliar with the snes9x codebase, so I don't know if I'll succeed.

**Comment by joepogo** [comment]
Nice man! Hopefully it's an easy fix. Thanks for posting this up! When I posted the hook issue it was something totally on my end. Hopefully all goes well with this. Please keep us updated.

**Comment by furrykef** [comment]
This was the commit that added `CPU.NMILine = FALSE;` line: https://github.com/snes9xgit/snes9x/commit/c3ce28b49d84d451541459f65af38f11326136b5#diff-62330ba1c266acb4158ab0d413eb12a0

**Comment by bearoso** [comment]
I don’t know what zones’ thinking was. We can remove that and see if it breaks anything.

**Comment by furrykef** [comment]
It's a bit of a wild guess, but I'm thinking the idea was that's when /NMI gets pulled high on hardware (I've yet to confirm this by any means), and the code was attempting to model the physical NMI line. Unfortunately, that's not the way the emulator actually uses it; it uses it as an NMI pending flag, and (as Anomie's doc shows) it's possible for an NMI to be pending while the /NMI line is high.

**Comment by furrykef** [comment]
It just came to my attention that zones's line was replacing the line `CPU.Flags &= ~NMI_FLAG;`, which probably did the same thing; the bug might actually predate the move to github.

**Comment by OV2** [comment]
We should probably rename it NMIPending and not reset it there (and also leave the NMITriggerPos). The actual NMILine flag is set directly in 0x4210, and should correctly be reset on VC=0 or when reading.

**Comment by bearoso** [comment]
Ok, I pushed a commit to the newcheats branch, since that's kind of my "working" branch ATM. Changed NMILine to NMIPending, removed the reset.

**Comment by bearoso** [comment]
Closing this as fixed, then.
