### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by bearoso** [snes9xgit/snes9x#287]
I made a couple new icons with blender to replace the existing Gtk+ icon:
![snes9xbig](https://user-images.githubusercontent.com/16159164/39539147-86bab5f4-4e04-11e8-8aa3-616aa6cbb4ac.png)
I'm leaning towards this simple one, which is just a fancy SFC/SNES logo:

![snes9x_128x128](https://user-images.githubusercontent.com/16159164/39547543-88edd4dc-4e1d-11e8-93b6-2fe9f33a8a6a.png)![snes9x_64x64](https://user-images.githubusercontent.com/16159164/39547597-a8ed1c5c-4e1d-11e8-89b1-2ee4bbb34e63.png)![snes9x_32x32](https://user-images.githubusercontent.com/16159164/39547599-aaa94912-4e1d-11e8-8481-65dbd45e9ad2.png)

But I also did this, which is more original, and when viewed at an angle an X made out of SNES buttons, but it's a little busy:
![snes9x_128x128](https://user-images.githubusercontent.com/16159164/39539285-d33b04e2-4e04-11e8-9188-05cdd18dccfc.png)![snes9x_64x64](https://user-images.githubusercontent.com/16159164/39539290-d5e47ade-4e04-11e8-8b63-4712dd4db411.png)![snes9x_32x32](https://user-images.githubusercontent.com/16159164/39539292-d82182b0-4e04-11e8-8c43-4ce23e57d463.png)

I'd also like to update the ancient Win32 icon. Any preferences or other possible submissions?

**Comment by OV2** [comment]
I'd also lean more towards the logo - the X might be hard to see in 16x16. As for the win icon: I don't mind changing it. The old one had 9X directly in the logo, which was nice, but I'm also fine with a plain logo.

**Comment by OV2** [comment]
One thing against the logo icon: it would look really similar to the older bsnes icon.

**Comment by bearoso** [comment]
The bsnes icon is also just the SFC/SNES logo with different coloration/style. No one's going to confuse the two because of the icon, and higan already has a new, unique logo.

**Comment by OV2** [comment]
I personally don't mind, I just expect there will be some users that have both pinned to start / taskbar like this: https://i.ytimg.com/vi/SSYuQelaxkM/maxresdefault.jpg
Those will probably complain.

**Comment by bearoso** [comment]
Ok, I've got the answer. We'll stick with the purple US SNES colors Snes9x has used before:
![snes9x_128x128](https://user-images.githubusercontent.com/16159164/39593992-0b13efb0-4ed1-11e8-8010-86e18094f729.png)![snes9x_64x64](https://user-images.githubusercontent.com/16159164/39593995-0d5320d4-4ed1-11e8-8dcf-6d0741021bf0.png)![snes9x_32x32](https://user-images.githubusercontent.com/16159164/39593997-0f354fc6-4ed1-11e8-9b50-ac649585978c.png)

Thus solving the problem once and for all...

**Comment by OV2** [comment]
I really like both of them - just wanted to point out some possible complaints. It might also be that everyone has switched to higan and this is a non-issue.
The european SNES also has colored buttons, so that's not really a valid reason ;)

IIRC win needs 16x16, 32x32, 48x48, and 256x256 variants, but I can probably create an ico from the finished image.

**Comment by bearoso** [comment]
Ok, we're now using the brighter, purply one on both Gtk+ and Windows.

**Comment by fancymelonub** [comment]
@bearoso yo the icon looks pretty good
@snes9xgit you need to see this

**Comment by Felipefpl** [comment]
I like 1 and 2, the cool thing is that the 2nd one seems to have removed teh buttons from zsnes' icon. :P

bearoso - a suggestion: you must ensure the icon will look good without jagged borders either on 640x480 or 8K resolutions (yes, 8K resolution, better be prepared for the future ;) )

**Comment by Felipefpl** [comment]
I like 1 and 2, the cool thing is that the 2nd one seems to have removed teh buttons from zsnes' icon. :P

bearoso - a suggestion: you must ensure the icon will look good without jagged borders either on 640x480 or 8K resolutions (yes, 8K resolution, better be prepared for the future ;) )

PS: i support the change of the icon in all systems including windows.

**Comment by Tatsuya79** [comment]
What about this one?

<a href='https://postimg.cc/image/ol0uf5wtz/' target='_blank'><img src='https://s31.postimg.cc/ol0uf5wtz/snes_logo.png' border='0' alt='snes_logo'/></a>


sorry... :sweat_smile:
