### ISSUE TITLE
s-dd1 mapping bug?

### ISSUE THREAD

**Issue by SimpleTease** [snes9xgit/snes9x#293]
Hi, there's a hack which converts Tales of Phantasia to s-dd1 mapper. Works in bsnes but not with snes9x 1.55. Got a reply that these need fixing:
- a0-bf:6000-7fff should be mapped to sram
- 40-5f should not be mapped to rom

**Comment by bearoso** [comment]
Snes9x uses heuristics to detect those two large games, mostly just reading the game title, so it might not be smart enough to detect that until we have manifests. Are you using Icarus to convert to game folder or an older version of bsnes?

**Comment by SimpleTease** [comment]
Was using bsnes 0.73. I think this is latest patch
https://www.sendspace.com/file/a5sukn

**Comment by bearoso** [comment]
That doesn't work on the clean Tales of Phantasia image.
