### ISSUE TITLE
Mario's Time Machine - surfing mini-game bug

### ISSUE THREAD

**Issue by SimpleTease** [snes9xgit/snes9x#294]
Hi, this problem has been around for awhile. When playing the surfing mini-game, sprites will disappear when you surf to the 'right' of them. Told this:
81/8843 REP #$20
81/8845 LDA $2136

This reads OpenBus @ 2137 and is not emulated correctly.

**Comment by bearoso** [comment]
Who’s telling you this? There’s a places we should update openbus, but don’t, so the value read is off.

**Comment by bearoso** [comment]
Found some posts on romhacking.net by the infamous sluffy about it. I’ll look into it tomorrow.

**Comment by bearoso** [comment]
We were returning the CPU open bus for $2137 instead of the PPU open bus. Fixed.
