### ISSUE TITLE
Weird Font/Aspect ratio bug in games "Treasure of the Rudras" & "G.O.D."

### ISSUE THREAD

**Issue by ImSpecial** [snes9xgit/snes9x#295]
First off these are ROM translations, but the original JAP versions of them also have this issue, and according to some people on Romhacking.net using byuu's BSNES core does not have this issue, but it does with Snes9X. Gideon Zhi, a person on that site who probably knows what he's talking about, said that the game renders its text using the SNES's hires mode. And that Snes9X isn't handling that properly.

The games in question; [Treasure of the Rudras](https://www.romhacking.net/translations/669/) / [G.O.D.](http://www.romhacking.net/translations/3515/) ([v1.0](http://www.dynamic-designs.us/index.shtml))

Okay so the issue is basically that when dialog happens in these games, the aspect ratio slightly shifts, and things become blurry somewhat, and in BizHawk using the Snes9X Core, the entire window changes size to a huge degree. I'm not really sure what else to add, since on a technical level I have no idea, the only hint was from Gideon Zhi. But maybe you guys will know what the deal is, and maybe it's a quick simple fix, or maybe not, but either way I wanted to bring this up.

**Comment by bearoso** [comment]
At those points, the game outputs those scanlines for the window at 512 pixels wide, so Snes9x outputs at that size. If you want to avoid the skipping, you either need to force the 512 output size on all the time, or reduce the 512 width to 256, both should be options in all Snes9x ports.

**Comment by bearoso** [comment]
Bsnes outputs at 512 width no matter the circumstance, but that can have other problems.

**Comment by bearoso** [comment]
And know that Snes9x 1.55 fixed an issue with G.O.D’s text, so if Bizhawk didn’t update, the text might look weird.

**Comment by bearoso** [comment]
I saw your thread on rh.net. It’s a bug with Bizhawk. It doesn’t understand when the Snes9x core gives it 512x224, and doesn’t keep aspect ratio properly. Pass this along to them.

**Comment by ImSpecial** [comment]
Sure enough, unchecking that Hi-Res option fixed things with Snes9x, thanks I had no idea...
