### ISSUE TITLE
Funaki Masakatsu Hybrid Wrestler - Tougi Denshou (Japan) -- mode7 garbage

### ISSUE THREAD

**Issue by SimpleTease** [snes9xgit/snes9x#298]
This game has some weird bug. After the Technos logo, it uses mode7 to draw the Pancrase logo. This image has some garbage tiles on top of screen. Canoe hack mentions something about wraparound tiles (211a = 00, VOffset:65512).

Sorry, don't have more information about this but tried in EmuCR-Snex9x-20180515-x86 and fails still. Thanks for fixing so many things recently in this snes emulator! I like not having to apply ips/bps game hacks to play games.

**Comment by jjfmz42015** [comment]
confirmed. same here.

**Comment by kps501** [comment]
Had some help. DMA is reading from PPU (2xxx) and writing to 2118. I think this is supposed to be PPU.OpenBus1?

DMA[7]: CPU->PPU Mode:1 0xA70000->0x2118 Bytes:12288 (inc) V:067


$81/F58D A9 01       LDA #$01                A:8080 X:0000
$81/F58F 8D 70 43    STA $4370  [$81:4370]   A:8001 X:0000
$81/F592 A9 18       LDA #$18                A:8001 X:0000
$81/F594 8D 71 43    STA $4371  [$81:4371]   A:8018 X:0000
$81/F597 8E 16 21    STX $2116  [$81:2116]   A:8018 X:0000
$81/F59A A3 06       LDA $06,s  [$00:1FFD]   A:8018 X:0000
$81/F59C 8D 72 43    STA $4372  [$81:4372]   A:8000 X:0000
$81/F59F A3 07       LDA $07,s  [$00:1FFE]   A:8000 X:0000
$81/F5A1 8D 73 43    STA $4373  [$81:4373]   A:80B0 X:0000
$81/F5A4 A3 08       LDA $08,s  [$00:1FFF]   A:80B0 X:0000
$81/F5A6 8C 75 43    STY $4375  [$81:4375]   A:80A7 X:0000
$81/F5A9 8D 74 43    STA $4374  [$81:4374]   A:80A7 X:0000
$81/F5AC A9 80       LDA #$80                A:80A7 X:0000
$81/F5AE 8D 0B 42    STA $420B  [$81:420B]   A:8080 X:0000


ppu.cpp

	uint8 S9xGetPPU (uint16 Address)

	if (Address < 0x2100)
	return (OpenBus); /* PPU.OpenBus1 ?? */


getset.h
	
	case CMemory::MAP_PPU:
	if (CPU.InDMAorHDMA && (Address & 0xff00) == 0x2100)
	return (OpenBus); /* PPU.OpenBus1 ?? */


ppu.cpp
switch (Address)
	{
	case 0x21c2:
	if (Model->_5C77 == 2)
	return (0x20);
	return (OpenBus);
	
	case 0x21c3:
	if (Model->_5C77 == 2)
	return (0);
	return (OpenBus);
	

	default:
	return (OpenBus); /* PPU.OpenBus1 ?? */
	}

This last one could be the glitch killer.

**Comment by bearoso** [comment]
Changed a couple of these that I could research were wrong. The one that fixes the glitch I'm not sure about, but I changed it anyway.

**Comment by OV2** [comment]
@kps501 does your help have a nickname for the changelog? Or does he want to stay anonymous?
