### ISSUE TITLE
[non-issue] Super Off Road - demo mode not random

### ISSUE THREAD

**Issue by kps501** [snes9xgit/snes9x#299]
Hello. If you let the demo mode play (don't touch joypad), snes9x always shows the same exact race every time at clean bootup. Real hardware is pretty random which course and how the race plays out (bonus items, when ai uses nitros, who wins, etc.). Bsnes gets this right and looks tied to ram being randomized on 1st boot. Thanks for looking at this bug. Hopefully can be fixed in this emu too!

**Comment by kps501** [comment]
Compared Super Off Road (USA) and matches latest no-intro. Using snes9x-1.55-win32. Always get sidewinder as 1st demo track.

With bsnes, everytime I start game fresh (no soft reset), I can get different 1st demo tracks: fandango, sidewinder, big dukes, huevos grande. Haven't checked real hardware in awhile but I remember something similar to bsnes when I power it on (random track as demo).

Maybe there's a config option I'm missing?

**Comment by jjfmz42015** [comment]
Tried a clean dump again (my own dump) and snes9x and bsnes both cycle through same tracks in attract mode. Real hardware same behavior. I honestly think its your rom.

**Comment by kps501** [comment]
Okay. That's enough proof snes9x is okay. My rom dump md5 is: 0C1CC5369A31C988858A087598BAB9C3.
http://datomatic.no-intro.org/?page=show_record&s=49&n=2799

Does this match yours? I'm almost ready to close this as non-issue after verification.

**Comment by Cibomatto2002** [comment]
My Rom is SHA-1: 1784C53C1B60047337109A5A9BF6A638D77B4219 and it works correct so try to find a Rom that has that SHA-1 and you should be OK. Super Off Road (USA).

**Comment by Cibomatto2002** [comment]
Have you tried the latest test build?

**Comment by bearoso** [comment]
This is probably a legitimate issue, but adding random memory means more nondeterminism, which I wouldn’t want to add until all our unintentional nondeterminism is completely eliminated.

byuu had to scale back the completely random memory to a pattern, and it’s done selectively, because fully randomized memory isn’t accurate, either.

**Comment by qwertymodo** [comment]
If we do add random initialization, it should probably be a config file option (not sure I'd even suggest putting it in the GUI), and disabled by default.  Randomized is a better approximation than zeroed, the pseudo-random patterns just happen to be an even better approximation than that.  I think higan offers all 3 options.

**Comment by jjfmz42015** [comment]
I will check when i get home.

Also was just thinking i tested snes9x 64 bita

**Comment by jjfmz42015** [comment]
Has anybody else actually tested. I was truly unable to replicate rhe issue

**Comment by kps501** [comment]
Going to close this then unless someone finds another legit reason to open this ticket for this particular game. Thanks!

**Comment by jjfmz42015** [comment]
your md5 is good so i tested again with both 32 and 64 bit. problem still doesnt happen. maybe try a fresh copy of snes9x

**Comment by kps501** [comment]
Tried versions of snes9x 1.54-1.43. Emucr builds of snes9x. Always get sidewinder as 1st demo / attract track. Money bag always shows up in same spot also. That's alright - I must be doing something wrong somehow.

bsnes-mercury 0.94 always gives me huevos grande (1st demo track).
bsnes-plus-0.73 is pretty random on 1st demo track (power off, power on).


Found some hack that changes the rng everytime a race is started and the ai uses nitros a lot more now in-game than before so I'm okay with this. Before I could finish some races and cpu would use nitro only once or twice. Now they do lot more often so game is more fair and less easy. Why I'm only one to have stupid (demo, enemy) behavior is beyond me. Thanks again!

**Comment by jjfmz42015** [comment]
try using 1.55 or newer. i only tested 1.55 and newer and problem is not there.

you reported a bug on an obsolete build.

**Comment by kps501** [comment]
Same behavior (for me) on 1.55 and recent github builds from www.s9x-w32.de/dl/testbuilds/.

I'm going to keep this closed and ignore it since no else can replicate this problem.

**Comment by jjfmz42015** [comment]
ok im wrong i misunderstood the complaint there is an issue

**Comment by jjfmz42015** [comment]
reopen im an idiot i misunderstood the complaint and was trying again and now i understand.

**Comment by bearoso** [comment]
As I said earlier, I’m not comfortable adding nondeterminism at this point, given it can exacerbate snes9x’s inherent timing discrepancies. If you can find the address being used as a seed, we could probably add a hidden flag that randomizes that particular region.

**Comment by bearoso** [comment]
bsnes-mercury and other forks used for TASs probably removed the randomization as it totally breaks videos and netplay.

**Comment by jjfmz42015** [comment]
considering the game fully plays proper and the issue is not so noticable ie even running it on real hardware took a few looks to realize I  dont think it would be worth possibly hurting other compatibility over it.

The current Snes9x is real nice.

**Comment by jjfmz42015** [comment]
This seems fixed. They either implemented randomization or game specific fix. Not sure what but it is working correct both on this anf latest higan

**Comment by bearoso** [comment]
No, nothing implemented.

**Comment by jjfmz42015** [comment]
There is an ips patch for this. Can info from the IPS patch be used to generate a game specific hack in snes9x? This would boot the list of compatible titles. I know it's not necessary anyone that really wants can just get the IPS but it would make snes9x more "compatible"

**Comment by jjfmz42015** [comment]
no that I know this it bugs me, I know an IPS patch exists cause I can find talks about it but cant find the actual patch. Anyone know where to obtain the fix? Im assuming it wont be added to snes9x so I figure I can just drop the ips in the correct folder for the time being.

**Comment by jjfmz42015** [comment]
think I have it https://drive.google.com/drive/folders/1qgLQjYypSVpMWClJ-OtHqDz7DKkkeMPG?usp=sharing

**Comment by jjfmz42015** [comment]
Can a game specific hack be added to snes9x for this? it would just bring it closer to being more compatible.

**Comment by qwertymodo** [comment]
Awhile back, I looked into implementing higan's randomization algorithms.  If I remember correctly, it didn't look that hard.  If there are no objections, I'll take another shot at it.  There were either 2 or 3 different algorithms with different amounts of entropy, so there would need to be a config file option for it, which would then also allow it to be completely disabled (which I think should be the default).

**Comment by jjfmz42015** [comment]
Have you tried the randomization? Just curious

**Comment by jjfmz42015** [comment]
is this coming to the windows port?
