### ISSUE TITLE
direct draw missing in latest dev builds.

### ISSUE THREAD

**Issue by jjfmz42015** [snes9xgit/snes9x#301]
Just noticed the last few dev builds seem to only have D3D and OGL no direct draw.

I Never use direct draw anyway but thought Ide mention it in case it matters.

**Comment by OV2** [comment]
Automatic builds from the appveyor system do not include ddraw, if I upload a testbuild I usually include it. Not sure where you get the dev builds from.

**Comment by jjfmz42015** [comment]
I use to gettest builds off the de download site but these days I been going here [https://ci.appveyor.com/project/snes9x/snes9x/history](url)

Is there ever a reason to use Direct Draw over OGL or D3D?
