### ISSUE TITLE
glitch that can close SNES9X

### ISSUE THREAD

**Issue by jjfmz42015** [snes9xgit/snes9x#304]
If you set SNES9X video to OpenGL

Disable Extended Height of snes image 

Output image prosessing to almost anything that is 2x or greater then load rom

Snes9X will crash.

Tested many builds on 5 systems all different hardware and on both windows 7 and 10.

Does not crash if in D3D mode or if you keep Extend enabled.

Can replicate 100% of the time.

**Comment by jjfmz42015** [comment]
why did you close it? issue 304 is wrong it happens on all builds even old ones.

**Comment by jjfmz42015** [comment]
did more testing
snes 9x this build and before are all ok

3 days ago by OV2
1.55-117
Clear config on destroy
master d8ef082c
3 days ago in 8 min 4 sec


and every build after this build is broken for sure
a day ago by OV2
1.55-120
win32: restore old style OGL .shader support
master a911503d
a day ago in 9 min 10 sec

There for sure is a problem with OGL going on from this build forward.

**Comment by bearoso** [comment]
No need to analyze it. Probably just a buffer sizing issue.

**Comment by jjfmz42015** [comment]
If there is some way I can help let me know.

Im only reporting stuff here to try and help. Im already as happy as possible with the emulator. Plays what I need it to play flawless.
