### ISSUE TITLE
Fix GoldFinger cheats by ilag11111

### ISSUE THREAD

**Issue by kps501** [snes9xgit/snes9x#306]
https://github.com/libretro/snes9x/commit/baa0d36d49ae036877b2bbf518b5d4572748631d#diff-91094a541e2dfe8f12d51e903db2be9d

(can't fork another snes9x to pull request this change; it's 1-line edit though)

**Comment by bearoso** [comment]
I actually deliberately dumped goldfinger with the new cheats format. No one ever used it, and this is yet more proof of that. Hell, even after that patch, the libretro support is still broken. They're not incrementing the address pointer at line 411.

**Comment by OV2** [comment]
Yeah, we don't call the function anywhere in our ports - I simply added it because it's only one line.
