### ISSUE TITLE
Accuracy: Pixel garbage missing in Top Gear

### ISSUE THREAD

**Issue by Pat86** [snes9xgit/snes9x#308]
In Top Gear 1 in the first stage there's supposed to be some turquoise pixel garbage under the speed display. In Snes9x its missing.

![higan](https://user-images.githubusercontent.com/20128108/40586782-293987b2-61c7-11e8-991f-5e200a1232f0.png)
![snes9x](https://user-images.githubusercontent.com/20128108/40586783-295b0fa4-61c7-11e8-83ab-3ec16a8d0d0d.png)

Checked on real hardware. Not that i miss it, just for accuracy reasons. ;)

**Comment by bearoso** [comment]
This is probably something we can't fix with a scanline-based renderer. I'd check it on bsnes/higan balanced and bsnes/higan accuracy. If it's there on the accuracy version but not the balanced, then that confirms it.

**Comment by Pat86** [comment]
It's not on the balanced core, only accuracy. Just gave it a try.

**Comment by bearoso** [comment]
There's no way we can fix it. Accuracy uses a dot-based renderer, which is much slower and which Snes9x is not designed to accommodate.
