### ISSUE TITLE
(Snes9x 1.5.6 last pre-release build) Windows XP not working! But it worked with the lastest version of 1.5.5

### ISSUE THREAD

**Issue by JonKaruzu** [snes9xgit/snes9x#309]
I compiled this build at the Morning using my new PC.
And opens the exe on my Older PC and the first time give a error.

"The procedure entry point QueryDisplayConfig could not be located in the dynamic link library USER32.dll"

Yeah, it dropped support for XP Users. And worked fine on Win7+ Computers.

The new 1.5.6 release is coming soon but how low-end computers didn't work on Windows.

Oh I forgot to update Visual C++ 2017 and still didn't work.

For now i recommend to upgrade Windows or buy new one

Windows XP not existing in 2014 to present and Security updates are Disabled for now

Now wait until get a job.

**Comment by bearoso** [comment]
It's just something dumb I did. We can probably do something like GetProcAddress and get that function if it exists in USER32.dll.

**Comment by bearoso** [comment]
Should be fixed now.

**Comment by kps501** [comment]
Tried on an old xp computer lying around and confirm appveyor runs without problem.
