### ISSUE TITLE
Feature request: always hide mouse cursor in fullscreen mode

### ISSUE THREAD

**Issue by etking** [snes9xgit/snes9x#31]
Would be really great if this was possible because the mouse cursor is always visible.

**Comment by vgturtle127** [comment]
#86 may be related, but I have a feeling this will be an issue that is hard to debug...

**Comment by SwinglesMan** [comment]
if this gets implemented, don't override the other one (mouse hide while inactive). Make them separate settings.

**Comment by bonimy** [comment]
This issue seems to be a duplicate of #86, which was resolved. Recommend closing.

**Comment by qwertymodo** [comment]
Yep, duplicate of #86
