### ISSUE TITLE
Snes9x crashing on speed up

### ISSUE THREAD

**Issue by Sun-in-jang** [snes9xgit/snes9x#310]
Reproduce steps:

1) Open any rom
2) Press "speed +" hotkey
3) Snes9x probably going crash

Video confirmation of this issue: https://youtu.be/wahTb7Xf44Q

**Comment by bearoso** [comment]
This should be easy to find. I imagine the syncing method is just spinning on something it didn't expect when the speed per frame changes.

**Comment by Sun-in-jang** [comment]
[snes9x config.zip](https://github.com/snes9xgit/snes9x/files/2043203/snes9x.config.zip)

**Comment by OV2** [comment]
The sound buffer was overflowing since I did not clear it with increased speed and sound sync enabled.
