### ISSUE TITLE
Super FX games buggy

### ISSUE THREAD

**Issue by kps501** [snes9xgit/snes9x#311]
Lots of slowness and flickering using latest emucr build (2018-05-26).

ex. Yoshi's Island, Star Fox, Stunt Race

**Comment by qwertymodo** [comment]
Are you able to reproduce the same results on the official AppVeyor builds?

**Comment by kps501** [comment]
https://ci.appveyor.com/project/snes9x/snes9x/build/job/6qh9pse48fosqr9u/artifacts.

Star Fox rev2 = buggy
Stunt Race = buggy
Yoshi's Island = looks fixed

**Comment by bearoso** [comment]
This broke on the battle blaze fix/revert. It's IRQ related again.

**Comment by kps501** [comment]
Genius work. All 3 are fixed. Thanks!

**Comment by bearoso** [comment]
Eh, there's still some timing issues with Stunt Race, but I didn't cause those.

**Comment by kps501** [comment]
I'm not complaining. Game is playable again. That's what counts! :)
(over that zod-awful flickering)

**Comment by kps501** [comment]
https://ci.appveyor.com/project/snes9x/snes9x/build/1.55-157/job/iqmy8pgyyqbpf1i1/artifacts

reopen issue: If you watch the intro for awhile, you'll see some random bar flicker move across the screen

**Comment by kps501** [comment]
Don't touch joypad and watch the big ship fly over. Eventually these strange vertical columns will keep moving around.

**Comment by Tatsuya79** [comment]
It's about Star Fox.

**Comment by bearoso** [comment]
I see it. If this isn't the last IRQ issue, then I'm reverting.

**Comment by kps501** [comment]
https://ci.appveyor.com/project/snes9x/snes9x/build/1.55-158/job/pi0dv6g9wolp1yx9/artifacts

Tales looks like it plays (new game) but Star Fox rev2 still does "jailbar" effect. I guess too precise timing is very high difficulty. Thanks for your valiant efforts!

**Comment by bearoso** [comment]
Not an IRQ issue. Fixed.

**Comment by bearoso** [comment]
I also fixed some flickering during Stunt race fx races. Don't know what's up with the menus, though.
