### ISSUE TITLE
[linux] Tales of fantasia stuck in black screen, while intro music is playing but with a SURPRISE!

### ISSUE THREAD

**Issue by retro-wertz** [snes9xgit/snes9x#312]
https://github.com/snes9xgit/snes9x/tree/1cd8d65705e88e4c7d83b6d1ab6ac2197f1a8eb4
in latest update seem to break Tales of Phantasia. loading the game gets stuck at black screen while intro music continues playing but vocals are replaced by.. something surprisingly sounding...

**Comment by jjfmz42015** [comment]
as a temp solution if you press start right when it initially starts writing on the screen before it goes black this will take you to the title screen.

**Comment by retro-wertz** [comment]
nah. being able to go into title screen still does not allow playing. still gets stuck after pressin OK on name entry

**Comment by jjfmz42015** [comment]
oh sorry.
Hopefully they can fix it.

**Comment by bearoso** [comment]
I'll look into it. Might just revert those IRQ changes with all the trouble they've caused.

**Comment by bearoso** [comment]
Fixed this.
