### ISSUE TITLE
Blarggs NTSC scanlines

### ISSUE THREAD

**Issue by jjfmz42015** [snes9xgit/snes9x#314]
Is it possible to mayber remove the scanlines from the Blarggs NTSC filters?

For those of us using media Centers with 60 inch tvs and certain resolutions the scan lines dont display correct.

**Comment by bearoso** [comment]
Yeah, Blargg's NTSC filter doesn't use scanlines by default. I don't think the Windows version even implements them, and the GTK+ version has a box to configure them. If you're using the libretro shaders, you'll need to remove the "gauss" shader from the preset.

**Comment by jjfmz42015** [comment]
ummm every version of snes9x win32 x86 and 64 bit shows scanlines with blarggs.... thats why im asking to remove them.


this i know im right on.

**Comment by bearoso** [comment]
Yeah, you’re right. Scan lines aren’t a part of the filter, so they have to be added on. I didn’t know that Windows did so.
