### ISSUE TITLE
super ghouls and ghosts USA random flashes

### ISSUE THREAD

**Issue by jjfmz42015** [snes9xgit/snes9x#317]
super ghouls and ghosts USA random flashes of graphics corruption during attract mode and gameplay

appvayor version 1.55-176

rom checksum 6AABA901

**Comment by Cibomatto2002** [comment]
I made a save state on 
[Super Ghouls'n Ghosts (USA).zip](https://github.com/snes9xgit/snes9x/files/2056539/Super.Ghouls.n.Ghosts.USA.zip)
This level seems to be the worse on graphics corruption.

**Comment by jjfmz42015** [comment]
Nice save point. The corruption is super obvious at that point!

**Comment by Tatsuya79** [comment]
If it's the result of IRQ changes that was made just for Speedy Gonzales (was it?) [there's a rom hack that can fix the switch problem.](https://www.romhacking.net/hacks/3875/)
Perhaps it could be added as a hack instead of the problematic changes?
Mentioning that just in case it would be possible.

**Comment by jjfmz42015** [comment]
I think the Speedy gonzales fix was already set up to only be active is speedy gonzales is loaded after the final fight break/fix. If Im not mistaken.

**Comment by kps501** [comment]
Tracked it down to Marko fix
https://github.com/snes9xgit/snes9x/commit/756ef37d7feaf39ee4c163efe90677445d2cf3eb

**Comment by bearoso** [comment]
> I think the Speedy gonzales fix was already set up to only be active is speedy gonzales is loaded after the final fight break/fix. If Im not mistaken.
No, I just made HDMA set the MDR only in the mode Speedy Gonzales uses. Final Fight was IRQ, which is a totally different thing.

**Comment by bearoso** [comment]
I repurposed the old Aero 2 variable for a proper fix for this. CLI and SEI (and others) don't clear the IRQ flag until the last cycle, so the next IRQ check uses the old value.
