### ISSUE TITLE
Kat's Run, video corruption during demo

### ISSUE THREAD

**Issue by Tatsuya79** [snes9xgit/snes9x#319]
Old bug, not related to recent changes.

Kat's Run - Zen-Nihon K-Car Senshuken (Japan) CRC 9DAB5AB1 (no-intro) shows corruption during the demo when reaching the cars presentation with a newspaper background.

<a href='https://postimg.cc/image/p5dczu23v/' target='_blank'><img src='https://s33.postimg.cc/p5dczu23v/Kat_s_Run_-_Zen-_Nihon_K-_Car_Senshuken_Japan_000.png' border='0' alt='Kat_s_Run_-_Zen-_Nihon_K-_Car_Senshuken_Japan_000'/></a>

**Comment by kps501** [comment]
I guess it broke between 1.43 (okay) and 1.51 (bad). No idea yet.

**Comment by bearoso** [comment]
Probably happened during anomie's renderer rewrite. A few rarer paths were probably never checked.

**Comment by kps501** [comment]
Something about bg2. vram e800 nt <> f000 nt. w:64, h:32. They should be same values but not. Looking more.

**Comment by kps501** [comment]
Something that is very worth noting: that newspaper background is same one in main menu, which works. But not during car showcase demo mode. Same drawing mode and everything. Changing cpu/dma cycle speed usually gets around glitch. Strange.

**Comment by bearoso** [comment]
Something else: if you wait, the car showcase is fixed on the next go around.
It seems to be dumping the entire background in one 8192-byte transfer. It doesn't look like anything is interfering with it, either, but that's probably not the case.

**Comment by Tatsuya79** [comment]
I can confirm it's fixed at https://github.com/snes9xgit/snes9x/commit/d1b90ddb96995875b1248fc4dadc4a3f9288585d.

Great work! closing it.
