### ISSUE TITLE
Windows: Audio Device is not selectable

### ISSUE THREAD

**Issue by panzi** [snes9xgit/snes9x#32]
If you have several audio devices you cannot select the one you want to use for playback. I haven't found a way in Windows to redirect the output of a process to a device. It seems like the program itself has to provide such functionality.

I guess the same is true for Linux (even though there should be some way to redirect the output of a process via PulseAudio, even though I haven't found a GUI app to do this).

**Comment by vgturtle127** [comment]
I thought you could do this in the audio playback settings in Windows?

**Comment by jcdenton2k** [comment]
You can do this in the audio settings in Windows; you have to change your 'default' audio device and POSSIBLY disable other devices temporarily if SNES9X still uses the older ones.  I know that SNES9X will ignore disabled devices.

**Comment by bearoso** [comment]
This was fixed.
