### ISSUE TITLE
Interlace drawing updates @ 30?

### ISSUE THREAD

**Issue by kps501** [snes9xgit/snes9x#322]
Not sure if this is a bug. Easiest to see during Air Strike Patrol, area radar briefing screen. When the text prints on bottom (interlace), snes9x you see full bold letters print out every 2 frames. On bsnes it updates every 1 frame - you see half letter on frame 1 (even lines?), then full letter on frame 2 (odd lines?).

I know that in gfx.cpp - S9xEndScreenRefresh - replacing S9xContinueUpdate with S9xDeinitUpdate draws at 60. Of course, I'm usually not knowing whether this is a good idea, or how to handle.

**Comment by bearoso** [comment]
It's arguable. It's up to the port how to handle the interlacing. You can get half the frame and update every half-frame on S9xContinueUpdate or just the whole frame on S9xDeinitUpdate. There's very few games that use interlacing, and the Snes9x way definitely looks better on Lufia 2's credits, but the "smoother" Air Strike Patrol UI might be more important to some.

**Comment by kps501** [comment]
Ah, okay. Not an issue then. Saw bsnes doing it and started wondering a bit why.

**Comment by kps501** [comment]
Not going to reopen this. But someone commented to me how official libretro + forked libretro snes9x ports have fast flickery graphics (besides Lufia 2) in some hires games but not in snes9x/windows.


For (un)confusion sake, I think mainline libretro should do same as other official builds.

libretro.cpp/S9xContinueUpdate
return true;
