### ISSUE TITLE
Lufia II - Rise of the Sinistrals (USA) has black bars on the side

### ISSUE THREAD

**Issue by Cibomatto2002** [snes9xgit/snes9x#323]
I'm sure this is not a bug but wanted to send it anyways to make sure

![capture6-3-2018-9 35 45 pm](https://user-images.githubusercontent.com/21169038/40895699-7b964144-6776-11e8-9647-d74dcc150d1c.jpg)

**Comment by kps501** [comment]
Happens in bsnes too. I think that's normal everywhere - cutscenes, towns, combat. If you disable clip windows, you'll see all sorts of weird stuff going on in the black bar area.

**Comment by bearoso** [comment]
Not a bug. Though Lufia 2 is full of bugs on its own. I recommend the Artemis patches: http://www.lufiaworld.com/forum/viewtopic.php?t=1386140
