### ISSUE TITLE
snes9x-1.55-321-g3af67e1-win32 cheat problem

### ISSUE THREAD

**Issue by Cibomatto2002** [snes9xgit/snes9x#325]
There is no info on what the cheat codes do. Also is snes9x going to convert the .BML format back to .CHT for us?

Here is a video on the cheat problem.

https://www.youtube.com/watch?v=GueNJI81yDc

**Comment by bearoso** [comment]
No. You're using prerelease software and there are no guarantees. Snes9x 1.56 will convert older .cht files, but the .bml extension is done and gone.

**Comment by bearoso** [comment]
And don't expect that things won't change again before release.

**Comment by bearoso** [comment]
The description field was changed to name, so your added cheats have no name. 
We're still working out the format, so don't assume anything is concrete.

**Comment by Cibomatto2002** [comment]
I had no idea you was still working on it. I just notice there was no description and thought it was a bug.
