### ISSUE TITLE
Won't compile

### ISSUE THREAD

**Issue by Ironsight** [snes9xgit/snes9x#328]
Trying to compile in elementary os 64-bit and I get this error:

                 from src/gtk_binding.cpp:11:
src/gtk_s9xwindow.h:84:9: error: ‘GdkDrawingContext’ does not name a type
         GdkDrawingContext *gdk_drawing_context;
         ^
In file included from src/gtk_s9x.h:8:0,
                 from src/gtk_cheat.cpp:3:
src/gtk_s9xwindow.h:84:9: error: ‘GdkDrawingContext’ does not name a type
         GdkDrawingContext *gdk_drawing_context;
         ^
In file included from src/gtk_s9x.h:8:0,
                 from src/gtk_config.cpp:14:
src/gtk_s9xwindow.h:84:9: error: ‘GdkDrawingContext’ does not name a type
         GdkDrawingContext *gdk_drawing_context;
         ^

**Comment by Ironsight** [comment]
Disregard, I wasn't in the unix folder XD have a good one.

**Comment by bearoso** [comment]
Really? You sure you don't want the GUI?

**Comment by Ironsight** [comment]
I switched it over to gtk2, and it compiled it that way... ./configure --prefix=/usr --with-gtk2 after I installed the gtk2 dev packages. looks like it's working

**Comment by Ironsight** [comment]
yep, working great :D

**Comment by bearoso** [comment]
GdkDrawingContext is GTK+ 3.22 and above only. I guess you've got an older version. I should check that in configure.

**Comment by Ironsight** [comment]
gtk+3.0 (3.18.9-1ubuntu3.3)

**Comment by Ironsight** [comment]
![image](https://user-images.githubusercontent.com/4589139/41120665-cc9ccb0c-6a5b-11e8-8864-1be05ab8ec61.png)
