### ISSUE TITLE
Snes9x v1.56 (It sounds distorted?)

### ISSUE THREAD

**Issue by lNFERNO969** [snes9xgit/snes9x#329]
Hi, I have a one big issue with the last new version 1.56 x64, all games sounds bad (distorted), I try in XAudio2 & DirectSound with Sync Sound check & uncheck, D3D & OpenGL, but the same result... in the v1.55 works perfect!

Games are constant 60FPS 60/60 and the CPU are load arround 8%

Please check this. :)

**Comment by bearoso** [comment]
Try up checking the automatic input rate button in sound settings and set the input rate to 32000.

Are you on a higher refresh rate monitor?

**Comment by lNFERNO969** [comment]
Yes 120Hz monitor, with the uncheck Auto Input and set rate to 32000, It's sound great again ^^

Many Thanks

**Comment by roflcopter777** [comment]
Currently having similar issues, using XAudio2 on Win 10, latency of 160 ms at 32 kHz, not sure why I'm getting crackling.  Using Realtek HD audio integrated sound card.

**Comment by bearoso** [comment]
I'm going to do a hotfix release for this issue, but roflcopter777, unless you're using a high refresh rate monitor, I think your problem is different. You should probably enable the "Automatic Input Rate" checkbox, set your actual output frequency to 44 or 48kHz, turn "Synchronize with Sound Core" on, and make sure the frameskip option is "fixed" to 0 in the graphics window. You can also try turning on the "Dynamic Rate Control" option in the sound settings.

**Comment by roflcopter777** [comment]
I had those on, I believe, my  monitor does have the option for high refresh, but I keep it at 60 Hz (120 looks too weird to me), I have it set to 32 kHz and 160 ms right now, sync core to audio was left on, I turned off dynamic rate control and automatic input rate, IDK, not sure why I'm experiencing it, I know I have adequately powerful hardware:  I'll try those

Intel Core i7 4770
16 GB DDR3 SDRAM

I had none of these issues on 1.55

**Comment by bearoso** [comment]
Post your snes9x.conf file here and I'll take a look.

**Comment by bearoso** [comment]
Try this one:
[snes9x.conf.txt](https://github.com/snes9xgit/snes9x/files/2082124/snes9x.conf.txt)
Rename this file back to snes9x.conf and replace your current one.

**Comment by roflcopter777** [comment]
@bearoso 

Tested the config file, and ran Sparkster (the game I noticed the crackling the most) Yoshi's Island, and a few other games,, then recorded to audio with Audacity to see if there were any gaps in the spectrogram. Seems that the issue has been resolved, not sure what changes were made, but thank you.  I owe you one.

**Comment by bearoso** [comment]
1.56.1 has a fix for this.
