### ISSUE TITLE
Keys are "sticky" after rewinding (latest commit, linux)

### ISSUE THREAD

**Issue by randomdude999** [snes9xgit/snes9x#331]
Using the GTK or Unix version of commit 5af624da323cfd3cd4bf3938848480dcd8c657c1.
After rewinding, if some keys that were being held down in the original try (before rewinding) are not held down in the new try (after rewinding), Snes9x acts like those keys are still being held down.

Steps to reproduce:
1. Hold down any key, for example A, for a few seconds.
2. Release that key.
3. Rewind into the part where you were holding A.
4. Even though you aren't holding A anymore, Snes9x still acts like A is being held.

This didn't happen on Windows, but it did happen with both the GTK and the Unix port.

**Comment by bearoso** [comment]
This is kind of a damned if you do, damned if you don't scenario. Rewinding is simply loading a state it saved earlier. If I copy an updated key state back in afterwards it could screw things up.

I'll try what I can.

**Comment by bearoso** [comment]
Should be fixed now.
