### ISSUE TITLE
Small graphic errors in Blargg 's filters NTSC

### ISSUE THREAD

**Issue by lordpeluca** [snes9xgit/snes9x#332]
When I use the Blargg 's NTSC (Composite, S - Video, RGB) effects in full screen (Alt + ent) some errors are seen in the lower part of the screen. It only happens with these effects in special, with the others not.

The error is difficult to show in photos, but with the game running they become more noticeable.

It happens in the megaman, mortal kombat 2, starfox and others.

My configuration:

https://s15.postimg.cc/gw8fmrkzf/image.jpg

Graphic error:

https://s15.postimg.cc/gxidg19wr/image.jpg

This did not happen in version 1.55

Congratulations for this update.

Excuse my english, I use goolge translator.

**Comment by bearoso** [comment]
This is a simple filtering artifact from sampling the texture outside the bounds of the desired image. Have you tried the OpenGL output option?

**Comment by lordpeluca** [comment]
select OpenGL option and it happens exactly the same. It only happens with the Blargg filters.
For now I will continue using version 1.55

Thanks for answering :)
