### ISSUE TITLE
Game errors (Dragon Ball Z - Super Butouden 2 (Japan) (Rev 1))

### ISSUE THREAD

**Issue by Enigma776** [snes9xgit/snes9x#333]
There is a new issue of screen tearing on Dragon Ball Z - Super Butouden 2 (Japan) (Rev 1) which was not on the previous version. 
![untitled](https://user-images.githubusercontent.com/6320742/41167232-3c952b00-6b3a-11e8-9ee6-7cdabf5cdb2e.png)
Video Options
![untitled2](https://user-images.githubusercontent.com/6320742/41167243-436393e0-6b3a-11e8-8053-54d6a8bc9fc0.png)
Could affect other games but not seen any others have the same issue.

**Comment by kps501** [comment]
I remember hearing about this one. During irq, ppu scroll writes are done. An hdma interrupts this and messes up when it finishes.

**Comment by bearoso** [comment]
I've pushed a workaround for this. I'm hoping it doesn't break anything.
