### ISSUE TITLE
feature request integral scale when stretch to prevent banding

### ISSUE THREAD

**Issue by jjfmz42015** [snes9xgit/snes9x#334]
feature request integral scale when stretch to prevent banding

when you stretch image and use scanline you get banding.

however if using integral scaling like we see in bizhawk, magic engine, ootake, and a gfew others banding wont occur.

if you like to maintain aspect ratio and use specific resolutions but do not integral scale it looks like a bad mess.

**Comment by ShadyGuyJose** [comment]
Integer scaling filters are available up to ×4, but it's not nearly enough. It would be best if the emulator detected the highest possible integer multiplier (such as ×9 on a 4k display) and put black borders on the top and bottom, respectively. I can work around it by setting the emulator to 240-line mode, but that leaves me with a huge bottom black border, and it doesn't work for people whose monitors' vertical resolution isn't a multiple of either 224 or 240.

**Comment by jjfmz42015** [comment]
i just noticed using the snes9x core via bizhawk setting scaling to integer i can use scan lines on my 4k tv without going to 4k

**Comment by Lululalu** [comment]
@ShadyGuyJose I'd rather play with black borders and a perfectly stretched image, instead of a distorted full screen. I think it needs to be a toggleable option.

**Comment by jjfmz42015** [comment]
I play with black borders. But k like the blarrgs ntsc filter which has scanlines that band due to stretch even though playing in 4:3

**Comment by jjfmz42015** [comment]
I wish i could either integer scale or disable scanlines when using ntsc filter

**Comment by bearoso** [comment]
I've added integer scaling to the GTK+ and Win32 ports. Word of warning: I'm not an experienced Windows programmer.

**Comment by ShadyGuyJose** [comment]
@bearoso can we expect a release build soon, or do we have to compile the current code?

**Comment by bearoso** [comment]
No upcoming releases are expected. If you want to test it grab the appveyor build here
https://ci.appveyor.com/project/snes9x/snes9x/build/job/rcn8hba94uscxx32/artifacts
or here for 32bit:
https://ci.appveyor.com/project/snes9x/snes9x/build/job/9cx65gncj5wq6idh/artifacts

**Comment by jjfmz42015** [comment]
thanks bearso.

However it doesnt seem to work properly. With it enabled in windowed mode display goes blank and fullscreen scaling is way small.

Im compairing to to integer scaling snes9x via bizhawk

Im not complaining just reporting back.

**Comment by ShadyGuyJose** [comment]
Working flawlesslt for me. Thank you so much!

**Comment by jjfmz42015** [comment]
in windows?

**Comment by ShadyGuyJose** [comment]
@jjfmz42015 How did you understand that I didn't think we needed it? I asked for it monts ago in the forum! I'll screenshot it and post again in a while.

**Comment by ShadyGuyJose** [comment]
![captura de ecra 12](https://user-images.githubusercontent.com/31470147/41359934-7e69116c-6f23-11e8-817b-acda610f1f99.png)
![captura de ecra 13](https://user-images.githubusercontent.com/31470147/41359935-7eb13604-6f23-11e8-9caa-6282ae3dd619.png)
![captura de ecra 11](https://user-images.githubusercontent.com/31470147/41359960-8c5526a8-6f23-11e8-889b-df54105319fa.png)
Full screen and windowed. Settings for clarity.

**Comment by ShadyGuyJose** [comment]
@jjfmz42015 @bearoso the behaviour is somewhat erratic, though. When I play around with filters and window stretching, sometimes I get the wrong integer.

Scanlines give me 8× instead of 9× scaling, for example, which leads me to believe there's conflicting code:

![captura de ecra 14](https://user-images.githubusercontent.com/31470147/41360422-a717ceae-6f24-11e8-9494-e0440ddd5430.png)

**Comment by ShadyGuyJose** [comment]
@jjfmz42015 @bearoso wait, I've figured it out. Scanlines double height and width to 512×448, giving me a maximum 4× scale to 2048×1792, which is the size of an 8× SNES image without added filters. Everything's just fine!

**Comment by ShadyGuyJose** [comment]
@jjfmz42015 my very first comment on this topic was me explaining why we needed this, not saying it was unneeded 😂

**Comment by bearoso** [comment]
@jjfmz42015 Would you post your snes9x.conf so I can reproduce your problems?

**Comment by ShadyGuyJose** [comment]
@bearoso His problems seem related to the window size and his filter. @jjfmz42015 are you using scanlines or TV/NTSC? If so, please test 2× and 4× window size, as 1× and 3× shouldn't work at all. Borderless full screen may also show a smaller image.

**Comment by jjfmz42015** [comment]
My config file. full screen image is scaled lower than expected. windowed cant see anything.

Same results no matter what computer I try.


All system I used are Windows 7 or 10

all different video cards and monitors.


[snes9x.conf.txt](https://github.com/snes9xgit/snes9x/files/2099856/snes9x.conf.txt)

**Comment by ShadyGuyJose** [comment]
Your config file shows a screen resolution (for fullscreen mode) of 1280×720. Using a scanline filter, like the Composite one you're using, sets the internal resolution to 512×448, as I said earlier. This only allows for 1× scaling (2× original SNES), as 2× (4× original SNES) would be 1024×896, which has a vertical resolution larger than your monitor's (or at least the one that's currently configured in Snes9x for fullscreen).

**Comment by bearoso** [comment]
And your window width isn't big enough for the whole image. It's only 512x448 and it needs to be 598x448 to fit with 4:3 aspect ratio. Though it should display centered and just cut off the edges, so I'm not sure what's up with that.

**Comment by ShadyGuyJose** [comment]
@jjfmz42015 For windowed mode, selecting 4:3 aspect ratio first and then 2× window size should work. @bearoso displaying with cut edges won't work, since it's currently coded to not display at all (0× integer scaling) if any of the window dimensions are below 1×. I don't know how to fix it without breaking the rest...

**Comment by jjfmz42015** [comment]
yes blargg filter without scan lines would be awesome then I dont need integer scaling.

thanks!

**Comment by jjfmz42015** [comment]
ok figured out why I see odd behavior.

if using integer scaling and certain filters the window mode issue happens. no filter no window mode issue.

In full screen example 1280 x 720 the integer scaling is rounding down too small somehow. I compare this to other emulators such as bizhawk when using snes 9x core results are much different.

That being said if having the NTSC filter without scanlines was an option I wouldnt need integer scaling and would be very very very happy :)

**Comment by ShadyGuyJose** [comment]
That's exactly what I said. Your resolution is too small for integer scaling to do 2× with scanlines (1024×896 - 4× original), so it sticks to 1× (512×448 - 2× original). With no filters (original - 256×224), it can go up to 3× (768×672).

**Comment by jjfmz42015** [comment]
oh i see. so snes9x is doing it right and bizhawk wrong.


ill try higher resolution and see the results .

**Comment by jjfmz42015** [comment]
hmm ok I see at higher resolutions it works. my hard head wanting 1280x720 is the problem.

and the window problem is only if the window is set to small so integral scale is working good. i apologize.

ability to have blarggs without scanlines would still be awesome if its easy for them to do.

**Comment by jjfmz42015** [comment]
as long as blargg with scanlines still exist somone I know knows I asked for this and said he want scanlines to stay. is it possible to have both? if not maybe leave as is.

**Comment by bearoso** [comment]
I'll try to add an option soon. The way the filters are hooked up in the win32 port is kind of confusing, though.

@jjfmz42015 Have you tried the NTSC GLSL shader?

**Comment by jjfmz42015** [comment]
I did try a few gsls ones the seem less refined in color blending than blarrgs.

If its a ton of trouble just leave as is i already am happy with what is there. I asked cause i assumed it would be simple. I think we can close this isssue as the integral scale does work I just never understood why I was causing it to fail. Thank you very much for adding it.

I really really appreciate this emulator and what you guys are doing.

**Comment by ShadyGuyJose** [comment]
@jjfmz42015 this is the correct behavior for scanline filters, though, since the whole image (including them) needs to be scaled afterwards. Anything else would blend the scanlines with the actual content, leading to banding and other artifacts.
