### ISSUE TITLE
ALSA driver: invalid argument

### ISSUE THREAD

**Issue by codingbum** [snes9xgit/snes9x#335]
Hi.

Archlinux has upgraded snes9x from 1.55 to 1.56 (x64) but now there is no more sound and games are running too fast. Problem seems to be from the ALSA driver. Have sound when using the SDL driver but there is then frame rate lags.

with snes9x 1.55

```
Sound buffer size: 8200 (2050 samples)
ALSA sound driver initializing...
    --> (Device: default)...OK
    --> (16-bit, Stereo, 44100hz, 64 ms)...OK
```

with snes9x 1.56

```
Sound buffer size: 8200 (2050 samples)
ALSA sound driver initializing...
    --> (Device: default)...OK
    --> (16-bit, Stereo, 44100hz, 64 ms)...Failed: Invalid argument

```

ALSA Version
-----------------

kernel: k4.16.13-2-ARCH.
library: 1.1.6

**Comment by bearoso** [comment]
That means one of your settings is being rejected. Try a different rate like 48000Hz or a different buffer size. If all else fails, and especially if you have pulseaudio running anyway, try the pulseaudio driver.

**Comment by bearoso** [comment]
@codingbum, did you get it working?

**Comment by codingbum** [comment]
No but could it be due to a bad linkage? the maintainer of the package changed the build script

https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/snes9x&id=99e7bbf7df980aac20ecb563c196b3e2f892015e

**Comment by bearoso** [comment]
No, it's because we're checking that some parameters are actually changed that weren't checked before. You might have been setting 44100kHz and getting 48000Hz for example. In the ALSA driver we just let it go disabled. The pulseaudio or PortAudio drivers might be a little more relaxed, so you should try those or even the OSS driver. The SDL driver is callback-based and terrible.

**Comment by bearoso** [comment]
The ALSA output now checks the values are within range of your driver and will fall back to the maximum supported, or at least report what's wrong.
