### ISSUE TITLE
Regression: Umihara Kawase Flickering on Vertical Scroll

### ISSUE THREAD

**Issue by mibro0224** [snes9xgit/snes9x#337]
In Umihara Kawase, after climbing the ladder in Level 1 (initiating a vertical scroll) the screen begins to flicker. The flicker was fixed in v1.55, but is a regression in v1.56. 

Video attached.

[umiharasnes153.zip](https://github.com/snes9xgit/snes9x/files/2097221/umiharasnes153.zip)

**Comment by bearoso** [comment]
The game scrolls the vtimer along with the bg and expects it to not occur when it hits 262. Fixed.
