### ISSUE TITLE
Cannot compile for ppc64

### ISSUE THREAD

**Issue by musuruan** [snes9xgit/snes9x#338]
I cannot  compile snes9x 1.56.1 for ppc64:
http://koji.rpmfusion.org/koji/taskinfo?taskID=229852

Full build log is here:
http://koji.rpmfusion.org/kojifiles/work/tasks/9857/229857/build.log

There are no problems on other architectures. AFAIK snes9x 1.55 was fine.

Any help is appreciated. Thanks!

**Comment by OV2** [comment]
Looks like left over from a constant name change - can you try again with the current git?

**Comment by musuruan** [comment]
Can I apply this patch on top of 1.56.1?

**Comment by OV2** [comment]
Yes, that should work.

**Comment by bearoso** [comment]
And if the colors are fudged up, it's not your fault. Just report back here.

**Comment by musuruan** [comment]
I'm the RPM Fusion maintainer for snes9x. I can just cross compile for ppc64. I don't have the hardware available. I'll try a rebuild soon and report here.

**Comment by musuruan** [comment]
It built fine now. Thanks!
