### ISSUE TITLE
Top Gear 3000 corruption

### ISSUE THREAD

**Issue by kps501** [snes9xgit/snes9x#339]
Mentioned by fr500:
Game has some problem which causes bad colors or screen flicker. Just go in-game and drive some bit to see the hud or something go wacky. I think it's irq again.

Happens on latest commit and 1.56 release. 1.55 is okay.

--edit: 1.56 has terrible color flashing. divert irq commit made it better but hud errors remain.

**Comment by bearoso** [comment]
Should be fixed. Game was entering into into WAI state while IRQ line was active, but we only cleared WAI on the timer hit.
