### ISSUE TITLE
memmap.c (unzip) memory leak

### ISSUE THREAD

**Issue by Cpasjuste** [snes9xgit/snes9x#343]
Hi,

I found and fixed a memory leak in memmap.c unzip handling when working on my switch port. Zip files are either not closed or closed if it should not : https://github.com/Cpasjuste/snes9x/commit/34e07413cbfa7ad5a8ff834a911bc59d82233151#diff-bda36ad9af1fd7fa7f5c13a59e4e7d2

Sorry for the bad formatting, and no pull request, my time is very limited..

**Comment by OV2** [comment]
Thanks for the hint, appreciated.
