### ISSUE TITLE
macOS build broken

### ISSUE THREAD

**Issue by marconett** [snes9xgit/snes9x#344]
I am not at all familiar with the code base, but I was trying to build snes9x for macOS. The build is broken since at least the merge of #283.

The cheat restructure stuff was not implemented for macOS.

I was able to build successfully with the a few changes (see <https://github.com/marconett/snes9x/compare/master...macos-build-quickfix>), but seeing that I just removed functionality, cheats are very likely broken.

But someone with knowledge of the source should be able to fix things using that diff.

**Comment by OV2** [comment]
Unfortunately we do not have a macOS maintainer at the moment, and we do not have the means to compile and run the macOS version. We can try to do the cheat changes blind, but it will probably be some tedious back and forth until it works correctly.

**Comment by marconett** [comment]
That's too bad, because it looks like it's kind of a small change. If you want to do it blind, I'd be willing to do the tedious back and forth..

**Comment by marconett** [comment]
Alternatively, I could provide you VNC access to a clean macOS VM (snes9x build already setup) you can use to test builds while debugging.

**Comment by OV2** [comment]
I've pushed some changes that hopefully make it work again. For a real integration of the new cheat system we'd need to adjust the dialog, and I have no knowledge of the mac gui system.

**Comment by bearoso** [comment]
You're probably going to need interface builder to fix the UI. Afaik, the file format is complex, more annoying than Gtk's xml.

**Comment by marconett** [comment]
thanks. builds fine now with your changes and #350.

but it crashes with "`Thread 1: EXC_BAD_ACCESS (code=1, address=0xfffffff8)` at https://github.com/snes9xgit/snes9x/blob/master/cheats2.cpp#L510 when enabling a cheat.

sorry, my c++ debugging skills are pretty much non-existent..

**Comment by OV2** [comment]
The previous S9xAddCheatGroup probably failed and index is -1 when calling S9xEnableCheatGroup. We can check for that and prevent the crash, but it won't fix the issue. Can you see the content of code that is passed to S9xAddCheatGroup?

**Comment by marconett** [comment]
i guess you mean here: https://github.com/snes9xgit/snes9x/blob/master/macosx/mac-cheat.cpp#L298

`int index = S9xAddCheatGroup(citem[i].description, code);`

* `citem is a "CheatItem"-Array with size 150`
* `i = 0`
* `(char [22]) citem[0].description = "Cheat 001"`
* `(char [10]) code = "0=0"`

results is `index = -1`

**Comment by OV2** [comment]
I've added some code that will prevent the crash. But if you enter a valid addresss/byte combination it should not end up with a "0=0" cheat...

**Comment by marconett** [comment]
current master (6ebe7b4) builds fine. wasn't able to reproduce the crash with a "0=0" cheat. i was able to add other cheats from the cheatfinder and click on "enable" and "apply cheats" without it crashing.

i have not tested if the cheats actually work, cause i have no idea how to use the cheat system..

https://github.com/snes9xgit/snes9x/commit/ff1925cc0aa768f1ffefb3396e0bf354b3110d62#commitcomment-29536055 is fixed now as well.

great stuff!
