### ISSUE TITLE
Windows port should always allow hi-res graphics

### ISSUE THREAD

**Issue by ghost** [snes9xgit/snes9x#348]
When you go to records menu, the city on top looks wrong. Works in 1.52-fix4 but is broken in 1.53. Some type of Mode1 --> Mode5 + Interlace double height sizing bug or similar.

**Comment by bearoso** [comment]
It's the same thing as in ASP's mission results screen (still there and buggy) and what you fixed earlier with the double height. It wasn't completely correct and I've needed to go back and look at it.

**Comment by bearoso** [comment]
We don't handle the case where we go from interlaced back to non-interlaced. I think F1 ROC is setting non-interlaced near the beginning of the frame, after having begun it as interlaced. Then it switches to interlaced again for the text. ASP's reports screen starts as interlaced, then sets non-interlaced for the bottom graphic.

**Comment by bearoso** [comment]
Relevant commit: 5e53e209b91280b872ee398597d032dd4300bb1a

**Comment by bearoso** [comment]
I really don't think interlaced mode gets enabled on anything but modes 5 and 6, or at least not the way those two modes work. These two games rely on it shutting off when switching modes without clearing the flag. Hence commit: ff1925cc0aa768f1ffefb3396e0bf354b3110d62.

@OV2, it was your commit that introduced these changes. I can't find anywhere that says interlaced mode is available outside 5 & 6. I only found some obscure posts on nesdev.com that suggest no one knows what it does to modes 1-4, if anything. Am I missing something?

**Comment by OV2** [comment]
The interlace OAM changes were for artifacts in "Brutal - Paws of Fury" and shadows in clay fighter. I think I allowed interlacing in all bgs because bsnes allowed that and it fixed problems in the blues brother opening.

I actually found the old thread in the s9x dev forum about it: http://www.snes9x.com/phpbb3/viewtopic.php?f=10&t=4800

So the blues brothers opening screen used mode 7 with interlace.

**Comment by bearoso** [comment]
I understand the OAM stuff. I think we can just add mode 7 to the allowed list of 5 and 6 to fix Blues Brothers. These other games definitely don't want mode 1 output interlaced, though.

**Comment by OV2** [comment]
Sure, we can do that. I'll see if I can find the folder with all the test games I used back then tomorrow, but I don't think there was any other with such a weird combination.

**Comment by kps501** [comment]
Confirmed https://github.com/snes9xgit/snes9x/commit/ff1925cc0aa768f1ffefb3396e0bf354b3110d62 fixes F1 ROC II records menu. :)

**Comment by Cibomatto2002** [comment]
Downloaded 1.56.2-256 from AppVeyor and F1 ROC II - Records graphics glitch is still there.

![capture6-26-2018-9 46 03 pm](https://user-images.githubusercontent.com/21169038/41950163-5cea30e0-798a-11e8-9fe7-791559356c94.jpg)

**Comment by bearoso** [comment]
You don't have hires support turned on. I don't know why that's still a toggle option anymore.

**Comment by Cibomatto2002** [comment]
The only reason I had it off was because it said Support the hi-res mode that a few games use, otherwise render the in low-res. it would be nice if snes9x knew what games need hi res was needed in and turn it on for you.

**Comment by bearoso** [comment]
>  it would be nice if snes9x knew what games need hi res and turned it on for you
It does. That's why I said the option should just go away. :-)

**Comment by Cibomatto2002** [comment]
I see well have a good day :)
