### ISSUE TITLE
Window size and position not saved - v1.56.2

### ISSUE THREAD

**Issue by LufiaSelan** [snes9xgit/snes9x#349]
Window size and position is not saved on exit. Running on snes9x-1.56.2-win32-x64. Tested on 1.56.1 as well with the same issue. Not an issue with version 1.51. I haven't tested other versions.

Let me know if more information is needed.

**Comment by OV2** [comment]
I can't reproduce this, works fine here. Is snes9x.conf writable? If so, can you post it and your install location?

**Comment by LufiaSelan** [comment]
Sure, I did just manually set the Width, Height, Left, and Top in the conf file to what I wanted and it seems to keep the settings. All other settings were saved, such as video preferences and controller inputs. As far as I can tell, this was the only thing not saving.

Prior to editing these settings, the config file displayed the window size for 1x and Left and Top of 0.

Path: "D:\Video Games\Super Nintendo\Snes9x-New\"


[snes9x.conf.txt](https://github.com/snes9xgit/snes9x/files/2145207/snes9x.conf.txt)

**Comment by LufiaSelan** [comment]
Yes, that would be it. I usually go there looking for a 'close rom' option and end up exiting and restarting instead via the menu. It's useful to have that option if you're editing a rom and making romhacks and need to test a change.
