### ISSUE TITLE
Stream.cpp: memStream::revert does not match behavior of fStream::revert?

### ISSUE THREAD

**Issue by Dwedit** [snes9xgit/snes9x#353]
I'm looking at the code for Stream.cpp right now.

It appears that for fStream::revert, the first parameter `from` is a constant like SEEK_SET, SEEK_CUR, SEEK_END, however for memStream::revert, the `from` parameter does not have the same meaning?

```
int memStream::revert (size_t from, size_t offset)
{
    size_t pos = from + offset;

    if(pos > msize)
        return -1;

    head = mem + pos;
    remaining = msize - pos;

    return 0;
}
...
int fStream::revert (size_t from, size_t offset)
{
    return (fseek(fp, offset, from));
}
```
Shoudn't it work the same way?  memStream::revert should treat `from` as a constant SEEK_SET, SEEK_CUR, or SEEK_END, then adjust the position relatively?

edit:

It also appears that the only constant used is SEEK_SET (0), so everything just happens to work.

**Comment by OV2** [comment]
Probably. It's never used anywhere with anything other than 0, that's why it never was an issue.

**Comment by Dwedit** [comment]
Also shouldn't it be signed numbers rather than unsigned numbers?  Since SEEK_CUR exists, you could go backwards by specifying a negative number.
