### ISSUE TITLE
SA-1 Bug: SMW SA-1 Pack 1.26 doesn't load, black screen.

### ISSUE THREAD

**Issue by James-F2** [snes9xgit/snes9x#360]
Super Mario World SA-1 Pack v1.26 hack that adds SA-1 support doesn't load anymore in 1.56 (also 1.56.1, 1.56.2).

Works in 1.55.
Works in Higan.

SHA256: cce2fb72fa1b8ab15dafd94bc42317e1d2a8458c0b7ee4ddcca64a7a5ef41677  Super_Mario_World_SA-1_Pack_1.26.smc

**Comment by bearoso** [comment]
The SA1 is running too fast. Reducing the SA1 opcodes to 4 per S-CPU fixes this.

**Comment by VitorVilela7** [comment]
SA-1 Pack v1.27 will fix it by adding additional cycle delays on boot up. Sadly SA-1 runs so fast that it messes SPC700 timing.

**Comment by BPaden** [comment]
A note for anyone who stumbles on this issue and just wants to play SMW hacks, reverting c6db74c3bdadb1dc4c8a3403738b0820f6c3e388 appears to fix this issue for me.

**Comment by bearoso** [comment]
Yeah, that was me trying to tune the speed slightly. Vitor has a branch that improves Snes9x's SA1 timing drastically, but it isn't complete. I think the SA1 IRQs are pretty much broken already, so that doesn't make much difference, though. As he mentions, the updated 1.27 pack works around this.

**Comment by bearoso** [comment]
This should be working in 1.59.2.
