### ISSUE TITLE
Feature Request 7-Zip support

### ISSUE THREAD

**Issue by Augusto7743** [snes9xgit/snes9x#361]
Snes9X support only ZIP.
7-Zip has more compression than ZIP and is good choice for use less space in disk.
Thanks for read my post.

**Comment by Felipefpl** [comment]
Good request, specially since some ppl have lots of roms in a single package. Display the roms as a list in the main window of snes9x with a search feature like Ctrl+F in case you have many roms is also a nice addition.

**Comment by bearoso** [comment]
The entire SNES library takes up something like 2.5GB, and 7/8 of those games are barely worth considering playing. They hardly make flash cards that small anymore. The idea that we need to conserve space with SNES ROMs is fallacious.

I'm against ZIP support, too.

**Comment by bearoso** [comment]
I don't mean to sound harsh, but 7z support would require pulling in a rather big third-party library to decompress them, and I don't think it's worth the effort--particularly when ZIP compresses almost as well, and we don't need to save that small amount of space to begin with.

**Comment by OV2** [comment]
We also don't support multiple games in one zip file, so 7z support wouldn't really help with the current SNES library. Which I guess is the biggest reason people are asking for it.
