### ISSUE TITLE
configure fails without libminizip installed.

### ISSUE THREAD

**Issue by orbea** [snes9xgit/snes9x#365]
When running `./configure` without `libminizip` installed it will fail with the following.
```
configure: error: --with-system-zip given but cannot find system minizip library
```
When `libminizip` is installed it will work, but the `--with-system-zip` should be correctly disabled if its not found.

**Comment by bearoso** [comment]
You're explicitly specifying --with-system-zip, so of course it's going to bail out if it can't give you what you ask for. Not specifying anything gives you the behavior you describe. To me, this is the only logical way of doing it.

**Comment by orbea** [comment]
Maybe I wasn't being clear enough? This happens with just this.
```
cd gtk
./autogen.sh
./configure
```
I am not specifying `--with-system-zip`, I can work around this with `--without-system-zip` though.

**Comment by bearoso** [comment]
Ok, I see what's going wrong. Fixed.

**Comment by orbea** [comment]
Oh wow, that was simple and I entirely overlooked it, thanks!
