### ISSUE TITLE
d3dx9_42.dll is missing!

### ISSUE THREAD

**Issue by Myramong** [snes9xgit/snes9x#372]
I'm submitting this issue on behalf of all of the people that had this issue on the ALttP randomizer discord.

Would it be possible to switch to a modern version of direct x?

How about including d3dx9_42.dll in the download (I'm not sure if that would work)

![dx9](https://user-images.githubusercontent.com/22064552/43655938-027bc1cc-9727-11e8-81f6-a2cf6c1503a7.png)

I'm just really tired of helping people install dx9. =\

**Comment by OV2** [comment]
Snes9x still supports windows xp, so we are limited to dx9. It would also require rewriting the dx render path and kill cg shader support for directx.

The link to the DX9 runtime is the first question in the included faq, but I guess nobody checks those anymore...

**Comment by qwertymodo** [comment]
The Right Way(tm) to address this, according to Microsoft, would be to include the dx9_redist.exe in our installer and run it at install time.  Unfortunately, we don't *have* an installer.  We're not allowed to just throw the .dll's in the zip.

**Comment by qwertymodo** [comment]
I do wonder, however... shouldn't it be possible to detect the presence (or lack thereof) of DX9 at runtime and gracefully disable it if it's missing, rather than just crashing?  .dll's are used for optional plugins all the time, shouldn't it be possible to do that here?  Because that would solve the real underlying problem.  It's fine that we support DX9, but having the entire application depend on it to the point of crashing is less than ideal.

**Comment by Myramong** [comment]
On windows (at least, windows 7) the readme & faq open in notepad by default, which doesn't interpret \n on its own as a newline character.  This leads to the entire file being written on one line and it's a mess; that's probably part of the reason why no one reads it :p.

Could the error message provide a link to the download?

**Comment by OV2** [comment]
At the moment that's not possible. S9x has a hard dependency on d3d9x, and the error message is produced by windows itself. If I can get rid of d9d9x (used for matrix operations and texture loading), then I might be able to adjust the xaudio2 error message to point to the redist. We could also include the dxwebsetup.exe installer.

**Comment by jjfmz42015** [comment]
This is more of a user issue than anything. If you download a d3d9 application install dx9. This doesn't only affect snes9x.....

**Comment by OV2** [comment]
I've succeeded in removing the d3dx9 dependency, but had to remove the old HLSL code. Probably not a big issue since there were almost no shaders around. Will do a few more checks before committing though.

**Comment by Myramong** [comment]
jjfmz42015, I agree with that, but I think it's unfortunate that so many people encounter the issue and don't know what to do.  I wanted to bring attention to it in hopes that something could be done.

OV2, thanks for the change.  I'm sad to see shader support removed though; Removing features isn't what I had in mind when I posted this. :frowning_face:

**Comment by Felipefpl** [comment]
"We're not allowed to just throw the .dll's in the zip."

Sorry but i never saw a disclaimer about this regarding any software. Also, if dlls couldnt be distributed sites like www.dll-files.com or dllme.com wouldnt exist EVER.

**Comment by qwertymodo** [comment]
Just because you've never seen the license doesn't change the fact that it exists, and neither does the fact that other people ignore it. It took 18 years before emuparadise stopped hosting ROMs, that doesn't mean we're going to start packaging those in with the download too.

**Comment by bearoso** [comment]
Plus, who knows how many .dll files you're missing. It'll only report the first one it can't find. There's 41 d3dx9_*.dlls before it. We can't package hundreds of megabytes of files just in case.

**Comment by qwertymodo** [comment]
@bearoso @OV2 would there be any objections to building an actual Windows installer? I'd be willing to do the work, and we could solve this issue for good. Taking off my dev hat for a minute, this is a legitimate and long-standing user issue, and as easy as it is to fall back to RTFM as the official answer, it *is* a solvable problem.

**Comment by jjfmz42015** [comment]
In making an installer you are taking a portable app and making it no longer portable. If a user downloads a portable app that is directed they should know they need to install that direct x. You are fixing not a problem by removing the important feature known as portability

**Comment by qwertymodo** [comment]
Nothing is breaking portability. We're not storing settings in the registry or %APPDATA%. An installer would basically just be a self-extracting archive that also handles the dependency installation. I can even make the DX install optional (enabled by default).

**Comment by jjfmz42015** [comment]
So one could extract the exe from the installer and keep just that?

**Comment by qwertymodo** [comment]
Also, if you're *actually* using this portably (i.e. installing to a portable drive to plug-and-play on multiple computers), then you still need to have DX9 installed on the computers you play on, which brings us back to the original problem here.

**Comment by jjfmz42015** [comment]
I'm sorry but that is not a problem. Just users that don't understand basic operation of the platform

**Comment by jjfmz42015** [comment]
You could make snes9x just check for required items at launch and a popup to download if missing

**Comment by qwertymodo** [comment]
Let me repeat, making an installer would not change ANYTHING with respect to portability. If you want to "install" it to your flash drive and walk away the result would be no different than manually unzipping.

**Comment by jjfmz42015** [comment]
I understand. But my opinion and truly just giving you a user's standpoint it's a step backwards. I might be wrong just giving an opinion. At the end of the day you guys as the devs know best. An installer unless you mean a self extracting archive is more to go wrong future wise. Packaging an emulator to be future friendly makes more sense I would think.

**Comment by bearoso** [comment]
Just because there's an installer doesn't mean there can't be a standalone zip file, too, ya know?

**Comment by jjfmz42015** [comment]
Good point.

**Comment by OV2** [comment]
Possibly helpful link: https://docs.microsoft.com/en-us/windows/desktop/dxtecharts/directx-setup-for-game-developers
At the moment we should only need the xaudio parts.

**Comment by OV2** [comment]
I've added an error message with a clickable link. If anyone has a system without the dx runtime installed I'd appreciate feedback if it works correctly.

**Comment by jjfmz42015** [comment]
@OV2 great solution and works.

https://drive.google.com/file/d/1z4QtySsPXv2kWKA2dZ_q6yErtuWwB5BI/view?usp=sharing
tested on a work station at work here with dx runtine was good then on one without was good. screenshot attached.
