### ISSUE TITLE
[Feature Request] Load Random Game

### ISSUE THREAD

**Issue by ImSpecial** [snes9xgit/snes9x#375]
So this is something I noticed Mesen (NES emualtor) has and man it's a really cool feature and I want this in all my emulators now, it's something I never new I wanted until now since using it.

So it's pretty simple, just an option that will load a random game from your ROMs directory when you either select it (Similar to File>Load Game...) or use its corresponding hotkey. (Mesen uses Ctrl+Insert by default.)

Please consider and thanks either way.

**Comment by bearoso** [comment]
While I understand your desire for a feature like this, I feel the concept encourages piracy.

That may not be the situation in your case, but most of the time it boils down to "I downloaded the entire set of ROMs for this console, and I want a new game to try." This explicitly contradicts the wishes of emulator developers, who would prefer you actually own some form of the game you're playing--in which case you've invested money into it and a spurious decision wouldn't need to be made. Or you've scrupulously searched for a way to purchase the game and found acquisition unfeasible or disproportionately costly, in which case you have invested time.

**Comment by DutchReady** [comment]
that's a pretty dumb notion for a rather cool idea, almost want to call you an idiot

**Comment by qwertymodo** [comment]
The application is fully open-source.  You're more than welcome to go right ahead and add the feature yourself rather than insulting people who are doing this work for free.

**Comment by bearoso** [comment]
> that's a pretty dumb notion for a rather cool idea, almost want to call you an idiot

We're not going to add useless gimmicks that amuse people once or twice. This kind of "idea" would further devolve into bug reports like "why isn't it picking these games," or requests like "it'd be cool if it also did this." 

There's other programs like LaunchBox that do collection management. Snes9x opens the files and runs them.
