### ISSUE TITLE
Yoshi's Island credits are too slow.

### ISSUE THREAD

**Issue by themalu866** [snes9xgit/snes9x#377]
On a real SNES the game's credits play two songs one after another that don't loop and without pauses.
But with SuperFx Speed at 100% it gets this huge gap without any music (almost 3 minutes)
The closest to "fixing" this is setting SuperFx Speed to 175% but in the second song the scene is still out of sync (the Level Complete jingle should play when baby Mario and Luigi image shows up)

**Comment by bearoso** [comment]
This is known. Even higan/bsnes runs the credits too slowly. I found that setting a higher SuperFX speed has no negligible effect (it won't run too fast), so setting it to 200% or higher should "fix" the problem.
