### ISSUE TITLE
Request: change lightgun cursor

### ISSUE THREAD

**Issue by ramtrooper** [snes9xgit/snes9x#378]
I saw some versions of snes9x allow changing lightgun icon, even using custom ones. Also I like being able to use the 50% transparent custom colors as it's easier to see through.

Thanks

**Comment by OV2** [comment]
You can change the lightgun type and colors in the config file:

```
[Controls]
MacsRifleCrosshair = 4 Red/Orange
```
Where it is TYPE FOREGROUND/BACKGROUND

Valid names are
```
Mouse1Crosshair
Mouse2Crosshair
SuperscopeCrosshair
Justifier1Crosshair
Justifier2Crosshair
MacsRifleCrosshair
```

Crosshairs go from 0 to 16
Custom ones are also possible.

Colors are
```
        "Trans",
	"Black",
	"25Grey",
	"50Grey",
	"75Grey",
	"White",
	"Red",
	"Orange",
	"Yellow",
	"Green",
	"Cyan",
	"Sky",
	"Blue",
	"Violet",
	"MagicPink",
	"Purple",
	NULL,
	"tBlack",
	"t25Grey",
	"t50Grey",
	"t75Grey",
	"tWhite",
	"tRed",
	"tOrange",
	"tYellow",
	"tGreen",
	"tCyan",
	"tSky",
	"tBlue",
	"tViolet",
	"tMagicPink",
	"tPurple"
```

**Comment by ramtrooper** [comment]
Oh, that's nice to use!

Does libretro port also have a config file?

**Comment by ramtrooper** [comment]
Thanks for making this work in libretro! But gui says 25% Gray, 50% Gray, 75% Gray -- these colors don't work.

I think it's a typo?
- 25% Grey, 50% Grey, 75% Grey
- 25% Grey (blend), 50% Grey (blend), 75% Grey (blend)

Otherwise this can be closed soon as solved!

**Comment by ramtrooper** [comment]
Works perfectly now! Thanks guys!

**Comment by ramtrooper** [comment]
I think it'd help others if those configuration instructions are written into the win32 readme or auto-generated into the conf file somehow.

I'm migrating off libretro to soak in what the standalone experience is like, and I don't want to forget how to do this later on.

Thanks for all the team keeps on doing for us! :)
