### ISSUE TITLE
Request: smart fast-forward

### ISSUE THREAD

**Issue by ramtrooper** [snes9xgit/snes9x#379]
I play with other console emulators that know when to automatically turn on,off frame skipping. This is done to speedup crazy slow boot times or shorten long (floppy disk, cdrom) loading scenes.

So when screen is black 0 and audio off, it skips all this unwanted time and makes games much more responsive.

I haven't seen any snes emulator do this yet but I think it's largely helpful in adding to fun factor.

Thank you

**Comment by ramtrooper** [comment]
Hacked emus I've used disable frame limiter (run at 999999 fps). Then later on re-enable frame limiter (60/50).

disk / cd access are still kept at normal 1x, because they break lots of games when overclocked.

**Comment by bearoso** [comment]
I'm not sure this would be as helpful on the SNES. The cartridge format removes most of the loading time, and this trick wouldn't work to bypass the long introductory credits in some games.

What games do you know of that are dark and soundless for more than a second?

**Comment by ramtrooper** [comment]
Magical Popn sticks out in my mind ~6-7 seconds boot (black screen). Lost Vikings II is also very slow boot (black screen).

I'll try coming up with a list.

**Comment by ramtrooper** [comment]
Had some talks with others and it's suggested that using higher overclocking (like fast vram,dma access) would likely achieve similar results for many games. And avoid some pitfalls like music or sound effects that have sizable audio pauses for drama effect (during blank screens).

Thanks anyway for considering this!
