### ISSUE TITLE
[Question] How contributr to translating??

### ISSUE THREAD

**Issue by jristz** [snes9xgit/snes9x#38]
So that...
I want contribute to translating the GUI to another language

so you have transifex, or any fancy mathematical place for that or like the old way of clone and pull??

**Comment by vgturtle127** [comment]
We do not have a transifex, and you should probably tell us what language you want to translate snes9x into first, since it may already be in that language.

Language isn't about math, by the way? :laughing:

**Comment by jristz** [comment]
Spanish (es), i have experience translating Xfce and Voxelands, both use
transifex, but also i know how poedit work.

**Comment by vgturtle127** [comment]
SNES9X doesn't use .po files either. I think translating might be an issue, since I believe everything is hardcoded...

**Comment by OV2** [comment]
The gtk version supports translations via po files, the windows version is not translatable without rebuilding.

**Comment by vgturtle127** [comment]
Oh, I didn't see that. Is the GTK version going to be upgrading to GTK3 soon? I only ask because GTK3 seems to cause some issues when building, and if we wanted people to help translate that version then we would want to upgrade first before anybody started modifying the current files.

Also, is there a chance we may move away from GTK, or use the GTK version on Windows or something?

**Comment by jristz** [comment]
Gtk2 is near death in the sence tha maybe no more updates will be shipped,
unless snes9x want get frozen in Gtk2 and risk Gtk2 bugs then better
migrate to Gtk3 Lije Xfce is doing or QT5 like Lxde, not mather what the
end I want translate Snes9x.

**Comment by vgturtle127** [comment]
@jristz Haha, OK. I can see you are interested. Is the current https://github.com/snes9xgit/snes9x/blob/master/gtk/po/es_VE.po file any use, or is it a different regional version of Spanish?

**Comment by jristz** [comment]
El lun 28/09/2015, 1:56 PM, vgturtle127 <notifications
<notifications@github.com>@ <notifications@github.com>github.com
<notifications@github.com>> escribió:

@ <https://github.com/jristz>jristz <https://github.com/jristz> Haha, OK. I
can see you are interested. Is the current https
<https://github.com/snes9xgit/snes9x/blob/master/gtk/po/es_VE.po>://
<https://github.com/snes9xgit/snes9x/blob/master/gtk/po/es_VE.po>github.com
<https://github.com/snes9xgit/snes9x/blob/master/gtk/po/es_VE.po>/
<https://github.com/snes9xgit/snes9x/blob/master/gtk/po/es_VE.po>snes9xgit
<https://github.com/snes9xgit/snes9x/blob/master/gtk/po/es_VE.po>/
<https://github.com/snes9xgit/snes9x/blob/master/gtk/po/es_VE.po>snes9x
<https://github.com/snes9xgit/snes9x/blob/master/gtk/po/es_VE.po>/
<https://github.com/snes9xgit/snes9x/blob/master/gtk/po/es_VE.po>blob
<https://github.com/snes9xgit/snes9x/blob/master/gtk/po/es_VE.po>/
<https://github.com/snes9xgit/snes9x/blob/master/gtk/po/es_VE.po>master
<https://github.com/snes9xgit/snes9x/blob/master/gtk/po/es_VE.po>/
<https://github.com/snes9xgit/snes9x/blob/master/gtk/po/es_VE.po>gtk
<https://github.com/snes9xgit/snes9x/blob/master/gtk/po/es_VE.po>/
<https://github.com/snes9xgit/snes9x/blob/master/gtk/po/es_VE.po>po
<https://github.com/snes9xgit/snes9x/blob/master/gtk/po/es_VE.po>/
<https://github.com/snes9xgit/snes9x/blob/master/gtk/po/es_VE.po>es_VE.po
<https://github.com/snes9xgit/snes9x/blob/master/gtk/po/es_VE.po> file any
use, or is it a different regional version of Spanish?

—
Reply to this email directly or view
<https://github.com/snes9xgit/snes9x/issues/38#issuecomment-143803622>
<https://github.com/snes9xgit/snes9x/issues/38#issuecomment-143803622>it
<https://github.com/snes9xgit/snes9x/issues/38#issuecomment-143803622>
<https://github.com/snes9xgit/snes9x/issues/38#issuecomment-143803622>on
<https://github.com/snes9xgit/snes9x/issues/38#issuecomment-143803622>
<https://github.com/snes9xgit/snes9x/issues/38#issuecomment-143803622>GitHub
<https://github.com/snes9xgit/snes9x/issues/38#issuecomment-143803622>.<img
src="
https://ci5.googleusercontent.com/proxy/X6c7bDg9npUwXNs2QDC3ibI1liKYvV81DDDKkrGOwjTai_yE96F6ALu3xzgRhntT5OcGPX4JT4kv2NdewGlYA16Xnz9Wn6whm93eGLR56go2buHdf7sNMbuad43E9rwODYYG-4IAbcI2EKxTd3mRMZxaj2jr5g=s0-d-e1-ft#https://github.com/notifications/beacon/AA0Orr_1XZb3co2hSWzKJqx0pt07z5gXks5o2WipgaJpZM4A6AM9.gif
">


es is panispanic, es_419 is latin american spanish and es_ES is spain
spanish, the current is es_VE wich is Venezuelan spanish, the advwntage of
es over regional extra is that this es is usable with any locale starting
with es bit es_VE only if es_VE is tjw locale.

**Comment by vgturtle127** [comment]
OK, I see. Too bad there isn't an English .po file that we could use to translate as a starter...

**Comment by jristz** [comment]
I manage to use the sourcecode to pull throw poedit the new strings and then I fork to finish the translation.
It need corrections but is at 100% unless poedit not take all the new strings.

**Comment by bearoso** [comment]
Use #225 for this.

**Comment by StanleyKid-22** [comment]
@bearoso, I understand that question has been raised more than one time, but... Is it possible to support PO translations for Windows? It would make sense for me to support the Ukrainian translation, since part of the resources (especially the unit "Strings") is encrypted for resource editors...

**Comment by bearoso** [comment]
The Win32 port can't use PO files. Win32's ability to handle translations is very manual, basically using macros for strings, so it's tedious to create and use them. 

There is a half-complete Qt port I started a while back that runs on Windows and could handle translations if I finish it. They'd be created and edited with Qt Linguist.

**Comment by StanleyKid-22** [comment]
> There is a half-complete Qt port I started a while back that runs on Windows and could handle translations if I finish it. They'd be created and edited with Qt Linguist.

Oh, that's great, thanks.
