### ISSUE TITLE
Request: cleaner hires blending

### ISSUE THREAD

**Issue by ramtrooper** [snes9xgit/snes9x#380]
I saw someone playing snes mini with Kirby's Dream Land 3 (hakchi snes9x). But screenshots show the hires blending is somehow different from normal or libretro snes9x -- it's a lot less blurry without filters, plus works correctly with shaders like scale2x.

I would love to have this clean hires blending -- I heard there's some hack that gives the same non-blurry mixing look, but it doesn't work the same when used with scale2x.

Do you know how they did this?

Thank you

**Comment by Tatsuya79** [comment]
[Probably something from here.](https://github.com/kps501/bright_snes9x/blob/master/libretro/render.cpp#L272)

**Comment by bearoso** [comment]
> Probably something from here.

That was copied from the GTK+ port. I just merge adjacent fields in pairs instead of a spatial blur to the right like bsnes and the Windows port.

**Comment by Tatsuya79** [comment]
Oh? I didn't know.
Something I noticed when snes9x is displaying a higher res (in Hoshi no Kirby 3), the left side of the screen has like a 1 pixel column with "artefacts".

**Comment by bearoso** [comment]
>Oh? I didn't know.
Something I noticed when snes9x is displaying a higher res (in Hoshi no Kirby 3), the left side of the screen has like a 1 pixel column with "artefacts".

This is probably due to the ppu window fix. I wonder if byuu's hires plotter will work now and fix that.

**Comment by bearoso** [comment]
Kirby 3 should be fixed. Depending on the BG offset, column 0 wasn't being updated most of the time, so garbage was left on the screen. @OV2, you might want to look and see if the change I made is OK.

**Comment by Tatsuya79** [comment]
Thanks that looks better now!
[Does it mean this buffering can be removed now](https://github.com/libretro/snes9x/commit/0c5cee96eaa2446b3bd40adf36a61d02e1d6e35b) as it was made to try to hide that issue (somewhat)?

I removed it locally and I didn't see any difference in kirby 3 hi-res clouds scrolling.

**Comment by bearoso** [comment]
> Does it mean this buffering can be removed now as it was made to try to hide that issue (somewhat)?

I guess. I don't understand why that's there.

**Comment by bearoso** [comment]
Ok, I added the merge option, and got rid of the buffers and merged your sprite limit increase to 128.

**Comment by Tatsuya79** [comment]
Thanks, works fine!

**Comment by ramtrooper** [comment]
That's really awesome of both of you! I have to wait until the libretro nightly buildbot pushes but I'm confident it's perfect.

Thank you again!

**Comment by OV2** [comment]
The buffer might have been added to be able to turn it on and off while paused?

@bearoso looks fine. I didn't think of the case where OffsetInLine falls into the previous line. Probably for clipped tiles?

**Comment by bearoso** [comment]
>The buffer might have been added to be able to turn it on and off while paused?

I thought about that, but Retroarch keeps a copy of its own that it shows when paused.

> looks fine. I didn't think of the case where OffsetInLine falls into the previous line. Probably for clipped tiles?

I checked to see if there was any weird wrapping behavior on other hires games, and it seems to work properly. I guess we'll have to just wait and see if any bugs crop up.

**Comment by ramtrooper** [comment]
Someone compiled latest libretro for me and yup: merge blur gives that perfect pixellated look. And scaling shaders upscale correctly. Exactly matches what I saw in hakchi.

Thanks a lot for adding that in! I'll start testing Japan hires games and looking for column 0 errors before closing this solved! issue.

**Comment by Tatsuya79** [comment]
[Kps501 added that buffer just after I reported the Kirby 3 little glitch, you can see it in that thread.](https://github.com/libretro/snes9x/pull/158)
I didn't see a problem either after pausing and changing the blending, I don't think that's needed at all now.

**Comment by ramtrooper** [comment]
Could we have a win32 conf option to choose between merge and blur, like in libretro port? Thanks regardless!
