### ISSUE TITLE
No macOS compiled builds for 1.56, 1.56.1, or 1.56.2 (or 1.54 or 1.54.1)

### ISSUE THREAD

**Issue by yetisyny** [snes9xgit/snes9x#385]
OK so versions 1.55, 1.53, 1.52, I can download macOS compiled builds for those that work. But 1.56.x and 1.54.x, no macOS builds of Snes9x for those versions are available.

Mostly I would just like to play the latest version of Snes9x on macOS. Currently the latest I can play is 1.55.

Oddly enough, though, I can also use another emulator called OpenEmu which includes Snes9x as an “emulation core” and in its latest version 2.0.6.1 it somehow includes Snes9x 1.56.2 as an “emulation core”. So that is what I have been using although it lacks various features of the standalone Snes9x. Also I am a little confused since OpenEmu 2.0.6.1 came out in December 2017 yet it includes Snes9x 1.56.2 which came out in June 2018 yet apparently it auto-updates its emulation cores somehow through some mechanism. Strange.

Anyway if the Snes9x emulation core version 1.56.2 can be compiled on a Mac, and Snes9x 1.55 was able to have its full .app package compiled on a Mac, certainly the full .app package for the latest Snes9x 1.56.2 ought to be able to be compiled on a Mac as well.

Apparently from [pull request 256](https://github.com/snes9xgit/snes9x/pull/256) which got merged, currently it can compile with the 10.7 thru 10.11 macOS SDK in Xcode 8 according to what it says there (the 10.12 or later macOS SDK no dice since QuickTime headers are missing). So it ought to be possible to compile and build the latest version using that technique. @tmkk who submitted that pull request seemed to successfully compile it. Perhaps we could get @tmkk to compile and build the current version since they came up with the directions for how to compile and build it not so long ago in that pull request? Or maybe the OpenEmu people could do that since they already do it for their Snes9x emulation core? I don’t know there has to be SOMEBODY willing to do it!

Yes I know you do not have a macOS maintainer presently. Well, having someone at least build it on macOS and get a working .app package that you can publish, that I can play on, that is good enough for me, to allow me to be able to play it. Sure it might have some platform specific bugs but that is better than not having it at all. Version 1.55 added MSU-1 support and I am glad to have that!! Version 1.56 and its subsequent updates have a lot of neat fixes, I would like those too.

As far as why I am not doing this myself, for one thing I don’t have an Apple Developer account which costs money so I can’t digitally sign it for it to be acceptable to Gatekeeper. Only someone with an Apple Developer account should be compiling and releasing the .app image so that it gets approved by Gatekeeper, the macOS security service that prevents unsigned applications from running. You just need to find someone with an Apple Developer account who is willing to do this and get them to do it for you.

**Comment by tmkk** [comment]
Here is a 1.56.2 OSX build with cheat fixes (77c3017, 645f471) applied
[snes9x-1.56.2-macosx-i386.zip](https://github.com/snes9xgit/snes9x/files/2280350/snes9x-1.56.2-macosx-i386.zip)
