### ISSUE TITLE
Psycho Dream

### ISSUE THREAD

**Issue by noooq** [snes9xgit/snes9x#387]
This game doesn't run correctly. Missing logo at start, blinking title screen and stays blank when starting a game.

**Comment by Tatsuya79** [comment]
It goes in game after a while, then it's constantly flickering and reacting on input randomly, like it's constantly pausing/starting again or something.

(testing in retroarch x64)

**Comment by lordpeluca** [comment]
The same thing happens to me in version 1.56.2 in window xp. I tried it with version 1.55 (which I have saved on the hard drive) and it works without problems.

**Comment by bearoso** [comment]
The dialogue stuff after the title screen sets an IRQ at the HC=1200 or so mark and expects it not to trigger. 

Does the V-IRQ on the same line possibly only work on reassertion of the same value, rather than initial set?

**Comment by bearoso** [comment]
Ok, what I'm thinking is that it needs to rewrite the VTIMER to trigger an IRQ again on the same line. So maybe writing to 4200 we pass false to S9xUpdateIRQPositions?

**Comment by OV2** [comment]
It seems I was wrong, the problem sequence with psycho dream looks like this:
IRQ is running, it reads 4211 to clear the flag. It then sets 4200 and 4209 to set up the new VIRQ, but our timer triggers after writing to 4200 and before 4209 is written. After the IRQ returns the next then fires immedately.

Changing cpuexec.cpp to this fixed it for me:
`if (CPU.Cycles >= Timings.NextIRQTimer && !CheckFlag(IRQ))`

**Comment by bearoso** [comment]
> but our timer triggers after writing to 4200
Yeah, that's why I think writing to 4200 shouldn't pass true to S9xUpdateIRQPositions, which fixes it for me.
I've tested the games that rely on this behavior, and they work, which makes me think that VTIMER needs to be written again to retrigger the IRQ. Reading some of byuu's past posts seems to confirm this.

**Comment by bearoso** [comment]
Are all games still working with your fix? If everything still works, we should probably commit both fixes.

**Comment by OV2** [comment]
Did some more testing, and my change would require
`if (CPU.Cycles >= Timings.NextIRQTimer && (!CheckFlag(IRQ) || CPU.WaitingForInterrupt))`
since the IRQ flag starts set and some games use WAI before clearing it.

I'll just table it for now since there is no added benefit.
