### ISSUE TITLE
bug: Looney Tunes B-Ball

### ISSUE THREAD

**Issue by ramtrooper** [snes9xgit/snes9x#389]
Only libretro port looks affected:
- set controller2 to multitap
- boot game. main menu. 3p-4p options greyed out
- reset game. main menu. all options ready

With win32:
- set super multi-tap (5-player)
- boot game. main menu. all options ready

**Comment by Tatsuya79** [comment]
That's something I was wondering if it was needed or not:
https://github.com/libretro/snes9x/pull/130/files

**Comment by bearoso** [comment]
Should be fixed by #402.
