### ISSUE TITLE
bug: air strike patrol

### ISSUE THREAD

**Issue by ramtrooper** [snes9xgit/snes9x#390]
win32
1. Save state1 on main menu
2. Save state2 on radar map
3. Load state1. Okay.
4. Load state2. Radar map bounces up-down for 1 frame.
5. Load state2 again. Weird graphics corruption on upper half for 1 frame.

libretro
1. Save state1 on main menu
2. Save state2 on radar map
3. Load state1. Weird interlace 1/2 screen for 1 frame.
4. Load state2. Weird graphics corruption on upper half for 1 frame.

**Comment by jjfmz42015** [comment]
which build(s) did you test? latest?

**Comment by ramtrooper** [comment]
Latest builds for both

**Comment by jjfmz42015** [comment]
will test a few builds when i get a chance to see if its a new bug

**Comment by bearoso** [comment]
Expected behavior. When loading a save state, there’s no data for the previous frame’s interlaced fields yet.

**Comment by jjfmz42015** [comment]
nothing here for me to test then lol

**Comment by ramtrooper** [comment]
libretro port suffers this drawing bug: on radar map screen (interlace), loadstate title/main menu (non-interlace). 1/2 height is shown for 1 frame, with black scanlines.

win32 looks perfect, no errors.

**Comment by retrotalker** [comment]
When ASP is on radar screen (interlace) and we loadstate to title (non-interlace), we still draw the title screen as interlace for 1 frame = black scanline bars. The next frame shows up normal as non-interlace and glitchy goes away.

Same when we go other direction. Although there's some leftover picture data that needs to be cleared from gfx buffer when going up in size.

So we just need to update the viewport sizing on load state. Which I think is solvable and doesn't require much work.
https://github.com/retrotalker/snes9x/pull/6

windows test apps:
https://ci.appveyor.com/project/retrotalker/snes9x/build/1.56.2-24

**Comment by ramtrooper** [comment]
Thanks guys! Another issue gone!
