### ISSUE TITLE
Clayfighter - blue clown face

### ISSUE THREAD

**Issue by Papermanzero** [snes9xgit/snes9x#391]
Start clayfighter and select a player. After the player entered the clownface, the face zooms out and becomes blue. However it has to stay white like in the original hardware.

**Comment by jjfmz42015** [comment]
can confirm this issue.

tested several builds then decided to go as far back as 1.52fix4 and it even happens there.

**Comment by bearoso** [comment]
> tested several builds then decided to go as far back as 1.52fix4 and it even happens there.

Well, it's a relief we didn't screw it up. It just means its an obscure bug in anomie's convoluted renderer again.

**Comment by jjfmz42015** [comment]
the rest of the game seems un effected.

**Comment by retrotalker** [comment]
bug:
dae6e3 lda #$0070
dae6e6 sta $002121
dae6ea lda #$0000
dae6ed sta $002122
dae6f1 sta $002122
dae6f5 jsr $19c3

cgram $71 gets corrupted by accident

**Comment by bearoso** [comment]
It's trying to set it $0071 to 0. What's the value instead?

**Comment by retrotalker** [comment]
clown white = 7bde; afaik, $71 stays unchanged and never updated

**Comment by bearoso** [comment]
Ok, I see what's going on. The write shouldn't go through unless it's written twice, but we're doing it anyway. 

sta $002121 is a 16-bit write, which hits $2122. This means the last sta $002122 shouldn't do anything. This is obviously a programming mistake in Clayfighter that just happens to work.

**Comment by bearoso** [comment]
Fixed in 1ca15b4a4f2cbbf3df64892eea41cdefc0a1ceb0
