### ISSUE TITLE
Final Fantasy VI: Top minimap line flickers on chocobo.

### ISSUE THREAD

**Issue by bearoso** [snes9xgit/snes9x#397]
Probably an IRQ problem.

**Comment by bearoso** [comment]
The horizon line also doesn't show properly while on chocobo. Not directly IRQ-related, but sort of. It's the timing of the render event.

Currently, our render event is at HC=192. If I move it slightly to the right it fixes the issue. 

bsnes renders at the start of the hblank interval. The idea is that most games will set up for the next line using that time. This fixes FFVI. Super Metroid, whose minimap is very susceptible to changes in the render location also works at hblank. 

@OV2, what do you think about changing this, and do you know of any games other than Super Metroid that might be hurt by it?

**Comment by OV2** [comment]
I wasn't even aware that Super Metroid is sensitive to render timing.

It looks like it was performed in HBLANK_END_EVENT until 1.50, where it was moved to its own event (probably during the rewrite from anomie).
So you'd move it to HC_HBLANK_START_EVENT ? Sure, go ahead.

**Comment by bearoso** [comment]
Ok, it looks like bsnes is using HC=512 at the moment, so we'll copy that and use 512, too. It seems to work just as well. If any issues crop up, we can look at it again.
