### ISSUE TITLE
Is this an glitch of emulation?

### ISSUE THREAD

**Issue by lordpeluca** [snes9xgit/snes9x#401]
I do not know if it is a graphic error of the emulator or if it also happens in the console.

In the fatality of sub-zero, when I throw ice before fatality (F F D - X), you see a little ice at the end of the screen:
https://s15.postimg.cc/y682khrfv/image.jpg

It is normal?

PD: It does not always happen, it's a random error.

**Comment by bearoso** [comment]
The way it appears looks to me like a programming oversight more than a bug in emulation. I'd definitely try to confirm it on hardware before looking further.

**Comment by lordpeluca** [comment]
I tried the higan emulator (v.106) and the same thing happens to me. It's something that happens randomly, sometimes it does not happen.

So, yes, I think the game is like that ...

Greetings.

**Comment by bearoso** [comment]
If it's happening in higan, it's likely just a game bug, not an emulator bug.
