### ISSUE TITLE
Stunt Race FX Garbage graphics on the course selection screen.

### ISSUE THREAD

**Issue by jjfmz42015** [snes9xgit/snes9x#405]
Stunt Race FX
Garbage graphics on the course selection screen.

I know this is a known issue, but is it forgotten?

Im sure the current team can nail this one with the miracles Ive seen.

**Comment by retrotalker** [comment]
superfx
7eee4 color
7eee5 loop
7eee6 plot (8-bit)


if( !(GSU.vPlotOptionReg & 0x10) )
{
  if( !(GSU.vPlotOptionReg & 0x01) && !(c&0xf)) return;
}


This fails during course select menu and never writes out noise pixels. I'm not even amateur in Super FX behavior so I stopped here.

But removing that line makes it work.

**Comment by bearoso** [comment]
I assumed it was a plotter, but I haven’t investigated this yet. I think I verified that the POR is being used correctly when debugging doom, so I’ll have a look at it.

**Comment by bearoso** [comment]
Well, you were mostly right. It just needs an extra check for a bit of the plot option register to determine if it uses the high bits.

**Comment by jjfmz42015** [comment]
fixed in 1.56.2-365 but when you press start the window now flickers real fast

**Comment by bearoso** [comment]
I know. We're running the SuperFX too slowly, so it doesn't finish in time. Bump up the SuperFX clock speed a bit to fix it.
