### ISSUE TITLE
1.57

### ISSUE THREAD

**Issue by jjfmz42015** [snes9xgit/snes9x#413]
With all the game compatibility that's been fixed and all the enhancement maybe it's time to push the latest WIP as a release? Most ppl I have talked to were using latest stable till I tell them about appveyor build. Snes9x is more compatible now might as well have the world notice?

All that being said just a suggestion. And thanks for this emulator!

**Comment by OV2** [comment]
I guess we could try to get to a new version. Still want to investigate the reported DMA issue, but haven't had much time lately. I've got some vacation coming up where I can maybe look into that.

@qwertymodo do you still want to give an installer a shot?

**Comment by qwertymodo** [comment]
I wasn't sure if it was still worth it, with the DX9 shortcut being added into the GUI, but sure, I can still do it.

**Comment by OV2** [comment]
Yes, an installer would need to install into %APPDATA% by default (or my documents). Similar to chrome etc.

The 32bit version should work, its settings will land in the virtualstore.

**Comment by Felipefpl** [comment]
Does that modified colored version of snes' icon will be in?

**Comment by jjfmz42015** [comment]
> 10 completely broke the ability for applications installed in the default %PROGRAMFILES% path to write to their own freaking config files if they happen to be hardcoded to write those files in the same directory as the application itself, so installing Snes9x into %PROGRAMFILES% breaks on launch because it can't create Valid.Ext, or snes9x.conf, or any of the various folders. The "Right Way" (aka "The M$ Way") would be for those files and folders

This was the only reason I originally feared going to installer. Future compatibility. Portable stand alone apps have less to go wrong when slight changes are made to an OS.

**Comment by bearoso** [comment]
So it's getting about time for the next release. There's a couple things I want to do in the GTK+ port before that:
* The relative-style save states as mentioned in pull request #89.
* Pointer-grabbing for the mouse.
Neither will take too long. 

We can add Felipefpl's requested colored icon as an additional resource to the win32 binary.

If there's anything else that should be included, now is the time to say something.

Before release, we need to 
* Update version number to 1.57
* Update copyrights.
* Write changelog.

I also need to remember to run autogen.sh in the gtk directory before making the source tarball.

**Comment by OV2** [comment]
I wanted to take a look at choosing the audio device for win32, but that can also wait for the next version.

I'll remove the high-res option in the win port for #348.

**Comment by bearoso** [comment]
* Relative states complete.
* Pointer grabbing complete.
* Multicolored icon complete
* Update version number complete 
* Copyrights were already 2018 complete

@OV2, you'll want to look at the changelog and see if I missed anything or failed to elaborate. The changes to the libretro version were so plentiful, I just grouped them into one big entry.

**Comment by OV2** [comment]
I've mirrored the files. @tmkk do you want to provide a mac build again?

**Comment by tmkk** [comment]
Here it is: [snes9x-1.57-macosx-i386.zip](https://github.com/snes9xgit/snes9x/files/2568371/snes9x-1.57-macosx-i386.zip)

**Comment by OV2** [comment]
Thanks a lot. I've added it to the release page and mirror.

**Comment by Felipefpl** [comment]
Thanks bearoso, ov2 or whoever added the icon, i really like it. :)
