### ISSUE TITLE
libretro sync

### ISSUE THREAD

**Issue by retrotalker** [snes9xgit/snes9x#422]
Instead of the hassle of keeping a shallow fork, @twinaphex is asking to merge the few remaining bits into master and then use upstream exclusively.

1) Some port fixes (no flto, ps3 misc)
https://github.com/libretro/snes9x/commits/master
https://github.com/libretro/snes9x/pull/176 (see tail end of thread)

2) Remove msvc and use makefile
https://github.com/libretro/snes9x/issues/177 (see last 2 posts)

pending fix for appveyor libretro:
https://github.com/retrotalker/snes9x/pull/2/commits/073bf70722c8e752dcb8cdec79f4850319d0e20a
https://ci.appveyor.com/project/retrotalker/snes9x/build/1.56.2-4 (libretro appveyor uses 5 windows platforms)

**Comment by twinaphex** [comment]
@retrotalker It's not really a huge hassle though. I have no qualms about starting to use upstream for some cores, however, I do not like being forced or 'nudged' in that direction either. I see this happening in the Genesis Plus GX core instance too and I hope you can keep in mind that I don't particularly like this. It is on my radar already and it doesn't need intermeddling by an intermediary party.

**Comment by twinaphex** [comment]
With that being said, let's try to get this done and let's hope it leads somewhere. Just keep this in mind when it comes to future repos and other projects. Whenever people get between other projects' affairs, accidents happen and I am trying to avoid that in the future.

**Comment by retrotalker** [comment]
Right, I get it now. Sorry about that.

I'd still like to try and discreetly reduce diffs if possible; there's so many different forks with all sorts of great ideas. And some not-so-usable ones without rewrites.

**Comment by twinaphex** [comment]
@retrotalker That is fine.

Anyway, no need to close this issue, we can let this remain open, since the points you raise are valid and they should definitely be addressed in upstream.
