### ISSUE TITLE
Why is OpenBus sometimes written multiple times?

### ISSUE THREAD

**Issue by bonimy** [snes9xgit/snes9x#433]
[cpuaddr.h:322-323](https://github.com/snes9xgit/snes9x/blob/master/cpuaddr.h#L322) and [cpuaddr.h:334-335](https://github.com/snes9xgit/snes9x/blob/master/cpuaddr.h#L334) are a few examples:

I'm basically seeing this a few times:
```c
OpenBus = addr2 >> 8;
addr2 |= (OpenBus = S9xGetByte(addr + 2)) << 16;
```

It seems to be pointless doing the first `OpenBus = addr2 >> 8;` instruction.

**Comment by OV2** [comment]
S9xGetByte can return OpenBus, depending on the address. In that case it should return the last value read on the bus.
