### ISSUE TITLE
libretro preferred aspect ratio (?)

### ISSUE THREAD

**Issue by lacastri** [snes9xgit/snes9x#438]
Not clear to me if this is a bug or intentional.

```
Chrono Trigger
8:7  = 256x224 (8:7 dar = 1:1 par)
ntsc = 293x224 (8:7 par)
4:3  = 299x224 (4:3 dar)
```
This seems okay to me.

```
Super Godzilla
8:7  = 273x239 (8:7 dar) <--- or should this be 256x239 (1:1 par)?
ntsc = 293x239 (8:7 par)
4:3  = 319x239 (4:3 dar)
```
If 8:7 dar intended, then no problems.

If we want 1:1 par when overscan is on
```
float get_aspect_ratio(unsigned width, unsigned height)
{
    if (aspect_ratio_mode == ASPECT_RATIO_4_3)
    {
        return SNES_4_3;
    }
    else if (aspect_ratio_mode == ASPECT_RATIO_8_7)
    {
        return SNES_8_7;
        ===>
        return (float)width * 1.0f / (float)height;
    }
```

Or we need another aspect_ratio_mode for 1:1 par.

**Comment by bearoso** [comment]
I don't think anyone actually wants 8/7 "stretched" aspect. It should always just be 1:1 PAR here.
I'm renaming 8:7 to "uncorrected," and it'll always have square pixels.
Fixed in c6ade49.

**Comment by lacastri** [comment]
Overscan screenshots look correct now. Thanks again!

**Comment by qwertymodo** [comment]
My understanding is that the two options people will want are 1:1 PAR which results in 8:7 DAR ("square pixels"), or 8:7 PAR, which results in 64:49 DAR (essentially 4:3, "CRT ratio").  People tend to get confused between PAR and DAR when referring to "8:7" (it doesn't help that both are relevant in this case).  Even the SuperNT gets it wrong in that regard.

**Comment by bearoso** [comment]
Yeah, and we have those two now, with the only numeric option being 4:3, which is deliberate. 8:7 PAR is NTSC and 1:1 PAR is "uncorrected."
