### ISSUE TITLE
tetris & dr mario glitch

### ISSUE THREAD

**Issue by jjfmz42015** [snes9xgit/snes9x#442]
tetris & dr mario glitch

Tetris Background first few lines rendered incorrectly. look at chains to notice.

Proper behavior can be observed in bsnes

**Comment by Tatsuya79** [comment]
I think it's just the overscan doing that, you probably have it disabled in bsnes (224 vs 240 lines).

**Comment by jjfmz42015** [comment]
You are correct. oops and thanks.
