### ISSUE TITLE
Feature request: crop extended height images equally from top and bottom

### ISSUE THREAD

**Issue by jjfmz42015** [snes9xgit/snes9x#443]
feature request add ability to crop over scan area

**Comment by bearoso** [comment]
Done (it's already there).

**Comment by bearoso** [comment]
On Windows, disable the check box "Extend Height of SNES Image."

**Comment by jjfmz42015** [comment]
doesnt crop enough. example tetris & dr mario. tetris mode. compair with bsnes and real hardware

**Comment by bearoso** [comment]
Oh, I see. The game outputs a 239 pixel image, and you want the top and bottom cropped mostly equally, when the Windows port just chops off the bottom 15.

**Comment by bearoso** [comment]
I’m not sure whether the libretro port does this correctly. I fixed the gtk port in the last version.

**Comment by Tatsuya79** [comment]
In retroarch:
![super mario world usa -181019-234341](https://user-images.githubusercontent.com/6266038/47245404-6505da80-d3f9-11e8-9e3d-49048c6b826d.png)
![super mario world usa -181019-234351](https://user-images.githubusercontent.com/6266038/47245405-6505da80-d3f9-11e8-9505-eca4162e7330.png)
![tetris dr mario usa -181019-234624](https://user-images.githubusercontent.com/6266038/47245406-659e7100-d3f9-11e8-935d-16f2ddb2b5ce.png)
![tetris dr mario usa -181019-234642](https://user-images.githubusercontent.com/6266038/47245407-659e7100-d3f9-11e8-8287-8b0144c8e914.png)

**Comment by OV2** [comment]
I'll try to add an option to the win port.

**Comment by bearoso** [comment]
libretro version should work now. It'll take 7 off the top and 8 off the bottom. Should we also center the non-extended image when we don't crop the overscan? That's what I do ATM in the GTK port.

**Comment by Tatsuya79** [comment]
It's like this now (auto/ON/OFF)
![super mario world usa -181024-234141](https://user-images.githubusercontent.com/6266038/47463642-17b5ae80-d7e7-11e8-90ec-d800318c4c52.png)
![super mario world usa -181024-234144](https://user-images.githubusercontent.com/6266038/47463643-184e4500-d7e7-11e8-867c-829425a45b91.png)
![super mario world usa -181024-234147](https://user-images.githubusercontent.com/6266038/47463644-184e4500-d7e7-11e8-8be3-bd4269433cdc.png)
![tetris dr mario usa -181024-234224](https://user-images.githubusercontent.com/6266038/47463645-184e4500-d7e7-11e8-8903-d4f121e50e26.png)
![tetris dr mario usa -181024-234228](https://user-images.githubusercontent.com/6266038/47463646-184e4500-d7e7-11e8-9a25-df5c3718ffcd.png)
![tetris dr mario usa -181024-234232](https://user-images.githubusercontent.com/6266038/47463647-184e4500-d7e7-11e8-9345-93883f66d2c5.png)

Centring would be better if possible yes.

**Comment by bearoso** [comment]
Whoops. Something isn't right there.

**Comment by bearoso** [comment]
Ok, fixed the dumb 224-line issue. I'll work on the centering.

**Comment by Tatsuya79** [comment]
Looks quite fine now (close to 0.5 pixel though :wink: ).
Thanks!

**Comment by OV2** [comment]
I've changed the win port and also added the centering. Any reason why gtk has -15 and libretro -16 in double height mode?

**Comment by bearoso** [comment]
I thought -16 was more appropriate, since double-height mode is interlaced, and 16 would cut off both fields of a scanline. I was going to change gtk to that.

**Comment by bearoso** [comment]
Ok, I fixed that in GTK+ port. I also changed the other 15 in the libretro port to 14, since it should be the complement of 16 to make 30.

**Comment by jjfmz42015** [comment]
Just tried latest build. Exactly what I was wishing for!!!!! Thank you guys!
