### ISSUE TITLE
Hotkeys to toggle graphics layers aren't user friendly.

### ISSUE THREAD

**Issue by Myramong** [snes9xgit/snes9x#444]
People accidentally disable layers and get confused quite often.  I don't think these hotkeys should be set by default.

**Comment by bearoso** [comment]
You're right. These needed to be accessible in the past because of transparency emulation problems, but they're rarely needed now.

**Comment by OV2** [comment]
I guess we can change the defaults to disabled for new configs.

**Comment by bearoso** [comment]
I went ahead and did this for win32. Should we do it for unix, too? I don't think its users would be confused by this.

**Comment by OV2** [comment]
I don't think that's necessary - if you're using the unix version then you probably know what you are doing.

**Comment by bearoso** [comment]
That's what I thought. Anyone using the unix version is probably using it for debugging.
