### ISSUE TITLE
BS Zelda not loading in Retroarch core

### ISSUE THREAD

**Issue by lilpuddy31** [snes9xgit/snes9x#445]
Hello all, recently I’ve noticed that BS Zelda is not loading with the latest Snes9x core, neither the plain version or the MSU version will load. I just get a blank screen. It does work on the standalone emulator though.  I’ve tried redownloading the rom and the core, but it still won’t play. Ancient Stone Tablets loads and plays just fine though. any suggestions? Could it be the rom or the core?

**Comment by Tatsuya79** [comment]
The retroarch snes9x repo just needs to be updated as it's working with the core built from this repo here.
I asked several times in RA dev chat but it seems to have been forgotten. Sorry I'm bad with git so I can't do it myself.

**Comment by bearoso** [comment]
I just put a pull request in on the libretro repository to merge snes9xgit/master.

**Comment by Tatsuya79** [comment]
Thanks!

**Comment by Tatsuya79** [comment]
Yes, when the buildbot comes to it.
It builds everything it can for a platform and then it finally uploads the files to the server.

**Comment by lilpuddy31** [comment]
Yep, you’re right. Windows Snes9x core now play BS Zelda again. Thank you guys for your help
