### ISSUE TITLE
Unable to build GTK at HEAD on Debian stretch (stable) due to old libepoxy.

### ISSUE THREAD

**Issue by alercah** [snes9xgit/snes9x#447]
HEAD does not currently build the GTK build on Debian stretch, currently the stable release, as the `epoxy_has_glx` function doesn't exist---stable packages only libepoxy 1.3.1. It will likely be well into 2019 before buster is released as stable.

**Comment by bearoso** [comment]
Ok, thanks for the heads-up. I’ll rework it so it doesn’t need that function.

**Comment by bearoso** [comment]
Should be fixed in de4699b .
