### ISSUE TITLE
Maximum Carnage USA doesnt fully display the background of the story's scenes

### ISSUE THREAD

**Issue by Felipefpl** [snes9xgit/snes9x#449]
Look at the pic, i took it with latest zsnes, you can see the squares with the text written inside and the characters that are part of the story on it. But this doesnt happen with snes9x 1.56 or 1.57, only the squares with text are shown while the place where the characters should be shows nothing, it's black. I have win7 x64 here.

![maximum carnage](https://user-images.githubusercontent.com/5569804/48315236-c9602800-e5ba-11e8-8390-d22e183f4426.gif)

**Comment by bearoso** [comment]
Don't have access to a computer right now, but I'm wondering if you just accidentally turned off the background layer with the text in it.

**Comment by OV2** [comment]
Check that you have transparency enabled in the video options, that would produce the effect you describe.

**Comment by Felipefpl** [comment]
bearoso, OV2 - i had transparency disabled, i enabled it and now it works fine, thanks for the help.

Just curious, why this option is there? I mean, zsnes doesnt have one like this.

**Comment by ImSpecial** [comment]
Good call on those hotkeys.
