### ISSUE TITLE
Kishin Kourinden: Oni & Bakumatsu Korinden: Oni - blank screen

### ISSUE THREAD

**Issue by noooq** [snes9xgit/snes9x#453]
When run, these two are just a blank screen. Latest from git.

**Comment by bearoso** [comment]
Working fine here on GTK+.

**Comment by bearoso** [comment]
Works fine on libretro port, too. I hope you remembered to turn off overclocking before submitting a bug.

**Comment by noooq** [comment]
Sorry false alarm. Close this.
