### ISSUE TITLE
(gtk) Crashes when ScanlineIntensity is missing from snes9x.conf

### ISSUE THREAD

**Issue by orbea** [snes9xgit/snes9x#457]
OS: `Slackware64-current`
snex9x: https://github.com/snes9xgit/snes9x/commit/1b61affbb55582ea47d1a01007de4af532d419e6

If the line `ScanlineIntensity = 4` is removed from the generated `snes9x.conf` file snes9x will segfault.
```
Thread 1 "snes9x-gtk" received signal SIGSEGV, Segmentation fault.
0x0000000000422e92 in ntsc_filter_init () at src/gtk_display.cpp:1529
1529	    snes_ntsc_scanline_offset = scanline_offsets [gui_config->ntsc_scanline_intensity];
(gdb) bt
#0  0x0000000000422e92 in ntsc_filter_init() () at src/gtk_display.cpp:1529
#1  0x0000000000422ef5 in S9xDisplayReconfigure() () at src/gtk_display.cpp:1538
#2  0x0000000000423c67 in S9xInitDisplay(int, char**)
    (argc=1, argv=0x7fffffffe228) at src/gtk_display.cpp:1899
#3  0x000000000042ad3f in main(int, char**) (argc=1, argv=0x7fffffffe228)
    at src/gtk_s9x.cpp:79
```
Full GDB log - https://pastebin.com/BbsYtZAx

This can also be reproduced if someone tries to use `docs/snes9x.conf.default`.
https://github.com/snes9xgit/snes9x/blob/1b61affbb55582ea47d1a01007de4af532d419e6/docs/snes9x.conf.default

This reveals a few problems.
1. It should not crash when `ScanlineIntensity` is missing or invalid and should set a safe default
2. It has been 8 years since `docs/snes9x.conf.default` was last touched and its grossly out of date. It should be either updated or removed. It doesn't seem needed anymore so the latter seems better.
3. There may be other lurking issues where missing or invalid configure options cause crashes?

**Comment by orbea** [comment]
Here is a band-aid, I imagine there is a better way.
```
diff --git a/gtk/src/gtk_display.cpp b/gtk/src/gtk_display.cpp
index aa64a1a..58d6d9c 100644
--- a/gtk/src/gtk_display.cpp
+++ b/gtk/src/gtk_display.cpp
@@ -1526,6 +1526,9 @@ S9xDisplayRefresh (int width, int height)
 static void
 ntsc_filter_init ()
 {
+    if (gui_config->ntsc_scanline_intensity > 4)
+        gui_config->ntsc_scanline_intensity = 4;
+
     snes_ntsc_scanline_offset = scanline_offsets [gui_config->ntsc_scanline_intensity];
     snes_ntsc_scanline_mask   = scanline_masks [gui_config->ntsc_scanline_intensity];
 
```

**Comment by bearoso** [comment]
There was a sanity check, but it mistakenly used MAX instead of MIN. Also fixed defaults where config file isn't complete.

**Comment by orbea** [comment]
Thanks!
