### ISSUE TITLE
1.58

### ISSUE THREAD

**Issue by bearoso** [snes9xgit/snes9x#460]
Because users don't tend to update to the small point releases, and because we have a couple important fixes (movie playback, and the translated config file problem in GTK+), I figure we should release a 1.58 version. I've updated the version number everywhere and added some stuff to changes.txt. 

@OV2, if you have anything else to add, feel free. If you give the go ahead I'll do another release.

**Comment by OV2** [comment]
I'll try to get the audio device selection done this weekend - if I encounter any larger problems then we can just release it without that.

**Comment by OV2** [comment]
Ok, I've committed the device selection. I just noticed your arrow-changes for the input display, looks good!
Movies work fine with the change. It looks like regular input and polling buttons should now also behave the same for movies.

I think we can do a release now.

**Comment by Isakku** [comment]
I would like to ask a little question about 1.58. Will it break save states? I hope it won't. I have many saved states and I would not like to loose them. BTW I use Snes on Linux thanks to the flatpaked version:
https://github.com/flathub/com.snes9x.Snes9x
Thanks a lot to everyone who works on this amazing project.

**Comment by bearoso** [comment]
Nothing in this release affected save states. If they’re working in 1.57, they’ll still work.

**Comment by tmkk** [comment]
1.58 Mac build: [snes9x-1.58-macosx-i386.zip](https://github.com/snes9xgit/snes9x/files/2684509/snes9x-1.58-macosx-i386.zip)

**Comment by OV2** [comment]
Thanks a lot, I've added it to the release page and mirrored it.

**Comment by jjfmz42015** [comment]
the change log is missing alot of the changes that happened since 1.57 for the windows port.


Such as the over scan and cropping fixes.

**Comment by OV2** [comment]
That was already included in 1.57.

**Comment by jjfmz42015** [comment]
sorry my bad/.
