### ISSUE TITLE
Request: add this extra link for the XAudio2 error message

### ISSUE THREAD

**Issue by themalu866** [snes9xgit/snes9x#464]
I know that when XAudio2 is unable to start a message appears with a link to download what is necessary to make it work but for some reason I couldn't install it on my PC.
I tried to look for a way to install it and found that a lot of people have this same problem on Windows 7 and after a long time trying to fix that error I discovered this link on Microsoft website that installed 
XAudio2 perfectly and now everything works.
I'm not asking to change the original link for this one but add it as an extra link for the people who couldn't install XAudio2 the other way.
I just thought this would make everyone's life easier and for being from Microsoft's official site it would be okay to add it.

https://www.microsoft.com/en-us/download/details.aspx?id=6812

**Comment by OV2** [comment]
This is the first time I've heard of any issues. We can add the link to the faq entry, but I don't want to suggest people download a 570mb sdk in the message box.

**Comment by themalu866** [comment]
I've seen some old comments talking about this problem in different places but never with any other solution than "just switch to DirectSound" so I assumed that people who couldn't normally install XAudio2 just changed to Snes9x DirectSound as I did but with the 1.58 release I had to look for a way to install it and I didn't find anything.

Seriously, you have no idea how long it took me to find this.
I not asking to replace the original link or for this SDK to be one of the first options to download but rather a message like "If you can't install DirectX June 2010 try checking DirectX Software Development Kit" or something like that, just to give people a direction of what they need. The link may not even be necessary.

**Comment by themalu866** [comment]
You can close the issue.
