### ISSUE TITLE
Mega Man X2 (USA) bug

### ISSUE THREAD

**Issue by Cibomatto2002** [snes9xgit/snes9x#465]
On Snes9x 1.58 the grafix are jumping around here is a quick save.
[Mega Man X2 (USA).zip](https://github.com/snes9xgit/snes9x/files/2689548/Mega.Man.X2.USA.zip)

**Comment by Dwedit** [comment]
I'm pretty sure that's intentional, as you are revisiting a cleared stage, and it's "destroyed", so there's screen shaking effects.

**Comment by lordpeluca** [comment]
I don't know if it will happen in the console, but I tried in a version of Bsnes and visualized the same effect.

**Comment by lordpeluca** [comment]
I don't know if it will happen in the console, but I tried in a version of Bsnes and visualized the same effect in the "dinosaur Tank" scene.

**Comment by lordpeluca** [comment]
I don't know if it will happen in the console, but I tried in a version of Bsnes and visualized the same effect in the "Dinosaur Tank" scene.

**Comment by lordpeluca** [comment]
I don't know if it will happen in the console, but I tried in a version of Bsnes and visualized the same effect.

**Comment by Cibomatto2002** [comment]
I found this video on youtube where you don't see it happening.

https://www.youtube.com/watch?v=lTi1ZUGJGNM

**Comment by Dwedit** [comment]
That's not revisiting the completed stage.

**Comment by Cibomatto2002** [comment]
Here is a save where I'm not revisiting this stage same thing happens.

[Mega Man X2 (USA).zip](https://github.com/snes9xgit/snes9x/files/2691589/Mega.Man.X2.USA.zip)

**Comment by Cibomatto2002** [comment]
Sorry about that I thought it was a bug.
