### ISSUE TITLE
[gtk+] Debug builds broken

### ISSUE THREAD

**Issue by orbea** [snes9xgit/snes9x#467]
Its now impossible to build with debugging symbols for the gtk+ frontend, apparently meson doesn't allow overriding default options and these are more or less hardcoded...

https://github.com/snes9xgit/snes9x/blob/0b787becc1c00c3993a5aa90eede67e0e15e0ca0/gtk/meson.build#L5

Meaning its always going to be doing a release build that is stripped...

**Comment by bearoso** [comment]
No, it works fine. Just remember that it'll also pick up {C,CXX}FLAGS in the environment.
```
meson -Dbuildtype=debug -Dstrip=false . build
meson configure build
```
```
buildtype       debug         [plain, debug, debugoptimized, release, minsize, custom] Build type to use                             
...snip...
optimization    0             [0, g, 1, 2, 3, s]                                       Optimization level                            
strip           false         [true, false]                                            Strip targets on install                      
```

**Comment by orbea** [comment]
Okay, thanks! I see the real bug is the `meson --help` is not actually helpful...
```
  --buildtype {plain,debug,debugoptimized,release,minsize,custom}
                        Build type to use (default: debug).
  --strip               Strip targets on install
```
It works when using `-Dbuildtype=debug` and `-Dstrip=false` as you pointed out.
