### ISSUE TITLE
OpenGL Direct3D Question

### ISSUE THREAD

**Issue by Cibomatto2002** [snes9xgit/snes9x#468]
Just wanted to know why does Direct3D take less CPU than OpenGL? On OpenGL I get around 55 to 60% CPU on snes9x on Direct3D I get around 25 to 30%.

**Comment by bearoso** [comment]
Given similar workloads, probably spinlocks in the OpenGL driver vs signals/interrupts in Direct3D. It's basically "fake" cpu usage. Spinlocks will give better latency, though.

**Comment by Cibomatto2002** [comment]
I Closed this because I found out other Emulators was doing the same thing I never noticed it until last night Directdraw is taking about the same CPU power at OpenGL. Thanks for helping me with this I had no idea where to go for info on it. So does 55 to 60% sound about right for my setup.

 Operating System
	Windows 10 Pro 64-bit
CPU
	Intel Pentium G3240 @ 3.10GHz	30 °C
	Haswell 22nm Technology
RAM
	8.00GB Dual-Channel DDR3 @ 698MHz (10-10-10-25)
Motherboard
	Gigabyte Technology Co. Ltd. H81-D3 (SOCKET 0)	28 °C
Graphics
	ELEFW328 (1360x768@60Hz)
	Intel HD Graphics (Gigabyte)
	1023MB NVIDIA GeForce GT 720 (EVGA)	36 °C
	ForceWare version: 417.35
	SLI Disabled
Storage
	931GB TOSHIBA DT01ACA100 (SATA )	27 °C
Optical Drives
	HL-DT-ST DVDRAM GH24NSC0
Audio
	Realtek High Definition Audio
