### ISSUE TITLE
1.58 GTK Version: Reduce Input Lag causes heavy Slowdown

### ISSUE THREAD

**Issue by Holledauer2** [snes9xgit/snes9x#470]
Dear Snes9x Developers,
I use snes9x on a Linux Retro-Gaming Box on Intel Apollo Lake (Pentium J4205).
It really worked great but since the 1.58 rework on the Reduce Input Lag Option I have a complete slowdown/stuttering in e. g. Megaman X (USA, V1.1). If I deativate the Option there is no slowdown.
It depends on the game, e. g. Super Mario World or F-Zero there is no problem
In the 1.57 everything went fine in all games.

**Comment by bearoso** [comment]
Ok, thanks for the info. I'll separate the two different methods into different options.

**Comment by Holledauer2** [comment]
Ok, thank you very much!

**Comment by bearoso** [comment]
This is now added in git. The original method is "Reduce Input Lag with glFinish", while the new method is "Reduce Input Lag with glFenceSync".

**Comment by Holledauer2** [comment]
Great! Ok than i close this issue.
Again much thanks for your fast respones!
