### ISSUE TITLE
Cannot select Snes9x DirectSound in config dialog

### ISSUE THREAD

**Issue by owomomo** [snes9xgit/snes9x#471]
The Snes9x DirectSound engine cannot be selected in the sound config dialog, every time you selected, it will back to XAudio in the next time.

**Comment by OV2** [comment]
Should be fixed, you can try this [testbuild](http://s9x-w32.de/dl/testbuilds/snes9x_win32_testbuild_2018-12-29.zip).
Alternatively changing it in the snes9x.conf file still works.
