### ISSUE TITLE
Bug or Feature? Behavior at In-Game Saving (1.58 GTK Version)

### ISSUE THREAD

**Issue by Holledauer2** [snes9xgit/snes9x#473]
Dear Snes9x developers,
i encoutered a (in my eyes) strange behavior.
Wenn doing an In-Game save (Zelda - Link to the Past in my example),
it does not write the srm file before I quit SNES 9x. But it works within the game (e.g. after a game reset), so I think you write it to RAM first.
So when I save at some point and do not quit SNES 9x but simply shutdown my Retro game Box
with the On/Off Switch the game save is lost. It was also lost during a power outage we had.
Is this intended behavior?

**Comment by bearoso** [comment]
Yes, it's intended behavior. There's an option "Save SRAM X seconds after change" that allows you to change this. Set it to 1.

**Comment by Holledauer2** [comment]
Ah ok. Thank you very much. I didnt realize that this option does this

Am 4. Januar 2019 17:39:54 MEZ schrieb bearoso <notifications@github.com>:
