### ISSUE TITLE
snes9x-1.58-24-g8387fce Sound

### ISSUE THREAD

**Issue by Cibomatto2002** [snes9xgit/snes9x#475]
Did something change in snes9x-1.58-24-g8387fce sound because now I have popping sounds in Super Metroid? Here is a audio sample. 
[Super Metroid.zip](https://github.com/snes9xgit/snes9x/files/2731814/Super.Metroid.zip)

**Comment by bearoso** [comment]
625448333b64271b64ef23d753ed5fa7e9f90efb had an effect on Windows, but I'm not familiar enough with it to know if it could have affected that.

**Comment by OV2** [comment]
That only fixed the output method dropdown box. What version are you comparing it to? Did you maybe switch output method accidentally?
