### ISSUE TITLE
Only part of the screen is rendered in some games (Secret of Mana, Tales of Phantasia)

### ISSUE THREAD

**Issue by jstolarek** [snes9xgit/snes9x#478]
I have run into a bug where instead of rendering the whole game screen, snes9x magnifies the left upper corner and renders just that. I can reproduce this bug consistently on the title screen of Secret of Mana and the ending credits in Tales of Phantasia. Before and after these scenes the display is correct. Happens both with software scaler and OpenGL one. I am using snes9x-gtk 1.57 under Linux (built from source). I tried running the same roms with Zsnes and it works fine. Let me know if there's any information I can provide for further troubleshooting.

![snes9xbug2](https://user-images.githubusercontent.com/1597921/51073767-cabad900-166d-11e9-8942-cad34c9bd009.jpg)

![snes9xbug](https://user-images.githubusercontent.com/1597921/51073768-cb536f80-166d-11e9-9e28-6bedf2e7c6e5.jpg)

**Comment by bearoso** [comment]
These two areas use 512-width mode, so the software scaler is capped at 2x. Unfortunately, the fallback doesn't seem to be working properly, so I'll look into it.  It looks like you're using xbr x4. Switching down to x2 will fix it.

**Comment by bearoso** [comment]
Size fallback is fixed, but it still looks like there's an issue with the threading, too.

**Comment by jstolarek** [comment]
> Switching down to x2 will fix it.

Yes, that indeed fixes the problem.
