### ISSUE TITLE
WWF WrestleMania - The Arcade Game - Screen stays black when gameplay starts + bad flickering

### ISSUE THREAD

**Issue by Pat86** [snes9xgit/snes9x#481]
When you start the game and don't do any input the self running demo starts with a random fight. On the current version, the screen stays black when entering ingame. music keeps playing. Happens to both PAL and US version.

**Comment by lordpeluca** [comment]
It's the same with me. It doesn't show any image but the music is still playing. Snes9x 1.58

**Comment by bearoso** [comment]
Noted. I'm not really in the mood at the moment to trace interrupt-related stalls, so I can't promise I'll fix it soon. 

Does the problem occur in older releases as well?

**Comment by Pat86** [comment]
Just did a quick test on previous versions: Its broken since 1.56. 
1.55 is the last one that plays demo.

**Comment by Pat86** [comment]
BTW: Not only the demo mode is broken. Actual gameplay is broken as well. Screen stays black after the "Versus" Screen.

**Comment by Pat86** [comment]
On the NTSC version there is also some bad flickering going on when the player character is running to his next opponent before a fight.

**Comment by bearoso** [comment]
@OV2 
It's swapping HTimer and VTimer enabled in register $4200.
This fixes it:
```
if ((Byte & 0x30) != (Memory.FillRAM[0x4200] & 0x30))
{
	// Only allow instantaneous IRQ if turning it completely on or off 
	if ((Byte & 0x30) == 0 || (Memory.FillRAM[0x4200] & 0x30) == 0)
		S9xUpdateIRQPositions(true);
	else
		S9xUpdateIRQPositions(false);
}
```
I tested Psycho Dream and it still works with this, but I don't have RoboCop vs Terminator or know where it breaks. Can you check if it still works with the fix?

**Comment by OV2** [comment]
Seems weird that this doesn't allow instantaneous trigger... but then again almost all of the irq timing is somewhat weird.

RoboCop vs Terminator still works fine with your fix, it always turns it off and on. No flicker visible.

**Comment by bearoso** [comment]
Ok, committed. It doesn't break anything else I tested, but who knows?
