### ISSUE TITLE
compiling error - shader_helpers.h

### ISSUE THREAD

**Issue by jhonathanc** [snes9xgit/snes9x#482]
Error on building to win32, shader_helpers.h:

line 273, where:
static std::string canonicalize(const std::string &noncanonical)
{
    char *temp = realpath(noncanonical.c_str(), NULL);
    std::string filename_string(temp);
    free(temp);
    return std::move(filename_string);
}

should be:
static std::string canonicalize(const std::string &noncanonical)
{
    char *temp = "";
    realpath(noncanonical.c_str(), temp);
    std::string filename_string(temp);
    free(temp);
    return std::move(filename_string);
}

**Comment by OV2** [comment]
Was fixed with 5b01fa2dc19d327aabb9a443bbe541768b18bda2
