### ISSUE TITLE
Glitch on Tv Mode (only on Direct3D)

### ISSUE THREAD

**Issue by themalu866** [snes9xgit/snes9x#483]
With the game loaded I choose Tv Mode on Output Image Processing and when I enable/disable Bilinear Filtering, Stretch Image or Integer Scaling everything burns black and the image only appears if things move on the screen. you can even see the trail from where things have moved.
![hmm](https://user-images.githubusercontent.com/42208976/51270344-ca8f4600-19ab-11e9-80a4-a024589a5d04.png)
![why](https://user-images.githubusercontent.com/42208976/51270353-d11dbd80-19ab-11e9-81ee-9efe178327be.png)
![what](https://user-images.githubusercontent.com/42208976/51270364-d5e27180-19ab-11e9-9804-9e40479c2387.png)

This only happens on Direct3D, BUT on OpenGL something similar happens, the screen don't get black but the message on the bottom still freeze.

![tytyt](https://user-images.githubusercontent.com/42208976/52539484-abdf5d80-2d65-11e9-9fd0-fe4f5e2ee3f4.png)
![rtrtrt](https://user-images.githubusercontent.com/42208976/52539507-f8c33400-2d65-11e9-9011-55d55f66c4fa.png)

**Comment by bearoso** [comment]
Fixed in git.
