### ISSUE TITLE
Glitch on An American Tail: Fievel Goes West

### ISSUE THREAD

**Issue by themalu866** [snes9xgit/snes9x#485]
Before some of the levels start there's a image that zoom in but if you try to use rewind or fast forward the image still appears as long as they active. (if you keep pressing them)
![rerer](https://user-images.githubusercontent.com/42208976/51507166-cb264300-1dd6-11e9-9dd2-3c72eab7ecdc.png)
![rtrt](https://user-images.githubusercontent.com/42208976/51507173-ceb9ca00-1dd6-11e9-930f-66c7a5fcd48a.png)
![dsffar](https://user-images.githubusercontent.com/42208976/51507176-d24d5100-1dd6-11e9-9c10-a6fb138b56fd.png)
![hjyh](https://user-images.githubusercontent.com/42208976/51507178-d5484180-1dd6-11e9-989d-57fae9a03d04.png)

**Comment by bearoso** [comment]
I'm not seeing this with the GTK+ or unix ports. It must be something with interlacing persisting in the Windows version.

**Comment by themalu866** [comment]
Yeah, it's the Windows  version I use.

**Comment by bearoso** [comment]
Fixed.
