### ISSUE TITLE
Key Loaded Incorrectly (Page Down)

### ISSUE THREAD

**Issue by NoSuck** [snes9xgit/snes9x#486]
Hello.  I set `Turbo B` to `Page Down` in the settings menu.  After exiting Snes9x, this shows up as the following in `snes9x.conf`:

```
Turbo B  = Keyboard Page Down
```

However, when I start Snes9x again, `Turbo B` shows up as `Keyboard Delete` in the settings menu.  Exiting Snes9x yet again changes the `snes9x.conf` line to the following:

```
Turbo B  = Keyboard Delete
```

Is this a bug?

```
snes9x-gtk 1.58
Linux 4.20.3-arch1-1-ARCH #1 SMP PREEMPT Wed Jan 16 22:38:58 UTC 2019 x86_64 GNU/Linux
```

Thank you.

**Comment by bearoso** [comment]
Fixed in git.
