### ISSUE TITLE
How to use Emscripten with this project?

### ISSUE THREAD

**Issue by MurhafSousli** [snes9xgit/snes9x#487]
Hi can anyone guide me 

I am trying to apply the ecmscripten tutorial https://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html to build and compile this project, but I cannot find figure out where to start from, I cannot find `./configure` nor any CMAKE file

![image](https://user-images.githubusercontent.com/8130692/51803828-5a65a780-226a-11e9-87c7-22a41f3be423.png)

Do I write the cmake file, and where is the main entry file where that I can use to compile all `cpp` files and get the application compiled?

Can anyone guide me on this please?

Many thanks

**Comment by bearoso** [comment]
We don’t support emscripten. You’re on your own.
