### ISSUE TITLE
Secret of Mama

### ISSUE THREAD

**Issue by Cibomatto2002** [snes9xgit/snes9x#488]
I'm not sure is this is a bug but in one frame you can see what look like a bug. Here is a quick save.
[Secret of Mana (USA).zip](https://github.com/snes9xgit/snes9x/files/2801662/Secret.of.Mana.USA.zip)

![capture1-28-2019-12 26 33 am](https://user-images.githubusercontent.com/21169038/51818229-b690f180-2293-11e9-91ec-7613e6b6ffb6.jpg)

**Comment by bearoso** [comment]
Nope. Secret of Mana has lots of little glitches like this.
