### ISSUE TITLE
Slang shaders WIP

### ISSUE THREAD

**Issue by bearoso** [snes9xgit/snes9x#489]
![slang](https://user-images.githubusercontent.com/16159164/51946115-447cf180-23e6-11e9-9d57-eb0aa7f2074b.png)
They're working pretty easily, once you get all the dependencies linked in. There are a couple snafus, though:

1. Figure out how to link glslang in on Windows and whether or not to make it optional. 

It works by running cmake to generate project files and including them in Snes9x's dependencies, but that's messy. I'd like to copy the zlib and png solution and make a unified library that we can pull as a submodule and just link in.

2. The shaders are being recompiling very often unnecessarily on Windows.

I was running a debug build with the crt-royale shader, and it had a ridiculous 12-second compile time, so I noticed it when:
* Closing the dialog box with OK if we've already clicked apply and nothing's changed
* Opening the shader parameters box and every value adjustment

3. I incorrectly assumed the GLSLShader object would always be destroyed and recreated like I do with the GTK+ port, but it's not with Windows, so I need to find where it doesn't clean up, because .glslp shaders stop working after .slangp shaders are used.

**Comment by OV2** [comment]
1. So you want to pregenerate project files and then link in the source via submodules?
I haven't used cmake yet, but I'll try to get glslang compiled.

2. This should be easy to fix for the gfx settings dialog, but the parameter dialog requires it for the auto-preview. I guess I could add a "no preview" checkbox to prevent it.

**Comment by OV2** [comment]
I somehow thought the parameters were defines in the shader... will change it so it doesn't reload if the filename stays the same.

For glslang I think we can use the generated (via cmake) project files as a base and throw out the unnecessary sub-projects. It looks like it generates the project files with absolute paths, but that should be a simple find/replace.

**Comment by OV2** [comment]
I've pushed a new slang-win32 branch that includes stripped down and adjusted project files for the glslang project and references it as a submodule. It no longer reloads the shaders if the filename does not change. Still needs some adjustments for the parameter dialog to work.
File size increases a lot, but I guess nowadays that's not really a problem anymore.

**Comment by OV2** [comment]
The parameter dialog is hardcoded to save to .glslp at the moment, that's why it's not working. Will fix it when I get home.

AFAIK I'm using release correctly, and it went from 6 to 9mb. There's a MinSizeRel config, but I don't think it's worth it.

I have to say, other than having a bit convoluted dependencies, this was a very nice drop-in addition.

**Comment by OV2** [comment]
Now I remember why it was reloading the shader every time: the shader params dialog was operating on its own GLSLShader instance and simply saving it to a file, which was then loaded again on every change.
That's also been changed, it should now work correctly.

**Comment by bearoso** [comment]
Hitting cancel doesn't revert the parameters. Just need to save a copy when opening the dialog and copy back if cancel is hit.  Do we need the apply button, since it auto-applies on changes?

The crt-royale shader is randomly causing the AMD Windows driver to crap garbage on other parts of the screen, but that's clearly their bug.

**Comment by OV2** [comment]
The apply button is needed when you manually enter new values, then it does not automatically trigger.

Does the royale shader have a minimum size? On 1x and 2x it looks broken.

**Comment by bearoso** [comment]
Ok, that explains it.

The royale shader needs 224/240p or 480 lines which it interlaces. It's working fine for me aside from the weird driver bug. It's kind of like a burn test because it's so ridiculous. We had an AMD Linux intermediate representation bug with it not too long ago.

**Comment by bearoso** [comment]
Tested royale again. Works fine. No more garbage after updating AMD drivers, either. 

I fixed the thing with cancel. I also futzed with the dialog box a bit. I aligned the spacing and removed the message at the top. I think it's unnecessary and might confuse some people. I hope you don't mind me butting in on your territory.

**Comment by OV2** [comment]
I just thought it might be confusing when you change parameters and afterward have a different shader selected. But I'm not that attached to the message, it looks fine the way you changed it.

**Comment by bearoso** [comment]
Closing, since it's merged.
