### ISSUE TITLE
[Linux] OpenGL Crash

### ISSUE THREAD

**Issue by 6a3b62** [snes9xgit/snes9x#490]
I'm experiencing the same problem as #313, just on linux, where choosing opengl under hardware acceleration causes the program to crash.

Steps to Reproduce:
1. Run snes9x-gtk
2. Click _Options_ > _Preferences..._ > _Display_
3. Under _Hardware Acceleration_, choose _OpenGL_
4. Click _Apply_ or _OK_

Additional Info:

Snes9x version: 1.58-84-g19f03c4

Error shown in the terminal:
Gdk-ERROR **: The program 'snes9x-gtk' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadFBConfig'.
  (Details: serial 26874 error_code 170 request_code 153 (GLX) minor_code 34)

[backtrace.log](https://pastebin.com/Ss28wAGt)

Extended renderer info (GLX_MESA_query_renderer):
    Version: 18.3.3
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL version string: 2.1 Mesa 18.3.3
OpenGL shading language version string: 1.20

OpenGL ES profile version string: OpenGL ES 2.0 Mesa 18.3.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16

**Comment by bearoso** [comment]
Aside from old hardware, this isn't the same as the other bug. Fixed in git master.
