### ISSUE TITLE
[Linux] Modifier Keys Loading Incorrectly

### ISSUE THREAD

**Issue by 6a3b62** [snes9xgit/snes9x#492]
With _Use modifier keys (CTRL, SHIFT, ALT) directly_ checked, any key set to just _shift_ or _alt_ will load incorrectly after a program restart. Same issue as observed in #486 but with modifier keys.

Steps to Reproduce:

1. Set any key to _Shift_ or _Alt_
2. Restart snes9x
3. Key is now set to _Shift + Unknown_ or _Alt + Unknown_

Additional Info:

_Ctrl_ works as intended from my testing.

Snes9x version: 1.58-85-gdd4614d

**Comment by bearoso** [comment]
Fixed in f65b876.
