### ISSUE TITLE
Regression in snes9x 1.57 & 1.58 - Cx4 Chip Error

### ISSUE THREAD

**Issue by Zenjir0** [snes9xgit/snes9x#494]
When you run the Cx4 Test Program found in certain SNES Games such as Mega Man X2 or X3 you will see that the test fails/errors out on the MALU test. 

The test also fails in snes9x 1.58

The same test passes fully without errors in snes9x 1.56.2

Edit: I only tested on the Windows version of snes9x.

**Comment by bearoso** [comment]
The only C4 change was a MSVC build fix, so it’s probably that. Could be compiler-specific.

**Comment by bearoso** [comment]
That was it. I'm not sure why they needed that. Reverted.
