### ISSUE TITLE
On Linux compile is still bad.

### ISSUE THREAD

**Issue by Csokis** [snes9xgit/snes9x#496]
Ubuntu 18.04.1 LTS :(

> g++  -I. -I.. -I../apu/ -I../apu/bapu -I../jma/ -I../filter/ -o snes9x ../apu/apu.o ../apu/bapu/dsp/sdsp.o ../apu/bapu/smp/smp.o ../apu/bapu/smp/smp_state.o ../bsx.o ../c4.o ../c4emu.o ../cheats.o ../cheats2.o ../clip.o ../conffile.o ../controls.o ../cpu.o ../cpuexec.o ../cpuops.o ../crosshairs.o ../dma.o ../dsp.o ../dsp1.o ../dsp2.o ../dsp3.o ../dsp4.o ../fxinst.o ../fxemu.o ../gfx.o ../globals.o ../logger.o ../memmap.o ../msu1.o ../movie.o ../obc1.o ../ppu.o ../stream.o ../sa1.o ../sa1cpu.o ../screenshot.o ../sdd1.o ../sdd1emu.o ../seta.o ../seta010.o ../seta011.o ../seta018.o ../snapshot.o ../snes9x.o ../spc7110.o ../srtc.o ../tile.o ../filter/2xsai.o ../filter/blit.o ../filter/epx.o ../filter/hq2x.o ../filter/snes_ntsc.o ../statemanager.o ../sha256.o ../bml.o unix.o x11.o ../jma/7zlzma.o ../jma/crc32.o ../jma/iiostrm.o ../jma/inbyte.o ../jma/jma.o ../jma/lzma.o ../jma/lzmadec.o ../jma/s9x-jma.o ../jma/winout.o -lm -lz -lpng -lSM -lICE -lX11 -lXext -lXv -lXinerama -lpthread
../apu/apu.o: In function `S9xInitSound(int, int)':
/mnt/minden/Sources/snes9x/unix/../apu/apu.cpp:215: undefined reference to `SNES::SPC_DSP::set_output(Resampler*)'
collect2: error: ld returned 1 exit status
Makefile:55: recipe for target 'snes9x' failed
make: *** [snes9x] Error 1

**Comment by OV2** [comment]
I had no further problems compiling yesterday. Did you try a clean?

**Comment by Csokis** [comment]
Not so far. It's good now. Thank You.

**Comment by bearoso** [comment]
Is there a particular reason you use the minimalist version?

**Comment by themalu866** [comment]
And for some reason the Windows version is crashing a lot.

**Comment by OV2** [comment]
Can you be a bit more specific? Crashing during regular play? When changing sound options?

**Comment by themalu866** [comment]
Oh, sorry. It happens randomly while playing normally but I noticed that it tends to happens more frequently while holding Fast Forward.

**Comment by OV2** [comment]
I think I've found the issue, try c90de1077b20a66d6eff5133a185084e54f7a2e3.

**Comment by bearoso** [comment]
Closing, since this seems fixed.
