### ISSUE TITLE
Bottom image area is not cleared on 239 to 224 line mode change

### ISSUE THREAD

**Issue by M-a-r-k** [snes9xgit/snes9x#50]
This applies to the GTK port of Snes9x when the use overscanned height option is enabled.

I noticed a small problem when changing from 239-line to 224-line mode. The bottom lines (corresponding to the 225th to 239th lines) are not cleared; the old image remains. Even if you reset the emulated console, the old image data is still there.

This arose from a post on the nesdev forum: http://forums.nesdev.com/viewtopic.php?t=11138

User ARM9 created a small test ROM:
https://dl.dropboxusercontent.com/u/13494639/overscan.sfc

Run that. When you press and hold B the output is in 239-line mode. Release B and the output reverts to 224-line mode. But the bottom part of the image is not cleared to black.

**Comment by bearoso** [comment]
Took 4 years, but this bug is fixed.
