### ISSUE TITLE
Regression in snes9x 1.59 - Blargg Tests Failing

### ISSUE THREAD

**Issue by Zenjir0** [snes9xgit/snes9x#506]
For the Windows version of snes9x 1.59 it fails the following tests from Blargg's Test Suite 2010-03-14
	
exec_io_tests\1-test_exec_from_io
exec_io_tests\2-test_single_instr
exec_io_tests\4-test_ram_disable
test_ram_disable_ipl
test_speed

All of these passed in 1.58.

Suite can be found here if anyone needs it: https://snescentral.com/article.php?id=1115

**Comment by bearoso** [comment]
Thanks. I know what's going on.

**Comment by bearoso** [comment]
Fixed in git. I'll do an updated 1.59.1 release.
