### ISSUE TITLE
v1.59.1 crashing on Direct3D mode

### ISSUE THREAD

**Issue by MelchiorGaspar** [snes9xgit/snes9x#507]
I just grabbed v1.59.1 and noticed SNES9x will crash when video output is set to Direct3D..
audio is set to XAudio2

I am running Windows 7 ULTIMATE x64 and SNES9x x64
system specs via CPUz Report.. [https://valid.x86.fr/qv6an5](url)

any questions from the devs?

**Comment by bearoso** [comment]
Nothing has changed since 1.58 regarding Direct3D. Can you explain what happens when it crashes? Is it displaying an error box or just closing? What is the series of steps you do to make it crash?

**Comment by MelchiorGaspar** [comment]
I just try to load a game and boom it crashes to windows desktop with a Windows error reporting popup..
it will also crash when I try to load a game after switching to OpenGL.. but only if I don't exit saving settings and reload the program first

> Problem Event Name:	APPCRASH
>   Application Name:	Snes9x-x64.exe
>   Application Version:	1.5.5.0
>   Application Timestamp:	5c773822
>   Fault Module Name:	Snes9x-x64.exe
>   Fault Module Version:	1.5.5.0
>   Fault Module Timestamp:	5c773822
>   Exception Code:	c0000005
>   Exception Offset:	000000000001941c

**Comment by bearoso** [comment]
Can you post your snes9x.conf. It may be something your settings are producing.

**Comment by MelchiorGaspar** [comment]
ok
[snes9x.conf.zip](https://github.com/snes9xgit/snes9x/files/2913115/snes9x.conf.zip)

**Comment by bearoso** [comment]
Thanks. Got it now. You've caused me to release two bugfix versions.

**Comment by MelchiorGaspar** [comment]
lol

**Comment by MelchiorGaspar** [comment]
so how long does it take to compile and upload the new Windows binaries?

**Comment by bearoso** [comment]
If this doesn't fix your crash, then it has a different cause, but I'm through for the day. @OV2 is going to be laughing at me when he wakes up.

**Comment by MelchiorGaspar** [comment]
lol.. 
yes it does seem to have fixed the bug so I will close this...
