### ISSUE TITLE
input config issue.. 

### ISSUE THREAD

**Issue by MelchiorGaspar** [snes9xgit/snes9x#508]
I am having and issue when I hit the 'R1' on my PS1 controller via a old but functional radio-shack PSX to USB adapter.. it pauses and makes the mouse cursor visible... but also performs the ingame action of changing the weapon in Final Fantasy Mystic Quest.. which is what I am currently playing..

any idea?  when I went to check the mapping its correct... BUT when I go to test remaping the [L] key  to the L1 key on my PS1 controller to I get [LCONTROL] for some odd reason...

also IF I remap and do [Select] on my controller to [Select] on the input config screen I get [Tab] key..

as an additional note.. the next key mapping in order will fill with the button that was pressed from the previous slot automaticly...

its all so strange because.. its possible a hardware issue.. not sure...

**Comment by MelchiorGaspar** [comment]
I am running Windows 7 ULTIMATE x64 and SNES9x v1.59.1 but its been happening on v1.58.0 too...
so IDK whats causing it for sure..

**Comment by MelchiorGaspar** [comment]
I tested with my PS2 controller too.. and its still happening and that one is brand new off of eBay...

**Comment by MelchiorGaspar** [comment]
I tested in ZSNES input config too... if I use the select button on my controller it tabs to the next controller input screen

**Comment by bearoso** [comment]
If you have steam, it can do something like redirect joystick buttons to keys. There's an option in there somewhere to turn if off.

**Comment by MelchiorGaspar** [comment]
as it happens I do have Steam and it is running in the back ground... let me exit Steam and see if that helps...

**Comment by MelchiorGaspar** [comment]
WOW that fixed the issue THX!
its under desktop config under controller settings...
