### ISSUE TITLE
Libretro API spec violation - SET_GEOMETRY can only be called from retro_run

### ISSUE THREAD

**Issue by twinaphex** [snes9xgit/snes9x#509]
The documentation for SET_GEOMETRY describes that SET_GEOMETRY can only be called from retro_run:

https://github.com/libretro/RetroArch/blob/master/libretro-common/include/libretro.h

* This can only be called from within retro_run().

Right now, the update_geometry check is being called by the update_variables function, which in turn is called by both retro_load_game and retro_run.

What needs to happen is that you need to take this conditional out of update_variables and check it inside retro_run instead. You can only call this environment callback from within retro_run, the reason for this is that some of the drivers on the frontend side are not guaranteed to have been initialized/setup yet at the retro_load_game stage.

Hopefully we can see a fix for this soon since it was already starting to confuse people into thinking that something on the frontend was broken, when it isn't.

**Comment by OV2** [comment]
I've removed all update_geometry calls outside of retro_run and added a comment to make sure this will not be called anywhere else.

**Comment by bearoso** [comment]
I'm curious. This code was two years old. What drivers was it breaking?

**Comment by twinaphex** [comment]
@orbea can you tell you more about that I believe.

**Comment by orbea** [comment]
@bearoso It was breaking the SDL2 video driver in RetroArch when running content from the menu. There is now a workaround to avoid crashes in the the video driver which most if not all other drivers already have. Regardless it seems like it should be fixed in the cores.

At least one other core that has this problem is nestopia, it might take some doing to find all of the offenders.

**Comment by bearoso** [comment]
Ok, thanks for the info. I was worried we’d have to do another emergency bug fix release, but it seems like it’s not too urgent.
