### ISSUE TITLE
The pad of the Xbox controller does not work with semicircle and circle movements. 

### ISSUE THREAD

**Issue by Dk64** [snes9xgit/snes9x#514]
When I play Street Fighter with the pad of the Xbox controller, it's impossible to make a special move by making a semicircle. Yet I configured the pad correctly with the diagonals. Nevertheless, with the analog stick, it works properly.

**Comment by bearoso** [comment]
Does the pad actually require having special diagonal assignments? If you leave those blank and press a diagonal in some game does it work or does it just stop? 

The SNES doesn't use diagonal input, but XInput "unpresses" the axis directions when you press eg. right+down and reports a special diagonal button, so we have to provide that option.

**Comment by Dk64** [comment]
> Does the pad actually require having special diagonal assignments?

Yes. When I play street fighter the diagonals work properly with the pad, I can move forward and jump at the same time, but can't make circles (quarter circle, half circle, and whole circle) to make a special move (example Fireball "Ha-Do-Ken" from ryu).

> If you leave those blank and press a diagonal in some game does it work or does it just stop?
The diagonals no longer work with the pad.

I don't have these problems with the analog stick ...

**Comment by Dk64** [comment]
I'm sorry ! 

I accidentally uninstalled the driver of the Xbox controller ... 
Everything is working properly now .... 
This message can be closed !
