### ISSUE TITLE
A doubt

### ISSUE THREAD

**Issue by lordpeluca** [snes9xgit/snes9x#515]
Is there any way to test the fixes before the official version of the emulator is released?, e.g:

-MSU-1 audio crackling in many games
-Remove most of GFX_MULTI_FORMAT.

etc

I remember downloading those updates non-official from ECR but it hasn't updated for days.

The axelay fix interests me because it's my favorite game and I'd love to play it fixed.

**Comment by bearoso** [comment]
Yes. If you click on Code, then Commits, you'll see a list of changes. There's a little green check mark next to some changes that you can click that will take you to the appveyor page. Click the entry for the build matching your computer, then the "artifacts" link. This will give you a download for whatever the change was.

**Comment by bearoso** [comment]
![1](https://user-images.githubusercontent.com/16159164/54323389-200c5b80-45c7-11e9-9c39-2fff3859a983.png)
![2](https://user-images.githubusercontent.com/16159164/54323391-226eb580-45c7-11e9-94e0-0e82456c46a8.png)
![3](https://user-images.githubusercontent.com/16159164/54323394-24387900-45c7-11e9-9cce-f2f724cfd4c4.png)
![4](https://user-images.githubusercontent.com/16159164/54323396-26023c80-45c7-11e9-8280-1a3ca4e38322.png)
![5](https://user-images.githubusercontent.com/16159164/54323398-27336980-45c7-11e9-8b9f-d23dbef4309f.png)

**Comment by lordpeluca** [comment]
Everything very well explained, even with images and marks on them so that one cannot get lost :)

Thank you very much, bearoso. I'll bookmark this!

**Comment by bearoso** [comment]
Made an entry in the wiki page in a FAQ section on how to do this.
