### ISSUE TITLE
Missing words in FF2 (Fan Translation Fr.)

### ISSUE THREAD

**Issue by Dk64** [snes9xgit/snes9x#516]
Hello,

In the game Final Fantasy 2, many texts don't display correctly, some words are missing. Some text windows are also completely empty.

I tried to turn off the transparency, then put the game in PAL or NTSC, but the problem persists.

There's not this problem with another emulator.

With snes9x
![Image3](https://user-images.githubusercontent.com/48523001/54365059-6bc61000-466e-11e9-95be-83df2c98818e.jpg)

With Zsnes
![Image4](https://user-images.githubusercontent.com/48523001/54365108-85ffee00-466e-11e9-866a-37f3b9a1e6ea.jpg)

**Comment by OV2** [comment]
It's  a broken translation that relies on invalid vram access. You can get it to work by setting
`BlockInvalidVRAMAccess    = FALSE`
in snes9x.conf, but it will break some other games.

**Comment by Dk64** [comment]
Thank you. It works properly now.

Can this problem be fixed in the next version of snes9x?

**Comment by OV2** [comment]
This is not a problem of snes9x, it is a problem of the translation.

**Comment by Dk64** [comment]
Sorry but I'm not a programmer and I do not always understand everything .... ^^

But it works with other emulators with the default settings. Why not snes9x ?

**Comment by bearoso** [comment]
No, it works with ZSNES with default settings. The translation was made to work with ZSNES. If you try the translation on an actual SNES it'll cut the text off just like in Snes9x.

**Comment by Dk64** [comment]
I see! Thanks for your quick answers, you are great !
