### ISSUE TITLE
Mighty Morphin Power Rangers - The Movie bug

### ISSUE THREAD

**Issue by Sun-in-jang** [snes9xgit/snes9x#519]
Impossible to complete due to the bug, i don't know if this is related to windows 10, or it is emulator / in-game bug

https://youtu.be/_mpJ8kFFzMM

![Mighty Morphin Power Rangers - The Movie](https://user-images.githubusercontent.com/38378342/55251488-674a4b80-5259-11e9-9e9e-6f761f99bde5.PNG)

**Comment by bearoso** [comment]
Need more info than that.

**Comment by Sun-in-jang** [comment]
After battle with Magnet Brain game has stuck, impossible to scroll screen

**Comment by bearoso** [comment]
That’s awfully ambiguous. We don’t know what Snes9x version or anything and I’m totally unfamiliar with the game. A save state near the lockup would be more helpful. I definitely don’t want to play through an hour (probably more because I don’t know the game) and find out we fixed it long ago.

**Comment by Sun-in-jang** [comment]
I can make a save to this moment

**Comment by Sun-in-jang** [comment]
I maked 2 savestates, one is when boss have very low hp (2 hits to die) and another one when boss beated, hope this is will be helpful
[Mighty Morphin Power Rangers - The Movie (Saves).zip](https://github.com/snes9xgit/snes9x/files/3024607/Mighty.Morphin.Power.Rangers.-.The.Movie.Saves.zip)

**Comment by bearoso** [comment]
Thanks for providing the save states. This isn't locking up for me on 1.59.2 or the git version.

**Comment by lordpeluca** [comment]
I tried it out of curiosity and it works normally in version 1.59.2. Although I must say that I only use XP.
https://i.postimg.cc/VkDtcbVv/F1.jpg
https://i.postimg.cc/TwZ7qsVz/F2.jpg

**Comment by lordpeluca** [comment]
I tried it out of curiosity and it works normally in version 1.59.2. Although I must say that I only use XP:

[img]https://i.postimg.cc/VkDtcbVv/F1.jpg[/img]
[img]https://i.postimg.cc/TwZ7qsVz/F2.jpg[/img]

Greetings

**Comment by lordpeluca** [comment]
I tried it out of curiosity and it works normally in version 1.59.2. Although I must say that I only use XP:

https://i.postimg.cc/VkDtcbVv/F1.jpg
https://i.postimg.cc/TwZ7qsVz/F2.jpg

Greetings

**Comment by stellarporter** [comment]
Maybe someone is compiling with gcc or libretro uwp?

**Comment by bearoso** [comment]
Don't think the compiler is the problem. I just think it was an old Snes9x version.
