### ISSUE TITLE
Android libretro core won't build anymore

### ISSUE THREAD

**Issue by trinemark** [snes9xgit/snes9x#520]
Hi. This used to work a month or two ago on Android NDK r17. But now it prints out this error:
```
[arm64-v8a] Compile++      : retro <= apu.cpp
C:/projects/snes9x/libretro/jni/../../apu/apu.cpp:90:72: error: no member named 'data' in 'std::vector<short, std::allocator<short> >'
                    msu::resampler->read((short *)msu::resample_buffer.data(),
                                                  ~~~~~~~~~~~~~~~~~~~~ ^
1 error generated.
```
C++11 STL.

Had to change this line here:
https://github.com/snes9xgit/snes9x/blob/master/libretro/jni/Application.mk#L1
```APP_STL := c++_static```

gnustl_static also works but it's deprecated beyond r17. Latest NDK is at r19c and r20 is around the corner I think.

**Comment by bearoso** [comment]
That's a little bit of C++11 that shouldn't have worked into the core. I'll change it to a regular array.

**Comment by OV2** [comment]
Doesn't vector guarantee that the data is continuous, so you can just use the address of the first element?

**Comment by bearoso** [comment]
Can you? Oh well. Changed already. :-)

**Comment by bearoso** [comment]
> Doesn't vector guarantee that the data is continuous, so you can just use the address of the first element?

Isn't the [] just an overload? If what it returns is plain old data, aren't you just getting the address of the rvalue? Or is it somehow a reference? I'll read into it.

**Comment by bearoso** [comment]
Ok, it is a reference. :-)

**Comment by trinemark** [comment]
Awesome. Without the blargg commit, Android builds again.

I've fixed the blargg commit to fully compile on droid.
https://github.com/snes9xgit/snes9x/issues/521

Then I think we can shut this down too. Another Snes9x success story.
