### ISSUE TITLE
Request: libretro blargg filters

### ISSUE THREAD

**Issue by trinemark** [snes9xgit/snes9x#521]
Hi, guess this was already asked in a fork and solved.
https://github.com/libretro/snes9x/issues/186

Since I use mainstream repo, asking for its inclusion here too. Because some devices can't support libretro shaders (NTSC, border cropping, image-adjustment) and we have to rely on the core to handle it in software. I think blargg filters would be a positive benefit since they're widely accepted and known.

Thanks for reading.

**Comment by bearoso** [comment]
Ok. Merged it.

**Comment by trinemark** [comment]
Great! Thank you for adding this. Windows and Linux works. But Android won't compile. Please add this edit:
https://github.com/snes9xgit/snes9x/blob/droid/libretro/jni/Android.mk#L16
```
LOCAL_SRC_FILES := $(SOURCES_C) $(SOURCES_CXX)
```

Then I get 4 android libs built.

**Comment by bearoso** [comment]
Done.
