### ISSUE TITLE
Release 1.60

### ISSUE THREAD

**Issue by bearoso** [snes9xgit/snes9x#522]
Getting ready for release 1.60. @OV2, @qwertymodo, any outstanding issues or regressions we need to address?

**Comment by Dwedit** [comment]
I'd double check the green bit calculation in the code for adding and subtracting colors.

**Comment by bearoso** [comment]
Good idea. I’ll do some unit tests to make sure it’s correct.

**Comment by OV2** [comment]
Nothing major on my end. I haven't really had much time to look at things lately, maybe I can find some time to check out the directdraw paths on some older systems this week.

**Comment by bearoso** [comment]
> I'd double check the green bit calculation in the code for adding and subtracting colors.

Yeah, you were right. I expanded the mask for the green, but didn't add the extra bit. It's easier and faster to just fix it at the very end. Tested and things match up now for sure.

**Comment by bearoso** [comment]
Of course, it wouldn't have been noticed. The white point would be off for math, but no one noticed that we didn't do the extra bit at all in previous versions, causing a slight pink shift. :-)

**Comment by themalu866** [comment]
After all this years and nobody seems to get the timing from Yoshi's Island credits right.
[Yoshi's Island.zip](https://github.com/snes9xgit/snes9x/files/3038534/Yoshi.s.Island.zip)

And I noticed that the Snes9x icon on Windows 7 looks kinda weird in some sizes.
I put it next to Bsnes for comparison and most of them look okay, except the medium size.
![sizes](https://user-images.githubusercontent.com/42208976/55479622-e2fb1e00-55f4-11e9-83be-363b78bc57f1.png)
Especially the medium size.
![sizepro](https://user-images.githubusercontent.com/42208976/55480137-f8247c80-55f5-11e9-980e-0b8e4e4956b3.png)

**Comment by LodanZark** [comment]
@themalu866 
something like this?





![logo](https://user-images.githubusercontent.com/11250310/55484339-3f276780-5620-11e9-97cb-b8ac51a7d314.png)
[flat icon and svg.zip](https://github.com/snes9xgit/snes9x/files/3038987/flat.icon.and.svg.zip)

**Comment by LodanZark** [comment]
@themalu866 
Also fixed the current icons by adding extra resolutions and smooth edges in lower res, just in case
[current_icons_fix.zip](https://github.com/snes9xgit/snes9x/files/3039600/current_icons_fix.zip)

**Comment by themalu866** [comment]
The biggest one got more blurred but medium size is a great improvement.
![dfdf](https://user-images.githubusercontent.com/42208976/55498535-3f246900-561a-11e9-88ae-abc67e36307b.png)
![frt](https://user-images.githubusercontent.com/42208976/55498542-45b2e080-561a-11e9-9440-9ec3c0877dcb.png)

**Comment by bearoso** [comment]
> After all this years and nobody seems to get the timing from Yoshi's Island credits right.

I'm aware of that. The SuperFX timing is annoyingly complex, and Snes9x's version is simple. I just bumped the speed of the SFX2 by 25%. We'll see if that's enough. I don't think the other SFX2 game will care.

@LodanZark 
I added your fixed icons. For the middle size it's probably using 48x48, which I didn't make. 
@themalu866 
I'll just remake the .ico file with a 48x48 size.

**Comment by themalu866** [comment]
I had to put SuperFX speed by 131% to get the first part right (13:12) that is to make the two songs to play simultaneously but the second part (13:43) is still too slow so I had to change to 171% for the goal music synch when the babies appear.
https://www.youtube.com/watch?v=uEG0E6Vqu1s

The small ones are better too.
![erer](https://user-images.githubusercontent.com/42208976/55499361-30d74c80-561c-11e9-8808-57d827e5caf0.png)

**Comment by bearoso** [comment]
I changed it to 1/3 faster instead of 1/4, but we're not going to get much better. Even higan gets this completely wrong, so I don't expect the lazily timed Snes9x core to do any better.

**Comment by bearoso** [comment]
I did a new svg and fixed the proportions of the flat icon and did a slightly glossy one, too. Now there's 4 icons included in the win32 exe.

**Comment by themalu866** [comment]
The small one still weird but the medium is great.
![hggh](https://user-images.githubusercontent.com/42208976/55674969-eeb74080-5891-11e9-9180-4b166d25b365.png)
Oh, and the first music in the credits cut just a little bit.
Sad that SuperFX speed can't be changed in which game individually.
But changing the speed will negatively affect other games?

**Comment by bearoso** [comment]
When you get that small you have to hand-tune it or it'll never look good. 

The problem with the SuperFX isn't on a game-level, it's on a sub-game level. Some instructions are running too quickly, while some are too slow. We can't make one part of the game 131% and another 171% speed. We'd have to identify what part of the SFX chip each segment is using and fix the speed. If we do that, we might as well do brand new SuperFX code entirely.

**Comment by themalu866** [comment]
Maybe someday the chip will be emulated properly.
Question: Super Punch Out not unlocking the Special Circuit is a old glitch that can't be currently fixed?
![yuyu](https://user-images.githubusercontent.com/42208976/55993897-a5e2fb80-5c86-11e9-8945-b2224bee5af8.png)
I noticed that there's even a cheat in the database.
![ddfd](https://user-images.githubusercontent.com/42208976/55993995-ed698780-5c86-11e9-9b78-e687a07a65c2.png)
Aaaand An American Tail - Fievel Goes West it's not loading now.

**Comment by bearoso** [comment]
> Aaaand An American Tail - Fievel Goes West it's not loading now.

That was the APU clock speed change. We'll have to go back to 32040.

> Question: Super Punch Out not unlocking the Special Circuit is a old glitch that can't be currently fixed?

No, it states that using game genie cheats is responsible for this.

**Comment by bearoso** [comment]
I reverted the clock speed change. That fixes An American Tail.

I'll give this a couple days to stew and if nothing pops up I'll tag the release.

**Comment by OV2** [comment]
I did some testing on a few different systems with ddraw, also haven't had any issues so far. I'm guessing on all the systems we support now we'll never run into any of the old color modes.

**Comment by bearoso** [comment]
No complaints for a while, so I released it.

**Comment by tmkk** [comment]
Mac build: [snes9x-1.60-macosx-i386.zip](https://github.com/snes9xgit/snes9x/files/3114918/snes9x-1.60-macosx-i386.zip)

**Comment by OV2** [comment]
Thanks a lot, I've updated the release post.

**Comment by azoreseuropa** [comment]
> After all this years and nobody seems to get the timing from Yoshi's Island credits right.
> [Yoshi's Island.zip](https://github.com/snes9xgit/snes9x/files/3038534/Yoshi.s.Island.zip)
> 
> And I noticed that the Snes9x icon on Windows 7 looks kinda weird in some sizes.
> I put it next to Bsnes for comparison and most of them look okay, except the medium size.
> Especially the medium size.
> ![sizepro](https://user-images.githubusercontent.com/42208976/55480137-f8247c80-55f5-11e9-980e-0b8e4e4956b3.png)
> If in the future you guys decide to change the icon but keep the idea of "Super Famicom logo but with north american button colors" I suggest making the lavender circles to look like concave buttons.

I prefer Europe/Japan color icons instead of North America ugly purple console and ugly icon.

**Comment by qwertymodo** [comment]
Re: SuperFX timings,  I just finished building a full set of socketed SuperFX carts, one for each chip revision, so if anybody ever writes up a timing test ROM, I can run it against all known chip revisions.  I know krom wrote up a fairly large test suite, but IIRC it was a ton of single-test ROMs, which is kind of annoying to have to burn a new ROM for every test, but I may give them a go one of these days.

**Comment by bearoso** [comment]
You should ask byuu. I think some aspects of the pipelining are missing, but it's hard to measure pipelining because of the myriad of combinations it entails. We probably need actual chip design specs to get speed exactly right.

**Comment by bearoso** [comment]
And needless to say, the Snes9x code is missing a lot more than that.

**Comment by qwertymodo** [comment]
At the very least, if we can get some decent "black box" external timing tests written, we could also compare the original chips against RedGuy's HDL implementation on the SD2SNES, and that could give us insight into the internal timings as well.
