### ISSUE TITLE
MSU-1 sound issue

### ISSUE THREAD

**Issue by GhostBelmont** [snes9xgit/snes9x#528]
When i try to load a save state playing a MSU-1 game, the sounds resets e sometimes the game lost the sound too. Is there any configuration to be done in the emulator? Case no, there is some patch to fix this? Thank you.

**Comment by bearoso** [comment]
No, I’m not aware of any existing problems like this. Please give us the version of Snes9x you’re using and the games that are problematic. Also note that save states aren’t strictly compatible between versions, so if you’re loading old save states on a newer version it might not work right.

**Comment by GhostBelmont** [comment]
Thank you for answer me bearoso, i'm using the snes 9x 1.59.2, i've tested Donkey Kong Country 1 MSU-1 Version, Donkey Kong Country 2 MSU-1 and Megaman 7 MSU-1. All of them resets the sound when i load a save state, sometimes they just lost the sound and i have to load the rom again. I've downloaded it in the snes9x website. The save states files are from this version too.

**Comment by bearoso** [comment]
Ok, I’ll look into it. Since you can produce it so reliably it should be easy to track down.

**Comment by GhostBelmont** [comment]
Ok, thanks for the help!

**Comment by bearoso** [comment]
I've reproduced the issue with Donkey Kong Country. Don't know what's wrong yet.

**Comment by bearoso** [comment]
@qwertymodo Any idea what's going wrong. I thought I had the fix, but that's not right either.

**Comment by bearoso** [comment]
Scratch that. I had a thinko. Fixed.

**Comment by GhostBelmont** [comment]
Bearoso, thank you very much for fixing the problem, just one doubt, where i can downloaded the fixed version?

**Comment by bearoso** [comment]
We’ll release 1.60 soon, but in the meantime, see:
https://github.com/snes9xgit/snes9x/wiki/How-do-I-download-a-prerelease-build%3F

**Comment by GhostBelmont** [comment]
Oh all right, I'll see this link. Thanks Again! Have a nice day.
