### ISSUE TITLE
Snes9x v1.60 for UNIX running too fast

### ISSUE THREAD

**Issue by musuruan** [snes9xgit/snes9x#530]
snes9x for UNIX v1.60 is running at maximum speed and it seems it is not possible to slow it down. Toggling turbo mode has no effect. snes9x-gtk is fine though.

Please note that snes9x for UNIX v1.59.2 is running at correct speed.

I'm using Fedora 29/x86_64 and I run snes9x through padsp.

**Comment by bearoso** [comment]
Thanks. I reproduced it with padsp. Don't know what's going on, but I'll look into it.

**Comment by bearoso** [comment]
Ok, PulseAudio is being too smart for its own good. With padsp, it always reports at least a fragment open for some reason, presumably rate control, so sound sync doesn't work for throttling. Sound sync defaults to true for the unix version even though the command line is supposed to *enable* it. I changed it to default to false in git. If you want to fix this with your current version, you can create a `~/.snes9x/snes9x.conf` file and write in it:
```
[Sound]
Sync = false
```
