### ISSUE TITLE
Double Click on Taskbar to Minimize Doesn't Pause Emulation

### ISSUE THREAD

**Issue by Nicholas-Steel** [snes9xgit/snes9x#534]
Windows 10 x64 v1903
Intel i7 920 CPU
Geforce 1070Ti
Integrated Audio

**Bug:**
Open Snes9x
Open a game
Configure Snes9x to Pause While Inactive
Double Click the open instance of Snes9x on the Taskbar to minimize it
Emulation continues to occur and audio can clearly be heard from the program.

**Comment by bearoso** [comment]
Fixed in git.
