### ISSUE TITLE
SNES 1.60 sound cracking

### ISSUE THREAD

**Issue by ADRIANOLAST** [snes9xgit/snes9x#541]
I can not find a solution to this. Always when able Vsync the audio is distorted. After many attempts, the current settings are defaults.

with vsync enabled it is ok.

I use a notebook with monitor 60hz.

help me please.

**Comment by ADRIANOLAST** [comment]
My config.

http://ge.tt/2EJ2yAw2

**Comment by ADRIANOLAST** [comment]
Guys, solved. The problem is my computer. I changed some external settings on the video card and power management and solved it.

**Comment by themalu866** [comment]
Star Fox is had cracking for me if I turn rewind ON. Windows 7 x64

**Comment by ADRIANOLAST** [comment]
I gave up the emulator. You have to play normally, and sometimes the game gets bad audio, I do not understand.

**Comment by jjfmz42015** [comment]
this could be an issue of weak hardware or bad drivers.


did you guys as least try changing the audio out modes?

The little bit I tried this no crackling on my end. However Im also running it on a machine that is fast and has proper drivers.
