### ISSUE TITLE
Application Package Not Signed

### ISSUE THREAD

**Issue by szippy** [snes9xgit/snes9x#544]
Hi Guys, 

I just downloaded snes9x from here:  http://www.snes9x.com/downloads.php and found that itisn't signed for OSX! I know apple has a path to getting a codesign certificate for free for nonprofits that I linked below, is there anything I can do to help get your binary signed?

https://developer.apple.com/support/membership-fee-waiver/

![image](https://user-images.githubusercontent.com/41277066/59208745-f41d5980-8b66-11e9-8cb3-b83d9f5c3f35.png)

**Comment by bearoso** [comment]
As mentioned in issue #527, the Mac port is not in a great state at the moment. Apple would undoubtedly deny said certificate for what we're publishing.

**Comment by MichaelBuckley** [comment]
I've been personally signing the builds in #586, so I'm closing this issue.

Thankfully, at least for now, Developer ID signing certificates on macOS aren't tied to App Store rules. Apple has only revoked Developer ID certificates for malware (or software accidentally flagged as malware). This is different than the certificate they just revoked for Fortnite. A few other emulators have been signing builds without issue, and at WWDC, an Apple engineer stated that the certificates and notarization are about security, not rules, and Apple will always support users running whatever code they want on their Macs.

That said, I doubt they'd provide a free certificate for Snes9x through their membership fee waver program. If I'm not mistaken, that program is only for apps that go on the App Store, which Snes9x is not, and you have to be a registered Nonprofit in an eligible country, which we also are not. Although emulators can be signed, they have to fork over $99/year for the certificate, or be signed by one of the developers. Large emulators like OpenEmu and Dolphin are signed, but it's unfortunately not unusual for smaller emulators to be unsigned.
