### ISSUE TITLE
Trials of Mana text distorts resolution

### ISSUE THREAD

**Issue by John-Enigma** [snes9xgit/snes9x#545]
Recently, the Trials of Mana ROM has been extracted from the Collection of Mana Switch game, and now the ROM has been dumped, and leaked on the Internet. 

I've been testing the ROM, and I can't really tell if this is normal or not, but every time the dialogue appears, or there's a lot of text (using the tiny font of course), the resolution itself distorts, and I don't even use Bilinear Filtering to play on snes9x. 

Here's an example: 
![tomtextresfade](https://user-images.githubusercontent.com/22717497/59478562-ab47f800-8e27-11e9-9c32-99c351937b49.PNG)

Then it pretty much comes back to normal:
![tomtextresnormal](https://user-images.githubusercontent.com/22717497/59478575-c155b880-8e27-11e9-9bff-827ca57c967f.PNG)

I'm using snes9x-64 v1.57.

**Comment by bearoso** [comment]
Not a bug. The game uses a higher resolution when it displays text. There is an option to force it to be 512 pixels wide all the time. I’ll have to check where that is in the Windows port, though.

**Comment by bearoso** [comment]
It also looks like you have that “blend hires pixels” option on, which will make it blurry.

**Comment by bearoso** [comment]
I guess the windows version doesn't have the force 512-mode option. But since you're not using bilinear filtering, just turn off the "Blend Hi-Res Images" option in Video->Display Configuration, and everything should be nice and crisp.

**Comment by bearoso** [comment]
And instead of 1.57, use the latest version from here: https://github.com/snes9xgit/snes9x/releases

**Comment by John-Enigma** [comment]
Ah. 

Okay. 

I didn't know this option existed. Thanks. Will try to uncheck it next time.

**Comment by OV2** [comment]
In the win version you can force 512 by using the simple2x filter.
