### ISSUE TITLE
Minor: Turbo volume setting not applied when (turbo) rewinding.

### ISSUE THREAD

**Issue by BrendonIrwan** [snes9xgit/snes9x#546]
This is a minor inconsistency that you guys might want to tweak up.

Basically, it'd be nice to lower the audio if it doesn't play at 1x speed. I have mine to rewind every 4 frames, which essentially means turbo rewind. It is when I'd like to have the volume setting applied.

Thanks!

**Comment by bearoso** [comment]
Fixed for next version.
