### ISSUE TITLE
incompatibility for YOSHI'S ISLAND in 1.5+ series

### ISSUE THREAD

**Issue by mckaygerhard** [snes9xgit/snes9x#56]
i have  a yewel, a YOSHI'S ISLAND rom image  (I have heard that few have it)

snes9x 1.5+ dont support it!!! **this its due removed deprecated SuperFX emulation in 1.43 release??**

hey? there's many roms (of course Japanesse) that use it the SuperFX chip!!

```
Reading config file /etc/snes9x/snes9x.conf.
Sound buffer size: 8192 (2048 samples)
fragment size: 472
Port 1: Pad #1. Port 2: Pad #2. 
No ROM file header found.
Map_SuperFXLoROMMap
"YOSHI'S ISLAND" [checksum ok] LoROM, 16Mbits, ROM+RAM+BAT+Super FX, PAL, SRAM:256Kbits, ID:YI  , CRC32:7BDC6A78
```

**Comment by mckaygerhard** [comment]
its now fixed? why close it and whiout any comment? due fixed it?

**Comment by OV2** [comment]
Yoshi's island works fine in Snes9x 1.5 and later. I'd guess you have a bad ROM, the crc does not match any of the 12 versions I have here, which all work.

**Comment by Oggom** [comment]
Judging from a quick internet search it appears that the checksum belongs to an ancient interleaved GoodSNES PAL 1.0 rom of said game.

So yeah, it's a bad dump.

**Comment by mckaygerhard** [comment]
a bad dump? ok i understand now.. umm i ask, ok my rom does not work property (well until now it works as expected)

my question now, this dump will not work as expected the original dump?

so its not a problem from emulator, another question: why the 1.42 can run that rom?
