### ISSUE TITLE
Feature Request: Save State/Load State GUI

### ISSUE THREAD

**Issue by xZabuzax** [snes9xgit/snes9x#560]
This is a feature that is available in the Mac/Os X version of Snes9X and isn't available anywhere else. The only emulator that has a feature somewhat similar are PPSSPP and Zsnes (this one looks plain ugly though) but the implementation of Snes9X in a Mac is far better than those ones. I know I'm asking a lot but it would be cool having more emulators with a feature similar to that one.

This is the feature I'm talking about:
https://imgur.com/a/em3USoV

**Comment by koitsu** [comment]
FYI, this individual has been going around to several places requesting this feature. Developers may want to read these threads first to get some context, insights, and food-for-thought.

- http://forums.nesdev.com/viewtopic.php?f=12&t=19184
- https://www.reddit.com/r/emulation/comments/copko3/save_stateload_state_gui_in_emulators/

**Comment by bearoso** [comment]
I've seen the threads. In the past I've refrained from adding something like this because of how platform-specific the ports are. The Windows display outputs don't have a way of doing this in a coherent manner, so there would be a lot of code duplication or refactoring to do it. This would be best done in a brand-new cross-platform UI.

**Comment by xZabuzax** [comment]
Hello, I apologize for bringing this subject up again but I noticed that the recent Git of Snes9x have these changes:

> **Merge branch 'win32-saveload-preview'**
> **win32: add hotkeys for preview dialog**
> **win32: only load screenshots in preview dialogs**
> **Add function to load only screenshot from snapshot file**
> **win32: add dialog for saving/loading with preview images**

Are those changes related to the **Save State/Load State GUI** that I described on this thread? and if that's the case, are there any pretty screenshots you guys can provide so we can take a look at it?

Thanks.

**Comment by OV2** [comment]
You can see a screenshot in #580 , and you can download a preview build here: https://ci.appveyor.com/api/buildjobs/hm5h7e85kh8mnr5m/artifacts/snes9x-1.60-170-g5a4c5be-win32-x64.zip

**Comment by xZabuzax** [comment]
> You can see a screenshot in #580 , and you can download a preview build here: https://ci.appveyor.com/api/buildjobs/hm5h7e85kh8mnr5m/artifacts/snes9x-1.60-170-g5a4c5be-win32-x64.zip

Oh hell yes!, more emulators needs these type of features. I can gladly do some testing for you if you like.

I would have loved if it had some sort of "Dark Theme" or something to look more like the Mac/Os X version but at this moment I can't be too picky about this, I'm just happy that it's finally being implemented in Snes9x for Windows after all these years.

**Comment by Max833** [comment]
I like that. Mesen-S has something similar (right at the start, though). A game selection screen, which shows a preview of a game you previously were playing and you can start the game immediately when you click on it. That would be cool for SNES9x as well. ^^

![image](https://user-images.githubusercontent.com/53529402/71679100-10911580-2d87-11ea-9dff-840d5ae8893a.png)

**Comment by xZabuzax** [comment]
> I like that. Mesen-S has something similar (right at the start, though). A game selection screen, which shows a preview of a game you previously were playing and you can start it immediately when you click on it. That would be cool for SNES9x as well. ^^

Exactly my thoughts on this, Mesen-S has that feature but unfortunately it only works when you start the emulator, it would be nice to have full control of that feature and have that GUI to open up with a hotkey. Mesen-S just needs to decrease the size of those pictures to have more slots available for the save states.

If Snes9x has something similar to that then it will be pretty close to the "Save State/Load State GUI" of Snes9x for Mac/Os X.
