### ISSUE TITLE
WAV Export?

### ISSUE THREAD

**Issue by YuzuMSX** [snes9xgit/snes9x#569]
I try to render some Music but there is not option for WAV Output.
But It's only export to AVI File.

Sorry was noob

**Comment by OV2** [comment]
At the moment you can only export an avi and then extract the audio stream from that.

**Comment by bearoso** [comment]
And what you should do is export the SPC file and use an audio player to convert to whatever format you want.

**Comment by YuzuMSX** [comment]
Yeah. Unfortunately recording to Avi file also no sound during recording. 
Some SPC Players have FIR Filter Bug. Also my emulator works fine.

Okay thanks for resolving this
