### ISSUE TITLE
Visual Studio 2019 Build

### ISSUE THREAD

**Issue by nbarkhina** [snes9xgit/snes9x#570]
I'm trying to build using Visual Studio 2019 and Windows 10 SDK. Everything actually builds and runs correctly except for the audio. I had to comment out these lines in CXAudio2.cpp - 

pXAudio2->GetDeviceCount(&num_devices);

It looks like that api is deprecated after the Windows 7 SDK. I know you don't support this configuration yet, but any ideas on what code I could use to replace this with in order to work with the new SDK?

Thanks.

**Comment by OV2** [comment]
There is no simple way to switch this to the new 2.8 api. You'd need to rewrite the device enumeration, a sample can be found here:
https://github.com/walbourn/directx-sdk-samples/blob/master/XAudio2/XAudio2Enumerate/XAudio2Enumerate.cpp

However 2.8 requires win8 and will not run on anything below that.

**Comment by nbarkhina** [comment]
Thanks i'll check out the sample

**Comment by Sanchez093** [comment]
How do i bulid snes9x? it says build failed! help me!
show me all the links for the required stuff please ASAP!
