### ISSUE TITLE
Add an option

### ISSUE THREAD

**Issue by lordpeluca** [snes9xgit/snes9x#571]
Is there any possibility in the future to add an option for a game to load automatically in full screen?

Something like: "Auto Switch to fullscreen after loading", or something like that...

I know you can go to full screen with "Alt + Enter", but it would be great an option to do it automatically.

Greetings

**Comment by lordpeluca** [comment]
And where do I write that?... in the "CONF" file?

**Comment by greg-kennedy** [comment]
`-fullscreen` is the command-line option.  You didn't specify which OS or port you're using, so it's hard to give better instructions on where to put that in.

**Comment by lordpeluca** [comment]
My emulation pc is an XP SP3 window.

Thank you for answering :)

**Comment by Max833** [comment]
> And where do I write that?... in the "CONF" file?


![image](https://user-images.githubusercontent.com/53529402/64986419-40dfa180-d8c7-11e9-9269-8b0ca3728f2a.png)

**Comment by bearoso** [comment]
I don't think that'll do what he wants unless he just drags games onto to the shortcut.

**Comment by lordpeluca** [comment]
I did, but it didn't work. When I open the emulator it puts me in full screen, but when I press the "Esc" key, to open the loading menu of the game (File - Load Game), it is minimized and remains in window mode and when I try to load a game it keeps starting in window.....

The way it says "bearish" works, but it's not what I wanted... that way it's a bit tedious. The idea was to load the game from a specific folder or from the "Custon ROM Open Dialog" option.

Greetings

**Comment by victicdin** [comment]
@lordpeluca If you're interested in launching a specific game in fullscreen you can do this in a shortcut:
`path\to\snes9x-x64.exe "path\to\rom\foo.smc" -fullscreen`
I noted that only using `-fullscreen` doesn't present the issue you described on my end when pressing escape to load a rom from the file menu. It seems to work as desired on windows 10 with snes9x v1.60. Are you still experiencing this on XP SP3?

**Comment by lordpeluca** [comment]
I didn't read the message. I apologize for not answering sooner @victicdin.

Yes, I use XP SP3. The idea was to do it with all the games and not with any specific one. Open the games as you do mame or fbn. 

Greetings
