### ISSUE TITLE
Firepower 2000 (USA) - Scanline Timing [snes9x v1.60]

### ISSUE THREAD

**Issue by Max833** [snes9xgit/snes9x#579]
https://github.com/byuu/bsnes/issues/115 (same behaviour with snes9x v1.60)

Hardware: http://streamable.com/mhucb

**Comment by jjfmz42015** [comment]
> [byuu/bsnes#115](https://github.com/byuu/bsnes/issues/115) (same behaviour with snes9x v1.60)
> 
> Hardware: http://streamable.com/mhucb

Renders perfect on Mesen-s DevWin 0.2.0.24 if this helps anyone

**Comment by jjfmz42015** [comment]
also fixed in bsnes now

**Comment by bearoso** [comment]
Should be fixed in 20f6dab.
