### ISSUE TITLE
G.O.D - Mezame yo to Yobu Koe ga Kikoe (Japan)

### ISSUE THREAD

**Issue by Max833** [snes9xgit/snes9x#581]
As soon as I talk to someone, the whole screen gets blurred. I can't reproduce this with bsnes or Mesen-S.

<img width="513" alt="11" src="https://user-images.githubusercontent.com/53529402/65280725-4d673280-db31-11e9-87ff-e67f618253d7.png">

**Comment by bearoso** [comment]
Video->Display Settings
Uncheck "Blend Hi-Res Images".
