### ISSUE TITLE
[Libretro] Feature request: gamma correction

### ISSUE THREAD

**Issue by tostenny** [snes9xgit/snes9x#589]
Sameboy has this sgb color correction feature called "correct curves". It's like a gentler TV gamma ramp that's more modest than the higan one.

Could this be installed into snes9x?
https://github.com/LIJI32/SameBoy/blob/master/Core/display.c#L175

I tried making a shader but couldn't figure it out.

**Comment by themalu866** [comment]
Yeah, the gamma shader available is way too dark even compared with the Higan.

**Comment by tryal-star** [comment]
I ported the Sameboy curves to glsl shader format. Works on many systems.
https://raw.githubusercontent.com/tryal-star/glsl-shaders/color_curves/color-curves.glsl

**Comment by tostenny** [comment]
Thanks! Games like Zelda 3 look great now!
