### ISSUE TITLE
Failed to open sound device on Fedora 30 x86

### ISSUE THREAD

**Issue by babakRz63ai** [snes9xgit/snes9x#591]
I have built snes9x from source for Fedora 30. When wanted to play a game, I can't hear any sound, and this error message is printed:

Snes9x 1.60 for unix
ERROR: Failed to open sound device /dev/dsp for writing.
	(Try loading snd-pcm-oss module?)

This is how configure was invoked:
`$ ./configure --enable-sound --enable-xvideo --enable-zip`

This is configure log file content:
[config.log](https://github.com/snes9xgit/snes9x/files/3799420/config.log)

**Comment by bearoso** [comment]
Fedora is using PulseAudio and you're using the Unix command line version that only supports OSS. Run it with `padsp snes9x`  to redirect OSS to PulseAudio.
