### ISSUE TITLE
Sugoro Quest++ - Dicenics (Japan) - Scanline Timing [Snes9x 1.60]

### ISSUE THREAD

**Issue by Max833** [snes9xgit/snes9x#595]
![image](https://user-images.githubusercontent.com/53529402/68551429-33e5b700-040d-11ea-8bd5-115f6e4e55d3.png)

**Comment by bearoso** [comment]
We’ll have gather all these cases and auto detect them with a new setting like bsnes does.

**Comment by bearoso** [comment]
Should be fixed in 20f6dab.
