### ISSUE TITLE
Dragon View Crashes after name input

### ISSUE THREAD

**Issue by GhostBelmont** [snes9xgit/snes9x#605]
Good Night, 

I'm having a issue with the Dragon View game, when I start the game and put the name of my character, the game freezes. Is this an emulator issue or is some emulator configuration? I'm using Snes9x 1.60. 

Thanks for the attention. 

Best Regards

Rafhael

**Comment by chipzoller** [comment]
I cannot reproduce this behavior on 1.60 win64 with ROM having CRC of AB893412. You may have a corrupt ROM.

**Comment by GhostBelmont** [comment]
Hi, Mr. Chipzoller. 
I will test with another ROM with the same CRC above to see. Anything i tell you. 
Thanks for the answer.

**Comment by GhostBelmont** [comment]
I've tried with another ROM and worked! Thanks again for the help!
