### ISSUE TITLE
Sound cracking on Rewinding SNES 1.60

### ISSUE THREAD

**Issue by Cibomatto2002** [snes9xgit/snes9x#606]
Here is a video of the problem.

https://streamable.com/vsigm

Operating System
	Windows 10 Home 64-bit
CPU
	AMD Ryzen 7
	Summit Ridge 14nm Technology
RAM
	16.0GB Dual-Channel Unknown @ 1197MHz (17-17-17-39)
Motherboard
	Dell Inc. 0VYXHD (AM4)
Graphics
	ELEFW328 (1360x768@60Hz)
	4096MB ATI AMD Radeon RX 580 (Dell)
Storage
	931GB Seagate ST1000DM010-2EP102 (SATA )
Optical Drives
	No optical disk drives detected
Audio
	High Definition Audio Device

**Comment by L0wMax** [comment]
Should even be playing while rewinding? I feel like it should be muted.

**Comment by OV2** [comment]
That is to be expected - when rewinding we only get sound for one frame, then sound of the previous frame and so on (depending on the rewind granularity). This will always sound weird, it's simply not regular sound played backwards. It will use the same volume as fast forwarding, so you can use that setting.

**Comment by Cibomatto2002** [comment]
This is the only emulator I ever heard when using Rewind that makes that sound when Rewinding that's why I thought it was a bug of some kind.
