### ISSUE TITLE
Command line switch reference

### ISSUE THREAD

**Issue by chipzoller** [snes9xgit/snes9x#607]
I am not finding any modern command-line reference guide in this repo, on snes9x.com, or elsewhere. Is there not a complete reference guide to the available switches per platform? Is there a somewhat complete guide if not?

**Comment by OV2** [comment]
You can start it with -help and it will print the core command line options (on win they will end up in stdout.txt). There are some port specific command line switches that will not be in the list (on win that is -restore, -hidemenu, -fullscreen and -cartb).

I'll see if I can add a wiki page with the options at some point, will leave this issue open until then.

**Comment by chipzoller** [comment]
Thank you, I hope this necessary info can make it into some form of written documentation somewhere. Ok, so then I want to suggest two enhancements based on this:

1. The win binary should respond to the traditional help switches of `/?` and `-h` in addition to `-help`. I tried both of these options before posting with no result.

2. The help output should print on-screen to stdout and not default to file logging. Stream redirection should be used if that is to be the desired result.

If these should be listed separately for tracking purposes, I'll gladly do so.

**Comment by OV2** [comment]
I can add the additional switches, but since s9x is a GUI application its default stdout is invisible. So the redirect will have to stay. I can maybe add a dialog that also displays the command line switches - or at least points to stdout.txt

**Comment by chipzoller** [comment]
Understand, but I think **something** needs to be returned to the user when the binary is called with any such "help" switches. Transparently and silently writing to a log file in the parent directory can be confused with no action taken unless you were otherwise aware.

**Comment by OV2** [comment]
I've changed it so that it also reacts to /? and -h, and will display a message box that mentions stdout.txt
