### ISSUE TITLE
Secret of Evermore (U) - reproducible emulator crash

### ISSUE THREAD

**Issue by r-bin** [snes9xgit/snes9x#609]
The second boss of the game crashes the emulator relatively consistent for me.

That being said:
- It requires speed running strategies
- I'm the only person in the community who has this problem
- It doesn't always happen, but if the (unknown) preconditions are met, it happens every time
- It crashes the emulator most of the time, but sometimes it just stops progressing the game and the music keeps playing (Soft lock)
- I cannot verify it with a console
- I tried Snes9x 160, 154 and 153, with the same  result
- It happened with Higan v106 as well, but I had just soft locks so far

Save state #00: [Secret of Evermore (U).zip](https://github.com/snes9xgit/snes9x/files/3996591/Secret.of.Evermore.U.zip)

- ![Capture2](https://user-images.githubusercontent.com/4923831/71384237-8a373f80-25e0-11ea-817a-41cc0920221c.PNG)
- Y closes the ring menu
- ![Capture3](https://user-images.githubusercontent.com/4923831/71384373-39741680-25e1-11ea-9cda-2108b746a711.PNG)

Variations of the crash:
- ![ball_of_death](https://user-images.githubusercontent.com/4923831/71384317-e4380500-25e0-11ea-80cd-46165eb25d63.PNG)
- ![Capture](https://user-images.githubusercontent.com/4923831/71384322-eef29a00-25e0-11ea-8574-9b3a785b9bd3.PNG)

**Comment by bearoso** [comment]
Hmm. I’m guessing that it’s somehow setting the S-CPU up in a halt state, since in some cases it doesn’t give control back to the UI. I think you might be hitting an actual game bug with arbitrary code execution.

**Comment by r-bin** [comment]
Thanks for your insight!
Here is a video with Higan v106: (Which tends to soft lock, instead of crashing)
https://youtu.be/z0WZir5MSzs?t=799

So it's likely that this would happen with actual hardware as well? Interesting...
Can I somehow access the crash logs? Is there a Wiki with guides on how to debug it?

**Comment by bearoso** [comment]
Yeah, you are probably going to see this on hardware in some form. I haven’t looked into it, but I’d guess it’s overwriting a jump address and jumping to and executing random data, typical ACE. 

I’d suggest trying bsnes-plus to debug it. The Snes9x debugger isn’t user friendly.

**Comment by r-bin** [comment]
You're totally right. I no longer think, that the emulator does something wrong.
Thanks for your help!
And I'll try to research if the crash can be turned into ACE, in case you have any hints or resources that might help.
