### ISSUE TITLE
Snes9x is no longer compatible with Windows XP?

### ISSUE THREAD

**Issue by lordpeluca** [snes9xgit/snes9x#612]
Try to test this arrangement:
https://i.postimg.cc/sDxwmgpc/F1.jpg
https://i.postimg.cc/L5wfN2pC/F2.jpg
https://i.postimg.cc/t4hPtKmk/F3.jpg

But when I try to open the exe, I get the following message:
https://i.postimg.cc/xqV8XCY2/F4.jpg

Greetings

**Comment by OV2** [comment]
I pushed a commit that replaces the functions that are not available in winxp.

**Comment by lordpeluca** [comment]
Thank you very much, OV2. Now the emulator starts up perfectly!

Greetings
