### ISSUE TITLE
New Super Mario Land 4 player not working fine

### ISSUE THREAD

**Issue by Darknior** [snes9xgit/snes9x#617]
Hi
Today i try to play New Super Mario Land on my Batocera PI with this core and 2 other Snes9x CORE and same Result, i can't play the game in 4 player ! :(

https://www.youtube.com/watch?v=ytaV_S9YDWY

First player press START it's OK, second player with Multiap press START and 4 Mario comes on screen like if the player two control all the 4 controllers alone :(
Same with : 

- libretro/pocketsnes
- libretro/snes9x
- libretro/snes9x_next

I've also try to play Super Bomber Man 5 with same settings and it work fine, only NSMB have this problem :(
But if i try to play it with : 

- libretro/mesen-s

Then the 4 players working fine :)
But this core is really too slow on PI to use it :(

Can we dream about a fix for this game ? I'm sure it's not some thing really hard, it works fine for many other games, but this one see only one controller and not 4 on the multitap :(

Thanks a lot

**Comment by OV2** [comment]
Are the same controls mapped to all 4 players? I just tried the current git build with retroarch 1.8.2 and had no problems (setting port 2 to multitap, then joining with three players).

**Comment by Darknior** [comment]
My settings are same for Bomberman 4 and 5 and working fine.
And it works with Messen-S, but not with Snes9x.

For the moment Batocera is in 1.81 ans will update in 1.8.2 in next release.
And core build is Snes9x 2010 (1.52.4 2d1ad1ad1cd4e)

![20200103_225836](https://user-images.githubusercontent.com/3703317/71752034-d9516000-2e7d-11ea-8d1a-f71be459a150.jpg)

**Comment by Darknior** [comment]
You are right @OV2 sorry, i understand after post my photo i've try with Snes9x 2010, i try again with Snes9x and it works fine :)
I've finished the game.
Thanks a lot

![20200104_023019](https://user-images.githubusercontent.com/3703317/71759332-edac5180-2eab-11ea-810e-fe7b7f653c89.jpg)
