### ISSUE TITLE
64Bit for macOS Catalina?

### ISSUE THREAD

**Issue by cyberfunk** [snes9xgit/snes9x#618]
Hello, any plans for a 64Bit update for macOS Catalina so we can take Snes9x with us into 2020 and beyond?

**Comment by OV2** [comment]
See #586

**Comment by MichaelBuckley** [comment]
Hello, @cyberfunk . As OV2 pointed out, there is an issue for this already. There are builds in that issue which work on Catalina (scroll to the bottom for the latest build), but many features are still being worked on. You can find more information in that issue, so I am going to close this issue as a duplicate. Please feel free to leave any feedback in that issue.

**Comment by cyberfunk** [comment]
Thanks!

**Comment by mahedi7up** [comment]
i like this 64Bit macOS Catalina for 64Bit prossesor
