### ISSUE TITLE
Permission to add Snes9x to Steam as free DLC for RetroArch

### ISSUE THREAD

**Issue by twinaphex** [snes9xgit/snes9x#620]
Hi there,

we would like to seek your permission to include Snes9x as a core as free DLC for RetroArch on Steam.

The user would have to manually install this, it would be freely made available.

If there's anything you are unsure of or are hesitant about, don't hesitate to bring it to our attention. We will always go with whatever you decide.

**Comment by OV2** [comment]
I think if you do not actively use it in promotions this way should comply with the license.

Personally I have no problems with the s9x core(s) being a DLC.

**Comment by twinaphex** [comment]
Yeah, there's no intent of us using it in promotions or anything like that.

**Comment by twinaphex** [comment]
Is there anybody else from the team that wants to chime in on this issue? Or is it considered fine to proceed as is?

**Comment by bearoso** [comment]
Fine by me.

**Comment by twinaphex** [comment]
Alright, I consider the issue resolved then. Thanks very much guys! I will keep you guys up to date when we are nearer to launch date.

**Comment by twinaphex** [comment]
Hi there, 

just wanted to let you guys know this finally happened -

https://store.steampowered.com/app/1227444/RetroArch__Snes9x/

**Comment by OV2** [comment]
That's great, thanks for letting us know!
