### ISSUE TITLE
Drag & Drop file support for Snes9x window?

### ISSUE THREAD

**Issue by ImSpecial** [snes9xgit/snes9x#627]
Hi, I'm not really sure how to name the title, but when dragging a ROM or .zip file with a ROM inside and dropping it on the Snes9X window I get an error message "Unknown file extension" [like so](https://i.imgur.com/MKyDLLF.png).

Is there a way to make this work? If not can this be made into a [Feature Request] of sorts and have this be added to a future release? Many emulators support this kind of behavior, and find dealing with my Explorer window much quicker then menus.

Anyway, thanks for what you do, you guys rock!

**Comment by OV2** [comment]
If you get the "Unknown file extension" error message then you have probably edited the valid.ext file and it no longer contains those extensions. You can manually delete the file and s9x will recreate a new one with the appropriate extensions included.

**Comment by ImSpecial** [comment]
Oh, right you are! I forgot that I changed that file many moons ago to prevent mucking up my system registry with file association stealing... hmm I guess I'll have to live without this then. /sad

**Comment by OV2** [comment]
There have been changes to how s9x registers itself with windows, you might want to check if you still have problems with that. You could try it by removing all but one extension from valid.ext.

**Comment by ImSpecial** [comment]
Just want to say that creating a fresh [valid.ext](https://i.imgur.com/y3wlzqy.png) does indeed fix this, but I won't be going with this solution long term because it does indeed muck of the registry, a PITA to clean out as well... (but a quick shout out to NirSoft and his tools used in doing so!)

IMO, Snes9x should be changed to not take association at all, period, unless given permission to do so by user, for example [Nestopia](https://i.imgur.com/hFOv31E.png) or [Mesen](https://i.imgur.com/WywY4as.png) handle things this way.

Any particular reason why Snes9x does what it does, when I can't think of any other emulator that does this, dropping .zip files or ROMs directly on (again) Mesen for example have none of these issues when running them, and Mesen isn't creating associations to generic .zip files in doing so either, many other emulators, same boat.

Please strongly consider this as a future feature request, I have no idea on the reason as to why it is how it is now, or how hard it would be to change (not asking for some GUI option window, just nuke'em :P) but I feel like this is a pretty big flaw with the emulator.

**Comment by OV2** [comment]
S9x does not do direct file associations, it simply enters itself as a program available in the "open with" list for its extensions. Double-clicking the files will not open s9x, and it does not change the icon displayed in explorer.
It does this because it is a requirement for those file types to show up in the jump list of the taskbar.

**Comment by ImSpecial** [comment]
I know it doesn't "steal" association, but even having it show up in your "jump list" as you say is not okay IMO, I don't have (again, again) Mesen for example show up in jump list with anything that was opened with Mesen (.zip files).

**Comment by OV2** [comment]
This is the jump list, it is a program specific list:
![](https://i.imgur.com/2lEhLPE.png)

I don't see the registry entries as a problem. If you have another reason other than "no changes on principle" let me know.

**Comment by ImSpecial** [comment]
Oh, that was not what I was referring to, it was actually the "Open with" dialog (my bad) you get when right clicking a file and bringing up the context menu.

**Comment by barttyr** [comment]
+1 to this request please! registry should never be touched, snes9x is portable, keep it that way please, at least by default it should not be changing or adding to anything in there...

Also I came across this topic because I had the same issue as OP, but I have a question about this Valid.EXT file, inside it has things such as...
```
smcN
zipY
msu1Y
gzY
swcN
figN
sfcN
bsN
jmaY
```
I guess the first part "smc" "zip" "sfc" are the extension types, but what does the "N" "Y" mean? No, Yes? What does altering these do, thanks for explanation in advance. :)

**Comment by OV2** [comment]
Y/N controls if the extension is a compressed format. This is mostly used in the old custom rom dialog.
