### ISSUE TITLE
Kaillera For The Online ?

### ISSUE THREAD

**Issue by Snipy44** [snes9xgit/snes9x#63]
Why dont integrate kaillera client ? pleas is better for netplay ! :D (im french sorry for my bad english)

**Comment by Snipy44** [comment]
I have tried many different version of Kaillera, the most stable version of Kaillera of 2007 I test more recent versions, but it encounters problems of desync.

So here Kaillera 2007 the most stable version to date, and SupraClient to also add that if you wish for and an alternative to Kaillera interesting.

http://sd-1.archive-host.com/membres/up/581484586/Kailera__SupraClient.rar

**Comment by vgturtle127** [comment]
Kaillera isn't actively maintained anymore. Most emulators and applications that use it have either moved to other libraries, created their own, or removed netplay support. The applications that still use it work OK and everything, but the future is uncertain for Kaillera (to me at least). If the source code was available, that would be a different story. But it isn't unfortunately. :disappointed:

**Comment by vgturtle127** [comment]
@Snipy44 There are also security issues now, and they are unfixable unless you have the source code. The SDK hasn't been updated in years...

**Comment by Snipy44** [comment]
Yes is here : https://github.com/Agent21/Emulinker-X , Emulinker X is a open source server kaillera, is just possible to create a link for use kaillera ? is really not bad ! pleas i need that, me and the community !

**Comment by vgturtle127** [comment]
@Snipy44 That isn't the same thing as a complete solution. SNES9X would have to implement support for that server specifically, and also add Kaillera support in general. As far as I can tell, this would also not work on other ports like Android, iOS, Mac, and some other systems.

It also uses Java, which I don't really like.

Besides, SNES9X already has great Netplay! This has been used by the community for a long time.

![screenshot 4](https://cloud.githubusercontent.com/assets/3183676/13268965/fa63ffcc-da4a-11e5-92a8-a61ee306e2d9.png)

![screenshot 5](https://cloud.githubusercontent.com/assets/3183676/13268977/09ccba62-da4b-11e5-8745-02e8dc7957fe.png)

**Comment by bearoso** [comment]
Irrelevant now.
