### ISSUE TITLE
Changing speed does not work

### ISSUE THREAD

**Issue by Cibomatto2002** [snes9xgit/snes9x#630]
When using -, = it does not change the speed of the emulator.

snes9x-1.60-191-g0a89725-win32-x64

Video of the problem.

https://www.youtube.com/watch?v=KEuj-PPMVIQ

**Comment by OV2** [comment]
You most likely have set frame skipping to "fixed" - speed changes only work with "automatic".

**Comment by Cibomatto2002** [comment]
That was it thanks.
