### ISSUE TITLE
unusual bad performance on soft scaler arm64 xbrz x2 (low cpu usage)

### ISSUE THREAD

**Issue by Askmewho** [snes9xgit/snes9x#631]
HI! Ive compiled master.. and I was expecting similar performance than on rpi4 at 2.0 ghz. this have two a72 at 2.0 ghz (on the image Ive shown just 1.8 bc 2.0 didnt change anything) and 4 a53 at 1.5 ghz. for some reason, even if I add 6 threads.. it barely use all cores

![2020-02-11-190449_1920x1080_scrot](https://user-images.githubusercontent.com/39385643/74269769-eb86af80-4d01-11ea-8a92-ad89aac77184.png)

**Comment by qwertymodo** [comment]
Emulation is something that really doesn't parallelize well.  I'm sure there's room for improvement, but those numbers really don't surprise me all that much.

**Comment by Askmewho** [comment]
It did a great job on rpi4 on multicore soft render. I will make an armhf test instead just for try it.. weird. Thanks
