### ISSUE TITLE
Increase SRAM size

### ISSUE THREAD

**Issue by cout** [snes9xgit/snes9x#637]
I have been wanting to play the Super Metroid practice hack (https://github.com/tewtal/sm_practice_hack) on snes9x, but the save state feature crashes the emulator due to lack of bounds checking when writing to SRAM in `getset.h`.

AFAICT, the save state feature works by copying WRAM/VRAM/CGRAM to the SRAM memory region (https://github.com/tewtal/sm_practice_hack/blob/master/src/save.asm) from $71000 to $7721FF.  Snes9x allocates 128KB of memory for SRAM, so the last valid address is at $71FFFF; writing beyond that invokes undefined behavior.

Per https://en.wikibooks.org/wiki/Super_NES_Programming/SNES_memory_map cartridge SRAM could be as large as 448KB, though the SM practice ROM needs 457KB (it could possibly be modified to use as little as 257KB).  I believe it is reasonable to allocate 512KB; this is enough to keep Snes9x from crashing without any additional bounds checking, as an address past 512KB would be in a different mapped region).

**Comment by OV2** [comment]
The problem with extending the SRAM is that this would affect s9x savestates, so we'd have to have a new version and it would increase the size. I'm not sure that would be worth it.
Why do you want in-game save states? Can't you use the s9x savestates when playing via s9x?

**Comment by cout** [comment]
AFAICT, increasing the amount of memory allocated for `Memory.SRAM` should have no effect on save states.  This is the only change that is necessary to prevent the emulator from crashing.  The size of SRAM in `snapshot.cpp` is hard-coded to 128KB, so only the first 128KB of SRAM is written to the save state file, regardless of the size of the array.

The size of the SRAM block in the snapshot can also be increased along with `Memory.SRAM`.  If I read the code correctly, it _should_ be backward-compatible, as `UnfreezeBlock` already checks the size of the block in the file against the expected size, truncating or zero-filling as necessary.  This behavior is also documented in `snapshots.txt`.  Since the save state file is compressed, the file should use no additional space on disk.

As for why in-game save states are desirable vs emulator save states: either one is probably fine.  The in-game save state has a couple of nice features over emulator save state.  State is only saved after a door transition is complete, so this makes it easier to consistently save state at the same point for each room.  Also, when restoring a state to a room that has the same music as the current room, the music keeps playing from the same spot; with the emulator save state, music is reset with the rest of the game.  IMO however, these are cosmetic improvements; the bigger issue is that the ROM can cause the emulator to crash.

In my local copy of snes9x, I have made the change to increase SRAM size, and saving state in-game no longer crashes snes9x.  I have also run under valgrind to verify that it no longer produces "invalid write of size 1" errors.

I would be happy to submit a pull request,  though I'm unsure how to test for regressions.

**Comment by OV2** [comment]
I have to admit I only did a cursory glance into snapshot.cpp when answering. With the length check in place I see no problem increasing the size. If you've already made the changes I'd appreciate a pull request.

What did you mean with "the SM practice ROM needs 457KB"? The save state asm code seems to save 192,5KB


@bearoso can you think of any other problematic places?

**Comment by cout** [comment]
It does write 6*32KB + 512 bytes, but the writes are spread out.  The address of the last byte is 0x7721FF and the start of SRAM is 0x700000, so 0x7721FF - 0x700000 == 467455.  I don't know why it is written the way it is.

**Comment by bearoso** [comment]
I don't anticipate any problems. Go ahead and increase the size and we'll see if any crop up.
