### ISSUE TITLE
GTK: glslang version incompatibilities

### ISSUE THREAD

**Issue by Csokis** [snes9xgit/snes9x#645]
I can't compile on Ubuntu 18.04.4 LTS. :(

> [3/4] Compiling C++ object 'snes9x-gtk@exe/.._shaders_slang.cpp.o'.
FAILED: snes9x-gtk@exe/.._shaders_slang.cpp.o 
ccache c++ -Isnes9x-gtk@exe -I. -I.. -I/usr/local/include/glslang -I../../apu/bapu -I../ -I../../ -I../src -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/SDL2 -I/usr/local/include -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/alsa -I/usr/include/minizip -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -g '-DGETTEXT_PACKAGE="snes9x-gtk"' -pthread -D_REENTRANT -DSNES9X_GTK -DUNZIP_SUPPORT -DNETPLAY_SUPPORT -DJMA_SUPPORT -Wall -W -Wno-unused-parameter '-DDATADIR="/usr/local/share/snes9x"' '-DSNES9XLOCALEDIR="/usr/local/share/locale"' -Wno-format-truncation -DUSE_OPENGL -DUSE_SLANG -DSPIRV_CROSS_EXCEPTIONS_TO_ASSERTIONS -DUSE_WAYLAND -DUSE_XV -DUSE_PORTAUDIO -DUSE_OSS -DUSE_ALSA -DUSE_PULSEAUDIO -DHAVE_LIBPNG -DSYSTEM_ZIP -DZLIB -DUSE_HQ2X -DUSE_XBRZ -DHAVE_MKSTEMP -DHAVE_STRINGS_H -DHAVE_STDINT_H -DRIGHTSHIFT_IS_SAR -DPTR_NOT_INT -fno-exceptions -fno-rtti -MD -MQ 'snes9x-gtk@exe/.._shaders_slang.cpp.o' -MF 'snes9x-gtk@exe/.._shaders_slang.cpp.o.d' -o 'snes9x-gtk@exe/.._shaders_slang.cpp.o' -c ../../shaders/slang.cpp
../../shaders/slang.cpp:191:6: error: braces around scalar initializer for type ‘int’
     }};
      ^
ninja: build stopped: subcommand failed.

**Comment by bearoso** [comment]
Your glslang version is too old. This is one of the perils of using the system version. Perhaps we should include our own copy from now on.

**Comment by bearoso** [comment]
Or just move the copy from the win32 version, since they already use a static copy.

**Comment by keithbowes** [comment]
> Perhaps we should include our own copy from now on.

RetroArch does that and its bundled glslang takes ages to compile.  That's why I always configure with `--disable-builtinglslang` so that it will use system glslang instead of taking ages to compile the bundled version.  If snes9x includes its own bundled version, please make it so that it can use the system version.

**Comment by Csokis** [comment]
Disabling the slang shaders (in meson config) is fine for me (I don't use shaders.). It's working, finally. :)

**Comment by bearoso** [comment]
> RetroArch does that and its bundled glslang takes ages to compile. That's why I always configure with `--disable-builtinglslang` so that it will use system glslang instead of taking ages to compile the bundled version. If snes9x includes its own bundled version, please make it so that it can use the system version.

I understand that, but glslang isn't structured for use as a shared library. In Issue #649 you can see that Debian is building in certain components that require other external dependencies. Some OSes are putting the libraries in different places. Some are omitting the resource limits library. Its easier to avoid all the weirdness and just bundle the parts we need. This is done as of e26649c.
