### ISSUE TITLE
Missing -lpthread in linking options

### ISSUE THREAD

**Issue by kwyxz** [snes9xgit/snes9x#647]
Attempting to build the latest Git rev on Debian GNU/Linux (stable). After following the build instructions on the Wiki, `-lpthread` was missing from the `LINK_ARGS` in build.ninja and caused the linking to fail.

Manually adding it fixed it. Sorry, not familiar enough with meson/ninja to submit a PR :(

**Comment by bearoso** [comment]
Fixed in a20e726.
