### ISSUE TITLE
Directional problems in some GAMEPAD

### ISSUE THREAD

**Issue by kirous** [snes9xgit/snes9x#65]
Hello. Well I have a problem about GAMEPAD HALION (HA2020 PUP), since in digital mode only works the up, down, left and right, however the vectors does not work when a fighting game is played as if STREET FIGHTER (and others) when I want my character jump to the vector position does not just jump up.

In contrast to analog mode, if it comes to fruition. The question is, because I will not be nearly incompatible directions in some GAMEPAD ?. Is there any way to fix it ?.

Note: The keyboard is operating correctly. And in my setup if it works correctly in other emulators and PC games.

![game-pad-ha2020-pup-plata](https://cloud.githubusercontent.com/assets/5083411/6203903/cc02e136-b505-11e4-812a-c3e3de69c547.jpg)

Sorry my bad English!!

**Comment by Ember2528** [comment]
I had the same problem with a ds4 in controller configure you need to assign upleft, downleft etc. to the game pad

**Comment by kirous** [comment]
THANX... Missing knew assign
