### ISSUE TITLE
Unable to open lawnmower man from command line in linux

### ISSUE THREAD

**Issue by Blad3forc3** [snes9xgit/snes9x#657]
Hi,

I am getting this error when opening the lawnmower man rom from the command line

Map_LoROMMap

(snes9x-gtk:1964114): GLib-GIO-CRITICAL **: 19:07:49.017: This application can not open files.

It used to work fine but since upgrading to 20.04 it fails running from the command line.

The rom works fine when loading from the UI

**Comment by bearoso** [comment]
It's something that happened in the gtkmm conversion. Fixed in a3c0c4621ddc5319c284df1cafda8713c1dd57f1.
