### ISSUE TITLE
Choosing Freeze/Defrost Slot "C" actually Freezes/Defrosts to different slot

### ISSUE THREAD

**Issue by orsi** [snes9xgit/snes9x#666]
At first saving to "C" slot was overwriting "A" slot, and vice verse. After reloading ROM it was freezing/defrosting to slot "1".

In all cases, no image showed up on slot C.

Mac OSX 10.15.4 Catalina

**Comment by orsi** [comment]
It's actually an issue with pressing any of the assigned controller keys, which the "C" key is one of :P. If you use the arrows to move to slot "C" and hit enter, it will correctly save into slot "C". However, if you press the "C" key, or any of the buttons assigned to A, B, X, or Y, it will simply save over whichever slot is currently selected.

**Comment by orsi** [comment]
Question is whether this is correct behaviour now? I imagine someone with a controller would need the ability to choose which slot to save to with these buttons.

**Comment by MichaelBuckley** [comment]
Yes, this is the intended behavior, if I understand your description correctly. The freeze state should always be saved to whichever slot has the yellow selection border, regardless of which button is pressed.

**Comment by orsi** [comment]
If you press 1-9, A, or B keys, it will save to the corresponding slot no matter what slot is selected/highlighted. However, if you have any of those keys mapped to the SNES controller's A/B/X/Y button, it will save to the selected/highlighted slow.

Basically, there's overlapping functionality between pressing a keyboard key and the mapped controller buttons, and the mapped controller buttons win if they conflict.

**Comment by MichaelBuckley** [comment]
Ah yeah, I see the disconnect. Pretty sure it's been that way for more than a decade, but it got made worse once I changed the default keys to match the Windows port. Prior to that, the D and C keys weren't mapped to anything.

At this point, I don't want to change it and mess up anyone's current muscle memory. If someone really needs to fast save using the C or D keys, they can remap their controls.

**Comment by orsi** [comment]
Legacy functionality.
