### ISSUE TITLE
Latest Snes9x dev build (2014/02/02) crashes when 360 pad is turned off

### ISSUE THREAD

**Issue by karasuhebi** [snes9xgit/snes9x#67]
Windows 8.1
Core i5-4670K @ 4.10GHz
8GBs of RAM
HD 7950 w/Boost @ 1078MHz
Snes9x build from here: http://www.emucr.com/2015/02/snes9x-git-20150202.html

**Comment by OV2** [comment]
70cf3df should have fixed the problem.
Note that that is not an official dev build, you can find my builds here: http://www.s9x-w32.de/dl/testbuilds/

**Comment by karasuhebi** [comment]
Oh OK cool. Are you going to update your folder soon with newer builds? Or is it OK if I get them from Emucr.com?

**Comment by OV2** [comment]
I've uploaded a new build with the fix. I usually always build a new version if there are any changes that warrant it. The 2/2/ from emucr for example has nothing of consequence compared to the 1/29.

Of course there is nothing bad about getting s9x from emucr, I just don't know how they build them. You'll still get support if you use those builds ;)

**Comment by karasuhebi** [comment]
Good to know. Thanks for the quick feedback and the build @OV2. Keep up the good work! :D

**Comment by shinra358** [comment]
This build removes hotplugging and afterplugging. When a controller times out or gets removed, turning the emu off and back on is the only way to continue playing with a controller. Can you add it back please.

Using this build for this problem: snes9x_testbuild_27022015

**Comment by karasuhebi** [comment]
@OV2???

**Comment by OV2** [comment]
It worked fine when I tested with my Xbox controller. Does it not work for you? Do you use a different controller?
I'll do some tests again this evening.

**Comment by shinra358** [comment]
DS4 Windows J2K w/ DS4
Logitech F510

**Comment by OV2** [comment]
I've uploaded a new testbuild that should fix the hotplugging issue. Tried with a 360 and PS4 controller.

**Comment by shinra358** [comment]
works

**Comment by shinra358** [comment]
Found an issue with afterplugging. Turn emu on. Turn controller on. Controller won't work. Turn controller off and then back on. Now it will work. So you will have to turn the controller on twice in order for afterplugging to work.

**Comment by OV2** [comment]
Does this still happen with the latest build? Works correctly here.

**Comment by SwinglesMan** [comment]
Seems to work correctly here now as well.

**Comment by shinra358** [comment]
All good. Works~
Thanks.

**Comment by karasuhebi** [comment]
Works just fine for me. 3 months later, I think it's now time to close this. :P Thanks again @OV2!

P.S. What's a good way to reach you? Haven't seen you in #snes9x at all.

**Comment by ivanershov51** [comment]
The emulator crashes when I turn my xbox360 gamepad on after its timeout. Windows 10. SNES9X build from 2015-10-11.
