### ISSUE TITLE
Full-screen freezes the emulator.

### ISSUE THREAD

**Issue by Achaean** [snes9xgit/snes9x#674]
At Win 10 Pro x64 b.1909. Snes9x v.1.60.

I tried different video options, with the same results.

**Comment by OV2** [comment]
Can't reproduce here. Can you post some more information about your system? How are you switching to fullscreen?
Can you post your snes9x.conf file?

**Comment by Achaean** [comment]
Usually I'm using the shortcut (Alt-Enter), but I also tried the menu (Video -> Full Screen).
I'm attaching the config file.
[snes9x.zip](https://github.com/snes9xgit/snes9x/files/5251030/snes9x.zip)

**Comment by OV2** [comment]
I can't see any issues here. You're using "emulate fullscreen", which simply uses a fullscreen window, so there should be no difference to windowed mode.
You've also mapped enter to select, maybe that triggers pause in the game you were trying?
Otherwise you might try Direct3D as video mode.

**Comment by Achaean** [comment]
> Otherwise you might try Direct3D as video mode.

I already tried all different combinations.
 
> You've also mapped enter to select, maybe that triggers pause in the game you were trying?

That's it! I never thought of that!  :-)
Mapping another key (-combination), without Enter involvement, solves the problem.
**THANKS!!!**  ;-)
A.

PS1. I'm not sure if I have to close the report or not. 

PS2. At readme-windows.txt says: "'Alt'+'Enter'        toggles between full-screen and windowed mode".
Maybe it should be changed a bit, in order to reflect the recent change of behavior.
