### ISSUE TITLE
random crashes on master compilation aarch64

### ISSUE THREAD

**Issue by Askmewho** [snes9xgit/snes9x#678]
as you can see... sometimes it crash on launch

pi@RK3399:~/Desktop$ snes9x-gtk 
PulseAudio sound driver initializing...
    --> (48000hz, 16-bit Stereo, 48ms)...OK
Segmentation fault (core dumped)
pi@RK3399:~/Desktop$ snes9x-gtk 
PulseAudio sound driver initializing...
    --> (48000hz, 16-bit Stereo, 48ms)...OK
[xcb] Unknown sequence number while processing reply
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
snes9x-gtk: ../../src/xcb_io.c:641: _XReply: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)
pi@RK3399:~/Desktop$ snes9x-gtk 
PulseAudio sound driver initializing...
    --> (48000hz, 16-bit Stereo, 48ms)...OK
Map_HiROMMap

**Comment by bearoso** [comment]
Can you post the core dump? Is OpenGL enabled? I think it’s a race condition between the OpenGL context creation and the X drawable.

**Comment by Askmewho** [comment]
yes it's enabled, and yes, you are probably right about that (that explains why is random, just on launching). I will, but it's probably out of the scope of the emulator.. or you think you could create some delays in between?? I will give you the dump if needed. but for now it doesn't disallow me to use it :)

**Comment by bearoso** [comment]
Ok, I added a couple commits to ensure init is structured properly. Give that a try and see if you get any crashes. If you have any crash dumps, they'll be helpful.

**Comment by bearoso** [comment]
I think I found the problem. The preferences window was being threaded to initialize and Gtk doesn't like multiple threads using it. That should take care of it. Also found a problem where the GLX driver was using an uninitialized value.

**Comment by Askmewho** [comment]
I will recheck later on. so far the performance was great! https://youtu.be/6br6dsp3oY4 check at the end.. for an arm sbc eight from the desktop (they usually don't are that friendly with x11)

**Comment by unassumingbadger** [comment]
This fixed the issue on my end. Thanks!

**Comment by Askmewho** [comment]
ok, we close for now. if I continue experiencing the issue I will just reopen! amazing emulator!!!
