### ISSUE TITLE
Unix version only supports OSS?

### ISSUE THREAD

**Issue by Zapeth** [snes9xgit/snes9x#68]
The Gtk version supports several different sound systems, the most important for me being ALSA, so why is there only one implementation for sound device loading/playing in the unix version?

Not to mention that error feedback for sound initialization is next to non-existent, since I don't have /dev/dsp on my system it would just silently fail to initialize the sound system resulting in having no sound at all.

Not knowing initially what the problem was I tried around a little bit with some settings in the config file and the -sounddev parameter but since I also didn't know what exactly I had to pass as a string (the absolute path to the sound device file), any attempts there were fruitless as well

After wasting my time with that I finally decided to dig into the source to see what the problem really was, only to find out that ALSA wasn't even supported.

**Comment by sergiobenrocha2** [comment]
OSS seems to be broken, in GTK too. Funny is that OSS appears as an option, even if you don't install oss4-dev.

**Comment by ivasim** [comment]
That's probably the reason why I don't have sound output in latest snes9x 1.53 on my Debian Jessie. I also tried some tricks using config file but without success. Available outputs on Jessie are PulseAudio, ALSA and SDL.

**Comment by sergiobenrocha2** [comment]
And PortAudio too.

OSS seems to not work on ubuntu based distros, it's disabled in kernel:

"Canonical/Ubuntu has chosen to disable OSS support in their kernels and ignore any bugs filed against OSS4 packages."

https://help.ubuntu.com/community/OpenSound

I'm trying to get it work on debian, but no success.

**Comment by ivasim** [comment]
As far as I know, OSS is considered deprecated by the linux kernel authors so preference should be given to more popular implementations.

**Comment by sergiobenrocha2** [comment]
Seems you need to build the OSS kernel module, to get it work:

http://forums.debian.net/viewtopic.php?f=16&t=52919

Let's see if it works

**Comment by sergiobenrocha2** [comment]
ugh, you need to mess with system config and purge Alsa... no way.

**Comment by ivasim** [comment]
Yeah, that's too much indeed. I appreciate your efforts.

**Comment by Zapeth** [comment]
Wow, I didn't expect answers to this...

Anyway since the unix version seems to be non-active at the moment (as well as the other versions?) I decided to add the support myself -> https://gist.github.com/Zapeth/433d92c69b9ba84a6964

Somebody feel free to push it to the repository but I'd very much recommend that someone with autoconf/snes9x/alsa experience double checks the changes.

Obviously you'll need to rerun autoconf to update the configure script, I didn't want to include mine because otherwise the patch would explode in size (I wonder if its actually a good idea to keep the configure script in the tracked files?).

As for the actual changes, I basically used the alsa code in the gtk version as a template and it seems to work (both compilation and the feature itself), however I didn't try the various sound settings to verify it so feel free to do that as well.

**Comment by rhelmot** [comment]
I can confirm that the above patch works perfectly for me, just applying it, running `autoconf`, and reconfiguring/rebuilding.

**Comment by vgturtle127** [comment]
When you guys say Unix, you mean any OS that is not Windows or Mac, right?

**Comment by keithbowes** [comment]
On Linux, using padsp works well for me:
$ padsp snes9x <file>

**Comment by terranigma** [comment]
Anyone knows where can I find the alsa support patch above? The link is dead and Google doesn't help me either.

I prefer gui-less versions of emulators and the idea of separation of gtk and stand-alone (unix) binaries a bit unusual. Gtk is just a window decoration tool kit and has nothing to do with emulation process. Gtk application should have been implemented as a fronted/launcher for the stand-alone binary... just like fs-uae, mame and many others.

**Comment by Zapeth** [comment]
I'm afraid I don't have the patch file anymore (which I linked to back then), but I guess it would be a bit tedious to apply now anyway due to changes in some of the files.

Luckily I still have the original files, but considering this was a relatively hacky solution to begin with (in the context of maintaining two identical implementations in one code base) I have no intentions of doing a PR for this -> https://filebin.net/rsgw219y7h1fw34z

**Comment by terranigma** [comment]
Thanks for patch. I just applied the patch and it works fine on current (1.55) version. I re-formatted the patch in order to use without configure script and added required definitions in Makefile.in file.

I uploaded the patch to the link you have given above: 
https://filebin.net/rsgw219y7h1fw34z

Now I have to find the cause of dreadful slow and laggy graphics performance of unix version.

**Comment by jb567** [comment]
@tanertas if you still have a copy of it, I'd love the patch file

**Comment by rhelmot** [comment]
I'm surprised every single link in this thread has gone dead. Here's the patch copied from my fork, uploaded to github. 
[0001-Zapeth-s-changes-to-support-ALSA.patch.gz](https://github.com/snes9xgit/snes9x/files/2178034/0001-Zapeth-s-changes-to-support-ALSA.patch.gz)

**Comment by Zapeth** [comment]
It appears ALSA support for the unix code parts has been added at some point in the last few months, so closing this
