### ISSUE TITLE
how to add additional flags to compilation (libretro)

### ISSUE THREAD

**Issue by Xephobia** [snes9xgit/snes9x#683]
Hi, I'm trying to compile with mingw-w64 (msys2, please stop telling me to use the windows toolchain) and I'm trying to add the flags "-O3 -pipe -march=native -mtune=native" everything goes fine until make tries to paste those flags into the cc executable, it fails because those flags are for gcc and g++... how could I fix this?

**Comment by bearoso** [comment]
What error are you getting. msys _is_ gcc/g++, so those flags should work.

**Comment by Xephobia** [comment]
Never mind, I have forgotten to close the issue... anyway, I need to do `make CFLAGS+='desiredcflags' CXXFLAGS+='desiredcxxflags'` this will build and append those flags without overriding them, thus not creating any errors.
