### ISSUE TITLE
Snes9x gamepads hotkeys bug.

### ISSUE THREAD

**Issue by edsonfeimberg** [snes9xgit/snes9x#684]
I can't map hotkeys to my gamepad since snes9x has a bug that prevents hotkeys to be mapped to controllers that aren't (j0). Is there any workaround for this bug at the moment? I wish i could close snes9x from my gamepad to enhance the couch game experience. My xbox controller is always detected as (j2). Any way i could make it (J0)?

**Comment by OV2** [comment]
I just tried binding the "Quit" hotkey to (J1), and it works without issues.

**Comment by edsonfeimberg** [comment]
It worked. It only works when the emulator is running a game. Thank you, @OV2

**Comment by OV2** [comment]
I'll take a look at that problem.
