### ISSUE TITLE
How to adapt Snes9x cheat files (.cht) for bsnes?

### ISSUE THREAD

**Issue by ElektroStudios** [snes9xgit/snes9x#685]
Hi. Years ago I managed to collect .cht files for my collection of roms to use them with **Snes9x**, I don't remember the format (GameGenie or ProActionReplay) of the cheats inside .cht files. The thing is that now I would like to know what options I have in order to convert / transform these cheat files into something that the **bsnes** emulator can understand.

This is a **Snes9x** .cht sample file for **ActRaiser** rom: https://mirrorace.org/m/3IAyN - as you can notice, the content is encoded some way.

Unfortunately **bsnes** does not support the encoded format used by **Snes9x**. **bsnes** accepts **ProAction Replay** and **Game Genie** cheats, it stores the cheats in a _non-encoded_ text-plain .cht file in the format:
```
cheat
  name: infinite lives
  code: aaaaaa=dd
```

I would like to understand how to read / decode the **Snes9x** .cht format to develop a personal conversion tool... if there is no easier solution to do this.

Thanks in advance.

**Comment by OV2** [comment]
Since version 1.56 snes9x also uses the bsnes format. If you load your cht file in a newer version of snes9x (by loading a rom with the corresponding name) it will automatically be converted into the bsnes format.

**Comment by ElektroStudios** [comment]
Oh, I see!, it is converted at program exit. Nice to know. This totally solves my problem!

I didn't noticed it before because I automate the emulator start / rom loading and .cht file copy using a script from other directory.

Thanks a lot.
