### ISSUE TITLE
A bit incorrect and/or inconsistent name spelling in the UI

### ISSUE THREAD

**Issue by GeneralFailer** [snes9xgit/snes9x#69]
Apparently this non-technical issue has existed since at least v1.40, but this must be brought up at some point IMO.
Basically, everywhere in the interface except for the title of the About window, the emulator's name is spelt as Snes9X (with a capital X). This bugs me a little as as far as I can see traditionally it's usually referred to as Snes9x, even on the official resources (blog, changelogs, license, forum interface, logo, hell even the GitHub summary). There are a few exceptions like the website disclamer and page titles though. This way it's a bit of a moot point which of the spellings is official, especially considering Snes9X is technically a little more sensible name for a successor of Snes96 and Snes97. All in all, I think it is a good idea for Snes9x team to consider choosing the official spelling before the next major release.

**Comment by GeneralFailer** [comment]
Now that I've thought to look it up in the dictionary, it turns out the lower-case x is actually somewhat more appropriate to be a placeholder for a digit, so disregard that point. I don't know why I even came to think otherwise.

**Comment by GeneralFailer** [comment]
Sorry, is there a misunderstanding about my previous comment? What I implied in it is that there's really next to no reason to not correct the UI so that it spells minuscule 'x'.

**Comment by OV2** [comment]
Sorry, I glanced over this too fast.
Snes9X is used mostly in the windows port (a relic of the early days). I'll do a search/replace for the next build.
