### ISSUE TITLE
Support for Apple M1 chip?  (re: has anybody been able to compile a native version?)

### ISSUE THREAD

**Issue by sofakng** [snes9xgit/snes9x#690]
Are there any efforts to port this to the Apple M1 chip?

It looks like there are ARM ports of Snes9x so I'm hoping it wouldn't be too difficult to compile a native version for better optimizations, etc?

**Comment by MichaelBuckley** [comment]
The latest build from https://github.com/snes9xgit/snes9x/issues/586 is M1 Native.

https://github.com/snes9xgit/snes9x/files/5184967/Snes9x.app.zip
