### ISSUE TITLE
[SNES Hack] Mother 2 Deluxe

### ISSUE THREAD

**Issue by breaktube** [snes9xgit/snes9x#691]
Unable to run, version 2.00 Mother 2 Deluxe, the hack of Earthbound (USA). 
It is a 6MB game similar to Star Ocean [SNES] 
When you open the ROM, you get a black screen. 
Tried to run the game on build "snes9x-1.60-971-cc7e028-win32" and every build back to version 1.57. 
Seems to run with out issue on other SNES emulators 
And would like the development team to take a look at this issue to increase the compatibility of this emulator. 
Hope you all continue to stay healthy while you do.

**Comment by bearoso** [comment]
Works now in a146093e.  Emulators have to guess what the ROM layout is, and this hack doesn't match any official game's mapping.
