### ISSUE TITLE
FTBFS with gcc-11

### ISSUE THREAD

**Issue by musuruan** [snes9xgit/snes9x#698]
snes9x 1.60 cannot be compiled with gcc-11. Tested on Fedora 34.

Please see the following build log:
https://koji.rpmfusion.org/kojifiles/work/tasks/2449/462449/build.log

**Comment by OV2** [comment]
I tried it with gcc-11 on ubuntu 21.04, where it compiled without problems (11.0.1 20210306 (experimental))

**Comment by bearoso** [comment]
gcc 11 isn't released. conffile.cpp hasn't changed for a *long* time. I'd say to file a regression report with gcc, but based on OV2's comment, it looks like it's fixed (you're using a build from January, his is from a few days ago).

**Comment by musuruan** [comment]
I finally had the chance to try gcc 11.0.1 on Fedora, but I got the same issues.

I had a successful build by adding "-std=gnu++14" to CFLAGS and CXXFLAGS though.
https://koji.rpmfusion.org/kojifiles/work/tasks/368/480368/build.log

**Comment by bearoso** [comment]
gcc 11 final *still* isn't released. gcc 11.1 is the actual final build number. I'm not going to try to fix it until that releases.

That said, I think it's probably the Red Hat additions causing trouble. Also, the Gtk build completes fine in your build log, so the lack of a "-std" parameter in the unix build could be hitting broken c++11 header code. Try "-std=c++03" and see if that works.

**Comment by musuruan** [comment]
Sorry for the late reply but time is always short.

I've dug a bit more about this issue (please note that I'm not fond of C++).

In the "Porting to GCC 11" guide, in section "Comparison Functions" I read: "GCC 11 now enforces that comparison objects be invocable as const. ".
https://gcc.gnu.org/gcc-11/porting_to.html

More details:
https://cplusplus.github.io/LWG/issue2542

This seems to be the exact issue I faced before adding "-std=gnu++14" to CFLAGS and CXXFLAGS.

**Comment by bearoso** [comment]
So this was fixed in git last year: 7f6d9d6432d912cd90763c64f7c92270b3e6c182. 
OV2 and I were using the latest version and not 1.60.

But if you're going to package the old version, adding the -std parameter is the correct fix. For the unix port it should probably gnu++03 instead.
