### ISSUE TITLE
Bug with Sound - Win7 x64 - Realtek Sound Card - Far East of Eden Zero - Snes9x 1.60

### ISSUE THREAD

**Issue by Felipefpl** [snes9xgit/snes9x#700]
This doesnt happen all the time, only once in a while.

Sometimes the sound becomes louder for no reason while playing, to solve this i must move the slider to other value, click ok and then make the slider go back to where it was before. Attached a pic of my config.

![Sound louder](https://user-images.githubusercontent.com/5569804/114626537-3e535280-9c8a-11eb-9a15-483ff51d26cf.gif)

**Comment by bearoso** [comment]
That's probably some kind of automatic volume leveling in the driver. It's detecting that Snes9x is outputting at a very low level and is amplifying it. I suggest increasing the volume slider back to 100%. The SNES volume doesn't normally exceed 50% of the potential amplitude, so it'll be quieter at 100% than other applications. Also, change the playback rate to 48KHz. Windows can't use 32KHz directly any more, so doing this avoids an extra resampling step.

If you **must** lower the volume level for Snes9x alone, do so using the volume mixer in Windows (Right-click the volume icon in the task bar tray and select "Volume Mixer").

**Comment by OV2** [comment]
Might be related to #603 - did you try with a recent nightly build?

**Comment by bearoso** [comment]
That sounds more likely than my theory. I still think it's better to rely on Windows to do the mixing, though.

**Comment by Felipefpl** [comment]
bearoso - thanks for the reply and for the info about how to deal with this, although i find it strange that i never met this bug with other snes emus.

OV2 - never tried a nightly from snes9x iirc. Thanks for the reply too.

Btw, i dont wanna create a new thread just for this question, is it possible to include ALL shaders in the compressed file of the emulator? It doesnt make sense to have a separate package just for them.

**Comment by bearoso** [comment]
Even if we got permission to distribute them, it's best to keep the shaders separate so people recognize that they were created and are maintained by other people.

**Comment by Felipefpl** [comment]
> Even if we got permission to distribute them, it's best to keep the shaders separate so people recognize that they were created and are maintained by other people.

I see, i had no idea you needed permission. :/ - I dont know if i agree with separate packages since this info about being created by others could come in the readme but thanks for the infos.

**Comment by Felipefpl** [comment]
Just add this one for the record since perhaps it can be useful, i got the same problem once (close to the end of the game) but in opposite side, the volume got lower and only it was fixed doing the same procedure above.
