### ISSUE TITLE
Filters Not Applied in Rudra No Hihou (translated) - Snes9x 1.60

### ISSUE THREAD

**Issue by Felipefpl** [snes9xgit/snes9x#702]
When you start the game the info showed below doenst use the filter (hq4x here but any filter wont do anything and Scale Messages with EPX is enabled) but this works on zsnes. STRANGELY the rest of the text in the dialog boxes IN-GAME seems to have the filters partially applied on both emulators and they dont look too good (also using hq4x on zsnes). Images below show what i meant above.

![No filter](https://user-images.githubusercontent.com/5569804/116315497-00c0f000-a787-11eb-9a5e-b800c1897601.gif)
![Zsnes](https://user-images.githubusercontent.com/5569804/116315506-03bbe080-a787-11eb-81ef-eeedacc88924.gif)

Also, the fonts used by zsnes have the same size which make the whole text look good.

**Comment by OV2** [comment]
Snes9x messages are only scaled with epx if you are using a filter with a 2x or 3x scale.

**Comment by bearoso** [comment]
This game one of a unique few that uses a combo of high resolution and low resolution lines in the same frame. No filter is going to work well for that.
