### ISSUE TITLE
blarggs RF filter broken tested 1.60 and all following builds.

### ISSUE THREAD

**Issue by Eggo-dotcom** [snes9xgit/snes9x#704]
blarggs RF filter broken tested 1.60 and all following builds.

dont know what else to say other than broken,

Tested on multiple windows 10 machines.

Just the rf one is broken.

**Comment by bearoso** [comment]
There was a bug report posted that complained it didn't look as dot-crawly as it did in Mesen. I looked at Mesen and it was doing it that way, so I changed it. Now that I think about it, it probably is supposed to just toggle and Mesen was wrong.
