### ISSUE TITLE
-port1 commandline parameter not working

### ISSUE THREAD

**Issue by Nition** [snes9xgit/snes9x#705]
Starting with `-port2 mouse1` as a commandline parameter starts as expected with input settings for a mouse in port 2.
Starting with `-port1 mouse1` starts with joypad. Expected mouse in port 1.

Port1 setting seems to be ignored.

**Comment by OV2** [comment]
I'm guessing you are talking about the windows port.

The parameters are interpreted correctly, but the windows port does not allow for all combinations. With `-port1 mouse1` you are trying to start with only a mouse in port1, and nothing in port2. But the windows port requires a controller in port2 if you want mouse1 in port1. If you use `-port1 mouse1 -port2 pad1` it should work.

**Comment by Nition** [comment]
Thanks! You're right, I was actually just coming back to post the same thing after working it out from the source. Should have just checked back here and saved some time. :)

Here's my little investigation since I've done it now anyway:

`WinParseCommandLineAndLoadConfigFile` loads the commandline config.
If using `-port2 mouse1` (the working configuration), the settings are now `controller[0]: JOYPAD`, `controller[1]: MOUSE`
If using `-port1 mouse1` (the failing configuration), the settings are now `controller[0]: MOUSE`, `controller[1]: NONE`

`ControllerOptionsFromControllers` then runs the following code:
` 
if (controller[0] == CTL_JOYPAD && controller[1] == CTL_MP5)
  GUI.ControllerOption = SNES_MULTIPLAYER5;
else if (controller[0] == CTL_MP5 && controller[1] == CTL_MP5)
  GUI.ControllerOption = SNES_MULTIPLAYER8;
else if (controller[0] == CTL_MOUSE && controller[1] == CTL_JOYPAD)
  GUI.ControllerOption = SNES_MOUSE;
else if (controller[0] == CTL_JOYPAD && controller[1] == CTL_MOUSE)
  GUI.ControllerOption = SNES_MOUSE_SWAPPED;
else if (controller[0] == CTL_JOYPAD && controller[1] == CTL_SUPERSCOPE)
  GUI.ControllerOption = SNES_SUPERSCOPE;
else if (controller[0] == CTL_JOYPAD && controller[1] == CTL_JUSTIFIER && !ids[0])
  GUI.ControllerOption = SNES_JUSTIFIER;
else if (controller[0] == CTL_JOYPAD && controller[1] == CTL_JUSTIFIER && ids[0])
  GUI.ControllerOption = SNES_JUSTIFIER_2;
else if (controller[0] == CTL_JOYPAD && controller[1] == CTL_MACSRIFLE)
  GUI.ControllerOption = SNES_MACSRIFLE;
else if (controller[0] == CTL_JOYPAD)
  GUI.ControllerOption = SNES_JOYPAD;
`

In the JOYPAD + MOUSE case, SNES_MOUSE_SWAPPED is selected.
But in the case for a mouse in port one it's looking for MOUSE + JOYPAD, not MOUSE + NONE, so it falls back to just selecting JOYPAD.

From looking at that I tried `-port1 mouse1 -port2 pad1` exactly as you've suggested and it worked.

I see you're a programmer on Snes9x yourself so you probably know all this already. Thanks for your work!
