### ISSUE TITLE
SNES9X menubar does not scale with my resolution on Ubuntu 20.04

### ISSUE THREAD

**Issue by BigChubbsXD** [snes9xgit/snes9x#721]
My current resolution on Ubuntu 20.04 is 4K, and my menubar in SNES9X is ridiculously small.

![image](https://user-images.githubusercontent.com/90588476/133016869-b8ba8135-ba97-44d1-8a8f-94a6ea06bb34.png)

**Comment by bearoso** [comment]
That's because you're running the windows version through Wine. Either tweak the DPI with winecfg or run the Gtk version.

**Comment by BigChubbsXD** [comment]
Ok thanks!
