### ISSUE TITLE
"Prevent the screensaver from activating" doesn't work on Wayland

### ISSUE THREAD

**Issue by SuperSamus** [snes9xgit/snes9x#723]
OS: NixOS 21.11;
Snes9x version: 1.60-gtk;
Window manager: Sway;

On a Wayland session, if someone is playing with a gamepad pressing its buttons doesn't reset the idle timer, forcing the user to do something with the mouse/keyboard to reset it.

**Comment by bearoso** [comment]
Added for Wayland in f56b1e7. You'll need to close and reopen Snes9x after changing the "Prevent the screensaver ffrom activating" setting, though.
