### ISSUE TITLE
There's a current bug for blargg ntsc filters at least in Donkey kong games for me

### ISSUE THREAD

**Issue by nad53** [snes9xgit/snes9x#724]
Hello there. I have seen very recently those bugs that seem to show up the moment I want to play Donkey kong country 1 or 2.

This bug only shows up to me at the very early logo screen from Nintendo. At least when the first level starts, this doesn't seem to happen. 
I use a 1600 x 900 monitor.  Either using blargg ntsc filters on core options from RetroArch or video filters section setting up any of blargg's video filters like RF, s-video, composite or RGB.

https://imgur.com/a/ga5iD9R

Last picture is from blargg composite video filter which shows a double image even more weird than the 2 previous which are exposed only by using blargg's ntsc video filter in core options.

I just downloaded the last snes9x - current core version and it's what happens, so it's not outdated.

I'd like to report this as a bug or if you know how to fix it, I'd appreciate it.

**Comment by bearoso** [comment]
Fixed by a4efafb.
