### ISSUE TITLE
Where can I download the latest nightly build, all artifacts are expired/deleted...

### ISSUE THREAD

**Issue by ImSpecial** [snes9xgit/snes9x#725]
I was hoping to grab a new build that has fixed this issue. https://github.com/snes9xgit/snes9x/issues/691

But it seems they are all expired at this point, R.I.P. me I guess.

Is there another place they can be downloaded?

**Comment by OV2** [comment]
I've uploaded a build of the latest commit here: http://s9x-w32.de/dl/testbuilds/

**Comment by ImSpecial** [comment]
Thank you OV2!
