### ISSUE TITLE
MacOS uncompatibily with 32bit

### ISSUE THREAD

**Issue by omerien** [snes9xgit/snes9x#726]
Hello. Since MacOS 10.15, the 32bit apps aren't compatible with MacOS and aren't runnable. Can you make the app 64bit, so it's runnable on MacOS 10.15, 11 and 12 ?

**Comment by MichaelBuckley** [comment]
This is a duplicate of https://github.com/snes9xgit/snes9x/issues/586

If you scroll down to the bottom of that issue, the latest post has a link to a development build that was rewritten in Cocoa. Features are still being added back in.
