### ISSUE TITLE
Chrono Trigger: Crimson Echoes glitch

### ISSUE THREAD

**Issue by mscofield0** [snes9xgit/snes9x#729]
A glitch occurs in Crimson Echoes after Porre's invasion of Guardia when you need to meet with the time-travelling reptite in the Epoch room. When you enter the Epoch room, a cutscene begins, a few dialogue boxes play out and then a freeze occurs. 

![image](https://user-images.githubusercontent.com/69715407/146826566-f28006a0-8474-4965-a5ae-fc15f48f78c0.png)

Pressing start does not work, moving around doesn't work, waiting doesn't fix it, etc.

**Comment by bearoso** [comment]
That particular hack was created with a particular version of zsnes and relies on its specific broken timing. It would be an astronomical effort to find all the things the hack does wrong so as not to break. The hack author says to only use zsnes, so that's your only recourse.

**Comment by mscofield0** [comment]
Do you happen to know how to transfer ROM save files to Zsnes, @bearoso? I've tried putting the ROM and the SRM file in the same directory as the zsnes executable, but it doesn't load it with the save.

**Comment by bearoso** [comment]
In zsnes, go to Config->Paths in the menu. Make sure the Saves entry is blank, and click the box that says "rom dir" on the bottom. I think that should work.
