### ISSUE TITLE
Possible license violation:

### ISSUE THREAD

**Issue by Hydro5** [snes9xgit/snes9x#73]
https://itunes.apple.com/app/id982939500

This guy is selling Snes9x, GenplusGX and other emulators plus some indie ("homebrew") games on the Apple store. It is said to be RetroArch iOS with Snes9x, GenplusGX and other cores. I believe Snes9x and Genplus GX have non-commercial clauses preventing their use in commercial products correct?

The Content Dispute Form is here:

http://www.apple.com/legal/internet-services/itunes/appstorenotices/

Also posted: 
https://github.com/libretro/snes9x/issues/12
https://github.com/libretro/Genesis-Plus-GX/issues/22

**Comment by twinaphex** [comment]
I would really implore you guys, @BearOso and/or @OV2, to start taking this seriously and to start counterreacting against this. Fill in the iTunes Content Dispute Form, that should be enough.

The last time something like this happened with Retron5, to the best of my knowledge there was no  response by SNES9xdev as a whole at all and OV2 just left our channel and never came back again. I wonder why that only happened after we asked him what he was going to do about it, his reply at the time was that he was going to contact Gary and/or Jeremy Koot and see what to do about it.

Your non-commercial license is not worth the TXT file it's written in if you don't at least uphold it and exercise it. You should make a firm stand to clamp down on this kind of abuse.

**Comment by Red-Chaos1** [comment]
I spoke with Jerremy via PM on the forums about this, his response was basically that he couldn't be bothered.

**Comment by twinaphex** [comment]
What about any others then?

Jerremy is no longer relevant to SNES9x anyway. If he doesn't care or can't be bothered, I'm sure there should be enough other people still involved with SNES9x to act instead.

**Comment by Hydro5** [comment]
@twinaphex

I am not certain how ownership works in open source projects or with he license that Snes9x has. I know with GPL, that it takes every single one of the contributors to sign off on a chance of license, which seems to imply that they are all equal owners. Since this appears to be the libretro-snes9x, then I think that twinaphex or anyone who contributed to snes9x-libretro has a justifiable right to file the content dispute claim with the Apple store. I apologize if that is not correct. So I suggest that twinaphex himself files a claim. 

Once Apple realizes it's emulators, regardless of any of the license dispute, they will take it down. Just a simple "oh by the way this is emulators not just indie games" to Apple will do. The Content Dispute form is probably just the quickest way for them to realize this.

**Comment by Red-Chaos1** [comment]
If it only takes one person making a complaint, then by all means. Jerremy is the sole remaining original author of Snes9x, Gary hasn't been around in a long long time. Many of the others who've contributed have long since disappeared as well. I'm not trying to say it's a hopeless endeavor, I wanted to fight it as well, but it seems an uphill battle. I am merely someone who has been around since ~1.2x, and have been moderator/admin of the forums for over 10 years, not a lick of code has been submitted by myself.

**Comment by Hydro5** [comment]
The link now redirects, so I guess that means that it has been taken down. Good work guys.

**Comment by OV2** [comment]
My disappearance has more to do with me having almost no free time at the moment, and thus not having been on irc in any way. I will definitely be back (and finally get to the almost one year old libretro merge request...).

As for license violations: keep bringing them to our attention. I can't promise we will get into any legal action, but we will at least contact them or the platform they are using for distribution.
