### ISSUE TITLE
Where is save state options in menu for macOS ?

### ISSUE THREAD

**Issue by spotanjo3** [snes9xgit/snes9x#731]
I am using SNES9X 1.60 but there is no option for save states. @_@

**Comment by MichaelBuckley** [comment]
@spotanjo3  The freeze and defrost keys can be configured in the controls preferences. By default on the keyboard, they are 1 for freeze and 0 for defrost. These are the keys above the letters, not on the numpad. You can re-assign them in the preferences, and you can also assign them to gamepad buttons if you'd like.

**Comment by spotanjo3** [comment]
I found it but the problem is that I put my old frz files and same title as ones rom's title. And run SNES9X game and press 0 to defrost it and I got an empty in each box. I put my old frz files in freezes folder. I dont understand. My old frz files was from older version of SNES9X version. I upgrade to 1.60 now.

**Comment by MichaelBuckley** [comment]
Unfortunately, the freeze format changed between 1.5 and 1.6, and there isn't a build of 1.5 that works on macOS Catalina or later. There is no way to get frz files from 1.5.x to work with 1.6.

I haven't tried it myself, and I'm not exactly sure how it could be done, but one option might be to manually install an Snes9x 1.5.7 core into OpenEmu or RetroArch.

**Comment by spotanjo3** [comment]
Which one works for Big Slur ? I tried older version and it shown slash on icon.

**Comment by spotanjo3** [comment]
I have an idea. I can used them on Windows then run the save state game then playing until game is automatically save the .. file.srm will appear then transfer here.
