### ISSUE TITLE
Release 1.61.

### ISSUE THREAD

**Issue by ghost** [snes9xgit/snes9x#732]
Why no new release? Many fixes since the .

just a thought.

**Comment by Eggo-dotcom** [comment]
Abandoned? I hope not

**Comment by bearoso** [comment]
No, just haven't got around to it.

**Comment by OV2** [comment]
There hasn't been much time to work on anything, and no really pressing issues. That said, I guess we could try to package the current state, since the auto-builds are not kept around forever.

**Comment by MichaelBuckley** [comment]
If you do put together a release, I've been signing the macOS prerelease builds with my personal Developer ID certificate, and I'd be happy to do so for an official release as well. Signing macOS apps is required for users to easily launch the app without getting warning dialogs that the software might be insecure. The signing certificates cost $99/year.

**Comment by Eggo-dotcom** [comment]
Thanks for the reply guys. I only asked cause the dev builds are expired and there were a few nice fixes. But I understand busy.

**Comment by bearoso** [comment]
Ok, I changed all the copyrights and wrote up a changelog of things that were most interesting. Please look it over and wrap up any loose ends.

**Comment by OV2** [comment]
Do you have a setup to verify #727 ?
I've added a few remaining win32 changes.

**Comment by bearoso** [comment]
I tested #727 and it the alsa support and i420 support works. I adjusted it to favor the better formats if they're available, though.

**Comment by bearoso** [comment]
Is that everything? If so, I'll package up the release.

**Comment by Eggo-dotcom** [comment]
the release will include this fix (that worked too right) https://github.com/snes9xgit/snes9x/issues/704

**Comment by OV2** [comment]
Nothing else on my end.
@MichaelBuckley  can you then build a macOS version that we can put in the release section?

**Comment by MichaelBuckley** [comment]
Certainly! Here's a build. I unfortuantely wasn't able to get cheat entry/finder finished for this release. Hopefully next build.

[Snes9x.app.zip](https://github.com/snes9xgit/snes9x/files/7989382/Snes9x.app.zip)

**Comment by OV2** [comment]
We can also wait a few weeks if you'd like to get that in, no problem there. But we can also simply release and you can work on it as you see fit, then do another release with it in.

**Comment by MichaelBuckley** [comment]
If it's not too much trouble to delay a release, I can at least get cheat entry in a good state within the next few days, and probably punt the cheat finder to a later release.

**Comment by bearoso** [comment]
Fine by me.

**Comment by Felipefpl** [comment]
Before the release of 1.61 i need to ask this: Werent the hq/xbrz or any of the other filters updated/optimized by the original devs or by someone else? It would be good to have them added to snes9x in case they are out there. 👍

**Comment by MichaelBuckley** [comment]
Here's a Mac build with cheat entry. I think it's good to go for a 1.61, but I'm happy to do more builds if we need to take more changes before 1.61.

[Snes9x.app.zip](https://github.com/snes9xgit/snes9x/files/8011404/Snes9x.app.zip)

**Comment by loganmc10** [comment]
I'd also like to put a +1 for a new release. I like to get stuff off of Flathub, but the apps on there generally only follow released versions (not nightly builds). I have a flatpak manifest ready to go for 1.61, just waiting for it to be released so I can update flathub.

**Comment by bearoso** [comment]
Should I just go ahead and tag a release now?

**Comment by thanuci** [comment]
Please, guys.
I have been waiting for a release for os Catalina, which is not recognizing my gamepad 🥺.
Hardly ever it does, actually.

**Comment by bearoso** [comment]
Ok, I tagged it, wrote a short synopsis, and added the binaries. Feel free to change anything wrong.

**Comment by keithbowes** [comment]
It's unfortunate that input bitmasks weren't backported from the libretro fork, but 1.61 has a very important fix for RetroArch:  it works with GLES enabled.
