### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by StanleyKid-22** [snes9xgit/snes9x#743]
Greetings.
I have the Ukrainian translation for SNES 9X. Is it possible to add to the project? Thanks in advance.
[uk.zip](https://github.com/snes9xgit/snes9x/files/8163275/uk.zip)

**Comment by bearoso** [comment]
Added in in 1041ff3.

**Comment by StanleyKid-22** [comment]
I've just read the topic #459, and understood that the translation won't work on Windows, even with the Ukrainian-lang format of regional standards.
But... is MO-multilang support possible for Windows in future? 'Cause it turns out that I was doing the translation in vain for that system.
