### ISSUE TITLE
snes9x-gtk appears to throw GTK3 errors on Ubuntu Vivid

### ISSUE THREAD

**Issue by ckaye89** [snes9xgit/snes9x#75]
$ ./snes9x-gtk --help

(snes9x-gtk:27848): Gtk-CRITICAL **: gtk_widget_set_double_buffered: assertion 'GTK_IS_WIDGET (widget)' failed

(snes9x-gtk:27848): Gtk-CRITICAL **: gtk_widget_realize: assertion 'GTK_IS_WIDGET (widget)' failed

(snes9x-gtk:27848): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(snes9x-gtk:27848): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(snes9x-gtk:27848): Gtk-CRITICAL **: gtk_widget_get_allocation: assertion 'GTK_IS_WIDGET (widget)' failed

(snes9x-gtk:27848): GdkPixbuf-CRITICAL **: gdk_pixbuf_new_from_data: assertion 'width > 0' failed
Sound buffer size: 4096 (1024 samples)
OSS sound driver initializing...
    --> (Device: /dev/dsp)...failed

(snes9x-gtk:27848): Gtk-CRITICAL **: gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed

(snes9x-gtk:27848): Gtk-CRITICAL **: gtk_widget_get_window: assertion 'GTK_IS_WIDGET (widget)' failed

(snes9x-gtk:27848): Gdk-CRITICAL **: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed

(snes9x-gtk:27848): Gtk-CRITICAL **: gtk_statusbar_get_context_id: assertion 'GTK_IS_STATUSBAR (statusbar)' failed

(snes9x-gtk:27848): Gtk-CRITICAL **: gtk_statusbar_pop: assertion 'GTK_IS_STATUSBAR (statusbar)' failed

(snes9x-gtk:27848): Gtk-CRITICAL **: gtk_statusbar_get_context_id: assertion 'GTK_IS_STATUSBAR (statusbar)' failed

(snes9x-gtk:27848): Gtk-CRITICAL **: gtk_statusbar_push: assertion 'GTK_IS_STATUSBAR (statusbar)' failed

(snes9x-gtk:27848): Gtk-CRITICAL **: gtk_statusbar_get_context_id: assertion 'GTK_IS_STATUSBAR (statusbar)' failed

(snes9x-gtk:27848): Gtk-CRITICAL **: gtk_statusbar_pop: assertion 'GTK_IS_STATUSBAR (statusbar)' failed

(snes9x-gtk:27848): Gtk-CRITICAL **: gtk_statusbar_get_context_id: assertion 'GTK_IS_STATUSBAR (statusbar)' failed

(snes9x-gtk:27848): Gtk-CRITICAL **: gtk_statusbar_push: assertion 'GTK_IS_STATUSBAR (statusbar)' failed
^C
(snes9x-gtk:27848): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

**Comment by ckaye89** [comment]
It works with gtk2, which doesn't ship by default.

**Comment by sergiobenrocha2** [comment]
I'm getting the same problem on Debian 8.

**Comment by vgturtle127** [comment]
#76 Can we close these and add a note about GTK version info into the docs and Wiki?

**Comment by BearOso** [comment]
Yes, this is the same as issue 76. Though it's newer, #76 has more info in it. I'm closing this one.
