### ISSUE TITLE
Game Boy Games Support PLS

### ISSUE THREAD

**Issue by CraftFan22** [snes9xgit/snes9x#759]
Please Add Support For Game Boy Games **(with .gb & .gbc File Extension)**. Add **SGB ROM BIOS** In **System Options** To Game Boy Games Require A **Super Game Boy or Super Game Boy 2 (.sfc File Extension)**. When If You Play Game Boy Games On **SNES**, It Will Show A **Super Game Boy Borders**. The Super Game Boy Menu Is **L+R**.

**Comment by bearoso** [comment]
Duplicate of #758.

**Comment by CraftFan22** [comment]
**Watch How To Emulate Super Game Boy On SNES Emulator** https://youtu.be/Z_vgTpDKK3Y
