### ISSUE TITLE
Directories for SRAMs, Saves, etc. seems to be ignored

### ISSUE THREAD

**Issue by Gnatzelle** [snes9xgit/snes9x#766]
Hi guys / gals...

I think since this commit > https://github.com/snes9xgit/snes9x/commit/784667f5b29f015c024aae3e997e8200827c6b97
the settings for storing the SRAMs, Saves, Patches, etc. are getting ignored by Snes9x and everything is getting read/written from/to the location of the actual ROM. Already deleted the .conf file an created a new from scratch, problem remains the same.

System btw. is Arch Linux (up-to-date) with ext4 as FS.

It's not that kind of a big deal, but after getting back after a while to play some stuff i was quite irritated why my saves weren't "there" anymore ^^"

Thanks for looking into it if theres some time for it :)

**Comment by bearoso** [comment]
Fixed. It was actually replacing the last directory component with the filename. So you must've had your srams in a subdirectory of your rom directory.

**Comment by Gnatzelle** [comment]
Yeah that's right. "SNES"-Dir with Roms in this Folder but Subfolders for SRAM, Saves, etc.

Thanks for the quick fix :)
