### ISSUE TITLE
I wonder is there has a way to make color into 8x?

### ISSUE THREAD

**Issue by Yave-Yu** [snes9xgit/snes9x#767]
An option that just make 15-bit color multiply by 8 to modern RGB, such as 248 white... rather than stretching it to 255.

**Comment by bearoso** [comment]
Not much point. The SNES color output can't map to any modern spec directly. If it did it would require negative values and much more precision. The conversion done is appropriate for not artificially limiting the contrast, and assuming your screen is properly sRGB calibrated, limiting to 248 would mismatch the gamma curve and make it more inaccurate.

If you want to get the same effect, just lower your monitor white level to 97%.
