### ISSUE TITLE
snes9x 1.60 Problems with romance of the three kingdoms 2

### ISSUE THREAD

**Issue by chrcoluk** [snes9xgit/snes9x#768]
For comparison game works properly on snes9x 1.52.

On 1.60 after the main credit screen there is normally a logo which I think uses mode 7 graphics to zoom out, then the scenario selection screen.  On 1.60 both of these screens dont display and is sound only.  On 1.54 displays as normal.

Not sure how to proceed with debugging.

**Comment by chrcoluk** [comment]
found the issue not a bug

**Comment by bearoso** [comment]
If you found the issue, it's often helpful if you say what it was. I'm assuming overclocking.

**Comment by chrcoluk** [comment]
I know, I apologise I didnt post and sadly cant remember what it was now but it wasnt something like overclocking, it was probably something dumb I did though.
