### ISSUE TITLE
broken NON-SSE2 CPUs compatibility

### ISSUE THREAD

**Issue by MELERIX** [snes9xgit/snes9x#77]
since: https://github.com/snes9xgit/snes9x/commit/7aafcd0d67216084b703aed982b0dc08ea49c7a1

Snes9x crashes at start in PCs with NON-SSE2 CPUs such as: AMD Athlon XP or AMD Sempron (Socket A CPUs).

probably adding `<EnableEnhancedInstructionSet>NoExtensions</EnableEnhancedInstructionSet>` can solve the issue.

**Comment by vgturtle127** [comment]
I don't currently have any non-SSE2 CPU's unfortunately, but could somebody else try to reproduce the bug on newer builds?

**Comment by DaMan69** [comment]
Starting with VS2012 the default is /arch:SSE2.  Setting /arch:SSE would fix the OPs problem.  Only a masochist would use Snes9x 1.5x an Athlon Classic so arch:IA32 isn't necessary.

**Comment by MELERIX** [comment]
> Only a masochist would use Snes9x 1.5x an Athlon Classic

NON-SSE2 CPUs can run Snes9x without troubles, the trouble here is that since VS2013 implementation the compatibility is broken, anyway it can be solved, so there is no reason to don't preserve the backward compatibility with NON-SSE2 CPUs.

**Comment by vgturtle127** [comment]
What about VS2015?

**Comment by jcdenton2k** [comment]
That's the beauty of open-source.  Find a way to compile the source code with the modifications listed and see if it works :)
