### ISSUE TITLE
Add in Subsystems

### ISSUE THREAD

**Issue by Squidward22** [snes9xgit/snes9x#771]
add Load Super Game Boy (Current Content: Game Boy ROM), Load Super Game Boy (Current Content: Super Game Boy ROM)

It's bsnes Emulation Core LIKE

**Comment by qwertymodo** [comment]
This has been requested multiple times before, the answer remains the same. It would require adding an entire game boy emulator, which is a huge task that nobody is currently willing to undertake.

See:
https://github.com/snes9xgit/snes9x/issues/357
https://github.com/snes9xgit/snes9x/issues/751
https://github.com/snes9xgit/snes9x/issues/759
