### ISSUE TITLE
Make that's extended 240 lines

### ISSUE THREAD

**Issue by ghost** [snes9xgit/snes9x#772]
You made 239 lines MISTAKE. Make that's extended 240 lines. SNES has 240 lines

Before **(239 lines)**
![Dr  Mario (U) 000](https://user-images.githubusercontent.com/107685666/177053188-8af546c7-b48a-4d5f-8f9c-62fa518919e9.png)

After **(240 lines)**
![SNES 256x240](https://user-images.githubusercontent.com/107685666/177053190-de1b3878-3a9e-44c9-a161-edb96a75a21f.png)

**Comment by bearoso** [comment]
The first line is always black on real hardware. It's considered in "blanking" mode and the PPU isn't even active yet. We could show the line, but it would just be black.
