### ISSUE TITLE
add support for Game Boy & Game Boy Color

### ISSUE THREAD

**Issue by SopTheSop25** [snes9xgit/snes9x#774]
It will NOT be huge task.

It's about:

- add .gb, .sgb, .gbc, .dmg, .cgb FILE EXTENSIONS for Game Boy & Game Boy Color ROMs

- add GB Emulation Hardware options:
- Auto
- Game Boy
- Super Game Boy (default)
- Super Game Boy 2
- Game Boy Color
- Game Boy Advance

- add Super Game Boy Palettes options:
- SGB 1-A
- SGB 1-B
- SGB 1-C
- SGB 1-D
- SGB 1-E
- SGB 1-F
- SGB 1-G
- SGB 1-H
- SGB 2-A
- SGB 2-B
- SGB 2-C
- SGB 2-D
- SGB 2-E
- SGB 2-F
- SGB 2-G
- SGB 2-H
- SGB 3-A
- SGB 3-B
- SGB 3-C
- SGB 3-D
- SGB 3-E
- SGB 3-F
- SGB 3-G
- SGB 3-H
- SGB 4-A
- SGB 4-B
- SGB 4-C
- SGB 4-D
- SGB 4-E
- SGB 4-F
- SGB 4-G
- SGB 4-H

- add GB Colorization options:
- Game Boy (Gray)
- Super Game Boy

- add Super Game Boy Borders options:
- Super Game Boy (default)
- Super Game Boy 2
- OFF

It will show different Super Game Boy Borders while SGB Enhanced ROMs is playing

**Comment by bearoso** [comment]
Computer programs do not work that way!

**Comment by MCPE2** [comment]
Computer programs do work that way
