### ISSUE TITLE
Game Boy support

### ISSUE THREAD

**Issue by Creeper25** [snes9xgit/snes9x#776]
Would you like to add Game Boy support.

SNES / Super Famicom is backward-compatible with Game Boy using Super Game Boy or Super Game Boy 2 SNES cartridge + Game Boy cartridge

--- **GB Emulation Model**  ---

- Game Boy
- Game Boy Pocket
- Super Game Boy
- Super Game Boy 2

--- **default GB Color Palettes** ---

- SGB 1-A
![SGB 1-A](https://user-images.githubusercontent.com/110823345/183762744-d290b3f6-0ab0-45e2-b765-b55771a6b9b7.png)
- SGB 1-B
![SGB 1-B](https://user-images.githubusercontent.com/110823345/183762771-19eaa6e3-74e3-42c4-9074-dd1d16660775.png)
- SGB 1-C
![SGB 1-C](https://user-images.githubusercontent.com/110823345/183762795-42ce7bc8-648f-4cde-b04c-26526d218e44.png)
- SGB 1-D
![SGB 1-D](https://user-images.githubusercontent.com/110823345/183762812-88ad0677-5ebe-4c9f-b52a-f34de5c07e17.png)
- SGB 1-E
![SGB 1-E](https://user-images.githubusercontent.com/110823345/183762831-54af52fa-b4ed-43ea-bd28-67b8f5c89044.png)
- SGB 1-F
![SGB 1-F](https://user-images.githubusercontent.com/110823345/183762880-02e94c68-779f-46ff-b8fe-c96bc0eaa312.png)
- SGB 1-G
![SGB 1-G](https://user-images.githubusercontent.com/110823345/183762909-a17a7728-ea47-49b1-8904-7187aba2b143.png)
- SGB 1-H
![SGB 1-H](https://user-images.githubusercontent.com/110823345/183762973-5e1bd6ce-e76c-4e32-ac44-baaeb817253c.png)
- SGB 2-A
![SGB 2-A](https://user-images.githubusercontent.com/110823345/183762999-f6f57798-5be7-460c-8dbe-d13ebb629e0e.png)
- SGB 2-B
![SGB 2-B](https://user-images.githubusercontent.com/110823345/183763063-6a5811c0-647e-428c-8882-8c6312abcd1b.png)
- SGB 2-C
![SGB 2-C](https://user-images.githubusercontent.com/110823345/183763095-b22fc711-bfff-46e1-8129-c7cb9cb37c13.png)
- SGB 2-D
![SGB 2-D](https://user-images.githubusercontent.com/110823345/183763129-49c61a96-55a1-4be1-be27-338b69458e39.png)
- SGB 2-E
![SGB 2-E](https://user-images.githubusercontent.com/110823345/183763151-30eb7aa9-e558-459d-b860-1350273287a9.png)
- SGB 2-F
![SGB 2-F](https://user-images.githubusercontent.com/110823345/183763174-4f83553f-74e7-4bd9-a5cb-fb96a9010197.png)
- SGB 2-G
![SGB 2-G](https://user-images.githubusercontent.com/110823345/183763209-b258f18c-f523-440f-902c-f51e56ec4a98.png)
- SGB 2-H
![SGB 2-H](https://user-images.githubusercontent.com/110823345/183763233-571d559c-8954-4fe1-b37d-1d29c399a25e.png)
- SGB 3-A
![SGB 3-A](https://user-images.githubusercontent.com/110823345/183763251-c98ebacf-daf6-4873-b820-2f54a69addcc.png)
- SGB 3-B
![SGB 3-B](https://user-images.githubusercontent.com/110823345/183763277-71e68cb1-58fb-4022-9bde-e2ffca707270.png)
- SGB 3-C
![SGB 3-C](https://user-images.githubusercontent.com/110823345/183763314-00ce8328-d200-40fb-9f37-174eb1260f28.png)
- SGB 3-D
![SGB 3-D](https://user-images.githubusercontent.com/110823345/183763352-e245a61d-c6a4-4e69-81b8-4a16b8a0d6dc.png)
- SGB 3-E
![SGB 3-E](https://user-images.githubusercontent.com/110823345/183763388-71a93ec9-9e5b-4591-9cf3-1c8d6d5dcdf4.png)
- SGB 3-F
![SGB 3-F](https://user-images.githubusercontent.com/110823345/183763412-1e86bb30-8c84-41e7-850d-dd843c690fa4.png)
- SGB 3-G
![SGB 3-G](https://user-images.githubusercontent.com/110823345/183763434-8ac2f39e-d0f3-43b4-8574-40a647f6e4eb.png)
- SGB 3-H
![SGB 3-H](https://user-images.githubusercontent.com/110823345/183763510-c0ec08fa-e8f9-46a6-96a3-81fd160f4aac.png)
- SGB 4-H
![SGB 4-A](https://user-images.githubusercontent.com/110823345/183763535-213c8146-3068-4925-b1b4-6aca81c57ea3.png)
- SGB 4-B
![SGB 4-B](https://user-images.githubusercontent.com/110823345/183763555-6f25bb54-e4a5-4b09-8a64-a98e23f4871e.png)
- SGB 4-C
![SGB 4-C](https://user-images.githubusercontent.com/110823345/183763614-aea93834-b3b3-4788-863e-528cfa4ed881.png)
- SGB 4-D
![SGB 4-D](https://user-images.githubusercontent.com/110823345/183763641-5a9aa6f4-2b6d-44e4-8824-78910aaf5d14.png)
- SGB 4-E
![SGB 4-E](https://user-images.githubusercontent.com/110823345/183763670-5f821e18-f765-4323-bf7d-631ffe831f0c.png)
- SGB 4-F
![SGB 4-F](https://user-images.githubusercontent.com/110823345/183763700-cb45dc62-105c-42e0-bbbf-218e52a2e2ba.png)
- SGB 4-G
![SGB 4-G](https://user-images.githubusercontent.com/110823345/183763762-b2b275f5-1903-40fb-a411-55abe90ca2bf.png)
- SGB 4-H
![SGB 4-H](https://user-images.githubusercontent.com/110823345/183763773-652c3c70-8ef7-48a0-99a1-70218fe1537b.png)

-- **GB Colorization** --

- Game Boy
- Super Game Boy

-- **default Super Game Boy & Super Game Boy 2 border** --

- when Super Game Boy is emulating
![sgb-border](https://user-images.githubusercontent.com/110823345/183764784-f05ff804-a19b-4e5d-ab4c-9c4aca51b9a3.png)
- when Super Game Boy 2 is emulating
![sgb2-border](https://user-images.githubusercontent.com/110823345/183764813-41221b9f-3a99-438f-97fa-5a619881702c.png)

**Comment by Creeper25** [comment]
I made a pull request https://github.com/snes9xgit/snes9x/pull/777

**Comment by qwertymodo** [comment]
No.  The Super Nintendo is not "backwards compatible" with the Game Boy.  The Super Game Boy is a cartridge containing an entire Game Boy console, which would have to be emulated in its entirety.  This is a huge amount of work, which has been requested multiple times, and the answer has not changed.  Also, please do not submit blank pull requests.  The point of a pull request is for you to submit code that you have written.  If you have not written any code, please do not submit a PR.
