### ISSUE TITLE
Super Drift Out - savefile/records issue

### ISSUE THREAD

**Issue by CometHunter92** [snes9xgit/snes9x#783]
Despite having apparently a fix https://github.com/snes9xgit/snes9x/blob/master/memmap.cpp#L3647#L3650 Super Drift Out initialize time tables for the lap records wrongly, and records for the "wrc" mode don't work.
Affects both Snes9x 1.61-win32-x64 and libretro core. 
If in Retroarch I erase the .srm file and I open the game with bsnes first, then loading the game a second time with Snes9x will work as intended. If I do the opposite it won't work (an .srm file created first from Snes9x have the same lap times and record issue if loaded with bsnes).
I attach the srm files.
[Super Drift Out srm.zip](https://github.com/snes9xgit/snes9x/files/9457209/Super.Drift.Out.srm.zip)

**Comment by OV2** [comment]
What ROM are you using? "Super Drift Out - World Rally Championships (Japan) (En)" sounds weird.

When trying with my ROM here it matches the fix and the srm is initialized correctly. Can you check "File->Rom Information..." after loading the rom? I get this:
```
File: Super Drift Out (J).smc
Name: SUPER DRIFT OUT
Speed: 20/SlowROM
ROM Map: LoROM
Type: 02
Kart contents: ROM+RAM+BAT
Header ROM Size: 16Mbits
Calculated ROM Size: 16 Mbits
SRAM size: 64Kbits (64Kbit)
Actual Checksum: 1E15
Header Checksum: 1E15
Header Checksum Complement: E1EA
Output: NTSC 60Hz
CRC32:	EC8C1CCA
Licensee: Unknown Company 
ROM Version: 1.0
Region: Japan
```

**Comment by CometHunter92** [comment]
My rom it's the same as yours:

```
File: C:\Users\lastk\OneDrive\Desktop\Super Drift Out - World Rally Championships (Japan) (En).sfc
Name: SUPER DRIFT OUT
Speed: 20/SlowROM
ROM Map: LoROM
Type: 02
Kart contents: ROM+RAM+BAT
Header ROM Size: 16Mbits
Calculated ROM Size: 16 Mbits
SRAM size: 64Kbits (64Kbit)
Actual Checksum: 1E15
Header Checksum: 1E15
Header Checksum Compliment: E1EA
Output: NTSC 60Hz
CRC32:	EC8C1CCA
Licensee: Unknown Company 
ROM Version: 1.0
Region: Japan
```

Are you sure is it initializing it correctly? When you boot the rom for the first time (with no previous srm), go to "WRC BEST RESULTS", if you see all times 0:00:00 signed by an "Impreza", is not initializing the srm correctly. All the lap times and WRC mode times will not be recorded after that.
The first screen is from Snes9x, the second from bsnes.
![snes9x](https://user-images.githubusercontent.com/83950018/188517487-70648750-9d69-4e84-b420-eca037bad22c.PNG)
![bsnes](https://user-images.githubusercontent.com/83950018/188517498-4c555dca-00ed-4c48-a637-af3c80bb0c10.PNG)

**Comment by CometHunter92** [comment]
@OV2 Oh, I found it! Snes9x doesn't apply mmap patches if the extension is .sfc, even if the binary is the same as the .smc file. 
Changed the extension to .smc and now the initialization works correctly. Is it a bug?

**Comment by OV2** [comment]
I had a mixup somewhere as well. It works with an SRAMInitialValue of 0xff, but I want to do check what bsnes does when I have the time.

**Comment by CometHunter92** [comment]
Nice! However, I tried to recompile the libretro core changing the SRAMInitialValue to 0xff for Super Drift Out but it doesn't work either. It can be my fault however

**Comment by OV2** [comment]
If I delete the .srm and run it with SRAMInitialValueset to 0xff the records screen looks like this for me:
![image](https://user-images.githubusercontent.com/415729/190864052-28e15cdd-5aea-4e5a-8baa-9f560dd55df7.png)

**Comment by CometHunter92** [comment]
Oh, nice!
As I said tried to compile a libretro core with that 
`// SRAM value fixes
	if (match_na("SATAN IS OUR FATHER!") ||
		match_na("goemon 4"))               // Ganbare Goemon Kirakira Douchuu
		SNESGameFixes.SRAMInitialValue = 0x00;

	if (match_na("SUPER DRIFT OUT"))           // Super Drift Out
	    SNESGameFixes.SRAMInitialValue = 0xff;
`
but it doesn't work, so it's my fault if it works on your side.

**Comment by bearoso** [comment]
You needed to delete the .srm file. Otherwise the one that was created with all zeroes is still there and corrupted.
