### ISSUE TITLE
None of the macOS nightly zip files are actually hosted

### ISSUE THREAD

**Issue by eisnerguy1** [snes9xgit/snes9x#784]
So, I'm trying to download any of the Mac nightly zips and all I get is an empty build.zip file.

For example, if you click the zip file on this page:
http://cirrus-ci.com/task/6527447301619712

you get this message:
{"code":500,"message":"There was an error processing your request. It has been logged (ID 5f8f8ba71f2dd2f8)."}

I went through all of the successful macOS build pages and got the same issue.

Are macOS nightly builds just broken right now?

**Comment by MichaelBuckley** [comment]
It appears they're only hosted for a few days. I ran http://cirrus-ci.com/task/6121774382317568 this morning and the build  appears to still be available.

**Comment by eisnerguy1** [comment]
Ah, gotcha. Yep, I was able to download it. Thanks! 😄
