### ISSUE TITLE
Crash when using OpenGL - Snes9x 1.61

### ISSUE THREAD

**Issue by Felipefpl** [snes9xgit/snes9x#785]
When i choose opengl as my renderer i get a crash when i start a game, no problems when using DDraw and D3D, my specs are:

Win7 x64, 4 GB RAM and Intel hd 2000

I also noticed something minor: when choosing a filter the emulator auto-chooses another filter for the Hi-Res, it's annoying having to disable this everytime a filter is changed in the Output Image Processing. Cant this behaviour be removed?

**Comment by jerCodesThings** [comment]
I'm not familiar with the code of this project or OpenGL at this time. Starting my time at University soon and I'm still learning the things xD haha.  However (after a little research) I noticed that all but [the Intel HD 2000's max OpenGL version is 3.1 ](https://www.intel.com/content/www/us/en/support/articles/000005524/graphics.html) Maybe that is causing the issue for you?

**Comment by Felipefpl** [comment]
Heck... i didnt even remember i had reported this before. :P
