### ISSUE TITLE
Found a couple of places where CPU cycle timing is wrong.

### ISSUE THREAD

**Issue by pi1541** [snes9xgit/snes9x#786]
BRL $xxxx
Opcode $82
is supposed to be 4 cycles, currently set to 3

JSL
Opcode $22
is supposed to be 8 cycles, currently set to 7

**Comment by pi1541** [comment]
Also StackRelativeIndirectIndexed is taking one cycle too many.
It does not need to do AddCycles(ONE_CYCLE); as StackRelativeIndirectIndexed calls StackRelative and it is done in there.

**Comment by bearoso** [comment]
I haven't got a chance to look at this yet, but thanks for the info.

**Comment by bearoso** [comment]
I confirmed you are correct by checking in Ares. I'm impressed you managed to navigate Snes9x's crazy opcode jumble to find these.
