### ISSUE TITLE
[Feature Request] Option to increase the Sound Rate in the libretro core

### ISSUE THREAD

**Issue by juamnitruh** [snes9xgit/snes9x#788]
Even if a real snes outputs at 32hz, the option to increase or decrease the soundrate would be great. Being locked to 32hz sucks.

**Comment by OV2** [comment]
This is the job of the libretro frontend - you can configure the output rate in retroarch.

**Comment by juamnitruh** [comment]
> This is the job of the libretro frontend - you can configure the output rate in retroarch.

no, i can't, at least there's no way to do that i'm aware of. And i've searched it.

**Comment by qwertymodo** [comment]
Just checked, and I don't see anywhere to manually set the resampler output rate, so maybe it's just locked to the rate of the currently selected output device, I'm not sure, but in any case, this is a RetroArch front-end issue, not an issue with the Snes9x core.

**Comment by OV2** [comment]
There is at least an option in the config file:
https://github.com/libretro/RetroArch/blob/master/retroarch.cfg#L312
It defaults to 48000 on PC, so that is what you will most likely get.
