### ISSUE TITLE
Does it support Sufami Turbo extension: .st?

### ISSUE THREAD

**Issue by soundsnow** [snes9xgit/snes9x#793]
I found an emulator related to snes9x, but it does not load the Sufami Turbo games I own
File Extension: .st
These games are [no-intro](https://datomatic.nointro.org/index.php?page=download&op=dat&s=78) verified
And [snes9x(libretro)](https://github.com/libretro/snes9x/blob/ae16176a18fa2a7d642be5d66dbe1926d9d08e90/libretro/libretro.cpp#L820) and [bsnes](https://github.com/bsnes-emu/bsnes/blob/6fc6bf14a39d32dab69c4f9687a81df26d412758/bsnes/target-bsnes/program/platform.cpp#L170) also provides support for .st
![Screenshot_20221017-093031_Android System](https://user-images.githubusercontent.com/109885044/196070977-2301086e-5a92-40e0-a5ca-7f934e311ec4.png)

can you add this file format? if not, why?

**Comment by odditude42** [comment]
Sufami Turbo ROMs aren't loaded via the standard dialog. On Windows, look under File -> Load MultiCart...

**Comment by OV2** [comment]
All file types are supported if you select "all files" in the dialog. I've added .st to the default extensions listed there - you can manually add "stN" to the Valid.ext file if you want to add this to your existing version.
