### ISSUE TITLE
I try to record European game videos (PAL) through "Start AVI Recording" but they come out without sound.

### ISSUE THREAD

**Issue by xRavenXP** [snes9xgit/snes9x#794]
Hello friends, how are you? I'm putting this message here because I record videos for Youtube and when I want to record the video of a PAL region (European) SNES game, the video comes out completely without sound, while NTSC games (both American and Japanese) the sound comes out perfect (I always use the Lagarith Loseless Codec). I downloaded version 1.61 of Snes9X but the problem in recording European games persists, so for European games I need to use the Bizhawk emulator. Is there any setting for European games videos to come out with sound?

**Comment by ReyVGM** [comment]
You're right, I don't get any sound either when recording a Euro game.
