### ISSUE TITLE
No File permissions on Chromecast with Google TV

### ISSUE THREAD

**Issue by cubiczar** [snes9xgit/snes9x#800]
After the Android 12 update for the Chromecast with Google TV dongle the OS seems to have completely removed the file manager.  There must also be some sort of permission changes because the app no longer has permissions to access the rom and save files I was using.  It also doesn't ask for permission and the permission doesn't show up under app or app permissions so I can't manually grant file access.

I don't know if there is an easy fix for the file manager/browser issue but I'm hoping changing the manifest to add the correct permissions for Android 12 will be an easy fix.

**Comment by odditude42** [comment]
Snes9x EX is not maintained by the Snes9x devs.

The dev's website is https://www.explusalpha.com/ and he can be reached via email at [info@explusalpha.com](mailto:info@explusalpha.com).

**Comment by cubiczar** [comment]
Ah, sorry will head over there then.  Thanks for the heads up
