### ISSUE TITLE
Update unix port

### ISSUE THREAD

**Issue by sergiobenrocha2** [snes9xgit/snes9x#81]
Is it possible to update these files?

unix/config.guess
unix/config.sub

I'm creating the package for debian, lintian complain about them.

They are at /usr/share/misc/, is it possible to copy from there when configure?

Thanks.

**Comment by OV2** [comment]
Currently nobody maintains the plain unix port, and I don't even have a system that can compile it. If you have a patch ready I can merge it in.

**Comment by vgturtle127** [comment]
When you guys say Unix, what exactly do you mean? The definition of Unix seems to differ sometimes...

**Comment by greg-kennedy** [comment]
I just updated these in the process of getting unix port working with more features.

Does this make me the official maintainer?  :P

**Comment by sergiobenrocha2** [comment]
Those files should be generated in the build time btw. It's what I'm doing in the deb package.

**Comment by greg-kennedy** [comment]
The benefit of providing config.sub and friends is that it makes snes9x-unix buildable by Average Joe without autotools installed.  That's the purpose of autotools in the first place, after all : )

You are right, though, in that we probably don't need to try to stay on top of new versions.  Package builders should run autoreconf -f -i each time to use their up-to-date autotools installation for config.sub, config.guess and install-sh.

**Comment by vgturtle127** [comment]
I see what's going on now, I got confused.

So it compiles fine and everything?

**Comment by bearoso** [comment]
Needs to have callback and timer removed from audio.

**Comment by greg-kennedy** [comment]
This issue should probably just be closed and new ones opened as needed.
