### ISSUE TITLE
Mac OSX Build Crashes if IOHIDDeviceRef Cannot Find Name

### ISSUE THREAD

**Issue by EveyJSwag** [snes9xgit/snes9x#810]
mac-joypad.mm:755   Iterates through devices and inside of the `AddDevice` function tries to get various attributes of connected devices. If the sys call can't find the name, the app will crash when trying to instantiate `std::string s = std::string(name.UTF8String);` in the `AddDevice` function.

**Comment by MichaelBuckley** [comment]
@EveyJSwag Thanks for reporting this! I've checked in a small fix that will name the device "Unknown Device" when `IOHIDDeviceGetProperty()` can't return a name.

**Comment by EveyJSwag** [comment]
Just checked out the changes and built it! Working like a charm! Thank you, @MichaelBuckley!
