### ISSUE TITLE
Libretro "current" core - Super Mario All-Stars hangs on Mario 3

### ISSUE THREAD

**Issue by ChocoChopin** [snes9xgit/snes9x#811]
This doesn't appear to be an issue with the standalone 1.61 implementation, but when using RetroArch's "current" Snes9x build, Super Mario All-Stars will hang on a black screen when loading Mario 3 (but not other games in the collection). The issue seems to persist between different versions of the game, including the regular U version as well as the All-Stars + World edition. Persists between different video backends as well.

Since this is such a popular game I wonder if this could somehow be a quirk with my particular setup/RA configuration, but it's the only notable bug I've encountered using Snes9x in many years.

**Comment by bearoso** [comment]
Check if you're using the overclock options.

**Comment by ChocoChopin** [comment]
I feel incredibly stupid--I had "reduce slowdown" enabled. Terribly sorry about that, I've had COVID and have been a little out of it in general.

**Comment by joepogo** [comment]
I just saw this issue as closed as i thought there might be some similarity with the fastrom issues on retroarch. 

Hey @bearoso is there anything you can recommend as far as something us end users can try to get those games working on snes9x retroarch? Some fastrom hacks work, some don't, its pretty strange.

**Comment by bearoso** [comment]
Snes9x has heuristics that guess the rom layout. The easiest way to check if it's getting that wrong is to look at the rom info dialog. If it says slowrom, then we need to adjust the heuristics. If it got it right and it says fastrom, then the hack isn't done right.

**Comment by joepogo** [comment]
@bearoso I just tried it out again on current PC snes9x to check the rom info on startup and all it says is lorom in the info I don't see fastrom anywhere BUT the patch does get rid of the slowdown like a fastrom hack should. 

When I load the same rom in current snes9x RetroArch it just black screens 

The game in question is super back to the future Ii fastrom hack. There's an issue opened up for this too #150.
