### ISSUE TITLE
r1096 to r1097 compatibility

### ISSUE THREAD

**Issue by 7zxkv** [snes9xgit/snes9x#815]
hello

it may be normal (although I didn't see in the commits any report) but the 32 bits r1096 binary is XP compatible while the 1097 is not. I just wanted to point it out in case it's not particularly a will of yours. Sincerely.

**Comment by OV2** [comment]
I'm not sure what you are referring to with rXYZ, but even the latest automated build is still winxp compatible.
We are not committed to always keep it that way, but for now they still work on xp.

**Comment by 7zxkv** [comment]
hi again, 

https://ci.appveyor.com/project/snes9x/snes9x/history

1096 work, 1097 not work (tested on real xp).

**Comment by OV2** [comment]
This is the vulkan test branch (as you can see in the middle on that page), which has different requirements.

**Comment by 7zxkv** [comment]
ok ;-)

**Comment by bearoso** [comment]
I might have fixed this. vk_mem_alloc.h was compiling in code that required WINVER=0x0600 (Vista). Can you check the latest vulkan build and see if it works?

**Comment by 7zxkv** [comment]
Work ;)
