### ISSUE TITLE
Fast forward mode way too fast, seems to ignore "frames to skip in ff mode" setting?

### ISSUE THREAD

**Issue by TheHorscht** [snes9xgit/snes9x#816]
This problem has been bothering me for ages (literally 5+ years) and just recently I found out about this github repo, so I thought I would mention it here since I can't find anyone else who has this problem.
I've had this problem since at least v1.53 and am currently using v1.61 on Windows10 with the default settings, except "Skip at most X frames in fast-forward mode" and "Skip at most X frames in auto-frame rate mode" both set to 2. And yet it goes crazy fast as soon as I enter fast forward mode.

Any ideas why that would be the case? I checked the `snes9x.conf` just in case the settings were not written correctly, but it seems to be correct:
```
AutoMaxSkipFramesAtOnce = 2
TurboFrameSkip = 2 
```

**Comment by TheHorscht** [comment]
Had to enable VSync, now it works as expected.

**Comment by OV2** [comment]
I'll still take a look if it can also work without vsync.
