### ISSUE TITLE
Run on ARM

### ISSUE THREAD

**Issue by sergiobenrocha2** [snes9xgit/snes9x#82]
I'm having the same problem of this guy, black screen when you load any rom. Trying on odroid U3 (Exynos 4412 cortex A9 quad core, Mali 400).

http://www.snes9x.com/phpbb3/viewtopic.php?f=6&t=5264

**Comment by vgturtle127** [comment]
Did you try any other ARM chips or other GPU's by chance?

**Comment by sergiobenrocha2** [comment]
Nope, I only have this board.

**Comment by vgturtle127** [comment]
Oh. Well, this is speculation, but do you know what drivers you are using? And what are your graphics settings?

**Comment by aworan** [comment]
Same problem black screen with raspberry pi 3 and raspberry pi 2 and opengl driver activated. So there is definitely a problem on arm architecture !

**Comment by loganmc10** [comment]
I use this via libretro on Android and it works fine

**Comment by aworan** [comment]
The bug is under Linux not Android.
I use Ubuntu and sergiobenrocha2 Gentoo but I think it is a general issue on Linux with arm chip.
I have the same problem like the first post forum link.
For example bsnes / Higan works good with opengl but a little bit slow even on rapsberry pi 3 under Ubuntu.

**Comment by vgturtle127** [comment]
@aworan Huh, it sounds like the issue I was thinking of probably isn't the issue. Does anybody on the team have any ARM devices, and has SNES9x been ported over officially?

**Comment by aworan** [comment]
@vgturtle127 everything compiles well so I think there is some specific bug for arm.
Maybe it is not a lot to fix to make it work, I can do tests if you need some !

**Comment by vgturtle127** [comment]
@aworan I'm unsure of the issue, there were issues in the past with some ARM devices and drivers, but that isn't the issue, so I'm not sure I can help you.

You might try another Pi operating system, like Raspian and see if that fixes it to be sure it isn't the OS. Just a wild guess though.

**Comment by aworan** [comment]
@vgturtle127 I try under raspbian last version (with my rpi3 and rpi2) I have the same problem no error in console and black screen with opengl driver activated.
So I guess it is on all arm linux system versions.

**Comment by vgturtle127** [comment]
@aworan Darn. 😞 

I wish I had a Raspberry Pi to test with so I could help debug the issue.

**Comment by gregoryz7** [comment]
Running into this same issue on a Pi3 running stretch. Wanted to note that running the version included with retropi works fine but no luck with this repo

**Comment by gregoryz7** [comment]
As a follow up the the previous comment, https://github.com/psyke83/snes9x-rpi is the optional emulator snes9x code that is being run by retropie. I managed to compile it and get it running so its confirmed running on ARM.  This code shares some similarities with this project but I havent had time to track down all of the changes. I would prefer to use this project as it has a lot of nice options. Will keep posting ;) if the issue presents itself.

**Comment by gregoryz7** [comment]
Ok I have a fix that got this up and running on ARM but am unsure how to implement it in this project correctly (so it doesn't interfere with other hardware builds).  For GTK I added -DARM and -Wno-narrowing to the end the extra flags string in configure.ac . Like so:
`EXTRA_FLAGS="-Wall -W -Wno-unused-parameter -DARM -Wno-narrowing"`
WAS `EXTRA_FLAGS="-Wall -W -Wno-unused-parameter"`

and I added the same flags in the configure file for the UNIX project and built. 

This solved the Black Screen issue for me for both projects. Also I built the unix project without -Wno-narrowing and it loaded but crashed. I dont know if that flag is needed for both projects or if some other flag would be more appropriate.

**Comment by bearoso** [comment]
-Wno-narrowing should have no effect except on whether compilation succeeds or not. It's not going to affect the binary. My guess is that you didn't do a clean build.

As for the need to define ARM, we should probably change the test in port.h to __arm__ instead.

**Comment by OV2** [comment]
With the latest change to port.h it works fine on my very old raspberry pi.

**Comment by gregoryz7** [comment]
It compiled just fine with or without the flag set. It just crashed
unexpectedly on the the Mario entry video / running but with a black screen
when neither flag was set. It's possible I forgot to clean and that caused
the crash? I haven't tried any other hardware except for a Pi3 running
stretch.

If you have a change to the port.h that you would like me to try just let
me know what to do.

**Comment by OV2** [comment]
Just try the latest git without any additional flags.

**Comment by gregoryz7** [comment]
Will do. If changes havent been made to port.h within the last 4-5 days i would expect a black screen again. Will try / look into this further tonight. Thanks!

**Comment by bearoso** [comment]
This was fixed.

**Comment by NeilXialijun** [comment]
[root@arm-linux]#./bin/snes9x  /mnt/sdcard/Neil_bin/jtbw.smc 


Snes9x 1.60 for unix
[  728.456672] DSP power on
fragment size: 0
Port 1: Pad #1. Port 2: <none>. 
[  728.457455] ##dsp##: DSP is ready to work, firmware version: CVR_V2.3.4_20180202
Found ROM file header (and ignored it).
Map_LoROMMap
"Street Fighter 2" [checksum ok] LoROM, 16Mbits, ROM, PAL, SRAM:0Kbits, ID:n  5, CRC32:8B93F566
joystick: No joystick found.
Failed to connect to X server.
[  729.302475] DSP power off
[root@arm-linux]#

I run error, have any friends encountered?
I need your help
