### ISSUE TITLE
4MB/8MB Super FX ROMs not supported

### ISSUE THREAD

**Issue by Anas13303** [snes9xgit/snes9x#822]
So Super FX has a feature which allows you to expand ROMs to 4MB or 8MB. Unfortunately, the only emulator that supports this is BSNES+. This is very limiting as there exists a special Yoshi's Island level editor called EggFlutter ([https://github.com/Yoshimaster96/EggFlutter](url)) which automatically expands to the ROM to 8MB for a lot more space than what the vanilla game offers. This means future hacks made with this editor are otherwise unplayable except with BSNES+. It would be appreciated if you could add support for this!

**Comment by qwertymodo** [comment]
This is not actually a feature of the Super FX, it's an emulator-only hack.
Early revisions of the Super FX (MARIO/GSU-1) only support 1MB, and later
revisions (GSU-2) expanded that to 2MB, but no revision of the chip ever
supported more than that.

**Comment by OV2** [comment]
This would be #712, right?

**Comment by qwertymodo** [comment]
Ah, that could be the case. I would have to look into the expanded ROMs to see for sure. If it works in bsnes+ it would probably be possible to use the manifest viewer to see how it's getting mapped there.

**Comment by bearoso** [comment]
Added to master.

**Comment by niuus** [comment]
> So Super FX has a feature which allows you to expand ROMs to 4MB or 8MB. Unfortunately, the only emulator that supports this is BSNES+. This is very limiting as there exists a special Yoshi's Island level editor called EggFlutter ([https://github.com/Yoshimaster96/EggFlutter](url)) which automatically expands to the ROM to 8MB for a lot more space than what the vanilla game offers. This means future hacks made with this editor are otherwise unplayable except with BSNES+. It would be appreciated if you could add support for this!

I added support to the relevant commit in [Snes9xRX](https://github.com/niuus/Snes9xRX/). Do you know of any released hacks that have been made with Eggflutter to test it thoroughly?
