### ISSUE TITLE
 SA-1 can mistakenly access WRAM

### ISSUE THREAD

**Issue by Anas13303** [snes9xgit/snes9x#823]
I'm no ASM programmer, but there exists a bug in the latest version of Snes9x (and probably the previous version as well) where SA-1 can mistakenly access WRAM, even though it's not supposed to be like that. I have simply heard this from some people in the SMW Central community and I don't think it has been reported yet, so I will drop the report here myself.

**Comment by bearoso** [comment]
This should be fixed in 33cab01.
