### ISSUE TITLE
1.62

### ISSUE THREAD

**Issue by bearoso** [snes9xgit/snes9x#824]
I've added a lot of stuff, so I imagine it's time to increment the version.

Feel free to suggest things that should be done before 1.62 is released.

**Comment by odditude42** [comment]
I'm not a Mac user personally, but since the question has shown back up on the [board](https://www.snes9x.com/phpBB3/viewtopic.php?t=29576&sid=96ac3be381cfcba920c040ddd9033604) recently - will there be an "official" Mac build of 1.62 supporting latest MacOS, or will that still be considered WIP?

**Comment by bearoso** [comment]
Well, they deprecated or removed a lot of the API that the old port used, so it's written partly from scratch. I'd still consider it WIP.

**Comment by MichaelBuckley** [comment]
Yeah, we had an official WIP Mac build of 1.61. I'm happy to do it again for 1.62, adding a few things I've been able to rewrite since then. Cheat finder, and possibly the music box, which used fewer removed APIs.

**Comment by OV2** [comment]
Let me take a final look this weekend, then it should be fine from my end.

**Comment by Felipefpl** [comment]
> Feel free to suggest things that should be done before 1.62 is released.

Would it be too much to ask to add an option on File > Recent Games Menu to clean the list of all games that were played? Other emulators have this and i know it's a small thing but that would be handy.

**Comment by Max833** [comment]
> I've added a lot of stuff, so I imagine it's time to increment the version.
> 
> Feel free to suggest things that should be done before 1.62 is released.

The number of people using 4k monitors is growing, so scaling up to 10x would be useful. Right now it's just 4x...

**Comment by bearoso** [comment]
Those were easy enough. Any more simple things?

**Comment by Felipefpl** [comment]
Well, perhaps there are but i dont know if those could be classified as such:

1 - Some filters such as: EPX, Simple, DOT Matrix, both TV Mode, lq3xbold, SuperEagle and Blargg dont offer too much of an improvement to the GFX, it would be nice to remove them but it's a personal opinion, i'll understand if this doesnt happen.

2 - There are optimized versions of HQX/XBRz filters around on net, it also would be nice if snes9x had them.

3 - I tried the Hi-Res filters in the output processing image and nohing changed here, only changing the filters above made a change in the GFX. No idea why this happens.

4 - You can choose the language on GTK build but not on windows. At least i didnt see any opton on GUI for that.

5 - Cosmetic change: there are several of the same resolutions to choose mixed with 16/32 bit plus 60/70/75 hz. Why not display only one resolution and make snes9x choose the bit/hz based on what is set by windows/unix/mac on desktop?

**Comment by Max833** [comment]
> Those were easy enough. Any more simple things?

Thank you! =)

**Comment by bearoso** [comment]
> Well, perhaps these are simple but i dont know if those could be classified as such:
> 
> 1 - Some filters such as: EPX, Simple, DOT Matrix, both TV Mode, lq3xbold, SuperEagle and Blargg dont offer too much of an improvement to the GFX, it would be nice to remove them but it's a personal opinion, i'll understand if this doesnt happen.

People will complain. They may not seem useful, but someone out there will get irritated if we remove anything.

> 2 - There are optimized versions of HQX/XBRz filters around on net, it also would be nice if snes9x had them.

License compatibility is the issue. So far, we only have the rights to use the versions we have.

> 3 - I tried the Hi-Res filters in the output processing image and nohing changed here, only changing the filters above made a change in the GFX. No idea why this happens.

Those are for when the game uses a 512 pixel wide mode, which is rare.

> 4 - You can choose the language on GTK build but not on windows. At least i didnt see any opton on GUI for that.

Windows doesn't have the resources to make this easy like Gtk does. A cross platform Qt version in the future might be an option.

> 5 - Cosmetic change: there are several of the same resolutions to choose mixed with 16/32 bit plus 60/70/75 hz. Why not display only one resolution and make snes9x choose the bit/hz based on what is set by windows/unix/mac on desktop?

Yeah, anything other than native refresh rate/bit rate and extra 32 bit/60hz modes is kind of pointless, but once again, someone might complain.

**Comment by bearoso** [comment]
> 5 - Cosmetic change: there are several of the same resolutions to choose mixed with 16/32 bit plus 60/70/75 hz. Why not display only one resolution and make snes9x choose the bit/hz based on what is set by windows/unix/mac on desktop?

To add on to this, I suggest just using the "Emulate Fullscreen" option on Windows. It doesn't change the screen resolution, just makes the window fullscreen, and makes this dialog box irrelevant. Showing all those extra modes in the box is left over from the days when people would need to lower the bit depth and resolution to get better performance, but we don't need that anymore. Drivers these days can automatically give exclusivity to fullscreen windows these days without needing the mode switch, too. 

Nowadays, it's still useful if you have a non-60-hz, non-variable-sync display, so you can change to a 60hz mode for smoother motion. You could also set up a custom resolution at 60.09881 Hz with tools like CRU and use this box to select that resolution so only Snes9x uses it and matches the hardware speed precisely.

**Comment by Felipefpl** [comment]
Thank you for all explanations regarding my suggestions. :+1: 

Btw, about the 6 remaining pull requests, what prevents them from being submitted, are they incomplete or just small things are missing/wrong and with those being submitted/fixed will they be able to be released?

**Comment by bearoso** [comment]
I've closed the ones that are irrelevant or outdated. I'd like to look at the point we escape from the frame loop in the future, so I'm leaving that one open. The SuperFX ROM size one is probably OK to merge.

**Comment by lordpeluca** [comment]
Is there any possibility to add an automatic fullscreen loading option when loading a rom?

Something like: "Auto Switch to fullscreen after loading".

Anything to avoid the "Alt + Enter".

Thanks for improving this great emulator :)

**Comment by ImSpecial** [comment]
> > Well, perhaps these are simple but i dont know if those could be classified as such:
> > 1 - Some filters such as: EPX, Simple, DOT Matrix, both TV Mode, lq3xbold, SuperEagle and Blargg dont offer too much of an improvement to the GFX, it would be nice to remove them but it's a personal opinion, i'll understand if this doesnt happen.
> 
> People will complain. They may not seem useful, but someone out there will get irritated if we remove anything.

Yes I'm one of them :), thanks for not removing these, and also thanks for the registry solution that you added too btw.

**Comment by zhr0000** [comment]
When I lock my screen and re-access, s9x reports the error with blackscreen: Failed to initialize currently selected display output! Try switching to a different output method in the display setting.

It used to be possible to solve the problem by switching, but the nightly version can only be restarted to complete.
I chose D3d in output method and this didn't happen on any other emulators.

**Comment by OV2** [comment]
For 1. you can try setting OpenGL:DisablePBOs to TRUE in snes9x.conf

2.: What does the message say besides that? Does this only happen in fullscreen mode or always? You can try to disable bilinear filtering and see if that helps. We will probably not do any real work on the DirectDraw mode.

**Comment by Felipefpl** [comment]
@OV2 1 - This tip worked. Could this be the standard or is this a problem for other video cards?

2 - I started the game on fullscreen/windowed mode and the colors are disabled in both ways. Bilinear filtering was already disabled (i dont like it since it makes the GFX ugly). The only message i see after what i saw is: "A running program isnt compatible with certain visual elements of Windows."

**Comment by bearoso** [comment]
I removed the PBOs in the Gtk port because they weren't providing a benefit. On an old PowerPC Mac they increased the transfer speed if you converted to 32 bit before, but in recent tests I've done they were no faster than regular glTexImage. I think it's safe to just get rid of them.

**Comment by bearoso** [comment]
@zhr0000: When you get that error message, Direct3D should show a message before that indicating what failed. Can you post that here? I'm trying to reproduce the crash, but for me it comes back OK from the lock every time. Do the other drivers like OpenGL and Vulkan also crash? Do you have multiple monitors?

**Comment by lordpeluca** [comment]
@bearoso 

Thanks for adding the option to load the rom automatically in full screen. :)

By the way, looking at my old posts, about 3 years ago I asked about this same thing, more precisely in this post:

https://github.com/snes9xgit/snes9x/issues/571

And that's basically what I was looking for. If they want they can close that thread since, for me, it is solved.

**Comment by zhr0000** [comment]
> @zhr0000: When you get that error message, Direct3D should show a message before that indicating what failed. Can you post that here? I'm trying to reproduce the crash, but for me it comes back OK from the lock every time. Do the other drivers like OpenGL and Vulkan also crash? Do you have multiple monitors?

I tried many ways. Seems this error occurred only when I minimized the window and locked screen customarily. Then heard error sound sometimes. Vulkan crashed too just at the emulator started. OpenGL is fine. I chose D3d to run the reshade injector and most of the filters above adapt it better than OpenGL.Mine is surfacepro with no multiple.

![image](https://user-images.githubusercontent.com/104200412/224873058-ce9d1e4e-ec8e-409c-b041-ea40fd73df88.png)
btw，thanks the anecdote that obscure for my rusty eng.

**Comment by bearoso** [comment]
It might be reshade crashing things. You know with OpenGL and Vulkan you can use any of the shaders here: https://github.com/libretro/slang-shaders. There's probably just as many options there as with reshade.

**Comment by Felipefpl** [comment]
@bearoso - Unrelated to 1.62 but perhaps you'll like the idea: several of the oldest issues here could be closed since they are related to gtk/compiling issues that may be fixed. ;)

Of course, there are some of those issues that arent among the oldest ones too.

**Comment by zhr0000** [comment]
> It might be reshade crashing things. You know with OpenGL and Vulkan you can use any of the shaders here: https://github.com/libretro/slang-shaders. There's probably just as many options there as with reshade.

But it has existed for a long time before I knew reshade, and still crashed after I uninstall it.

**Comment by odditude42** [comment]
not sure if this counts as easy or not -

support two, independent ffwd levels, with independent toggle and hold hotkeys.

usage: i'd like to be able to play an RPG at (ffwd lv 1) by toggling that setting.
on demand, i'd like to jump up to (ffwd lv 2) using the hold hotkey, such that when i release the hotkey it returns to (ffwd lv 1), which has remained toggled on.

**Comment by BananaManner** [comment]
I'd like to see HD Mode 7 if it's not already implemented.

**Comment by Max833** [comment]
If the xbox 360 controller is turned off while SNES9x is already running and you turn it on, the controller will not work (OS: Windows 10). The Controller must be turned on before you start SNES9x. Is this fixable as well?

**Comment by bearoso** [comment]
There's a menu option "Detect Gamepad Changes"? Does that detect the controller? It would be easy enough to check constantly, but that might cause hiccups.

HD Mode 7 isn't happening, at least for a while. It would require a PPU rewrite. 

Why do you need a hotkey for "show frame rate?" It will be either 50 or 60 all the time unless you're running a computer from two decades ago. I don't understand why you would need to rapidly turn it on or off.

**Comment by Max833** [comment]
> There's a menu option "Detect Gamepad Changes"? Does that detect the controller? It would be easy enough to check constantly, but that might cause hiccups.

It's a little bit strange, because with ares/mesen I don't have to do anything, but... it does the job. Thanks!

**Comment by zhr0000** [comment]
> Why do you need a hotkey for "show frame rate?" It will be either 50 or 60 all the time unless you're running a computer from two decades ago. I don't understand why you would need to rapidly turn it on or off.

Well some shaders from reshade causing this. I would consider deprecating it anymore. Thanks!

**Comment by OV2** [comment]
> > There's a menu option "Detect Gamepad Changes"? Does that detect the controller? It would be easy enough to check constantly, but that might cause hiccups.
> 
> It's a little bit strange, because with ares/mesen I don't have to do anything, but... it does the job, I think. Thanks!

The problem with automatic change detection was that this sometimes crashed inside the windows multimedia functions that snes9x still uses for controller access. Thus this workaround. A proper fix would probably require switching to dinput/xinput, which I never got around to.

**Comment by OpalCogdillYy** [comment]
The conversation is about the development of Snes9x, an emulator for the Super Nintendo Entertainment System. The discussion centers around the release of version 1.62 and what features should be included. The collaborators and contributors suggest various features, including adding an option to clean the recent games list, scaling up to 10x for 4k monitors, removing some filters, including optimized versions of HQX/XBRz filters, and adding an option to choose the language on the Windows version. The collaborators also mention that some features might be difficult to implement due to license compatibility or potential user complaints.

**Comment by lordpeluca** [comment]
A cosmetic change more than anything else. 

In "help/about", do not forget to update dates, that is:

(c) Copyright 2009 - 2022 BearOso, OV2 
(c) Copyright 2009 - 2023 BearOso, OV2

**Comment by ImSpecial** [comment]
> Gtk:
> - Removed graphics options most people won't understand or need.

What were these if you don't mind me asking?

**Comment by bearoso** [comment]
You think otherwise? PBOs, POT textures, and GLX_OML_sync_control usage.

**Comment by Felipefpl** [comment]
> You think otherwise? PBOs, POT textures, and GLX_OML_sync_control usage.

Talking about PBOs is it possible to remove them from win32 builds as you suggested? I'd like to have the option to choose OpenGL (if this doesnt harm snes9x of course). After that only the problem with DirectDraw will remain. ;)

**Comment by bearoso** [comment]
I set it to disable PBOs by default on Windows. If you have an existing config file, you'll need to edit it so DisablePBOs is set to true or erase it and start anew.

**Comment by Felipefpl** [comment]
Thanks, i did as you suggested on previous post. :+1:

**Comment by bearoso** [comment]
I've made a potentially breaking change by moving S9xSyncSpeed. It shouldn't cause problems in theory, but who knows? Testing is appreciated.

**Comment by psyalemao** [comment]
An appimage would be great. I tried to setup a script but didn't edit the yml or CMakeLists.txt

[make-appimage.zip](https://github.com/snes9xgit/snes9x/files/11024835/make-appimage.zip)

**Comment by bearoso** [comment]
@psyalemao: Your script doesn't get the right shared libraries. Using the linuxdeploy program is probably the best way to do that. I'm not going to add an AppImage to CI right now. I could make one for the release version, though.

**Comment by bearoso** [comment]
Anything else that needs to go in before release?

**Comment by Felipefpl** [comment]
None unless you wanna look at those small issues opened. ;)

Btw, here is one that needs to be closed:

https://github.com/snes9xgit/snes9x/issues/732

**Comment by psyalemao** [comment]
> I could make one for the release version, though.

Didn't know about linuxdeploy.  Thanks for taking appimage in consideration. What about 7zip support?

**Comment by bearoso** [comment]
Tagging 1.62.

**Comment by Felipefpl** [comment]
Thanks for that, the other sites will be updated with the changelogs too?

**Comment by bearoso** [comment]
Other people control those sites. I can only make the update here.

**Comment by Felipefpl** [comment]
> Other people control those sites. I can only make the update here.

I see, didnt know that. Thanks for the info.

**Comment by OV2** [comment]
The file size results from the change to static CMemory allocations. @bearoso maybe we should simply change those to vector<uint8> ?

**Comment by bearoso** [comment]
I tested that on Linux, but didn't get any decrease, but the size there is already a third of Windows. I guess MSVC *does* embed the globals in the text section.

**Comment by bearoso** [comment]
Changing ROMStorage to a vector cuts the size by 12MB. With ELF binaries it does nothing. Crazy Windows.

I'll look into the others.

**Comment by OV2** [comment]
I'm not sure why the compiler doesn't put it into bss, will have to do some investigation.

**Comment by bearoso** [comment]
Other than that, SRAM and GFX.Screen are the only other large things showing up in .data, for a total of about 1MB. I suppose that's why they were dynamically allocated in the first place.

**Comment by MichaelBuckley** [comment]
Thanks for tagging me. I'll do a bit of testing and upload a Mac build Saturday at the latest.

**Comment by Felipefpl** [comment]
I found a couple of things, mostly minor stuff, i wish i had seen that before release:

1 - The input configuration screen is missing a msg saying that ESC clean the entries, customize hotkeys screen has this msg.

2 - Changelog still refers to 2022.

3 - When cleaning the keys with ESC on customize hotkeys section it avoids the last box in the left side and several boxes in the middle/right side, to reproduce this just fill the boxes in the middle/right side attaching them with several keys and clean them with ESC, you'll see what i mean. ;)

4 - When choosing the Output Image Processing after you choose the filter in the 1st box snes9x auto-chooses a filter in the Hi Res box below, it would be nice if this changed only if we chose a Hi Res filter ourselves.

5 - I dont have support for vulkan in my old GPU, When choosing vulkan there is an error msg and snes9x crashes, it'd be better if snes9x only displayed a msg saying "This backend isnt supported by your video card, Snes9x will now revert to the previous backend used before."

6 - This is a big one: there is a "light" crackling sound now in snes9x, i chose Front Mission patched to english to play, have Win7 and realtek sound card. Tried xaudio/waveout, disabled Sync Sound Core, changed from 48 to 32 khz and the crackling still happened.

**Comment by bearoso** [comment]
3, 4, and 5 are fixed.

1. I think your font is hiding the last line. What version of Windows are you on?
2. I did a grep for 2022, there's nothing that needs to be updated left.

**Comment by Felipefpl** [comment]
> There wasn't space for this when I cleaned it up a couple years ago. I didn't want to make the box bigger.

I see.
 
> Which Changelog, where?

Meh, this is what happens when i dont check what i wrote. I meant the about dialog box. :P
 
> The "Automatic" frame skip option works slightly differently now. You should use Sound Sync and the Fixed frame skip option. And make sure the "adjust input rate to display" option is turned on in the sound options.

Sorry for this, this got nothing to do with the sound, i changed the filter from HQ2X to Super2XSai and this fixed my issue.

I'm on Win7 x64.

**Comment by bearoso** [comment]
I changed the HQ2x implementation to a smaller one that compiles faster. It runs faster on my systems, too. It must be slower on yours, though. I'll debate changing it back. You know, the XBRZ filters are faster than HQ2X and I think they look better. You might try one of those.

With Win7, you shouldn't be missing any text because of the font. Mind posting a screenshot of that dialog box?

**Comment by Felipefpl** [comment]
> I changed the HQ2x implementation to a smaller one that compiles faster. It runs faster on my systems, too. It must be slower on yours, though. I'll debate changing it back. You know, the XBRZ filters are faster than HQ2X and I think they look better. You might try one of those.

Strange, XBRZ filters are REALLY slow here. Not only in snes9x but in any emulator i try here.
 
> With Win7, you shouldn't be missing any text because of the font. Mind posting a screenshot of that dialog box?

![Sem título](https://user-images.githubusercontent.com/5569804/227655350-92349dc6-d84d-4b6d-a6c9-a5ae70d07722.gif)

**Comment by KamiLordus** [comment]
When can we expect version 1.62 on liberto?

**Comment by bearoso** [comment]
@Felipefpl It says right up there on the top right: "Buttons can be disabled with escape." I guess the wording is kind of ambiguous, though.

Also, I've force-inlined the functions in hq2x. It should be faster now.

@KamiLordus: libretro has been keeping up with the repository. What they have is basically 1.62.

**Comment by Felipefpl** [comment]
> @Felipefpl It says right up there on the top right: "Buttons can be disabled with escape." I guess the wording is kind of ambiguous, though.
 
No problem at all with the wording, i'm just and IDIOT who reads things too fast instead of looking at them calmly... X(

> Also, I've force-inlined the functions in hq2x. It should be faster now.

Thanks for that. I'll try a nightly to see what it happens.

**Comment by bearoso** [comment]
> @bearoso I like to see new versions of cores on liberto. Sometimes they show up very late. Especially since I see very frequent updates of standalone Snes9x and on liberto ... silence :)

They usually just silently pull the changes as they come in. If you use their core updater, it will be up to date, even if the version number doesn't match. 1.62 is mostly standalone changes, anyway.

**Comment by KamiLordus** [comment]
@bearoso Thanks for the info and great job on Snes9x.

**Comment by bearoso** [comment]
Looks like we'll probably do a 1.62.1 this weekend.

**Comment by lordpeluca** [comment]
It's funny, the option "adjust input rate to display" has never let me activate or deactivate it... I just can't do anything. No idea, I use a 14" crt pc monitor.

https://i.postimg.cc/636qy4JM/hg.jpg

**Comment by OV2** [comment]
> The tab order is just mixed up. I don't know much about this right now, so we'll see if @OV2 gets to it before I do.

This is simply the order in the rc file, or in Visual Studio Format->Tab Order.

> 4 - When choosing the Output Image Processing after you choose the filter in the 1st box snes9x auto-chooses a filter in the Hi Res box below, it would be nice if this changed only if we chose a Hi Res filter ourselves.

I don't really mind, but If I recall correctly this was introduced because of many questions from people who selected a regular filter and then were puzzled why their game sometimes looked different when it switched to hight-res (since they have no idea about the different snes resolutions).

> It's funny, the option "adjust input rate to display" has never let me activate or deactivate it... I just can't do anything. No idea, I use a 14" crt pc monitor.

This only works if your monitor has a refresh rate somewhat close to 60, or multiple of that.

**Comment by Felipefpl** [comment]
@bearoso - Tested a nightly and everything works fine:

1 - Selecting a vulkan backend without support for it doesnt crash snes9x anymore.

2 - HQ2X is faster now as it was before, thanks for that. Are there such optimizations for the XBRZ filter?

The only problem i can see here is choosing DirectDraw as the backend, it disables the blue theme of Win7:

Before changing to DirectDraw:
![Sem título](https://user-images.githubusercontent.com/5569804/227721727-3625ab29-3443-4382-be39-4d09976cab75.gif)

After choosing DirectDraw:
![Sem título](https://user-images.githubusercontent.com/5569804/227721747-271b894b-15c2-43fd-8b88-18a033f78ba6.gif)

The msg in the dialog box says: "The color scheme was change to Windows 7 Basic, A running program isnt compatible with certain visual (or would it be graphic?) elements of Windows. Click here to obtain more information."

**Comment by bearoso** [comment]
DirectDraw is just really old, so Windows flips on a compatibility mode. It wasn't intended to be used with Windows 7 and it isn't hardware accelerated anymore. I highly suggest *not* using it. Obviously, the Vulkan backend is the newest, and the OpenGL backend also supports shaders, so I'd prefer those. Direct3D is also fine. It's not slower, it just doesn't have all the new stuff.

@lordpeluca Like OV2 says, it only works if it detects you have a refresh rate close to 60hz or a multiple thereof. Switch to 60hz and it'll work. If you're using something else on a non-VRR monitor, you're gonna have a bad time. It'll stutter like mad. What I'd recommend, if you're technically savvy enough, is to use Custom Resolution Utility (https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU) to set up an exact 60.09881 mode or one close to it. Then you'll have the exact speed of the real hardware. You can actually do this with most monitors.

> This is simply the order in the rc file, or in Visual Studio Format->Tab Order.

I just reordered the rc file. Now I know there's a Visual Studio option, too.

**Comment by Felipefpl** [comment]
> DirectDraw is just really old, so Windows flips on a compatibility mode. It wasn't intended to be used with Windows 7 and it isn't hardware accelerated anymore. I highly suggest _not_ using it. Obviously, the Vulkan backend is the newest, and the OpenGL backend also supports shaders, so I'd prefer those. Direct3D is also fine. It's not slower, it just doesn't have all the new stuff.

I understand now, thanks for the explanation. :+1:

**Comment by bearoso** [comment]
> I see, i tested high res filters and they never made a change in the GFX here, what surely is strange.

Very few games use the high-res mode. Off the top of my head:

* Seiken Densetsu 3 and Marvelous use it for menus and text boxes. They flip it on and off all the time, which is what OV2 talks about being confusing.
* Kirby's Dream Land 3 and Jurassic Park use it for fake transparency.
* Donkey Kong Country uses it during the Nintendo logo in the intro for some reason.

**Comment by Felipefpl** [comment]
I see, that explains why i never saw any improvements, thanks for teh info.

**Comment by Felipefpl** [comment]
Maybe this thread can be closed now. Will there be an official release for 1.62.1 with changelog on github/other sites?

**Comment by bearoso** [comment]
1.62.1 is officially released.

**Comment by bearoso** [comment]
1.62.1 is will delete your SRAM saves. Don't use it.

**Comment by Felipefpl** [comment]
Wouldnt be better wait to release 1.62.2 till issue #836 is fixed? (in case it's a real issue).

**Comment by p3st-textures** [comment]
true is worse as the msu-1 problem i have :)

**Comment by ImSpecial** [comment]
Well now, so it sounds like I wasn't crazy. That's good!

**Comment by lordpeluca** [comment]
@OV2 @bearoso 

Thanks for the explanation about the "adjust input rate to display" option.

In the image I put above, the bar that appears there I can adjust it, what does not let me activate is the option "Automatic Input Rate":

![rr](https://user-images.githubusercontent.com/40054709/228420077-402ec20e-cd3e-4fba-92cc-2929a1756b05.jpg)


Although I don't know if it is relevant to activate or not the option "automatic Input Rate" in my monitor. 

It was a doubt more than anything, and by the way, I think my monitor is 60 or so I think:

![mo](https://user-images.githubusercontent.com/40054709/228420105-ff946986-dfde-474a-ac42-9842a41f5e42.jpg)


Greetings

**Comment by bearoso** [comment]
@lordpeluca 
The ability to read exact refresh rates was added to Windows later, your version is too old. Increasing the input rate manually is fine, you just have to guess and check. For an exactly 60hz monitor it should be around 31973. I mentioned before that program "CRU by toastyx". You can download that and it can tell you the exact refresh rates your monitor uses. Then you can use the formula `exactrate / 60.9881 * 32040` to get the input rate to use.

**Comment by bearoso** [comment]
@OV2, when you think you've weeded out all of my mistakes, let me know so we can do the 1.62.3 release.

**Comment by OV2** [comment]
@bearoso with the amount of fixes you made I'm amazed we had so few issues.
I think we can do 1.62.3 now.

**Comment by bearoso** [comment]
Ok, setting up 1.62.3. 

@ReyVGM 
I'll look into that. It should be pretty easy to do.

**Comment by ReyVGM** [comment]
[bearoso](https://github.com/bearoso) Awesome!

**Comment by bearoso** [comment]
@OV2, I added a hotkey to toggle the background color. Can you make sure I wired it up right in Windows. The placement is at the very end among save state hotkeys, so it's a bit out of place, but I don't know what to move or if to make room. I noticed while doing this that you can assign keys to the empty slots and it crashes.

**Comment by OV2** [comment]
Looks good. You're right about the position, I moved the superscope turbo key to the other turbo keys and put the backdrop key to the other background toggle keys.
Good find with the empty slots - weird that nobody ever noticed...

**Comment by ImSpecial** [comment]
Not sure if you guys were doing another dot release, and I'm not sure if you consider this a typo, it's super minor either way, but in the display settings in 1.61 it said shader file, in 1.62 it just says "OpenGL/Vulkan".

Maybe name it to "OpenGL / Vulkan Shader File" for constancy 

![2023-03-31_17-47-27](https://user-images.githubusercontent.com/4022372/229251478-30f835ab-5ca4-472d-9e63-35e149339ed4.png)

**Comment by Felipefpl** [comment]
I got a weird bug with sound here.

When i'm playing i hear a crackling sound, i changed filters/sound settings and nothing worked but then i tried this: i changed the backend from D3D to OpenGL while the game was running and the crackling disappeared.

Then i started the emu again and the crackling sound was back, i changed the backend from OpenGL to D3D and the crackling sound disappeared again, again i did this with the game running.

I have Win7 and a Reatek Sound Card with the latest drivers. I'm also using the latest nightly.

**Comment by bearoso** [comment]
@Felipefpl:
Turn on Sound Sync. Either turn on automatic input rate or, if it's not available, set your input rate manually to 31987.

XAudio should work slightly better than WaveOut. WaveOut is effectively the same as directsound with Windows Vista and higher. Make sure your buffer size is big enough. 64ms for XAudio should be decent, while WaveOut needs at least 100ms per Microsoft. Unfortunately, both of those APIs are deprecated. Window 7 and above really want WASAPI, but it's annoyingly complex for our use case. I'd just pull in SDL or cubeb as the replacement.

**Comment by Felipefpl** [comment]
@bearoso - sound sync is always on, i tried disabling it to see if it fixed the problem and it didnt. Auto input rate is always on too. I always keep the sound settings on default except by audio volume/i went from 48000 to 44100 hz.

Thanks for all the info about xaudio/waveout/dsound.

**Comment by odditude42** [comment]
@bearoso XAudio2 is not only not deprecated, but is recommended over WASAPI for games etc.

sources:
https://learn.microsoft.com/en-us/windows/win32/xaudio2/xaudio2-introduction
https://learn.microsoft.com/en-us/windows/win32/directx-sdk--august-2009-

**Comment by bearoso** [comment]
@odditude42
No, I mean we're stuck with version 2.7. XAudio has a lot of features like spatial audio and mixing intended for native games. We just need a dumb buffer with low latency, that's why WASAPI would be preferred.

**Comment by Felipefpl** [comment]
Since this thread is still opened i'd like to suggest 2 things for the next version:

1 - Add support in the "Customize Hotkeys" section to increase/decrease the volume as some emus like duckstation allow us to do (Using the -/+ numlock keys for this is GREAT), We can raise the volume like 0-5-10-15 till 100 and vice-versa, this is much better than having to go to the sound section everytime we need to change the sound specially when some games have the volume lower/higher than usual.

2 - Replace the ugly font plus the way how the specs of the game are displayed now:
![Sem título](https://user-images.githubusercontent.com/5569804/235664509-7b0357c3-3454-4bc0-a5e0-f4f24a98252b.gif)

With the font/way how is displayed on zsnes, it's much better for the eyes ;) :
![Sem título](https://user-images.githubusercontent.com/5569804/235664834-3f1d40c7-94b8-4dbf-9be2-b3d30ccbf533.gif)

**Comment by bearoso** [comment]
I worked on some imgui stuff for the Gtk port this weekend that might be better. We can do much better overlays with it.

**Comment by bearoso** [comment]
This is basically how I've got the overlays right now.
![Screenshot_20230502_171402](https://user-images.githubusercontent.com/16159164/235798182-489f2bd5-270b-4cbf-8c6e-b4c3a59a59de.png)
![Screenshot_20230502_171514](https://user-images.githubusercontent.com/16159164/235798910-c3ee1ce0-34ef-4eb4-82f3-38629cf1dead.png)

**Comment by lordpeluca** [comment]
There is an option in the "sound" section that is disabled by default: "dynamic Rate control".

Under what circumstances should this option be activated, or is it better to leave it as it is and not touch it?

It is a doubt more than a problem. Regards

**Comment by Felipefpl** [comment]
@OV2 - I removed EPX and it didnt make a difference regarding the appearance but i tried the 2nd tip "Display message before applying filters" and it worked (althought the font still looks bad). Even without HQ2X zsnes' font still looks better.

Btw, the phrase "Display message before applyig filters" suggests you see a message before applying a different filter in the emulator, it would be better if it was renamed to something that reflects better what this does.

@bearoso - It looks good, i have some small suggestions to make it look better:

4 Mbits instead of 4Mbits, CRC32: 0xcedf3ba7 instead of CRC32:0xcedf3ba7 and Checksum: Ok instead of checksum ok. :+1: 

Now only volume settings in customize hotkeys remain. ;)

**Comment by bearoso** [comment]
> There is an option in the "sound" section that is disabled by default: "dynamic Rate control".
> 
> Under what circumstances should this option be activated, or is it better to leave it as it is and not touch it?

Dynamic rate control tries to prevent overflows and underflows in the sound output. These can be heard as crackles and pops. It takes a fairly large buffer size to work well (80ms or more), and as long as your input rate is configured properly it shouldn't be necessary. Feel free to mess with the option. If it works, great. If not, oh well.

**Comment by bearoso** [comment]
@OV2, how attached are you to the current status messages on the Windows port. Would you be offended if I went ahead and replaced them with this imgui stuff? It'll work on D3D, OpenGL, and Vulkan, but I'd have to keep a fallback solution for directdraw.

**Comment by lordpeluca** [comment]
@bearoso - Thank you for answering my question.

The frequency of my monitor is 60Hz and the sound options are set like this:

![f1](https://user-images.githubusercontent.com/40054709/236075557-28b83b0b-de65-4682-87c7-04a55d775eea.jpg)


The sound goes fine, no distortion, crackling, etc. So I think I will leave it as it is.

Regards

**Comment by OV2** [comment]
I'm not opposed to using imgui, although I have no experience with it so far.
But I wouldn't completely eliminate the old method - I think it's a useful way to quickly get message display working on new ports.

In the windows port it currently also provides a way to get messages into avi recordings, IIRC some people use this together with the input display option. But it's probably not an especially important feature. Or we make it an optional switch, if we need it anyways for DDraw.

**Comment by bearoso** [comment]
It's just available in the Gtk port at the moment.

**Comment by Felipefpl** [comment]
> It's just available in the Gtk port at the moment.

I see, i thought it was for windows too. :/

**Comment by bearoso** [comment]
The OpenGL and vulkan drivers in Windows now have the advanced overlay. This can be enabled by making sure the option to draw inside the image in display settings is disabled. Also, I moved the variable width in-display font to the core, so that text should look better, too.

**Comment by ImSpecial** [comment]
Can this "advanced overlay" be disabled?

**Comment by Felipefpl** [comment]
Tested the latest nightly and notice 2 things:

1 - On screen display size doesnt affect the text (is that its intention?) i set the sizes as 11 and 50 and the text's size remains the same.

2 - The text doesnt use the same font, neither is displayed in the same way as in GTK
![Sem título](https://user-images.githubusercontent.com/5569804/236466424-808077b0-4b1f-4472-8e1d-a3b439a887a1.gif)

**Comment by bearoso** [comment]
Direct3D can now use the normal resolution overlay. By default, the setting will still use the old behavior. You must disable the option "Draw messages inside SNES image" in the Windows display options. Gtk will automatically use the new overlay when it can.

**Comment by bearoso** [comment]
And I'm going to close this issue. 1.62 is over and done with.
