### ISSUE TITLE
Unable to compile from source...

### ISSUE THREAD

**Issue by Gnatzelle** [snes9xgit/snes9x#825]
Hi Guys and Gals...

I think your Wiki-Page got outdated with the latest changes in the last few days...i'm unable to compile snes9x from source now since there is no "meson.build" file anymore...

Don't know if this was by mistake or you all didn't had the time for it yet...just wanted to inform you ^^"

Greetings...

**Comment by bearoso** [comment]
Yep. The Gtk port switched to cmake from meson for a few reasons. I'll update it.

**Comment by Gnatzelle** [comment]
Thank you bearoso :)

**Comment by Felipefpl** [comment]
> Yep. The Gtk port switched to cmake from meson for a few reasons. I'll update it.

Talking about gtk is there any reason why my translation in the PRs wasnt submitted?

**Comment by bearoso** [comment]
Laziness. It's merged now.

**Comment by Felipefpl** [comment]
Thanks.
