### ISSUE TITLE
Patched rom doesn't run

### ISSUE THREAD

**Issue by andoruB** [snes9xgit/snes9x#83]
So, I've tried to run a patched version of Super Puyo Puyo Tsu (patch here: http://romhacking.net/translations/465/), with the distinct patch in the patch folder, by patching the rom directly with LunarIPS, and by downloading an already-patched rom, but none of these work. When I boot the FPS counter turns to yellow, and I'm left with a black screen and with 30-40% CPU usage (which is typical for normal usage). I remember that with the previous versions of Snes9x (stable) I was able to run the same patched rom...

Here's what I get as ROM info:
```
Information for ./Super Puyo Puyo 2 (J) [T-Eng].smc

Name: _____________
Speed: 30/FastROM
Map: LoROM
Type: 00
Contents: ROM
ROM Size: 16Mbits
Calculated Size: 16
SRAM Size: 0Kbits
Header Checksum: 903A
Checksum Compliment: 6FC5
Actual Checksum: 20A2
Video: NTSC 60Hz
CRC32: 12B3F36A
Revision: 1.0

This ROM has been modified or damaged
```

The unpatched version runs well:
```
./Super Puyo Puyo 2 (J).sfc

Name: _____________
Speed: 30/FastROM
Map: LoROM
Type: 00
Contents: ROM
ROM Size: 16Mbits
Calculated Size: 16
SRAM Size: 0Kbits
Header Checksum: 903A
Checksum Compliment: 6FC5
Actual Checksum: 903A
Video: NTSC 60Hz
CRC32: 271E1F3F
Revision: 1.0
```

**Comment by Oggom** [comment]
It's not mentioned in the readme, but the patch probably requires a headered rom to work.
The patched game is running fine on my end.

**Comment by andoruB** [comment]
Got a different version of the ROM and now it works. Thanks.
