### ISSUE TITLE
Snes9x 1.62.2 appimage doesn't start on LMDE 5

### ISSUE THREAD

**Issue by VladimirVSC** [snes9xgit/snes9x#837]
The appimage doesn't start on Linux Mint Debian Edition 5, giving the message 

"./usr/optional/checkrt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./usr/optional/checkrt)
./usr/optional/checkrt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./usr/optional/checkrt)" 

when trying to start from the terminal.

**Comment by bearoso** [comment]
I'll update it. I built it on too recent of a system.

**Comment by VladimirVSC** [comment]
> I'll update it. I built it on too recent of a system.

Thanks in advance!

**Comment by bearoso** [comment]
I had a bit of trouble on this. There were some incompatibilities to work out. Hopefully I've got just the right set of libraries included now, and it's built on Debian bullseye.

**Comment by bearoso** [comment]
Thanks this gives me enough info. LMDE 5 is based on bullseye, so it should work, but I'm using a newer GCC to compile, and I ripped out the checkrt function which should handle that. I can fix it later tonight.

**Comment by bearoso** [comment]
I've replaced the AppImage in the 1.63.3 download section. Can you try it now?

**Comment by VladimirVSC** [comment]
> I've replaced the AppImage in the 1.63.3 download section. Can you try it now?

It works now. Thanks a million!
