### ISSUE TITLE
Segfault loading version 11 snapshot in 1.62.2

### ISSUE THREAD

**Issue by Rakashazi** [snes9xgit/snes9x#838]
Looks like a bug slipped into in the old APU snapshot code with d5400f7. In the 2nd memove(), spc_block_size is added again even though it was already accounted for in new_dsp_registers_position, causing the operation to write past the allocated space. The correct call should be:

`memmove(local_apu_sound + new_dsp_registers_position,
                                        local_apu_sound + spc_block_size,
                                        added_bytes_v12);`

**Comment by OV2** [comment]
Thanks a lot!

**Comment by bearoso** [comment]
I'm dumb. I applied Rakashazi's initial fix without considering the last 16 bytes, so I fixed that, but left that spc_block size in. This is what happens when I rush to fix things.
