### ISSUE TITLE
Attempt to unlock mutex that was not locked

### ISSUE THREAD

**Issue by ghost** [snes9xgit/snes9x#84]
Hi,

I'm using Slackware 14.1 x86_64 and it comes with glib2-2.36.4 which works fine for snes9x.

But I recently upgraded glib2 to this version, glib2-2.42.2, and I then noticed that snes9x did not want to start, it would give me this message at startup;

```
>$snes9x
Sound buffer size: 4096 (1024 samples)
ALSA sound driver initializing...
    --> (Device: default)...OK
    --> (16-bit, Stereo, 32000hz, 32 ms)...OK
Attempt to unlock mutex that was not locked
zsh: abort      snes9x
```

Can we please get a patch for snes9x to work with newer glib2

thank you

**Comment by Geyup** [comment]
I had the same problem with deadbeef audio player and found a patch for it. Looking over the deadbeef player patch I came up with the patch for snes9x. 

I applied the patch and snes9x ran without error. I'm not sure if this is the correct way to go about this problem with glib2, but please look at the patch and if it's correct, please commit, or please create a correct patch.

https://gist.github.com/Geyup/920a457a50ecdeee9255

**Comment by bearoso** [comment]
Fixed long ago.
