### ISSUE TITLE
[ENHANCEMENT] MSU1 .ogg or .flac Possibly?

### ISSUE THREAD

**Issue by crashGG** [snes9xgit/snes9x#841]
It would be very nice if could in future compressed music with .ogg files or .flac files.
flac is lossless, saving about half the size,128k ogg is enough high fidelity, only about 1/12
To save huge Space on sd-cards and other small saveplaces.
Its that possibly or never?

**Comment by bearoso** [comment]
That would break compatibility with other emulators, and I don't think lossy audio was part of the original intent.

We do have a compression solution already there with the .msu1 file format. You basically make a zip file with the patch, data rom, and tracks, and change the extension to .msu1 and filename to match the game.

There's a tool that can make them here: https://github.com/qwertymodo/Mercurial-Magic
and the readme discusses the structure the files need to be in.
