### ISSUE TITLE
Quick save shortcuts not working properly

### ISSUE THREAD

**Issue by xhsdf** [snes9xgit/snes9x#842]
Hello,
since version 1.63 the quick save/load shortcuts aren't usable anymore because they save/load to different slots.
When quick saving slot 0 it says: "`quick save-state 011 saved`" (before it was "`new.000`")
When quick loading slot 0 it says: "`new.000 loaded`" just like in the previous version.

I'm using snes9x-gtk on Archlinux.

**Comment by ReyVGM** [comment]
I know they redesigned the hotkeys menu, maybe check it out and make sure the keys are assigned where you want them to be.

**Comment by xhsdf** [comment]
They are set up correctly. There is not much you can do wrong.

![2023-04-20-154452_443x93_scrot](https://user-images.githubusercontent.com/2945602/233385967-6afadbcf-9c02-486f-8d5f-71e501429196.png)

**Comment by bearoso** [comment]
I will investigate.

**Comment by xhsdf** [comment]
It works. Thank you!
