### ISSUE TITLE
Add an option to separate SPC echo buffer

### ISSUE THREAD

**Issue by Wohlstand** [snes9xgit/snes9x#843]
Hello!

There is a problem when attempting to play some of romhacks (for example, [this](http://smwdb.me/db/0/0aeeb77753a5bbd6061cef7c65be9b237d73f127/), it's for SMW), originally designed for ZSNES (which has no any updates after 2007 year!), making a totally broken sound because their SPC programs expected a separated echo buffer. When using an accurate mode with a shared echo buffer, the sound gets completely broken.

So, it's would be cool to add this option for the SPC emulator to allow such romhacks worm normally. You may say that advanced users would modify the romhack to fix all of the SPC programs to make their echo being hardware-comaptible, however, a significant amount of normal users won't be able to do that.

**Comment by qwertymodo** [comment]
This already exists.Emulation>Hacks> Separate Echo Buffer From RAM

**Comment by Wohlstand** [comment]
Ah, I am glad that this is here. I may guess, I actually have a very old thing... I use Linux Mint 21.1 and ~~the snes9x being installed from the system~~ Nope, I have totally no idea from where I installed it or built it from the sources a while ago and forgot... I shall check what is actually on my end..
