### ISSUE TITLE
"snes9x.exe has detected a problem and should be closed."

### ISSUE THREAD

**Issue by lordpeluca** [snes9xgit/snes9x#845]
I have downloaded the latest build available on github (Gtk: Disable ROM info at start.), I can open the emulator, play, etc, but the problem is that, when I want to exit the emulator, I get the message of the title of this thread:

![f1](https://user-images.githubusercontent.com/40054709/236762318-9c1faee1-bbd4-426d-bb5c-f20a8a1b27ab.jpg)

My video configuration is this (I have not touched of it):

![f2](https://user-images.githubusercontent.com/40054709/236762355-eb5a6cd5-014d-4d07-8085-0a52cad15f4d.jpg)

Another fact, when I activate the option "Display messages inside SNES image", the emulator simply sends me the same message "snes9x.exe has detected a problem and should be closed.".... The funny thing in this case, is that when I do that and go back to the emulator, there are still active processes in the windows task manager, that is, if I open the emulator 5 times and close it, there will be 5 "snes9x" processes open in the windows task manager... but this only happens when I try to activate the option "Display messages inside SNES image"and well, I can't delete them manually so I have to restart the computer.

I have tried everything, install the emulator from 0, delete my "ini" configuration, etc, but nothing worked.

I had to go back to a previous build from May 3rd (imgui: Update font. Test ROM status line.) and the emulator worked again for me without problems.

A thousand apologies for the inconvenience. Regards

PS: My operating system is Windows XP

I see that they changed some options in "Display Settings/SNES Image". In the build that I'm using now and that doesn't give me errors is different:

![f1](https://user-images.githubusercontent.com/40054709/236765850-21ac058c-eb28-42f7-a842-f6063fc471f8.jpg)

**Comment by bearoso** [comment]
It's the direct 3d shutdown code double freeing something. I'm not a big directx expert. Thanks for the heads up.

**Comment by OV2** [comment]
I haven't really had time to take a look, but I've pushed a small fix that should fix the d3d issue. Hopefully I'll have some more time tomorrow.

**Comment by lordpeluca** [comment]
@bearoso @OV2 

Thank you very much for solving it. Now the emulator works correctly.

Regards.
