### ISSUE TITLE
Snes9x libretro core old version

### ISSUE THREAD

**Issue by KamiLordus** [snes9xgit/snes9x#846]
The Snes9x current core for Retroarch has followed upstream and the latest version 1.62.3 has been available for 2-3 weeks.
However, I noticed that for a few days the core has been downgraded to version 1.61 and fixes are being added to it.
https://git.libretro.com/libretro/snes9x/-/commits/master/
It looks like a bug and someone forgot about version 1.62.3 and adds fixes to the old version 1.61. Unless I'm wrong.
@bearoso could you check it out?

**Comment by bearoso** [comment]
The experience is literally the same. Only the version number is different. They've got all the accuracy improvements, they just backed out the standalone GUI changes.
