### ISSUE TITLE
Snes9x 1.6.2 Wont run, just crashes at start

### ISSUE THREAD

**Issue by Solverbolt** [snes9xgit/snes9x#849]
Previous issue report was my mistake, i thought I was in a different github when I started it. 

But so far, every emulator I have tested in the 72 hours, over 12 now, fails to start. I have checked that I have the most recent DX9 update, as well as verified or run compatibility mode.  Snes9x wont even run for more than 5 seconds before the system states its no longer responding, and it will continue to sit there, eating resources, and failing to respond to any input.  I had 1.54 before this and it worked when it was windows 7, but now compatibility mode will not work even for that. I am quite sure my hardware is up to spec, as I just built this system 3 years ago using the most current hardware available within my price range, as listed below

Windows 10 64 Bit
RTX 3050 8GB GPU
Ryzen 5 3600 6 Core Processor
32GB GSkill Ripjaw V 8GB PC4 25600 Ram - 4 Modules on Dual Channel
WD Blue NAND 1TB m.2 2280

To be blunt, If I can run games like Fallout 76, Ark, Conan, Life is Feudal and many others at max settings, this program should not be an issue, but it is

**Comment by epman100** [comment]
snes9x 1.62 is no longer the latest version.  did you update snes9x to 1.62.3?
