### ISSUE TITLE
Please support SNES Mouse via Adapter for SNES Classic

### ISSUE THREAD

**Issue by Akeraiotitasoft** [snes9xgit/snes9x#850]
Please support SNES Mouse via Adapter for SNES Classic

Use this repo:
https://github.com/Akerasoft/extenmote

There is a sample SNES Mouse implementation.

**Comment by ReyVGM** [comment]
Hope this gets added.

**Comment by bearoso** [comment]
Sorry to disappoint, but that's a lot of code that would be added for only one or two people to use a proprietary adapter that could easily be substituted with something else.

Plus, that repository is GPL3, so we legally can't use it.

**Comment by Akeraiotitasoft** [comment]
You don't need the code from the repository.  When I make a physical copy I can give it to you.  I mean that I can give you the adapter.  Then you are a user of it.  Not the maker of it.  Then you can use it for testing.  You only need to know the data that is being sent by the adapter.

**Comment by Akeraiotitasoft** [comment]
How do you know only 1 or 2 people will use the adapter?
This is based on Raphnet code.  If proven to work Raphael Assenat (www.raphnet.com<http://www.raphnet.com>) might make it as well.  I opened a pull request for him already.  Just he won’t take the code unless there is proof that it works.  He sells the adapter or similar existing adapters to many people.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by bearoso** [comment]
If it uses a standardized protocol, there's no need to do anything. It'll just work. If it's just bits over the wire, depends how complex it is and the interface.

**Comment by Akeraiotitasoft** [comment]
Let me know where in the code the change needs to be.  I might also try to do it.  Also, it can be changed so that Mouse moves left is same as analog stick left.  But SNES classic does not normally see analog stick as mouse movement.  I was trying to avoid making the real SNES mouse through the adapter look that much like a regular controller, but it can be done if needed.  There are extra bits as a trailer after standard classic controller data that could identify the mouse and so the emulator could know that it is a mouse.

**Comment by Akeraiotitasoft** [comment]
It is the SCL/SDA interface called TWI or I2C.  The same one on the NES Classic, SNES Classic, and on the Wii Mote in the extension port.

**Comment by Akeraiotitasoft** [comment]
This is the type of code change that would only work on an SNES Classic or NES Classic running on the ARM processor.  The console would be modded with Hackchi2 and Mario Paint would be added (by ripping the cartridge).  So usually running on ARM through RetroArch.

**Comment by Akeraiotitasoft** [comment]
This change might actually need to be made in RetroArch.  It seems that the mouse data is being sent from there.  Which repo do they use for libretro to send data from SNES Classic to SNES9x?

**Comment by bearoso** [comment]
Yes, it would be at the port input later, so done in the RetroArch frontend. That would be in https://github.com/libretro/retroarch
