### ISSUE TITLE
Fast Forward doesn't work when I'm going to record an AVI video.

### ISSUE THREAD

**Issue by xRavenXP** [snes9xgit/snes9x#853]
I record videos with Snes9X, but version 1.62 when I go to record a video using the "Start AVI Recording" option, I press the Fast Forward button but it does not accelerate while the video is being extracted, while Fast Forward works normally if not recording. With version 1.60 I can record videos and i use Fast Forward without a problem while recording, but with the newer version I can't and Fast Forward is missing when extracting frames from a movie.

**Comment by xRavenXP** [comment]
Yes it is true. I really like Bizhawk a lot and use it a lot (even for Super Nintendo games), but I also never stop using the Snes9X, due to its speed and the fact that it is light.

I will continue to use Snes9x version 1.60 for recording, but hopefully later versions will allow fast forwarding while recording AVI, as 1.60 does. Many thanks for the reply.

**Comment by bearoso** [comment]
I promise I will get to this eventually.
