### ISSUE TITLE
snes9x.exe & snes9x-x64.exe immediately close after minimizing, then restoring window

### ISSUE THREAD

**Issue by epman100** [snes9xgit/snes9x#856]
I downloaded the most recent build of snes9x.exe & snes9x-x64.exe (1.62.3-1304) and every time I minimize the program window and then restore it, it immediately closes as if it crashed.  downloaded & tested older dev builds and the problem occurred starting with build 1287 where both snes9x.exe & snes9x-x64.exe close after minimizing, then restoring window.

the problem did not occur with dev build 1285 & older.

OS: Windows 10

**Comment by bearoso** [comment]
I presume you're using Direct3D, because I reproduced your bug with only that driver and fixed it. See if the latest build works.

**Comment by epman100** [comment]
ok thanks.  seems to be fixed now using Direct3D in the recent 1305 dev build.

**Comment by LuckwurstJoe** [comment]
Hey there, 

didn't want to open a new issue for that, but with the version 1.62.3 from 30.03.2023 (the latest i can find), this problem still occures. Is there a newer version?

**Comment by OV2** [comment]
You can download a recent dev build here: https://ci.appveyor.com/project/snes9x/snes9x
Click on the version you want(32/64), then on artifacts.
