### ISSUE TITLE
auto-hide mouse cursor 

### ISSUE THREAD

**Issue by stoniemahonie** [snes9xgit/snes9x#86]
doesn't work in snes9x_testbuild_02042015 from http://www.s9x-w32.de/dl/testbuilds/

hope it is connected to the project here.

When loading a rom, the mouse cursor stays all-time. When i click on the menubar 

emulation->input->use snes joypad(s) (what is already chosen)

then the cursor will disappear normally and come back if i move the mouse.

**Comment by OV2** [comment]
I've found the problem, will put up a new version when I can find the time. Just FYI: the newest version is snes9x_testbuild_24052015.zip (sort by last modified).

**Comment by WizLizard** [comment]
The mouse actually will disappear on its own if you launch a second game and so on without closing the emulator. Once closed you have to repeat the process. This has been present for at least the last 5 builds, maybe more.

**Comment by DaMan69** [comment]
The ChangeInputDevice(); move in this [commit] (https://github.com/snes9xgit/snes9x/commit/7948c062caf4b0d3a3860d363cbd0f549bee9855) is the cause.

**Comment by vgturtle127** [comment]
Has this been fixed? I can't tell since it has always worked for me...

**Comment by WizLizard** [comment]
@vgturtle127 Are you using last stable or latest test build?

**Comment by vgturtle127** [comment]
Latest test build. The last stable was a VERY long time ago. :laughing:

**Comment by WizLizard** [comment]
@vgturtle127 Strange the issue exists on my windows 8.1 machine and my clean installed windows 10 machine. Like i said in my first post it's only the first game i launch that the mouse decides not to hide, launching a game immediately after without closing the emulator it finally decides to hide. What version of windows are you using? Are you using true fullscreen or emulated (doesn't seem to matter for me)?

**Comment by vgturtle127** [comment]
I am running Windows 7 at the moment, but I am upgrading to Windows 10 in a few days, so maybe I can test it then to.

I have a few VM's setup with Windows 8.1, I may try them.

I am using real fullscreen (emulated fullscreen is something I have never tried because I don't know how it works and I didn't know of any benefits).

The second I go fullscreen the mouse cursor disappears. This applies to all emulators I have ever used as well. Maybe I am experiencing a bug and I just never noticed because I use a controller. *shrug*

**Comment by DaMan69** [comment]
The move of [ChangeInputDevice](https://github.com/snes9xgit/snes9x/commit/7bd0e2af33bdf6ab688036b06f6b03f622c70124) broke this.  Here's a [fixed build](http://daman6009.home.comcast.net/snes9x.7z).

**Comment by WizLizard** [comment]
@vgturtle127 I believe emulated is just borderless fullscreen.

**Comment by WizLizard** [comment]
@DaMan69 Is this official why is the icon different?

**Comment by WizLizard** [comment]
Interesting this build uses c++ 2015 and the issue is fixed in this build. I would just like to know if this is official?

**Comment by DaMan69** [comment]
Not official (I've just submitted a few patches).  OV2 said he had found the problem otherwise I would have sent the fix earlier.

**Comment by vgturtle127** [comment]
@WizLizard How is borderless fullscreen implemented in SNES9X?

@DaMan69 So when will the problem be fixed in the master branch?

**Comment by WizLizard** [comment]
@vgturtle127 Not 100% sure to be honest. I hope it's fixed soon in the master branch as well it's been present for a while.

**Comment by OV2** [comment]
I'll try to find some time this weekend to finally get some of the piled up changes in.

**Comment by vgturtle127** [comment]
@OV2 I would send pull requests, but my current PC has 28MB left on the hard drive. :laughing: 

Did you happen to see the Cppcheck results in #66?

**Comment by WizLizard** [comment]
@OV2 Fixed will latest test build!

**Comment by vgturtle127** [comment]
@stoniemahonie Can you close this issue since it is fixed?

**Comment by stoniemahonie** [comment]
Thank you :+1:
