### ISSUE TITLE
Input Shortcuts for save states save into the wrong/non-existent slot

### ISSUE THREAD

**Issue by ShadowOne333** [snes9xgit/snes9x#863]
I'm using version 1.62.3 of Snes9x, compiled and installed through emerge on a Gentoo-based machine, and I've been experiencing some weird issues where, no matter what type of button combo or key I select for quick save/load a save state, it always saves 11 slots above the desired state slot.

For example, my default settings are these:
```[Shortcuts]
QuickLoad000             = Keyboard 1
QuickLoad001             = Keyboard 2
QuickLoad002             = Keyboard 3
QuickLoad003             = Keyboard 4
QuickLoad004             = Unset
QuickLoad005             = Unset
QuickLoad006             = Unset
QuickLoad007             = Unset
QuickLoad008             = Unset
QuickLoad009             = Unset
QuickSave000             = Keyboard Shift+1
QuickSave001             = Keyboard Shift+2
QuickSave002             = Keyboard Shift+3
QuickSave003             = Keyboard Shift+4
QuickSave004             = Unset
QuickSave005             = Unset
QuickSave006             = Unset
QuickSave007             = Unset
QuickSave008             = Unset
QuickSave009             = Unset
```
With this configuration, if I press Shift+1 to save the state into slot 000, it should save into slot 000, creating a file with the ROM name and then .000 as the extension. Same for Shift+2 -> ROM.001, Shift+3 -> ROM.002 and Shift+3 -> ROM.003.
However, what Snes9x does instead is saving the state into slot 011 with the message `"Quick save-state 011 saved"`, and creating a file ROM.011

This causes the problem of not being able to load any of the save slots, since Quick Load is still looking for a file named .000 instead of .011, and the emulator doesn't allow saving or loading anything past save slot 009.

One interesting thing is that, while both Quick Save and Quick Load seems to broken for slots, using the option for Saving/Loading the currently selected slot saves properly as 000 and it loads it up as well:

```
GTK_state_load_current   = Keyboard 1
GTK_state_save_current   = Keyboard Shift+1
```

So the issue seems to be persistent only for the Quick Save/Load options for numbered save slots.
I have attached my conf file for Snes9x with the Quick Save/Load shortcuts set to Shift+1 for saving and only pressing 1 for loading.
It's worth noting that changing the button combo gives the same result/issue.

[snes9x.zip](https://github.com/snes9xgit/snes9x/files/12347061/snes9x.zip)

**Comment by bearoso** [comment]
This was fixed in commit 5188dd3, but it hasn't gone out in a release yet.

**Comment by ShadowOne333** [comment]
Oh so it has been fixed already. Thanks for confirming.
I'll just wait for the next minor update then, thanks again!

**Comment by FreedomBen** [comment]
Is this planned for release anytime soon?  I'm hitting this on the Fedora package, but it is version 1.62.3 which is the latest released version on Github.  

A workaround I have (which is still a bit painful) is to save states like normal, but then to load them I have to open the load from file, set "show all" (since the high-numbered files won't show up under the default setting) and then mentally do math to figure out which file my save went into, select the right file, and load the state.  It's a surprising amount of friction.
