### ISSUE TITLE
ROM file not closed.

### ISSUE THREAD

**Issue by hdejin** [snes9xgit/snes9x#864]
In the Windows version of 1.62.3, when loading a new ROM, the previous ROM still appears to be opened, and cannot be deleted/modified.

**Comment by bearoso** [comment]
Is this a normal ROM file or one that's in a .zip file?

**Comment by hdejin** [comment]
just zipped ones.

**Comment by bearoso** [comment]
I suspected as much. Is it just the rom in that file or are you using msu1, etc with it?

**Comment by hdejin** [comment]
Never tested with msu1, only zip files with roms only and those with ips patches.
