### ISSUE TITLE
Unix CLI -conf option is not loading config, though it says it is.

### ISSUE THREAD

**Issue by XAUTHORITY** [snes9xgit/snes9x#865]
Using snes9x from Manjaro repo after fresh rolling release update:
```
extra/snes9x 1.62.3-1 [installed]
    Portable Super Nintendo Entertainment System (TM) emulator
extra/snes9x-gtk 1.62.3-1 [installed]
    Portable Super Nintendo Entertainment System (TM) emulator
```
I have a config that works as expected when I open snes9x-gtk and then my rom using GUI menus, however when I run the other snes9x from CLI, as shown below, neither the video nor controls act as they should. It is as if snes9x is trying to use complete different settings than what I have specified.

`$ snes9x -nostdconf -conf ~/.config/snes9x/snes9x.conf SUPER\ METROID.sfc `
```
Snes9x 1.62.3 for unix
Skipping standard config files.
Reading config file /home/xlogin/.config/snes9x/snes9x.conf.
Port 1: Pad #1. Port 2: <none>. 
No ROM file header found.
Map_LoROMMap
"Super Metroid" [checksum ok] LoROM, 32Mbits, ROM+RAM+BAT, NTSC, SRAM:64Kbits, ID:____, CRC32:D63ED5F8
joystick: No joystick found.
```
The debug log reads as if everything is running as intended but this is not the case, any help is appreciated.

**Comment by bearoso** [comment]
The Gtk port config file is entirely different from the Unix port's. None of the settings will transfer over.

**Comment by XAUTHORITY** [comment]
> The Gtk port config file is entirely different from the Unix port's. None of the settings will transfer over.

tyvm i did need a different config. i found a functional config I copied and edited from the github, [I will link it here](https://github.com/snes9xgit/snes9x/blob/master/unix/snes9x.conf.default) for any others that may find it helpful, issue closed. I can finally snes9x launch roms from file manager script :100: 

I do have one burning question in my head though, am I losing out on a lot of features by not using gtk does anyone know?

**Comment by bearoso** [comment]
Unless you use XVideo, you're primarily missing out on hardware blitting, which means no vsync or proper scaling, so it will probably be a bit stuttery and have some pixel shimmering.

**Comment by XAUTHORITY** [comment]
thank you bearoso i will be sure to weigh it all out, happy collaborating!
`Closed with comment`
