### ISSUE TITLE
Why changed input from verison 1.39 to now ? 

### ISSUE THREAD

**Issue by spotanjo3** [snes9xgit/snes9x#866]
I may be late but I wonder why do you changed it ? I like this much better and a very nice apperance of controller. Maybe Super Famicom/SNES PAL version of controller on it for a colorful one ? A purple is ugly due to American version of SNES. Sorry about my English. Look below:

https://www.emulation64.com/images/tutorials/snes9x/images/input_2_default.jpg

**Comment by bearoso** [comment]
Because it's a weird, low-res render being covered over by a bunch of opaque text boxes. A decent picture or diagram of the controller would be fine (that one _is_ kind of ugly), but it's stupid to overlay the text boxes on top of it.

**Comment by spotanjo3** [comment]
Can you say it in simple English, please ? And is there a way I can replace it to my colorful SNES controller like Super Famicom or PAL verison ? I hate American SNES version. Its very ugly. A purple ? Ugh!

**Comment by OV2** [comment]
No, the image cannot be changed without recompiling.

**Comment by spotanjo3** [comment]
Okay then can I compiling a building and change the image then recompiling ?

**Comment by Felipefpl** [comment]
@bearoso - Sorry for the off-topic but i didnt want to create an issue for such small issue and since snex9x doesnt have an irc chat on libera i decided to post here: 

Is there a reason for having an imgui.ini file in the roms' folder?

**Comment by bearoso** [comment]
> @bearoso - Sorry for the off-topic but i didnt want to create an issue for such small issue and since snex9x doesnt have an irc chat on libera i decided to post here:
> 
> Is there a reason for having an imgui.ini file in the roms' folder?

No, you can delete it. This was fixed so it shouldn't be created again.

**Comment by Felipefpl** [comment]
Good to know, thanks for the info.

**Comment by spotanjo3** [comment]
I am confused. I thought this is about input questions? I know that you said its off topic but can't you make a new topic of your own ? 

Anyway, I will keep v1.39 with snes animation unless you have a good reason why I should update it ? I dont see any issues with my favorite games like Megaman, Castlvania, and mario. Thats are only my list I care about.

**Comment by bearoso** [comment]
Wow. So you'll continue using an obsolete version of the program simply because a window you only need to look at once to configure the input is missing a particular background image. I'm impressed. They say users are often irrational, but this takes the cake.

**Comment by spotanjo3** [comment]
LOL! Yeah. I still think it is so cool. Surely, it is only one time set up but I will knowing that it is still there and I still enjoy it. :D

**Comment by spotanjo3** [comment]
I have an idea.. Since you have purple controller. Why dont you add EUrope controller as well ? Here it is:

https://i.postimg.cc/tRsbhFNS/s-l1600.jpg

**Comment by spotanjo3** [comment]
Can I replace that through compiling build ?
