### ISSUE TITLE
Italian patched Seiken Densetsu 3 didn't work

### ISSUE THREAD

**Issue by fabiobps** [snes9xgit/snes9x#874]
Hi,
after apply a patch for italian dialogues SD3 stop working. 
I've tried from version 1.62.3 to 1.60.
The error seems to be something about ExHiROM and it's appearing from release 1.61. The release 1.60 works fine.
Thank you.

[stdout.txt of working application](https://github.com/snes9xgit/snes9x/files/12575949/stdout.txt)
[stdout.txt of not working application](https://github.com/snes9xgit/snes9x/files/12575955/stdout.txt)
[Italian Patch] (https://www.mumble.romhacking.it/files/itptch_sd3_v100_beta_6a93e9f.zip)
Original Japanes ROM *deleted*

**Comment by bearoso** [comment]
Fixed in 84ac947.

**Comment by bearoso** [comment]
When it finishes building, you can download and try it out from the page here: https://ci.appveyor.com/project/snes9x/snes9x/build/job/3r8ap5to9bq0x6ye/artifacts

**Comment by fabiobps** [comment]
It works fine! Thank you very much!
