### ISSUE TITLE
Windows Build Fail

### ISSUE THREAD

**Issue by DQ318** [snes9xgit/snes9x#878]
Hello everybody!
I'm trying to build the application on Windows, using Visual Studio 2019 and I'm encountering the zconf.h file not found error.
A few years ago I used Visual Studio 2017 and everything worked fine.
I download the project's dependencies from GIT but I believe it is something from zlib itself.
Could you help me with this?

build on visual studio 2019 on windows 10

`1>------ Compilation started: Project: zlib, Configuration: Debug Unicode Win32 ------
1>adler32.c
1>c:\users\downloads\snes9x\win32\zlib\src\zlib.h(34): fatal error C1083: Cannot open file include: 'zconf.h': No such file or directory
1>compress.c
1>c:\users\downloads\snes9x\win32\zlib\src\zlib.h(34): fatal error C1083: Cannot open file include: 'zconf.h': No such file or directory
1>crc32.c
1>c:\users\downloads\snes9x\win32\zlib\src\zlib.h(34): fatal error C1083: Cannot open file include: 'zconf.h': No such file or directory
1>deflate.c
1>Generating Code...
1>Ready build project "zlib.vcxproj" -- FAILED.`

**Comment by bearoso** [comment]
You used the git submodule command to get the dependencies, right? It should still work even with the latest VS2022, but if everything isn't in the exact right spot the zlib project won't build.

**Comment by DQ318** [comment]
> You used the git submodule command to get the dependencies, right? It should still work even with the latest VS2022, but if everything isn't in the exact right spot the zlib project won't build.

Exactly!
On a new installation of Windows 10, with Directx 10 and 12 I did the following procedure:

1 - I installed VS2019 and necessary dependencies.
2 - Git clone snes9x
3 - git submodules to download zlib, libpng and directxmath
4 - I compiled the application.
5 - Error! even with all submodules in their respective folders, within win32

**Comment by OV2** [comment]
zconf.h is part of the zlib submodule, so I'd check if that worked correctly. Maybe delete the zlib folder and redo `git submodule update --init`
