### ISSUE TITLE
Small problem with the sound GUI

### ISSUE THREAD

**Issue by Felipefpl** [snes9xgit/snes9x#883]
The description of default sound devices isnt fully shown, i have the latest nightly:
![Sem título](https://github.com/snes9xgit/snes9x/assets/5569804/17399863-649c-4656-80c0-2c0bff9e8bae)

**Comment by OV2** [comment]
This is a limit of the waveout api, which limits the returned device names to 31 characters. If you switch to xaudio2, the names should no longer be truncated.

**Comment by OV2** [comment]
I've added a workaround for this you can try in the newest commit.
