### ISSUE TITLE
Nightly Build 1.62.3-1352 issue

### ISSUE THREAD

**Issue by ReyVGM** [snes9xgit/snes9x#888]
This is my first time downloading a Nightly Build, so I hope "1.62.3-1352" (x64) means that it's the version I downloaded.

I noticed that if I disable a graphical layer and then go into Video -> Display Configuration and exit out of the screen, all the graphical layers will be re-enabled. It's not a major issue, but I suspect this isn't suppose to happen.

**Comment by bearoso** [comment]
@OV2, can we just remove the S9xGraphicsDeinit and S9xGraphicsInit from the dialog's calling code? From what I see it should only be affected by the core pixel format, so we don't need to reset this on frontend changes.

Settings.BG_Forced and Settings.ForcedBackdrop should probably be reset somewhere else like the rest of Settings members, but I don't think it's a good idea to make these even semi-permanent settings. Someone might change them and not know how to switch them back.

**Comment by OV2** [comment]
I think those are leftover from when we supported different pixel formats in the core (which was only used by ddraw). We can probably remove them.

**Comment by ReyVGM** [comment]
> Settings.BG_Forced and Settings.ForcedBackdrop should probably be reset somewhere else like the rest of Settings members, but I don't think it's a good idea to make these even semi-permanent settings. Someone might change them and not know how to switch them back.

I don't know what this means exactly, but any disabled backgrounds reset themselves if you close and reopen the emulator. 

But, speaking of which, a hotkey toggle to enable all disabled backgrounds would actually be a good idea.
