### ISSUE TITLE
This emulator should have a feature for dumping sounds and music! Please consider adding one for next update!

### ISSUE THREAD

**Issue by Philhubk98** [snes9xgit/snes9x#892]
While there might be some tools for ripping sounds and music from Super Nes games, they are surprisingly difficult to find plus Zsnes being the only known emulator with that feature is no longer a reliable option to us due to a likely possible risk that the Zsnes is too vulnerable that might attract viruses when running a game and thats why everyone including myself are sticking with the only best Super Nes emulator but now the main issue is we can't dump sounds or music with this thing! Its quite unbelievable why after all these years nobody ever thinks about implementing such useful features for ripping and dumping things from Super Nes games meanwhile look at the Nes, Sega Genesis, and N64 emulators they all have features and tools for dumping sprites, textures, and audio! I hope the community and whoever else left of the original team behind this wonderful amazing emulator should not treat it like a forgotten relic from the past. Super Nes games are becoming hard to find and their price increasing on ebay nowadays, forcing many of us to move on with Super Nes emulation to play the classics we grow up with that most of us already lost or no longer have. So please consider updating this emulator with a better focus on more additional features besides bug fixing. Also, the Sounds Resource are surprisingly lacking sound effects there from most Super Nes games and Im trying to get the ones I want myself! We really need a sound effect dumping feature with this emulator, BIG TIME.

**Comment by odditude42** [comment]
https://www.vgmpf.com/Wiki/index.php/SNES_Sound_Ripper

**Comment by ReyVGM** [comment]
Dude, paragraphs!

>  due to a likely possible risk that the Zsnes is too vulnerable that might attract viruses when running a game 

That's ridiculous.

>  I hope the community and whoever else left of the original team behind this wonderful amazing emulator should not treat it like a forgotten relic from the past. 

It is not being treated that way just because it doesn't have a feature you want.
