### ISSUE TITLE
[steam deck] hotkeys not working with touch menu

### ISSUE THREAD

**Issue by lonelycare** [snes9xgit/snes9x#898]
using appimage,
hotkeys bounded correctly and works with keyboard, but not with touch menu, other apps work fine

![299705857-6672a43f-1e13-4939-a1d0-5f8e07e0a921](https://github.com/snes9xgit/snes9x/assets/145258276/17217b0c-fa13-4dd1-94e2-e8c41377260a)

**Comment by OV2** [comment]
You'll need to report this to the emulation station issue tracker, we have nothing to do with that version.
