### ISSUE TITLE
autogen.sh problems

### ISSUE THREAD

**Issue by MarkkusBoi** [snes9xgit/snes9x#90]
When the configure script is generated for the GTK frontend on Fedora 22, it contains an error.

`./configure: line 4548: syntax error near unexpected token```0.37.0'
./configure: line 4548:` `IT_PROG_INTLTOOL(0.37.0)'`

I was able to bypass the error from changing this part in the configure script.

From this:

`IT_PROG_INTLTOOL (0.37.0)`

To this:

`IT_PROG_INTLTOOL "0.37.0"`

When configuring with the changes, it give this:

`./configure: line 4548: IT_PROG_INTLTOOL: command not found`

I don't think that really does anything but break that part but I was able to configure and compile the GTK frontend for snes9x.

**Comment by bearoso** [comment]
Fixed long ago.
