### ISSUE TITLE
Snes9x crashing after monitor sleep

### ISSUE THREAD

**Issue by uhyeahright** [snes9xgit/snes9x#901]
I am using the latest release snes9x 1.62.3 win32 x64, and any time my pc goes into sleep or standby mode when I come back to the application is just frozen and unresponsive.

I don't know what would cause this? I have tried using DirectX and DirectDraw Output methods and both methods still have this issue.

**Comment by odditude42** [comment]
s9x on Windows hangs if the audio device disappears, which happens if audio output is going through HDMI and the monitor goes to sleep.

**Comment by b-errouane** [comment]
To prevent this from happening disable the "Synchronize with sound core" option in the sound settings. At least for me it stops this from happening.

**Comment by bearoso** [comment]
Does this happen with both the XAudio2 and WaveOut drivers?

**Comment by b-errouane** [comment]
Where can I adjust this setting?

**Comment by bearoso** [comment]
I'm not able to reproduce this with the latest build. Can you try that?

https://ci.appveyor.com/project/snes9x/snes9x/builds/49145901/job/82plgrcg48c26i2f/artifacts

**Comment by odditude42** [comment]
@bearoso 
at least as I was experiencing the issue, appears to have been fixed somewhere between 1.60 and 1.61-1097 (which I still happen to have on this PC).

1.60: after resuming from sleep, Snes9x is unresponsive and must be killed.
1.61b1097: after resuming from sleep, Snes9x continues running.
