### ISSUE TITLE
`Save states` Problem

### ISSUE THREAD

**Issue by Yang-Kyle** [snes9xgit/snes9x#904]
> The latest version of Snex9x in AppImage format has problems with Save states
### a file named `<RomName>.011` is created in the sav dir instead of `<RomName>.000`. 

The same goes for Shots 1-9.

**Comment by schuman-aaron** [comment]
This is still happening as of release 1.62.3

**Comment by bearoso** [comment]
It's fixed in git for what will be 1.63.
