### ISSUE TITLE
Super Star Wars: The Empire Strikes Back crashes on the Millennium Falcon level

### ISSUE THREAD

**Issue by SidSector** [snes9xgit/snes9x#907]
The game crashes randomly on the Millennium Falcon level (a.k.a the Asteroid Field level), the password for the level is **WWBGHF** for anyone who wants to test it. 
I've tried with all rom versions i could find (1.0 and 1.1) as well with the European and Japanese version and the game always crashes on that level on Snes9x.
![Super Star Wars - The Empire Strikes Back (U) (V1 1)  ! 002](https://github.com/snes9xgit/snes9x/assets/116836442/d331b7e4-6b4a-4968-854d-3d43af4c721a) ![Super Star Wars - The Empire Strikes Back (U) (V1 1)  ! 003](https://github.com/snes9xgit/snes9x/assets/116836442/e2895057-2131-4a49-a752-7efb37272c93)
snes9x configuration file:
[snes9x configuration.zip](https://github.com/snes9xgit/snes9x/files/14813704/snes9x.configuration.zip)

There are two versions of this game 1.0 and 1.1, in version 1.0 the whole emulator crashes and i have to close it with Task Manager. In version 1.1 the game freezes or the screen glitches (as shown above) or the screen goes black, this is after 5 to 30 seconds, music keeps playing in the background.
This problem also happens on Zsnes, however in Bsnes the level doesn't crash and works fine.

**Comment by Hexaae** [comment]
Works fine and stable here with 1.62.3 (Win 11 23H2, GTX 1070 8GB, i7-8750H, NVidia 551.86 SD).
My cfg:
[snes9x.conf.txt](https://github.com/snes9xgit/snes9x/files/14864361/snes9x.conf.txt)

**Comment by SidSector** [comment]
Thank you, thanks to your config file i think i found the problem; it was the "Allow Left+Rt/Up+Dn" option on input configuration turning it OFF solved it (at least i think it did), i tested it and managed to pass the level a couple of times.
