### ISSUE TITLE
Suggestion: Mute sound while triggering "turbo"

### ISSUE THREAD

**Issue by andoruB** [snes9xgit/snes9x#91]
So I sometimes use turbo to speed through some tedious parts in games, and it's quite a useful feature to have in the emulator, but the only annoyance with it is that you can still hear the sounds, and  since everything is sped up, I end up hearing only screeches. Is it possible to add an option to mute the sound (or disable it altogether) while triggering the turbo mode? This could benefit performance as well, as no extra resources will be used to emulate the sound while speeding through.

**Comment by jcdenton2k** [comment]
There should be an existing option in the Sound Settings called 'Frame Advance Mute' that does what you want.  If this solves your issue then please post back that it is solved (and close the issue if it lets you do so).

**Comment by andoruB** [comment]
Not sure what version you're using, or what git commit you've compiled, but I don't have that option in the sound settings.

**Comment by jcdenton2k** [comment]
Using a precompiled version from EmuCR current as of the April 16th 2016 commit on this GitHub.
http://www.emucr.com/2016/04/snes9x-git-20160418.html

**Comment by andoruB** [comment]
Do you know what patches they applied to have extra features?

**Comment by jcdenton2k** [comment]
I'm unaware of specific things that they've done but it may be worth a shot to give that build a go if you want.  And if you don't trust their compilation then feel free to download and compile a Windows version yourself using the official SNES9X github.

**Comment by andoruB** [comment]
I'm using Linux, not Windows, which might explain why I'm missing that feature.

**Comment by jcdenton2k** [comment]
@andoruB : It may be worthwhile to recompile from the latest git version for your linux distro and see if that helps with adding in that feature since the last commit was on April 18 2016.  Let me know if it still shows up or not.  If it does not then I'll poke through the code to see what they did to enable it in the Windows version and let you know.

**Comment by andoruB** [comment]
I _am_ using a build with the latest commits ;)

**Comment by jcdenton2k** [comment]
I'll take a quick look and see if I find anything

**Comment by andoruB** [comment]
I wonder why this isn't included in the linux section of the code. To tell you honestly, I am not that comfortable with doing it. Would adding those lines to the corresponding linux cpps work, or would it require additional code to make it work?

**Comment by jcdenton2k** [comment]
I'm not a primary coder on the PCSX2 team so I cannot advise you on what to change or how to change it.  You wanted me to find the parts of the code that dealt with it and I have done so.  I'm not an official dev, just a random contributor here and there.

Feel free to poke one of the devs and ask them directly.  They are much better qualified and informed on the PCSX2 codebase than I am and can point you in the right direction.

**Comment by andoruB** [comment]
Of course, I did not expect you to do it. I'll try it myself first, then ask the devs. Thanks for pointing out where the relevant code is! (as I forgot to do it in the previous message... )

**Comment by jcdenton2k** [comment]
@andoruB if you do get it working, feel free to submit a patch via a pull request on GitHub (which is how most of em work) or poke one of the devs to ask them which process to use to integrate it into the latest Linux-based commits

**Comment by bearoso** [comment]
See if the new commit works. I don't have speakers at the moment.

**Comment by andoruB** [comment]
@bearoso Thanks for the commit, but unfortunately it doesn't seem to work. I did get the feature in the settings tab, but when turning on turbo, I still hear the emulated sound.

**Comment by bearoso** [comment]
I'll have to hook up some speakers and mess with it.

**Comment by andoruB** [comment]
Or you could tell me how I could help you with debugging ;)

**Comment by bearoso** [comment]
That's OK, since I didn't test it I overlooked the fact that the code just saved the mute state, it didn't actually do the mute. When I get to my computer I'll fix this.

**Comment by bearoso** [comment]
New commit should work.

**Comment by andoruB** [comment]
Thanks, now this feature actually works, but for some reason I get some weird behaviours video-wise, which I'm not sure if it's caused by this commit. The FPS drops below 56 on NTSC games, I hear constant skips in the audio (as it is synchronized), and it doesn't scale properly (I'm using Simple3x, and while I chose that in the settings, the emulated video doesn't stretch to the whole frame, leaving black boxes, and instead is of Simple2x size)
Again, I'm not sure if this commit is causing it, but I never had these issues before.

**Comment by bearoso** [comment]
Hmm, commit shouldn't do that, nothing in it would affect those things. Audio is still emulated the same, it's just replaced with silence to be output. Could you run a 
git checkout 1714ecf
on your source tree to see if the older version still works?

**Comment by andoruB** [comment]
Did that, and the issue still persisted. So instead I compiled the latest commit again, and removed the xml settings file, and now things are working so far. There's still one quirk that hasn't been solved, but I'll likely start a new issue for that.

**Comment by bearoso** [comment]
Did that fix the FPS and sound issue, but not the scaling? If you're building against GTK3, the automatic DPI scaling screws things up. It reports the wrong width and height in half the cases.

**Comment by andoruB** [comment]
No, it's a different issue altogether. I'm not sure what caused that weird scaling issue, could've been a corrupted settings file.
