### ISSUE TITLE
Unable to Load Game

### ISSUE THREAD

**Issue by ual1n** [snes9xgit/snes9x#911]
I have some games on my list that I simply cannot play using the **Snes9x**, as is the case with **Super Bomberman 4**, I have already changed the emulator version, re-downloaded the games and I still continue to have this problem.

When starting, the game simply stays on a black screen and does not load, however, when testing with Retro Arch, everything worked normally.

![Snes9x - Super Bomberman 4](https://github.com/snes9xgit/snes9x/assets/131735376/bcabd01c-c7f2-4f35-8eea-c79ac7767a77)
![Retro Arch - Super Bomberman 4](https://github.com/snes9xgit/snes9x/assets/131735376/b7f6bc66-6b53-4a77-aa5f-9e56b1f1b66a)
![Retro Arch - Super Bomberman 4 (2)](https://github.com/snes9xgit/snes9x/assets/131735376/8c70ef3e-86e7-4ff0-91ce-e14d02e05882)

Furthermore, I would like to suggest a more friendly interface for Snes9x, where the user could insert a customized background, and when scanning a directory, it would be displayed on the emulator's home screen with the games in a list showing the Cover and Name of each game, then, would be more practical than always having to access the games list on the PC, especially if you are playing with the controller.

In this case, when closing a game, there could also be a bind in the emulator's hotkeys for the user to return to the home screen and choose another game, instead of having to close and open it again.

**Comment by SidSector** [comment]
I tested Bomberman 4 and both the rom and translation work fine for me, except when using the CPU overclock hack. 
Maybe you are using the CPU overclock hack?, many games don't even load with it on.

**Comment by ual1n** [comment]
Ah, so that's it. Thanks, I didn't even think about testing without overclocking.
