### ISSUE TITLE
[REQUEST] Hotkey for Maintain Aspect Ratio 4:3 <-> 8:7

### ISSUE THREAD

**Issue by Hexaae** [snes9xgit/snes9x#912]
Please, can you add a configurable Hotkey to switch Maintain Aspect Ratio 4:3 <-> 8:7 on the fly for PAL/NTSC games having different aspect ratio?

**Comment by odditude42** [comment]
a clarification: this option is not for a difference between PAL and NTSC, it's to account for the difference between the 1:1 pixel aspect ratio of 8:7 produced by the SNES and the 4:3 aspect ratio of actual TVs and composite monitors that the SNES would be connected to.

having it set to 8:7 displays each pixel as a square; having it set to 4:3 horizontally stretches the image in the same manner it would appear on a TV.

**Comment by Hexaae** [comment]
Yes, the reference was to the aspect ratio of PAL/NTSC games since they had different pixel proportions resulting in taller or smaller graphics (e.g. a circle can look like an ellipse, "squashed").
