### ISSUE TITLE
Request: When selecting a save slot #, note if it's empty or used

### ISSUE THREAD

**Issue by ReyVGM** [snes9xgit/snes9x#917]
Hello!

Like the title says, a request for the on-screen popup message to note if a save state slot is used or empty when you press the "Select Slot #" key.

Currently, there's no way to tell if a save slot is used unless you load it first (or check your saves directory).

Thanks!

**Comment by bearoso** [comment]
Not a bad idea. This shouldn't be too difficult.

**Comment by ReyVGM** [comment]
> Not a bad idea. This shouldn't be too difficult.

Awesome! Thanks.

**Comment by bearoso** [comment]
Done.
