### ISSUE TITLE
Bug: Missing Background Graphics

### ISSUE THREAD

**Issue by ReyVGM** [snes9xgit/snes9x#923]
Version:
Snes9x v1.62.3 for Windows 64bit.

Game:
Bishoujo Senshi Sailor Moon SuperS - Fuwafuwa Panic

Issue:
When you beat the game, the credits are missing some of its background animations. The aurora borealis is missing, and ground is missing its bubbles and the overall colors are more muted. See image:

![2](https://github.com/snes9xgit/snes9x/assets/7338867/2a31db33-82d7-484d-8e91-6891e7809b44)

Save state at the credits:
[Bishoujo Senshi Sailor Moon SuperS - Fuwafuwa Panic (Japan)2.zip](https://github.com/snes9xgit/snes9x/files/15369986/Bishoujo.Senshi.Sailor.Moon.SuperS.-.Fuwafuwa.Panic.Japan.2.zip)

By the way, this is how BSNES takes the screenshot. It seems the game is using a half hi-res mode (512x224) in that spot. Since SNES9X is rendering that same scene at 256x224, maybe that's the reason why the background details are missing?
![3](https://github.com/snes9xgit/snes9x/assets/7338867/43663a1f-e75b-4f5a-80cb-d93c4b54f71b)

**Comment by ReyVGM** [comment]
Ignore. For some reason now I'm see in the missing graphics, although the colors are still muted.

**Comment by bearoso** [comment]
I think bsnes always takes screenshots at 512x224 when the accurate PPU is used. 

I'm not sure what's causing the muted colors. Master brightness would have been my first guess, but the text is full white.

**Comment by OV2** [comment]
Maybe it's the ntsc gamma ramp option in bsnes?

You could try it with the ntsc filter in snes9x.

**Comment by ReyVGM** [comment]
> Maybe it's the ntsc gamma ramp option in bsnes?
> 

Yep, that's it!

Sorry to have wasted your time. Please close the thread.
