### ISSUE TITLE
Bug? Hotkey config isn't saving "Bank-" & "Bank+" entries

### ISSUE THREAD

**Issue by ReyVGM** [snes9xgit/snes9x#925]
Can anyone check this?

snes9x x64 1.62.3

Hotkey config menu:
If you assign a key to the "Bank-" and "Bank+" entries, the settings are not saved after you close and reload the emulator.

It might be because the snes9x.conf doesn't contain entries for them?

**Comment by OV2** [comment]
Thank you, the shortcuts were not hooked up for saving in the config file.
