### ISSUE TITLE
Snes9x pauses when navigating the GUI even when "Pause when inactive" is unchecked

### ISSUE THREAD

**Issue by karasuhebi** [snes9xgit/snes9x#93]

**Comment by OV2** [comment]
That is expected behavior. "Inactive" is when the window does not have focus.

**Comment by karasuhebi** [comment]
Understood. So then could we have an option so that Snes9x doesn't pause emulation when navigating the GUI? I myself like listening to the title screen music of some games while I'm tweaking stuff. :)

**Comment by bearoso** [comment]
I believe this is impossible to do because win32 menus are modal. We'd have to use a different toolkit.

**Comment by meisei4** [comment]
> I believe this is impossible to do because win32 menus are modal. We'd have to use a different toolkit.

can you explain what this means? I am trying to visualize certain animations of a game while simultaneously moving through different graphics settings

**Comment by bearoso** [comment]
The Windows event loop for the main window is halted and a secondary, limited event loop is run for the dialog box. The only way to get around this is to have a separate emulation thread. That's how the Qt port works, but it's still incomplete.
