### ISSUE TITLE
Snes9x crashes with Vulkan. 

### ISSUE THREAD

**Issue by petran79** [snes9xgit/snes9x#931]
Emulator worked fine but suddenly it crashes whenever I pick Vulkan, whether from config file or from Display options. In Display options it crashes immediately. 
Only older version 1.62.3 works fine. 1.63.1415 crash

Also in config file there is an option 3 but no Vulkan description. Only OpenGL and Direct3D.
I use WIndows 10 and Nvidia GTX 1080 with 551.86 drivers.

**Comment by bearoso** [comment]
I'm aware of this. You're using code that's being worked on.

**Comment by bearoso** [comment]
This is fixed now, BTW.

Just note that by using snapshots you're putting yourself at risk of bugs, especially if you download a build that's just minutes old.
