### ISSUE TITLE
v1.63's readme-windows.txt is outdated

### ISSUE THREAD

**Issue by QuestioningEspecialy** [snes9xgit/snes9x#932]
[snes9x-1.63-win32-x64.zip](https://github.com/snes9xgit/snes9x/releases/tag/1.63)'s `readme-windows.txt` file says "version 1.62.3  March, 2023" 🤷🏿‍♂️

**Comment by ImSpecial** [comment]
Might as well post another inconsequential thing here too, right click Snes9X > Details  tab > Copywrite 1996-20**23**

**Comment by bearoso** [comment]
The text file should say something like "last updated on X for version X", because that's the intent. 

2023 vs 2024 means we've only got 25 years of the copyright left. I better update that in a hurry. 😉
