### ISSUE TITLE
No Game Window MacOS Sonoma

### ISSUE THREAD

**Issue by ckrokosh** [snes9xgit/snes9x#934]
As there is no Mac binary for the 1.63 release I compiled it from source using the instructions from the wiki. It built fine however when I run it there is no game window.

I can open the preferences no problem. When I load a game it runs. I can here the sound and it appears to react to gamepad input however there is no game window.

I am running a M2 Max with the latest version of Sonoma. 

1.62.3 runs fine.

**Comment by MichaelBuckley** [comment]
This is due to macOS SDK changes since the 1.62.3. It works if you compile it with an older version of Xcode.

I'll try to get this fixed up and release a build over the weekend, assuming I can find the time.

**Comment by ckrokosh** [comment]
Thanks for the response. Will stick with 1.62.3 for now.

**Comment by MichaelBuckley** [comment]
Fixed in the latest code. Here's a 1.63 build for Mac.

[Snes9x.zip](https://github.com/user-attachments/files/16228618/Snes9x.zip)

**Comment by ckrokosh** [comment]
Thanks. Works perfectly. Very much appreciated.

**Comment by chenrui333** [comment]
> Fixed in the latest code. Here's a 1.63 build for Mac.
> 
> [Snes9x.zip](https://github.com/user-attachments/files/16228618/Snes9x.zip)

can you upload it to the 1.63 release? It would help with the homebrew cask bump, thanks!
