### ISSUE TITLE
Frame Count does not appear in Snes9X 1.63.

### ISSUE THREAD

**Issue by xRavenXP** [snes9xgit/snes9x#935]
I just downloaded Snes9X version 1.63 and was eager to check out the new features, especially the hotkeys. The "Show Pressed Keys" and "Movie Ready-Only" are working perfectly and have a new look, but the "Movie Frame Count" doesn't work (no matter which button I press), and without the frame counter on the screen it's impossible to record videos smoothly.
What happened to make this important hotkey not work?

![imagem_2024-07-12_223039895](https://github.com/user-attachments/assets/50316565-4f1d-4b94-a3e3-69ae7e63f055)

**Comment by OV2** [comment]
This simply has not been added to the new text overlay yet. I've committed a fix.

In 1.63 you can enable "Display messages inside SNES image" if you don't want to download a nightly build.

**Comment by xRavenXP** [comment]
It worked perfectly. Thank you very much for this tip. This hud from version 1.63 is much better and I really like the new font used.

![imagem_2024-07-14_014130806](https://github.com/user-attachments/assets/911591ec-76d2-4302-99ea-be1c6d3a7803)
