### ISSUE TITLE
[Request] A new audio backend for windows port

### ISSUE THREAD

**Issue by branchus** [snes9xgit/snes9x#938]
Hi

The default XAudio2 is not immediately available on windows, is it possible to have a new audio backend using SDL2, OpenAL or something from Qt please?

**Comment by OV2** [comment]
What is the problem with using WaveOut?

**Comment by branchus** [comment]
Thank you for the reply

the wave out sound is choppy...

Thanks

**Comment by Zerodarkage** [comment]
Hi, branchus! Are you using any software to enhanced audio? I'm asking because sometimes this type of software causes games/emulators to have audio issues! (FxSound for example).

**Comment by branchus** [comment]
Hi ZeroDarkage

I didn't use any software to enhance audio. but my sound card is not a common one either. It is a Focusrite Scarlett 2i4 Audio Interface. It supposed to provide low latency, it may optimized for Digital Audio Workstations. Yeah, not sure whether this is just my own issue.

By the way, the XAudio2 has no choppy issues.

**Comment by Zerodarkage** [comment]
Hi, branchus!

That's interesting! This device is amazing! I heard it produces very high quality audio! Could be a driver problem or something like that. The two things I suggest now is to search on google for people using this device! Maybe someone else has a similar problem! An update your Operation System (softwares/drivers) and the official updates for you Focusrite Scarlett 2i4 Audio Interface. I know that's second recomendation is lame but sometimes is all you need!

**Comment by branchus** [comment]
Hi Zerodarkage

Ever since I knew this only affecting me, I started looking sound settings. and I found as long as the buffer length is equal or longer than 64ms, there is no choppy sound using WaveOut. Problem solved

Thanks
Please close the ticket
