### ISSUE TITLE
Higher refresh rates seem less smooth.

### ISSUE THREAD

**Issue by BParks21** [snes9xgit/snes9x#94]
For some reason any refresh rates higher than 60hz seem to have less smooth, jittery/stuttering horizontal panning. Tried both opengl and d3d with vsync on/off. Shouldn't this be the opposite? Other emulators are fine at high refresh rates. higan v095 is one of them.

**Comment by BearOso** [comment]
I don't know what you're expecting, but the SNES runs at ~60hz or ~50hz depending on region. Unless you're using 120hz (or 100, respectively) on your monitor, you can expect it to display each frame generated by the emulator for 1 or 2 frames in a regular rhythm. It's technically impossible to handle it any other way while running near the correct speed. I guess you could temporally blur it, but what would be the point?

**Comment by WizLizard** [comment]
I don't understand how other emus don't have this issue when they also emulate games that originally ran at 60hz?

**Comment by BearOso** [comment]
They probably aren't using vsync. It's impossible to be smooth when frames have to alternate between 1 and 2 monitor refreshes. That, or some other tradeoff. You'll get a better experience if you just use 60hz.

**Comment by vgturtle127** [comment]
@ghost You can turn VSYNC off in SNES9X though, can't you?

**Comment by Nicholas-Steel** [comment]
Are you using Fullscreen Exclusive, Fullscreen Borderless or Windowed display mode?

If the former doesn't suffer the issue but the latter 2 do, then you can try opening the snes9x.conf file with Notepad and look for DWMSync, change its value to True and save the file.

Now try the emulator and see if the problem is resolved, and report back here.

**Comment by BParks21** [comment]
I use exclusive fullscreen. I use snes9x RA core now and notice it looks a little less smooth there as well. I'm thinking i'm gonna close this. Probably just a result of the internal framerate/refresh rate mismatch.
