### ISSUE TITLE
[Request] Rewind option

### ISSUE THREAD

**Issue by X3MBoy** [snes9xgit/snes9x#945]
Recently I've been using my Nintendo Switch with the NES and SNES games. One thing that caught my attention was the option to rewind the current game. I think is an option like saving state and load state very quick so you can go back a few seconds without stopping your current game.

I don't know any details on implementation but it was a good option while playing to not necessarily re do everything from last saved state, but just the last 5 to 10 seconds.

**Comment by OV2** [comment]
Emulation->Settings, set "Rewind buffer size" to something like 32mb.
Use the Rewind hotkey ("R" by default).

**Comment by ReyVGM** [comment]
This has been available for years now, but you have to turn it on.
