### ISSUE TITLE
diagonal suddenly stopped working

### ISSUE THREAD

**Issue by akacoda1** [snes9xgit/snes9x#951]
pretty much title. been using SNES9x for the past couples weeks now with no issues but now for some reason it does not want to recognize my diagonal in the input selector. I've tried maybe ways for it to recognize the diagonal direction but no avail. Online said I could try holding left, reselect the up left bind, move my stick up and that would be a easy way for it to pick it up incase I just suck but that still didn't work either. I recognized only "up" 

really not sure what this issue could be. Like I said it was working before. I use a mayflash gamecube controller. Just a regular old gamecuber controller with a pc/wiiu usb port. on dolphin my controller works fine. not sure what the issue is

**Comment by bearoso** [comment]
I've never seen a situation where those diagonal bindings were needed. The gamecube controller only has analog and a four-direction membrane d-pad. I suggest you just clear those diagonal entries and set up only the cardinal directions.

**Comment by akacoda1** [comment]
im playing super mario 64 and there is a section where I need to make a diagonal jump in order to get through it. setting up only the cardinal directions is how I have it now however I can't progress. What I don't get is why this just suddenly stopped working. I had no issues the weeks prior and I haven't updated or gotten a new version since

**Comment by akacoda1** [comment]
hm actually it seems to be working now. It was yesterday after making that post so after a computer restart it works fine. not sure what the cause or origin was but maybe something on my end considering it was solved after a computer restart.
