### ISSUE TITLE
Feature Request - ScaleFX Filter

### ISSUE THREAD

**Issue by Felipefpl** [snes9xgit/snes9x#952]
In the VBA-M discord channel there was a conversation about adding the ScaleFX filter in the emulator. I'm wondering if this could happen with snes9x since the improvement seems quite nice:

https://www.reddit.com/r/OpenEmu/comments/vc40xg/have_you_tried_the_scalefx_shader_yet/

There are ppl who believe it's even better than xBRZ, i cant say that since i never tested it but it's interesting nevertheless:

https://www.reddit.com/r/EmulationOnAndroid/comments/qai8u2/scalefx_filter_on_retroarch_plus_is_amazing/

**Comment by bearoso** [comment]
We already support slangp shaders on OpenGL and Vulkan and have forever. https://github.com/libretro/slang-shaders

**Comment by bearoso** [comment]
Scalefx is only currently implemented as a shader. It probably wouldn't perform very well as a CPU filter, even if ported.
