### ISSUE TITLE
Severe softlock gameplay glitch in 'Magical Drop'

### ISSUE THREAD

**Issue by McRmie** [snes9xgit/snes9x#955]
Once you get a game over in 'Endless Mode' the game softlock. Normally, this is what you should see:
![SFC - Magical Drop (Japan)-241010-170720](https://github.com/user-attachments/assets/34592388-8141-4088-8a42-773696256f2c)

But instead, it gets stuck on this screen:
![SFC - Magical Drop (Japan)-241010-170642](https://github.com/user-attachments/assets/894304b4-5a7c-480f-9deb-20fd879986d3)

The 'Game Over' never come out and you get effectively soft locked.

To reproduce:
From the main menu press down twice to select 'tokoton mode' (endless mode). Next, select your character (I tested with 'Fool'). And then just get a game over when the blocks/drops get to the bottom of the screen. You can achieve this faster by moving the drops on a single column. Takes about 30secs overall. 

Tested with the latest 1.63 version. Both standalone and the libretro core.

Doesn't occur with the SupaFaust core or Mesen-S. However, it does seem to also occur in bsnes (tested with the multiple bsnes libretro cores including 'bsnes accuracy 2014'.).

**_edit_**:  Another glitch:
Normally, during gameplay when you make combos/chains, there are a bunch of voice effects that plays. You can hear them correctly in [this](https://www.youtube.com/watch?v=d0tJKZHfalg) video (right side audio for sfc). Those are completely missing in snes9x, as seen in [this](https://www.youtube.com/watch?v=5wBsguYkbm4) video. They play correctly in SupaFaust or Mesen-S. My guess is that the first video was captured on hardware and the second one with either snes9x or bsnes.

Might be related to the softlock game over glitch.

**_edit 2_**: 
Just out of pure curiosity and to be as thorough as possible, I also tested with MAME. Same exact issues: voices don't play and the game over animation doesn't trigger, causing the soft lock.

**_edit 3_**:
Sorry, another edit. [Known bug](https://bsnes.org/articles/snes-game-bugs/) apparently. Can happen on real hardware, though only occasionally apparently while here it occurs every time.

> 
> In Tokoton mode, losing the game will sometimes soft-lock, preventing you from entering your initials and then trying again.
> 
> This bug is caused by the game not initializing the SNES DSP registers at startup. The register values are non-deterministic at SNES startup, and when the wrong value ends up in certain registers (PITCH and ENVX), this bug will surface.
> 
> This bug is somewhat uncommon to trigger on a real SNES, but multiple confirmations have shown that it can and does happen on real hardware.

**Comment by bearoso** [comment]
I initialized a couple of register locations to 1 instead of 0 and that seems to prevent the lock from happening.

**Comment by McRmie** [comment]
Thank you for looking into it. Assuming the change doesn't affect other games, sound good (or the way it initializes could be made optional I guess)

Guessing this also fixes the voice effects not playing during gameplay issue (simplest way to test: there's a voice that's supposed to play as you see the 'Game Over' animation/sprite).

**Comment by bearoso** [comment]
Yeah, the voice effects do seem to be working. Initializing those locations isn't likely to hurt anything else. Other games will have written to those and not used them uninitialized. The existing behavior of just zeroing everything out doesn't match the hardware either.

**Comment by McRmie** [comment]
Sorry, found [some more information](https://mgba.io/2017/07/31/holy-grail-bugs-2/#magical-drop) regarding this (from 2017):


> One of the issues with fixing the S-DSP randomness is that much of the internal state is opaque beyond the S-DSP itself, making it difficult to tell what should be random and what shouldn’t be. Another issue is due to a lack of proper test cases to ensure nothing breaks. In fact, byuu attempted to randomize the entire S-DSP state, and sure enough, it broke things that previously worked. For example, King of Dragons would randomly drop sound effects and channels. Further, which ones were missing varied every boot. So clearly some things weren’t random…but some things are. The issue has not yet been fully investigated on hardware, but research is ongoing and will hopefully yield a further understanding as it continues. Until then, well, you’re resigned to using less accurate emulators for this specific game.

Additional discussion [here ](http://web.archive.org/web/20190702152424/https://helmet.kafuka.org/bboard/thread.php?id=108) and [here](http://web.archive.org/web/20190118205038/http://helmet.kafuka.org/byuubackup2/viewtopic.php@f=4&t=1668&start=10.html)

I'm don't know if keeping the current initialization behavior (even if it's not actually accurate either) might not be better, at least for now. Your call of course but I'd just hate if it broke other games that we might not be aware of could be affected by this.

**Comment by bearoso** [comment]
I changed 2 bits to initialize to 1 instead of 0. Not randomly. If it breaks something that relies on uninitialized behavior then we tweak it again until both games work.
