### ISSUE TITLE
OpenGL Output broken since Oct. 13th(?) Commits

### ISSUE THREAD

**Issue by Gnatzelle** [snes9xgit/snes9x#960]
Hi :)

Since the recent "GTK Commits" between Oct, 13th - 16th, the OpenGL Output is broken and shows only a fraction of the actual windows if the scaling is higher than 1x (2x draws only a 1/4 of the windows, 3x 1/9th, 4x 1/16...and so on). Vulkan works fine though...
![Screenshot_20-10-2024_23-44-42 895](https://github.com/user-attachments/assets/56579f6c-fe87-47ef-8158-e4909b7e93a1)
This is with 2x Scaling

I can't specify which commit started this behaviour cause only with the recent commits from Oct. 17th i could run Snes9x again due to instant crashes (Segfaults) with those 4 Commits before

Last fully working commit would be: https://github.com/snes9xgit/snes9x/commit/b19e31c83ff9fb31aa2cd397f0a22a9ae3a58cc0

System is an up-to-date Arch Linux with a AMD RX 7600 GPU (Mesa 24.2.5)

**Comment by bearoso** [comment]
Fixed in [932b093](https://github.com/snes9xgit/snes9x/commit/932b093d98b7ace4ea5e9b50d94abb22169faedb).
