### ISSUE TITLE
A.S.P. - Air Strike Patrol it has no effects

### ISSUE THREAD

**Issue by andreluaz** [snes9xgit/snes9x#962]
Please, could you fix two problems with this game (A.S.P. - Air Strike Patrol)? The first one is the 'Good Luck' message at the start stage; it doesn't show effects. The second issue is the shadow of the airplane on the sand during the game. (tested on snes9x-1.63-1463-932b093-win32-x64)

![image](https://github.com/user-attachments/assets/64c9d28b-af3a-459f-9912-32c12694b85d)

![image](https://github.com/user-attachments/assets/d65a1720-0112-4dcd-ac2c-9fe29d2e695d)

**Comment by bearoso** [comment]
You mean could we fix the bug in the extremely obscure game that people only know about because of that bug?

Refer to issues #747, #561, #524, #390, #53.
