### ISSUE TITLE
Mac asset missing from 1.63 release

### ISSUE THREAD

**Issue by brantonb** [snes9xgit/snes9x#964]
I use Homebrew to install snes9x. [The cask](https://github.com/Homebrew/homebrew-cask/blob/55e6162dd0e5f011f74825bba0d6ee76fcf3f882/Casks/snes9x.rb) is still for 1.62.3. Issue #934 posted a zip file for the Mac release and there was an unanswered comment asking for it adding it to the release so that Homebrew could be updated.

Is it possible to get the Mac zip file added to [the 1.63 release assets](https://github.com/snes9xgit/snes9x/releases/tag/1.63) so Homebrew users can install it? I'm happy to update the cask definition to point to it once it's available as a release asset.

**Comment by bearoso** [comment]
Done.
